defmodule Aesir.ZoneServer.Content.Npc.Warps.Dungeons.LhzDun.LhzDun51 do
  @moduledoc """
  Transpiled from rAthena warps/dungeons/lhz_dun.txt:41 (lhz_dun5-1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "lhz_dun02", x: 149, y: 149, dir: 4, sprite: 45, name: "lhz_dun5-1", trigger: {2, 2}}
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if (get_char_var(ctx, :Upper, 0) != 1 and base_level(ctx) < 95) or
           (get_char_var(ctx, :Upper, 0) == 1 and base_level(ctx) < 90) do
        warp(ctx, "lhz_dun02", 145, 149)
      else
        warp(ctx, "lhz_dun03", 140, 133)
      end

    ctx
  end
end
