defmodule Aesir.ZoneServer.Content.Npc.Umbala.Pasto do
  @moduledoc """
  Transpiled from rAthena cities/umbala.txt:462 (Pasto#um).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "umbala", x: 177, y: 153, dir: 3, sprite: 97, name: "Pasto"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Pasto]")
    |> emotion(:surprise)
    |> mes("Oh my god~! Finally,")
    |> mes("another Rune-Midgartsian!")
    |> mes("I've never seen anyone from")
    |> mes("home in this place before!")
    |> mes("Nice to meet you, my name is Pasto!")
    |> next()
    |> mes("[Pasto]")
    |> mes("This place is called Umbala.")
    |> mes("The local people in this village")
    |> mes("have formed a culture that's")
    |> mes("totally different from other")
    |> mes("places I've been.")
    |> next()
    |> mes("[Pasto]")
    |> mes("I guess it's because this")
    |> mes("place has been isolated from")
    |> mes("other regions because of its")
    |> mes("geographical features.")
    |> next()
    |> mes("[Pasto]")
    |> mes("They look different from us, and")
    |> mes("use a language that is still very")
    |> mes("confusing to me. I was also")
    |> mes("confounded by their different use")
    |> mes("of facial expression.")
    |> next()
    |> mes("[Pasto]")
    |> mes("Of course, there are some")
    |> mes("similarities. However, you might")
    |> mes("want to be careful about certain")
    |> mes("issues.")
    |> next()
    |> mes("[Pasto]")
    |> mes("Sometimes, what you say or do")
    |> mes("or do could be misinterpreted as")
    |> mes("having the totally opposite meaning.")
    |> next()
    |> mes("[Pasto]")
    |> mes("I wish I could speak their")
    |> mes("language...*Sigh*")
    |> mes("...Or I wish I could meet more")
    |> mes("people here that speak my")
    |> mes("language...I...I'm...")
    |> mes("So very lonely...*Sob*")
    |> emotion(:cry)
    |> close()

    exit(:normal)
  end
end
