defmodule Aesir.ZoneServer.Content.Npc.Umbala.UtanKid149165 do
  @moduledoc """
  Transpiled from rAthena cities/umbala.txt:605 (Utan Kid#3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "umbala", x: 149, y: 165, dir: 4, sprite: 781, name: "Utan Kid"}]

  @impl true
  def on_talk(ctx) do
    if get_char_var(ctx, :event_umbala, 0) >= 3 do
      ctx
      |> mes("[Klumatan]")
      |> mes("It's really scary, falling from")
      |> mes("such a high place...")
      |> mes("But I guess you have to do it,")
      |> mes("otherwise no one will ever")
      |> mes("consider you a grownup.")
      |> next()
      |> mes("[Klumatan]")
      |> mes("I guess I don't want to")
      |> mes("be a grownup right away.")
      |> mes("But some kids my age are")
      |> mes("in too big of a hurry")
      |> mes("to not be kids anymore.")
      |> close()

      exit(:normal)
    else
      ctx
      |> mes("[???]")
      |> mes("Umbahumba umumbah.")
      |> mes("Umbahumbah umbabah.")
      |> mes("Umbahumhumbabahum.")
      |> close()

      exit(:normal)
    end
  end
end
