defmodule Aesir.ZoneServer.Content.Npc.Jobs.M21.Hunter.Manager do
  @moduledoc """
  Transpiled from rAthena jobs/2-1/hunter.txt:1040 (Manager#hnt).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "job_hunte",
        x: 1,
        y: 1,
        dir: 1,
        sprite: 66,
        name: "Manager",
        scope: :shared,
        unique_name: "Manager#hnt"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  def on_event("OnEnable", ctx), do: ev_onenable(ctx)
  def on_event("OnMyMobDead", ctx), do: ev_onmymobdead(ctx)
  def on_event("OnMyMobDead2", ctx), do: ev_onmymobdead2(ctx)
  def on_event("OnReset", ctx), do: ev_onreset(ctx)
  def on_event("OnDisable", ctx), do: ev_ondisable(ctx)
  def on_event("OnTimer1000", ctx), do: ev_ontimer1000(ctx)
  def on_event("OnTimer3000", ctx), do: ev_ontimer3000(ctx)
  def on_event("OnTimer5000", ctx), do: ev_ontimer5000(ctx)
  def on_event("OnTimer7000", ctx), do: ev_ontimer7000(ctx)
  def on_event("OnTimer9000", ctx), do: ev_ontimer9000(ctx)
  def on_event("OnTimer11000", ctx), do: ev_ontimer11000(ctx)
  def on_event("OnTimer13000", ctx), do: ev_ontimer13000(ctx)
  def on_event("OnTimer14000", ctx), do: ev_ontimer14000(ctx)
  def on_event("OnTimer74000", ctx), do: ev_ontimer74000(ctx)
  def on_event("OnTimer134000", ctx), do: ev_ontimer134000(ctx)
  def on_event("OnTimer164000", ctx), do: ev_ontimer164000(ctx)
  def on_event("OnTimer187000", ctx), do: ev_ontimer187000(ctx)
  def on_event("OnTimer188000", ctx), do: ev_ontimer188000(ctx)
  def on_event("OnTimer189000", ctx), do: ev_ontimer189000(ctx)
  def on_event("OnTimer191000", ctx), do: ev_ontimer191000(ctx)
  def on_event("OnTimer192000", ctx), do: ev_ontimer192000(ctx)
  def on_event("OnTimer193000", ctx), do: ev_ontimer193000(ctx)
  def on_event("OnTimer194000", ctx), do: ev_ontimer194000(ctx)
  def on_event("OnTimer195000", ctx), do: ev_ontimer195000(ctx)
  def on_event("OnTimer197000", ctx), do: ev_ontimer197000(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_oninit(ctx) do
    disablenpc(ctx, "Manager#hnt")
  end

  def ev_onenable(ctx) do
    ctx
    |> donpcevent("Switch#hnt::OnDisable")
    |> enablenpc("Manager#hnt")
    |> set_npc_var("MyMobs", 6)
    |> initnpctimer()
    |> summon_mob(mob_id: 1015, map: "job_hunte", at: {67, 80}, event: "Manager#hnt::OnMyMobDead")
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {114, 78},
      event: "Manager#hnt::OnMyMobDead"
    )
    |> summon_mob(
      mob_id: 1002,
      map: "job_hunte",
      at: {89, 127},
      event: "Manager#hnt::OnMyMobDead"
    )
    |> summon_mob(mob_id: 1041, map: "job_hunte", at: {53, 73}, event: "Manager#hnt::OnMyMobDead")
    |> summon_mob(
      mob_id: 1016,
      map: "job_hunte",
      at: {125, 70},
      event: "Manager#hnt::OnMyMobDead"
    )
    |> summon_mob(mob_id: 1015, map: "job_hunte", at: {90, 92}, event: "Manager#hnt::OnMyMobDead")
    |> summon_mob(
      mob_id: 1016,
      map: "job_hunte",
      at: {85, 100},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1041,
      map: "job_hunte",
      at: {72, 102},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {108, 103},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1002,
      map: "job_hunte",
      at: {88, 127},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {125, 69},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1016,
      map: "job_hunte",
      at: {77, 112},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {53, 106},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1002,
      map: "job_hunte",
      at: {53, 73},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {125, 70},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {90, 91},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {67, 80},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1016,
      map: "job_hunte",
      at: {77, 112},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {53, 106},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {53, 73},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {125, 70},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1041,
      map: "job_hunte",
      at: {90, 91},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1002,
      map: "job_hunte",
      at: {85, 100},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {72, 102},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {108, 103},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {77, 112},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {112, 139},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {112, 139},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {112, 139},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {112, 139},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {90, 91},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1002,
      map: "job_hunte",
      at: {53, 73},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {53, 106},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {77, 112},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {72, 102},
      event: "Manager#hnt::OnMyMobDead2"
    )
    |> summon_mob(
      mob_id: 1015,
      map: "job_hunte",
      at: {108, 103},
      event: "Manager#hnt::OnMyMobDead2"
    )
  end

  def ev_onmymobdead(ctx) do
    ctx = set_npc_var(ctx, "MyMobs", get_npc_var(ctx, "MyMobs", 0) - 1)

    ctx =
      if get_npc_var(ctx, "MyMobs", 0) < 3 do
        ctx
        |> mapannounce(
          "job_hunte",
          "Okay, good job... Now, find the switch in the center of the map!! Be careful of the traps!!",
          1
        )
        |> set_char_var(:HNTR_Q, 14)
        |> donpcevent("switch#hnt::OnEnable")
        |> donpcevent("Manager#hnt::OnDisable")
      else
        mapannounce(ctx, "job_hunte", "Okay~ You're almost there!!", 1)
      end

    ctx
  end

  def ev_onmymobdead2(ctx) do
    ctx
    |> mapannounce(
      "job_hunte",
      Rathena.concat(char_name(ctx, 0), "!! You made a mistake...Please try again."),
      1
    )
    |> set_char_var(:HNTR_Q, 13)
    |> warp("job_hunte", 176, 22)
    |> donpcevent("Manager#hnt::OnReset")
    |> donpcevent("Waiting Room#hnt::OnStart")
  end

  def ev_onreset(ctx) do
    stopnpctimer(ctx)
  end

  def ev_ondisable(ctx) do
    ctx |> killmonsterall("job_hunte") |> disablenpc("Manager#hnt")
  end

  def ev_ontimer1000(ctx) do
    mapannounce(ctx, "job_hunte", "The test shall now begin.", 1)
  end

  def ev_ontimer3000(ctx) do
    mapannounce(
      ctx,
      "job_hunte",
      "As mentioned before, only hunt the monsters labeled 'Job change monster'.",
      1
    )
  end

  def ev_ontimer5000(ctx) do
    mapannounce(ctx, "job_hunte", "***** Be careful of the traps when hunting. *****", 1)
  end

  def ev_ontimer7000(ctx) do
    mapannounce(
      ctx,
      "job_hunte",
      "Once you hunt 4 'Job change monster' the switch in the center will begin to operate.",
      1
    )
  end

  def ev_ontimer9000(ctx) do
    mapannounce(
      ctx,
      "job_hunte",
      "When you activate the escape switch, exit the testing area through the warp portal in the 12 o'clock direction.",
      1
    )
  end

  def ev_ontimer11000(ctx) do
    mapannounce(ctx, "job_hunte", "Everything must be completed within 3 minutes.", 1)
  end

  def ev_ontimer13000(ctx) do
    mapannounce(
      ctx,
      "job_hunte",
      "You will have 3 minutes from now on. You will be notified after each minute passes.",
      1
    )
  end

  def ev_ontimer14000(ctx) do
    mapannounce(ctx, "job_hunte", " ****** 3 minutes remaining. ****** ", 1)
  end

  def ev_ontimer74000(ctx) do
    mapannounce(ctx, "job_hunte", " ****** 2 minutes remaining. ****** ", 1)
  end

  def ev_ontimer134000(ctx) do
    mapannounce(ctx, "job_hunte", " ****** 1 minute remaining. ****** ", 1)
  end

  def ev_ontimer164000(ctx) do
    mapannounce(ctx, "job_hunte", " ****** 30 seconds remaining. ****** ", 1)
  end

  def ev_ontimer187000(ctx) do
    mapannounce(ctx, "job_hunte", " Test ends in 5 seconds...", 1)
  end

  def ev_ontimer188000(ctx) do
    mapannounce(ctx, "job_hunte", " Test ends in 4 seconds...", 1)
  end

  def ev_ontimer189000(ctx) do
    mapannounce(ctx, "job_hunte", " Test ends in 3 seconds...", 1)
  end

  def ev_ontimer191000(ctx) do
    mapannounce(ctx, "job_hunte", " Test ends in 2 seconds...", 1)
  end

  def ev_ontimer192000(ctx) do
    mapannounce(ctx, "job_hunte", " Test ends in 1 second.", 1)
  end

  def ev_ontimer193000(ctx) do
    mapannounce(ctx, "job_hunte", " 0 ", 1)
  end

  def ev_ontimer194000(ctx) do
    mapannounce(ctx, "job_hunte", " Time's up. Please try again.", 1)
  end

  def ev_ontimer195000(ctx) do
    areawarp(ctx, "job_hunte", 50, 64, 129, 143, "job_hunte", 176, 22)
  end

  def ev_ontimer197000(ctx) do
    ctx |> donpcevent("Manager#hnt::OnReset") |> donpcevent("Waiting Room#hnt::OnStart")
  end
end
