defmodule Aesir.ZoneServer.Content.Npc.Warps.Cities.Umbala.UmShaman11 do
  @moduledoc """
  Transpiled from rAthena warps/cities/umbala.txt:31 (um_shaman1-1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "umbala", x: 220, y: 189, dir: 0, sprite: 45, name: "um_shaman1-1", trigger: {1, 1}}
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if get_char_var(ctx, :event_umbala, 0) == 7 do
        warp(ctx, "um_in", 32, 71)
      else
        ctx
      end

    ctx
  end
end
