defmodule Aesir.ZoneServer.Mmo.MobManagement.Mobs.Poring do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.MobManagement.Definition,
    id: 1002,
    aegis_name: :PORING,
    name: "Poring",
    level: 1,
    hp: 55,
    base_exp: 150,
    job_exp: 40,
    atk_min: 1,
    atk_max: 1,
    def: 2,
    mdef: 5,
    stats: %{str: 6, agi: 1, vit: 1, int: 0, dex: 6, luk: 5},
    attack_range: 1,
    size: :medium,
    race: :plant,
    element: {:water, 1},
    walk_speed: 400,
    attack_delay: 1_872,
    attack_motion: 672,
    client_attack_motion: 288,
    damage_motion: 480,
    ai_type: 2,
    drops: [
      %{item: "Jellopy", rate: 7_000},
      %{item: "Knife_", rate: 100},
      %{item: "Sticky_Mucus", rate: 400},
      %{item: "Apple", rate: 1_000},
      %{item: "Wing_Of_Fly", rate: 500},
      %{item: "Apple", rate: 150},
      %{item: "Unripe_Apple", rate: 20},
      %{item: "Poring_Card", rate: 20, steal_protected: true}
    ]
end
