defmodule Aesir.ZoneServer.Content.Npc.Cities.Amatsu.Jyaburo do
  @moduledoc """
  Transpiled from rAthena cities/amatsu.txt:298 (Jyaburo#ama).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "amatsu",
        x: 287,
        y: 266,
        dir: 3,
        sprite: 766,
        name: "Jyaburo",
        scope: :shared,
        unique_name: "Jyaburo#ama"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Jyaburo]")
    |> mes("This place is special to me.")
    |> mes("It's filled with memories of my wife.")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("It was under that big tree where")
    |> mes("I first told her I loved her. At")
    |> mes("the time, I really didn't know that she also had feelings for me.")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("After that day, we had many")
    |> mes("conversations here. Quiet")
    |> mes("and peaceful, this was our")
    |> mes("favorite place to be together.")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("When I close my eyes here, I")
    |> mes("can picture our good times,")
    |> mes("and it feels like it all happened yesterday.")
    |> mes("...")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("My wife passed away...")
    |> mes("So now I only come here by")
    |> mes("myself...But I feel like I'm with her whenever I'm here.")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("Do you have anyone that you")
    |> mes("think about? If you have a")
    |> mes("special someone, don't hesitate")
    |> mes("or hold back. Be sure to treat")
    |> mes("that person specially.")
    |> next()
    |> mes("[Jyaburo]")
    |> mes("Human beings live such short")
    |> mes("lives. But we're able to laugh")
    |> mes("throughout life and forget the")
    |> mes("sadness.")
    |> mes("...Always be happy.")
    |> close()
  end
end
