defmodule Aesir.ZoneServer.Content.Npc.PreRe.Warps.Fields.VeinsFild.VeFild62 do
  @moduledoc """
  Transpiled from rAthena pre-re/warps/fields/veins_fild.txt:33 (ve_fild6-2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :pre_renewal,
    spawn: [
      %{
        map: "ve_fild06",
        x: 81,
        y: 177,
        dir: 0,
        sprite: 45,
        name: "ve_fild6-2",
        scope: :pre_renewal,
        trigger: {1, 1}
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if Rathena.truthy?(:rand.uniform(2) - 1) do
        warp(ctx, "ve_fild04", 115, 55)
      else
        warp(ctx, "ve_fild05", 354, 191)
      end

    ctx
  end
end
