defmodule Aesir.ZoneServer.Content.Npc.PreRe.Functions.FJobswdstaff do
  @moduledoc """
  Transpiled from rAthena pre-re/jobs/1-1/swordman.txt:333 (F_JobSwdStaff).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false
  alias Aesir.ZoneServer.Script.Rathena

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, _args) do
    {ctx, v1} =
      ctx
      |> mes("[Test Hall Staff]")
      |> mes("Do you surrender?")
      |> next()
      |> select(["Yes.", "No."])

    ctx =
      if v1 == 1 do
        ctx =
          ctx
          |> mapannounce(
            "job_sword1",
            Rathena.concat(Rathena.concat("Applicant ", char_name(ctx, 0)), " quit the test."),
            1
          )
          |> warp("izlude_in", 65, 165)

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx = ctx |> mes("[Test Hall Staff]") |> mes("Bravo! Go for it again!") |> close()
    throw({:script_end, ctx})
  end
end
