defmodule Aesir.ZoneServer.Content.Npc.Alberta.Fisk do
  @moduledoc """
  Transpiled from rAthena cities/alberta.txt:198 (Fisk).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "alberta", x: 189, y: 151, dir: 5, sprite: 100, name: "Fisk"}]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Fisk]")
      |> mes("Ahoy mate,")
      |> mes("where'd ya")
      |> mes("wanna go?")
      |> next()
      |> select(["Sunken Ship -> 250 zeny.", "Izlude Marina -> 500 zeny.", "Never mind."])

    ctx =
      case v1 do
        1 ->
          ctx =
            if zeny(ctx) < 250 do
              ctx
              |> mes("[Fisk]")
              |> mes("Hey now, don't try to cheat me! I said 250 zeny!")
              |> close()

              exit(:normal)
            else
              ctx
            end

          ctx |> pay_zeny(250) |> warp("alb2trea", 43, 53)
          exit(:normal)

        2 ->
          ctx =
            if zeny(ctx) < 500 do
              ctx
              |> mes("[Fisk]")
              |> mes("Ain't no way yer getting there without the 500 zeny first!")
              |> close()

              exit(:normal)
            else
              ctx
            end

          ctx = pay_zeny(ctx, 500)

          _ =
            if Rathena.truthy?(checkre(ctx, 0)) do
              warp(ctx, "izlude", 195, 212)
            else
              warp(ctx, "izlude", 176, 182)
            end

          exit(:normal)

        3 ->
          ctx |> mes("[Fisk]") |> mes("Alright...") |> mes("Landlubber.") |> close()
          exit(:normal)

        _ ->
          ctx
      end

    ctx
  end
end
