defmodule Aesir.ZoneServer.Content.Npc.PreRe.Guides.GuidesGonryun.KunlunGuide do
  @moduledoc """
  Transpiled from rAthena pre-re/guides/guides_gonryun.txt:16 (Kunlun Guide#gon).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :pre_renewal,
    spawn: [
      %{
        map: "gonryun",
        x: 163,
        y: 60,
        dir: 4,
        sprite: 780,
        name: "Kunlun Guide",
        scope: :pre_renewal,
        unique_name: "Kunlun Guide#gon"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[He Yuen Zhe]")
      |> mes("Ni Hao!")
      |> mes("Welcome to Kunlun~")
      |> mes("Take a walk around and experience")
      |> mes("the ancient history and tradition")
      |> mes("of our breath taking city.")
      |> next()
      |> mes("[He Yuen Zhe]")
      |> mes("I am responsible for helping you")
      |> mes("with any questions you may have.")
      |> mes("Please feel free to ask me anything.")
      |> next()
      |> select([
        "Residence of the Chief",
        "Tool Dealer",
        "Weapon Dealer",
        "Armor Dealer",
        "Wine Maker"
      ])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> viewpoint(1, 109, 131, 0, 16_724_821)
            |> mes("[He Yuen Zhe]")
            |> mes("Please follow your minimap, and head over to the ^FF3355+^000000 mark.")
            |> mes(
              "There, you'll get to the residence of the Chief. Enjoy your stay in lovely Kunlun!"
            )
            |> mes("Xie Xie!")
            |> close()

          throw({:script_end, ctx})

        2 ->
          ctx =
            ctx
            |> viewpoint(1, 147, 82, 1, 13_525_760)
            |> mes("[He Yuen Zhe]")
            |> mes("Please follow your minimap, and head over to the ^CE6300+^000000 mark.")
            |> mes("There, you'll get to the Tool Dealer. Enjoy your stay in lovely Kunlun!")
            |> mes("Xie Xie!")
            |> close()

          throw({:script_end, ctx})

        3 ->
          ctx =
            ctx
            |> viewpoint(1, 174, 104, 2, 5_635_891)
            |> mes("[He Yuen Zhe]")
            |> mes("Please follow your minimap, and head over to the ^55FF33+^000000 mark.")
            |> mes("There, you'll get to the Weapon Dealer. Enjoy your stay in lovely Kunlun!")
            |> mes("Xie Xie!")
            |> close()

          throw({:script_end, ctx})

        4 ->
          ctx =
            ctx
            |> viewpoint(1, 173, 84, 3, 3_364_351)
            |> mes("[He Yuen Zhe]")
            |> mes("Please follow your minimap, and head over to the ^3355FF+^000000 mark.")
            |> mes("There, you'll get to the Armor Dealer. Enjoy your stay in lovely Kunlun!")
            |> mes("Xie Xie!")
            |> close()

          throw({:script_end, ctx})

        5 ->
          ctx =
            ctx
            |> viewpoint(1, 215, 114, 3, 13_461_961)
            |> mes("[He Yuen Zhe]")
            |> mes("Please follow your minimap, and head over to the ^CD69C9+^000000 mark.")
            |> mes("There, you'll get to the Wine Maker. Enjoy your stay in lovely Kunlun!")
            |> mes("Xie Xie!")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
