defmodule Aesir.ZoneServer.Content.Npc.Airports.Airships.AirshipStaff25058 do
  @moduledoc """
  Transpiled from rAthena airports/airships.txt:769 (Airship Staff#airplane01).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "airplane_01",
        x: 250,
        y: 58,
        dir: 2,
        sprite: 67,
        name: "Airship Staff",
        unique_name: "Airship Staff#airplane01"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Airship Staff]")
      |> mes("Welcome")
      |> mes("to the Airship.")
      |> mes("How may I help you?")
      |> next()
      |> select(["Using the Airship", "Captain's Cabin", "Facilities", "Cancel"])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Airship Staff]")
            |> mes("When you see a broadcast")
            |> mes("announcing that we have")
            |> mes("arrived at your destination,")
            |> mes("please use one of the exits")
            |> mes("located at the north and")
            |> mes("south ends of the Airship.")
            |> next()
            |> mes("[Airship Staff]")
            |> mes("If you happen to miss")
            |> mes("your stop, don't worry.")
            |> mes("The Airship is constantly")
            |> mes("en route and you'll get")
            |> mes("another chance to arrive")
            |> mes("to your intended destination.")
            |> close()

          throw({:script_end, ctx})

        2 ->
          ctx =
            ctx
            |> mes("[Airship Staff]")
            |> mes("The Captain's Cabin")
            |> mes("is located at the front")
            |> mes("of the Airship. There, you")
            |> mes("can meet the captain and")
            |> mes("the pilot of the Airship.")
            |> close()

          throw({:script_end, ctx})

        3 ->
          ctx =
            ctx
            |> mes("[Airship Staff]")
            |> mes("The Airship provides")
            |> mes("various Mini Games for")
            |> mes("the entertainment of all")
            |> mes("our passengers. We invite")
            |> mes("you to try your luck and skills")
            |> mes("in the Airship's Mini Games~")
            |> close()

          throw({:script_end, ctx})

        4 ->
          ctx =
            ctx
            |> mes("[Airship Staff]")
            |> mes("Well, I hope you")
            |> mes("your flight aboard")
            |> mes("our Airships. Thank")
            |> mes("you and have a good day.")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
