defmodule Aesir.ZoneServer.Content.Npc.SplIn01.LaphineStaff do
  @moduledoc """
  Transpiled from rAthena cities/splendide.txt:693 (Laphine Staff#ep13_1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "spl_in01", x: 189, y: 207, dir: 3, sprite: 439, name: "Laphine Staff"}]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) > 0 and get_char_var(ctx, :ep13_2_rhea, 0) > 99 do
      ctx =
        ctx
        |> mes("[Laphine Staff]")
        |> mes("Hm, what's up?")
        |> mes("I'm sorry, but we don't sell food to strangers.")
        |> next()
        |> mes("[Laphine Staff]")
        |> mes("You guys also need to be careful of food here.")
        |> mes("Food is scarce here.")
        |> next()
        |> mes("[Laphine Staff]")
        |> mes("You're going to have to find food somewhere else.")
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Laphine Staff]")
        |> mes("VeldAnoWeh Or ")
        |> mes("TurWos")
        |> mes("......ah...")
        |> next()
        |> mes(
          "- You just grin and smile. It's frustrating not to be able to understand their language. -"
        )
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
