defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.ANun do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:12235 (A Nun#2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "iz_ac02",
        x: 152,
        y: 165,
        dir: 5,
        sprite: 95,
        name: "A Nun",
        unique_name: "A Nun#2"
      },
      %{
        map: "iz_ac02_a",
        x: 152,
        y: 165,
        dir: 5,
        sprite: 95,
        name: "A Nun",
        unique_name: "A Nun#2_a"
      },
      %{
        map: "iz_ac02_b",
        x: 152,
        y: 165,
        dir: 5,
        sprite: 95,
        name: "A Nun",
        unique_name: "A Nun#2_b"
      },
      %{
        map: "iz_ac02_c",
        x: 152,
        y: 165,
        dir: 5,
        sprite: 95,
        name: "A Nun",
        unique_name: "A Nun#2_c"
      },
      %{
        map: "iz_ac02_d",
        x: 152,
        y: 165,
        dir: 5,
        sprite: 95,
        name: "A Nun",
        unique_name: "A Nun#2_d"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    if job_level(ctx) > 10 or class(ctx) != :novice do
      ctx =
        ctx
        |> mes("[A nun]")
        |> mes("Wow... this academy is amazing?")
        |> mes("It was not like this when I used to train in the past.")
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        if not Rathena.truthy?(checkweight(ctx, [{1119, 3}])) do
          ctx =
            ctx |> mes("- You have too many items. Clear inventory and try again. -") |> close()

          throw({:script_end, ctx})
        else
          ctx
        end

      if not Rathena.truthy?(isbegin_quest(ctx, 4269)) do
        ctx =
          ctx
          |> mes("[A nun]")
          |> mes("Wow... this academy is amazing?")
          |> mes("It was not like this when I used to train in the past.")
          |> next()
          |> mes("[A nun]")
          |> mes(
            "You can ^ff0000register^000000 at the ^ff0000information center of the Criatura Academy^000000, it will be a great help."
          )
          |> close()

        throw({:script_end, ctx})
      else
        {ctx, v1} =
          ctx
          |> mes("[A nun]")
          |> mes("Ahem..~")
          |> mes("Who are you?")
          |> mes("Are you interested in this ^ff0000introductory course^000000?")
          |> next()
          |> mes("[A nun]")
          |> mes(
            "This introductory manual is mysterious! It enables the ^ff0000use a couple of an Acolyte's skill^000000."
          )
          |> mes("Will you borrow it?")
          |> next()
          |> select(["Take the Acolyte Course.", "Stop."])

        ctx =
          if v1 == 2 do
            ctx =
              ctx
              |> mes("[A nun]")
              |> mes("Well.. if you are not interested.. fine.")
              |> mes("murmuring")
              |> close()

            throw({:script_end, ctx})
          else
            ctx
          end

        if isequippedcnt(ctx, [2821]) > 0 or count_item(ctx, 2821) > 0 do
          ctx =
            ctx
            |> mes("[A nun]")
            |> mes("You already have one.")
            |> mes("We do not give two.")
            |> close()

          throw({:script_end, ctx})
        else
          ctx =
            ctx
            |> mes("[A nun]")
            |> mes("Then, use it for good.")
            |> mes(
              "^ff0000Equip (double click or drag to equipment window)^000000 and open the ^ff0000skill window(Alt+S)^000000 to see the skills in manual."
            )
            |> give_item(2821, 1)
            |> close()

          throw({:script_end, ctx})
        end
      end
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
