defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.Arena do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:1779 (Arena#iz).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "izlude",
        x: 207,
        y: 167,
        dir: 3,
        sprite: 858,
        name: "Arena",
        scope: :renewal,
        unique_name: "Arena#iz",
        trigger: {3, 3}
      },
      %{
        map: "izlude_a",
        x: 207,
        y: 167,
        dir: 3,
        sprite: 858,
        name: "Arena",
        scope: :renewal,
        unique_name: "Arena#iz_a",
        trigger: {3, 3}
      },
      %{
        map: "izlude_b",
        x: 207,
        y: 167,
        dir: 3,
        sprite: 858,
        name: "Arena",
        scope: :renewal,
        unique_name: "Arena#iz_b",
        trigger: {3, 3}
      },
      %{
        map: "izlude_c",
        x: 207,
        y: 167,
        dir: 3,
        sprite: 858,
        name: "Arena",
        scope: :renewal,
        unique_name: "Arena#iz_c",
        trigger: {3, 3}
      },
      %{
        map: "izlude_d",
        x: 207,
        y: 167,
        dir: 3,
        sprite: 858,
        name: "Arena",
        scope: :renewal,
        unique_name: "Arena#iz_d",
        trigger: {3, 3}
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnInit", ctx) do
    ev_oninit(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnTouch", ctx) do
    ev_ontouch(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx =
      set_local(
        ctx,
        :total,
        isbegin_quest(ctx, 7475) + isbegin_quest(ctx, 7476) + isbegin_quest(ctx, 7477)
      )

    if isbegin_quest(ctx, 7474) == 1 do
      if not Rathena.truthy?(isbegin_quest(ctx, 7476)) do
        ctx =
          ctx
          |> mes("== Challenge! Arena! ==")
          |> mes("Breath taking battle with monsters!")
          |> mes("Where is your limit?")
          |> mes("PvE party with your comrad!")
          |> mes("All these at Arena!!")
          |> next()

        if get_local(ctx, :total, 0) == 1 do
          {ctx, _} =
            ctx
            |> mes("Except for the Arena promtional board, nothing can be found here.")
            |> next()
            |> select(["Nothing again?"])

          ctx =
            ctx
            |> mes("[Lumin]")
            |> mes("Hmmm. Its not nothing....")
            |> mes("There were potions here...")
            |> mes("I was tired of waiting for you so I took it too.")
            |> cutin("nov_lumin01.bmp", 2)
            |> next()
            |> mes("[Lumin]")
            |> mes("But why does this potion never make me full?")
            |> mes("*gulp*")
            |> mes("Oh well looks like it's all gone.")
            |> next()
            |> cutin("", 255)
            |> mes("Lumin beat you again.")
            |> mes("Better beat him to the last spot.")
            |> setquest(7476)
            |> viewpoint(2, 207, 167, 3, 16_711_680)
            |> close()

          throw({:script_end, ctx})
        else
          if get_local(ctx, :total, 0) > 1 do
            {ctx, v1} =
              ctx
              |> mes("[Lumin]")
              |> mes(".......")
              |> cutin("nov_lumin01.bmp", 2)
              |> next()
              |> mes("[Lumin]")
              |> mes("Muahahaha.")
              |> cutin("nov_lumin03.bmp", 2)
              |> next()
              |> select(["Are you kidding me?!", "Where's the treasure?"])

            v2 = Rathena.bool_int(v1 == 1)

            ctx =
              case v2 do
                _ -> ctx
              end

            ctx =
              ctx
              |> mes("[Lumin]")
              |> mes("Red potions.")
              |> mes("If I hand it over to you, you'll just waste 'em so I'll just keep them.")
              |> cutin("nov_lumin01.bmp", 2)
              |> next()
              |> mes("[Lumin]")
              |> mes("Come on this is just friendly competition.")
              |> cutin("nov_lumin05.bmp", 2)
              |> next()
              |> mes("[Lumin]")
              |> mes("I am doing this for you to make you stronger.")
              |> mes("Now, so long.")
              |> cutin("nov_lumin03.bmp", 2)
              |> next()
              |> cutin("", 255)
              |> mes("^4d4dff...I have to report of the result to Information staff...^000000.")
              |> setquest(7476)
              |> viewpoint(2, 207, 167, 3, 16_711_680)
              |> close()

            throw({:script_end, ctx})
          else
            {ctx, _} =
              ctx
              |> mes("Except for the Arena promotion signboard, nothing can be found.")
              |> next()
              |> select(["Why is there nothing?"])

            {ctx, _} =
              ctx
              |> mes("[Lumin]")
              |> mes("Of course.")
              |> mes("I already packed it.")
              |> mes("There were Red Potion hidden here.")
              |> cutin("nov_lumin01.bmp", 2)
              |> next()
              |> select(["So can I have some?"])

            ctx =
              ctx
              |> mes("[Lumin]")
              |> mes("That's not fair, I was here first so they're mine.")
              |> mes("You better get to the next stop faster if you want the prize.")
              |> cutin("nov_lumin02.bmp", 2)
              |> next()
              |> mes("[Lumin]")
              |> mes("Well, then.....")
              |> cutin("nov_lumin03.bmp", 2)
              |> next()
              |> cutin("", 255)
              |> mes("Lumin disappeared with his long hair in the air.")
              |> mes("This guy...")
              |> setquest(7476)
              |> viewpoint(2, 207, 167, 3, 16_711_680)
              |> close()

            throw({:script_end, ctx})
          end
        end
      else
        ctx =
          ctx
          |> mes("== Challenge! Arena! ==")
          |> mes("Breath taking battle with monsters!")
          |> mes("Where is your limit?")
          |> mes("PvE party with your comrad!")
          |> mes("All these at Arena!!")
          |> close()

        throw({:script_end, ctx})
      end
    else
      ctx =
        ctx
        |> mes("== Challenge! Arena! ==")
        |> mes("Breath taking battle with monsters!")
        |> mes("Where is your limit?")
        |> mes("PvE party with your comrad!")
        |> mes("All these at Arena!!")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_oninit(ctx) do
    questinfo(ctx, 0, 0, fn ctx ->
      not Rathena.truthy?(isbegin_quest(ctx, 7476)) and isbegin_quest(ctx, 7474) == 1
    end)
  end

  def ev_ontouch(ctx) do
    ctx =
      if isbegin_quest(ctx, 7474) == 1 and not Rathena.truthy?(isbegin_quest(ctx, 7476)) do
        emotion(ctx, :surprise)
      else
        ctx
      end

    ctx
  end
end
