defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.CriaturaAcademyStaff do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:808 (Criatura Academy Staff#0).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "izlude",
        x: 122,
        y: 207,
        dir: 3,
        sprite: 903,
        name: "Criatura Academy Staff",
        unique_name: "Criatura Academy Staff#0",
        trigger: {3, 3}
      },
      %{
        map: "izlude_a",
        x: 122,
        y: 207,
        dir: 3,
        sprite: 903,
        name: "Criatura Academy Staff",
        unique_name: "Criatura Academy Staff#a",
        trigger: {3, 3}
      },
      %{
        map: "izlude_b",
        x: 122,
        y: 207,
        dir: 3,
        sprite: 903,
        name: "Criatura Academy Staff",
        unique_name: "Criatura Academy Staff#b",
        trigger: {3, 3}
      },
      %{
        map: "izlude_c",
        x: 122,
        y: 207,
        dir: 3,
        sprite: 903,
        name: "Criatura Academy Staff",
        unique_name: "Criatura Academy Staff#c",
        trigger: {3, 3}
      },
      %{
        map: "izlude_d",
        x: 122,
        y: 207,
        dir: 3,
        sprite: 903,
        name: "Criatura Academy Staff",
        unique_name: "Criatura Academy Staff#d",
        trigger: {3, 3}
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnInit", ctx) do
    ev_oninit(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnTouch", ctx) do
    ev_ontouch(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx =
      if not Rathena.truthy?(checkweight(ctx, [{1304, 3}])) do
        ctx =
          ctx
          |> mes("Quest cannot be continued due to the overfilled inventory.")
          |> mes("Continue the quest after organizing the inventory.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx = viewpoint(ctx, 2, 122, 207, 1, 16_777_215)

    ctx =
      if class(ctx) == :novice and base_level(ctx) < 15 do
        ctx =
          if isbegin_quest(ctx, 7472) == 1 do
            ctx =
              ctx
              |> mes("[Hun]")
              |> mes("Oh.. you must be the adventurer Carocc was talking about.")
              |> mes(
                "I don't know where your homeland is but Midgard is a good place to start your life's journey."
              )
              |> next()
              |> mes("[Hun]")
              |> mes("It's a good sight to see new adventurers start their journey.")
              |> mes("You must be tired. Need a drink?")
              |> completequest(7472)
              |> getexp(200, 0)
              |> setquest(7473)
              |> give_item(531, 1)
              |> next()
              |> mes("[Hun]")
              |> mes(
                "You can open the Item window by clicking on the 'item' icon on top left portion of the screen."
              )
              |> next()
              |> mes("[Hun]")
              |> mes(
                "The items are automatically catagorized by 'consumables' 'equipment' 'etcetera' and 'personal' suitable for each use."
              )
              |> mes("It will do the automatic sorting per indiviaul useage to")
              |> next()
              |> mes("[Hun]")
              |> mes("Either ^4d4dffdouble click on the item^000000 you intend to use")
              |> mes("or drag it onto^4d4dff the equipment window and use it^000000")
              |> next()
              |> cutin("tutorial03.bmp", 4)
              |> mes("!- Information -!")
              |> mes("^4d4dffItems can be used or equipped with simply double-clicking.")
              |> mes("Item window can be opened with shortcut key Alt+E")
              |> next()
              |> mes("!- Information -!")
              |> mes("^4d4dff Equipped items can be checked with Alt+ Q")
              |> mes("Items can also be dragged onto the location where you wish to equip it.")
              |> next()
              |> cutin("", 255)
              |> mes("[Hun]")
              |> mes(
                "For detailed info on individual items^4d4dff, right click ^000000on that item."
              )
              |> mes("You can check the detailed info on the item.")
              |> next()
              |> cutin("tutorial04.bmp", 4)
              |> mes("!- Information -!")
              |> mes(
                "^4d4dffRight-clicking on the item icon^4d4dff  brings up detailed info on the item."
              )
              |> next()
              |> mes("!- Information -!")
              |> mes(
                "^4d4dffWhen you select other players, you can trade, party up with them with the community window that pops up."
              )
              |> next()
              |> cutin("", 255)
              |> mes("[Hun]")
              |> mes("Ok now ^4d4dffdrink the apple juice that I gave you^000000.")
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              if not Rathena.truthy?(isbegin_quest(ctx, 7473)) do
                ctx =
                  ctx
                  |> mes("[Hun]")
                  |> mes("Hey there.")
                  |> mes("Rest up for a bit.")
                  |> next()
                  |> mes("[Hun]")
                  |> mes("It's joyous to see new adventurers starting out.")
                  |> mes("You want something to drink while you are resting?")
                  |> setquest(7473)
                  |> give_item(531, 1)
                  |> next()
                  |> mes("[Hun]")
                  |> mes(
                    "Right clicking on the item icon ^4d4dffon the basic item window at the upper left corner brings up the detailed info on the item"
                  )
                  |> next()
                  |> mes("[Hun]")
                  |> mes(
                    "The items are automatically catagorized by 'consumables' 'equipment' 'etcetera' and 'personal' suitable for each use."
                  )
                  |> mes("It will do the automatic sorting per indiviaul useage to")
                  |> next()
                  |> mes("[Hun]")
                  |> mes("Either ^4d4dffdouble click on the item^000000 you intend to use")
                  |> mes("or drag it onto^4d4dff the equipment window and use it^000000")
                  |> next()
                  |> mes("[Hun]")
                  |> mes(
                    "For detailed info on individual items^4d4dff, right-click ^000000on the item."
                  )
                  |> mes("You can check the detailed info on the item.")
                  |> next()
                  |> cutin("tutorial04.bmp", 3)
                  |> mes("!- Information -!")
                  |> mes(
                    "Right clicking on the item icon ^4d4dffbrings up the detailed info on the item"
                  )
                  |> next()
                  |> mes("!- Information -!")
                  |> mes(
                    "When you select on other players^4d4dff you can trade, party up with them with the community window that pops up."
                  )
                  |> next()
                  |> cutin("", 255)
                  |> mes("[Hun]")
                  |> mes("Ok now ^4d4dffdrink the apple juice that I gave you^000000.")
                  |> close()

                throw({:script_end, ctx})
              else
                ctx =
                  if isbegin_quest(ctx, 7473) == 1 do
                    ctx =
                      if count_item(ctx, 531) > 0 do
                        ctx =
                          ctx
                          |> mes("[Hun]")
                          |> mes("Consume the apple juice that I gave you in your inventory.")
                          |> mes("Then we'll talk.")
                          |> close()

                        throw({:script_end, ctx})
                      else
                        ctx =
                          if isbegin_quest(ctx, 4269) > 0 do
                            ctx =
                              ctx
                              |> mes("[Hun]")
                              |> mes("How's the taste?")
                              |> mes(
                                "Pretty good-taste of sweet and sour, right? It might not be much but it also has healing properties."
                              )
                              |> next()
                              |> mes("[Hun]")
                              |> mes("I want to give you more but that was the last of it")
                              |> mes(
                                "Anyways here's some potions. They'll come in handy when you start fighting."
                              )
                              |> completequest(7473)
                              |> give_item(569, 30)
                              |> getexp(200, 0)
                              |> next()
                              |> mes("[Hun]")
                              |> mes(
                                "Criatura Academy is a good place to build up experience for the future."
                              )
                              |> mes("And I'm not just saying this because I work here.")
                              |> next()
                              |> mes("[Hun]")
                              |> mes("I'm for real... haha")
                              |> close()

                            throw({:script_end, ctx})
                          else
                            {ctx, v1} =
                              ctx
                              |> mes("[Hun]")
                              |> mes("How's the taste?")
                              |> mes(
                                "Pretty good-taste of sweet and sour, right? It might not be much but it also has healing properties."
                              )
                              |> next()
                              |> mes("[Hun]")
                              |> mes("I want to give you more but that was the last of it")
                              |> mes(
                                "Anyways here's some potions. They'll come in handy when you start fighting."
                              )
                              |> completequest(7473)
                              |> give_item(569, 30)
                              |> getexp(200, 0)
                              |> next()
                              |> mes("[Hun]")
                              |> mes("What do you plan to do from now on?")
                              |> mes("Have you found a place to stay?")
                              |> next()
                              |> select([
                                "I need help with that",
                                "Anything will do really.",
                                "Don't worry."
                              ])

                            ctx =
                              case v1 do
                                1 ->
                                  ctx =
                                    ctx
                                    |> mes("[Hun]")
                                    |> mes("But still, though.")
                                    |> mes("It's tough to be out alone in a new place.")
                                    |> mes("That's why Criatura Academy is there.")
                                    |> next()
                                    |> mes("[Hun]")
                                    |> mes("Carocc sent you to me probably for the same reason.")
                                    |> mes(
                                      "Even though I'm just a work-hand here, I could show you around."
                                    )
                                    |> next()
                                    |> mes("[Hun]")
                                    |> mes("If you follow this road up to north, you can see")
                                    |> mes(
                                      "<NAVI>[the Academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                    )
                                    |> mes("Anybody can enroll, so take advantage of it.")
                                    |> next()
                                    |> emotion(:surprise)
                                    |> mes("[Information Staff]")
                                    |> mes("Sorry to interrupt.")
                                    |> mes(
                                      "But ^4d4dffif you need location info, please ask me.^000000"
                                    )
                                    |> next()
                                    |> mes("[Information Staff]")
                                    |> mes("Hun's information has limits")
                                    |> close()

                                  throw({:script_end, ctx})

                                2 ->
                                  ctx =
                                    ctx
                                    |> mes("[Hun]")
                                    |> mes("How optimistic of you.")
                                    |> mes(
                                      "If you need help, feel free to visit Criatura Academy any time."
                                    )
                                    |> next()
                                    |> mes("[Hun]")
                                    |> mes(
                                      "There's no requirement or payment to enroll so it would be a great help to you."
                                    )
                                    |> mes(
                                      "When you go through this way to the north, you'll find"
                                    )
                                    |> mes(
                                      "<NAVI>[the academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                    )
                                    |> next()
                                    |> mes("[Hun]")
                                    |> mes(
                                      "If there are more adventurers like you, the future will be brighter."
                                    )
                                    |> mes("Hahahaha.")
                                    |> next()
                                    |> emotion(:surprise)
                                    |> mes("[Information Staff]")
                                    |> mes("Sorry to interrupt.")
                                    |> mes(
                                      "But ^4d4dffif you need location info, please ask me.^000000"
                                    )
                                    |> next()
                                    |> mes("[Information Staff]")
                                    |> mes("Hun's information has limits")
                                    |> close()

                                  throw({:script_end, ctx})

                                3 ->
                                  ctx =
                                    ctx
                                    |> mes("[Hun]")
                                    |> mes("You already have a plan laid out?")
                                    |> mes("Well prepared.")
                                    |> mes(
                                      "But just in case, if you are curious about the Criatura Academy, make a visit."
                                    )
                                    |> next()
                                    |> mes("[Hun]")
                                    |> mes(
                                      "When you go through this way to the north, you'll find"
                                    )
                                    |> mes(
                                      "<NAVI>[the academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                    )
                                    |> mes("What is well, is well- isn't it?")
                                    |> next()
                                    |> emotion(:surprise)
                                    |> mes("[Information Staff]")
                                    |> mes("You are correct.")
                                    |> mes("Preperation is the key.")
                                    |> mes(
                                      "But ^4d4dffif you need location info, please ask me.^000000"
                                    )
                                    |> next()
                                    |> mes("[Information Staff]")
                                    |> mes("Hun's information has limits.")
                                    |> close()

                                  throw({:script_end, ctx})

                                _ ->
                                  ctx
                              end

                            ctx
                          end

                        ctx
                      end

                    ctx
                  else
                    ctx =
                      if not Rathena.truthy?(isbegin_quest(ctx, 4269)) do
                        {ctx, v2} =
                          ctx
                          |> mes("[Hun]")
                          |> mes("It's you..")
                          |> mes("What do you plan to do from now on?")
                          |> mes("Have you found a place to stay?")
                          |> next()
                          |> select([
                            "I need help with that",
                            "Anything will do really.",
                            "Don't worry."
                          ])

                        ctx =
                          case v2 do
                            1 ->
                              ctx =
                                ctx
                                |> mes("[Hun]")
                                |> mes("But still, though.")
                                |> mes("It's tough to be out alone in a new place.")
                                |> mes("That's why Criatura Academy is there.")
                                |> next()
                                |> mes("[Hun]")
                                |> mes("Carocc sent you to me probably for the same reason.")
                                |> mes(
                                  "Even though I'm just a work-hand here, I could show you around."
                                )
                                |> next()
                                |> mes("[Hun]")
                                |> mes("If you follow this road up to north, you can see")
                                |> mes(
                                  "<NAVI>[the Academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                )
                                |> mes("Anybody can enroll, so take advantage of it.")
                                |> next()
                                |> emotion(:surprise)
                                |> mes("[Information Staff]")
                                |> mes("Sorry to interrupt.")
                                |> mes(
                                  "But ^4d4dffif you need location info, please ask me.^000000"
                                )
                                |> next()
                                |> mes("[Information Staff]")
                                |> mes("Hun's information has limits")
                                |> close()

                              throw({:script_end, ctx})

                            2 ->
                              ctx =
                                ctx
                                |> mes("[Hun]")
                                |> mes("How optimistic of you.")
                                |> mes(
                                  "If you need help, feel free to visit Criatura Academy any time."
                                )
                                |> next()
                                |> mes("[Hun]")
                                |> mes(
                                  "There's no requirement or payment to enroll so it would be a great help to you."
                                )
                                |> mes("When you go through this way to the north, you'll find")
                                |> mes(
                                  "<NAVI>[the academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                )
                                |> next()
                                |> mes("[Hun]")
                                |> mes(
                                  "If there are more adventurers like you, the future will be brighter."
                                )
                                |> mes("Hahahaha.")
                                |> next()
                                |> emotion(:surprise)
                                |> mes("[Information Staff]")
                                |> mes("Sorry to interrupt.")
                                |> mes(
                                  "But ^4d4dffif you need location info, please ask me.^000000"
                                )
                                |> next()
                                |> mes("[Information Staff]")
                                |> mes("Hun's information has limits")
                                |> close()

                              throw({:script_end, ctx})

                            3 ->
                              ctx =
                                ctx
                                |> mes("[Hun]")
                                |> mes("You already have a plan laid out?")
                                |> mes("Well prepared.")
                                |> mes(
                                  "But just in case, if you are curious about the Criatura Academy, make a visit."
                                )
                                |> next()
                                |> mes("[Hun]")
                                |> mes("When you go through this way to the north, you'll find")
                                |> mes(
                                  "<NAVI>[the academy building]<INFO>iz_ac01,100,39</INFO></NAVI>."
                                )
                                |> mes("What is well, is well- isn't it?")
                                |> next()
                                |> emotion(:surprise)
                                |> mes("[Information Staff]")
                                |> mes("You are correct.")
                                |> mes("Preperation is the key.")
                                |> mes(
                                  "But ^4d4dffif you need location info, please ask me.^000000"
                                )
                                |> next()
                                |> mes("[Information Staff]")
                                |> mes("Hun's information has limits.")
                                |> close()

                              throw({:script_end, ctx})

                            _ ->
                              ctx
                          end

                        ctx
                      else
                        ctx =
                          ctx
                          |> mes("[Hun]")
                          |> mes(
                            "Criatura Academy is a good place to build up experience for the future."
                          )
                          |> mes("I'm not saying this just because I work here.")
                          |> next()
                          |> mes("[Hun]")
                          |> mes("For real... hahahaha")
                          |> close()

                        throw({:script_end, ctx})
                      end

                    ctx
                  end

                ctx
              end

            ctx
          end

        ctx
      else
        ctx =
          ctx
          |> mes("[Hun]")
          |> mes(
            "The Royal Criatura Academy was founded to help budding adventurers on their initial journey."
          )
          |> next()
          |> mes("[Hun]")
          |> mes(
            "Although I'm but a work-hand here, it makes me happy to see students graduate here and become fine members of society."
          )
          |> close()

        throw({:script_end, ctx})
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_oninit(ctx) do
    questinfo(ctx, 0, 1, fn ctx ->
      class(ctx) == :novice and base_level(ctx) <= 14 and
        not Rathena.truthy?(isbegin_quest(ctx, 7473))
    end)
  end

  def ev_ontouch(ctx) do
    ctx =
      if not Rathena.truthy?(isbegin_quest(ctx, 4269)) do
        emotion(ctx, :surprise)
      else
        emotion(ctx, :smile)
      end

    ctx
  end
end
