defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.FoolishPoring do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:5291 (Foolish Poring#pet_3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "new_1-3",
        x: 105,
        y: 163,
        dir: 5,
        sprite: 2398,
        name: "Foolish Poring",
        scope: :renewal,
        unique_name: "Foolish Poring#pet_3"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
  end
end
