defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.FrightenedTrainee do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:6461 (Frightened Trainee#ac).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "iz_ac02",
        x: 159,
        y: 79,
        dir: 7,
        sprite: 891,
        name: "Frightened Trainee",
        unique_name: "Frightened Trainee#ac"
      },
      %{
        map: "iz_ac02_a",
        x: 159,
        y: 79,
        dir: 7,
        sprite: 891,
        name: "Frightened Trainee",
        unique_name: "Frightened Trainee#ac_a"
      },
      %{
        map: "iz_ac02_b",
        x: 159,
        y: 79,
        dir: 7,
        sprite: 891,
        name: "Frightened Trainee",
        unique_name: "Frightened Trainee#ac_b"
      },
      %{
        map: "iz_ac02_c",
        x: 159,
        y: 79,
        dir: 7,
        sprite: 891,
        name: "Frightened Trainee",
        unique_name: "Frightened Trainee#ac_c"
      },
      %{
        map: "iz_ac02_d",
        x: 159,
        y: 79,
        dir: 7,
        sprite: 891,
        name: "Frightened Trainee",
        unique_name: "Frightened Trainee#ac_d"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx |> mes("[Frightened Trainee]") |> mes("That man looks too scary.") |> close()
  end
end
