defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.InformationStaff do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:1128 (Information Staff#0).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "izlude",
        x: 120,
        y: 207,
        dir: 4,
        sprite: 105,
        name: "Information Staff",
        scope: :renewal,
        unique_name: "Information Staff#0"
      },
      %{
        map: "izlude_a",
        x: 120,
        y: 207,
        dir: 4,
        sprite: 105,
        name: "Information Staff",
        scope: :renewal,
        unique_name: "Information Staff#a"
      },
      %{
        map: "izlude_b",
        x: 120,
        y: 207,
        dir: 4,
        sprite: 105,
        name: "Information Staff",
        scope: :renewal,
        unique_name: "Information Staff#b"
      },
      %{
        map: "izlude_c",
        x: 120,
        y: 207,
        dir: 4,
        sprite: 105,
        name: "Information Staff",
        scope: :renewal,
        unique_name: "Information Staff#c"
      },
      %{
        map: "izlude_d",
        x: 120,
        y: 207,
        dir: 4,
        sprite: 105,
        name: "Information Staff",
        scope: :renewal,
        unique_name: "Information Staff#d"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnInit", ctx) do
    ev_oninit(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx =
      if not Rathena.truthy?(checkweight(ctx, [{1304, 3}])) do
        ctx =
          ctx
          |> mes("Quest cannot be continued due to the invenory being full.")
          |> mes("Please try it again after re-organizing your items.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx =
      if base_level(ctx) < 15 and not Rathena.truthy?(isbegin_quest(ctx, 7474)) do
        {ctx, v1} =
          ctx
          |> mes("[Information Staff]")
          |> mes("Hi, how are you?")
          |> mes("I am in charge of navigation directions for Izlude's key locations")
          |> mes("I wish to propose a simple game along with the navigation, would that be ok?")
          |> next()
          |> select(["Sure, let's play!", "I already know them all."])

        ctx =
          if v1 == 1 do
            ctx =
              ctx
              |> mes("[Information Staff]")
              |> mes("First of all, how to check the mini-map.")
              |> mes(
                "You can check your location through the mini-map at the top right of the screen"
              )
              |> next()
              |> mes("[Information Staff]")
              |> mes(
                "If you receive information on a town or a city, a waypoint ^4d4dff+^000000 can be marked on the map."
              )
              |> next()
              |> mes("[Information Staff]")
              |> mes(
                "Press ^4d4dff[Ctrl] and [ ~ ] on your keyboard and you can see the world map^000000."
              )
              |> next()
              |> mes("[Information Staff]")
              |> mes(
                "Through the ^4d4dffworld map you can check the location of you, your party members and the level of monsters in the area.^000000"
              )
              |> next()
              |> mes("[Information Staff]")
              |> mes("This is useful info to remember.")
              |> mes("Now then, should we play a simple game?")
              |> next()
              |> mes("[Information Staff]")
              |> mes("I will ^4d4dffmark three specific locations on the mini-map.^000000")
              |> mes(
                "Please ^4d4dffvisit those locations ^000000using the waypoints as reference."
              )
              |> next()
              |> mes("[Information Staff]")
              |> mes("Think of it as a treasure hunt and go.")
              |> mes("I've hidden some useful items there.")
              |> viewpoint(1, 179, 75, 1, 13_434_879)
              |> viewpoint(1, 45, 94, 2, 65280)
              |> viewpoint(1, 207, 167, 3, 16_771_910)
              |> setquest(7474)
              |> next()
              |> mes("[Information Staff]")
              |> mes("Vist me again after going by all three locations.")
              |> mes("I will check up on it.")
              |> next()
              |> mes("[Information Staff]")
              |> mes("Ah, there' somebody who started out right before you!")
              |> mes("If you don't hurry that person will take all the items!")
              |> mes("So, run!")
              |> npcskill(29, 10, 10, 10)
              |> close()

            throw({:script_end, ctx})
          else
            ctx
          end

        ctx
        |> mes("[Information Staff]")
        |> mes("Do you need information on all the locations of Izlude?")
        |> mes(
          "By clicking on the introduced ^B9062F[base camp name]^000000, I will offer you guidance so follow the ^B9062FRed Arrows^000000."
        )
        |> next()
        |> loop_1()
      else
        ctx =
          if isbegin_quest(ctx, 7474) == 1 do
            if isbegin_quest(ctx, 7475) + isbegin_quest(ctx, 7476) + isbegin_quest(ctx, 7477) > 2 do
              {ctx, _} =
                ctx
                |> mes("[Information Staff]")
                |> mes("What's with the long face?")
                |> mes("It looks like you found all the locations I marked.")
                |> next()
                |> mes("[Lumin]")
                |> mes("Turtle...")
                |> cutin("nov_lumin01.bmp", 2)
                |> next()
                |> select(["What'd you call me?"])

              {ctx, v5} =
                ctx
                |> mes("[Lumin]")
                |> mes("Because you are too slow.")
                |> mes("Yes, it is. I have been waiting for you for what seems like forever.")
                |> next()
                |> mes("[Lumin]")
                |> mes(".......Shall I share with you?")
                |> cutin("nov_lumin03.bmp", 2)
                |> next()
                |> select(["I don't need your sympathy.", "!!!!!"])

              ctx =
                if v5 == 1 do
                  ctx
                  |> mes("[Lumin]")
                  |> mes("Is that so?")
                  |> mes("Captain always told me to help the poor people.")
                  |> mes("But you get rid of my chance to help.")
                  |> cutin("nov_lumin02.bmp", 2)
                  |> next()
                  |> mes("[Lumin]")
                  |> mes("Ahhh. Irritating.")
                  |> next()
                else
                  ctx =
                    ctx
                    |> mes("[Lumin]")
                    |> mes("Well, now we can divide 7 to 3?")
                    |> mes("I am OK with 6 to 4.")
                    |> cutin("nov_lumin02.bmp", 2)
                    |> next()

                  ctx
                  |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
                  |> mes("This guy...")
                  |> next()
                end

              ctx =
                ctx
                |> cutin("", 255)
                |> mes("[Information Staff]")
                |> mes("Ahhh, you two calm down.")
                |> mes("Lumin took them all.")

              ctx =
                ctx
                |> mes(
                  Rathena.concat(
                    Rathena.concat("", char_name(ctx, 0)),
                    " I will give you one set separately."
                  )
                )
                |> next()
                |> mes("[Information Staff]")
                |> mes(
                  "Think of the reason, it was my fault to leave one person's but sent both of you."
                )
                |> next()
                |> cutin("nov_lumin03.bmp", 2)
                |> mes("[Lumin]")
                |> mes("Simple and fair decision.")
                |> mes("OK. Now I am going.")
                |> mes("See you again, my friend.")
                |> next()
                |> cutin("", 255)
                |> mes("[Information Staff]")
                |> mes("Aren't you two friends?")
                |> mes("You guys both seemed friendly enough right?")
                |> next()
                |> mes("[Information Staff]")
                |> mes("Well, this is my present for you.")
                |> mes("Hope it will be useful.")
                |> completequest(7474)
                |> erasequest(7475)
                |> erasequest(7476)
                |> erasequest(7477)
                |> getexp(300, 20)
                |> give_item(12323, 20)
                |> give_item(12324, 10)
                |> give_item(569, 20)
                |> next()
                |> mes("[Information Staff]")
                |> mes("Have a wonderful journey.")
                |> close()

              throw({:script_end, ctx})
            else
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("You have not found the treasure I hid.")
                |> mes("Here are the locations again.")
                |> mes("Hurry up!")
                |> viewpoint(1, 179, 75, 1, 13_434_879)
                |> viewpoint(1, 45, 94, 2, 65280)
                |> viewpoint(1, 207, 167, 3, 16_771_910)
                |> close()

              throw({:script_end, ctx})
            end
          else
            ctx
            |> mes("[Information Staff]")
            |> mes("This is Izlude - the satellite city of Prontera.")
            |> mes("Do you need directions?")
            |> next()
            |> mes("[Information Staff]")
            |> mes(
              "If you click on the ^B9062F[area name]^000000, I can ^B9062Fnavigate^000000 a path for you to follow."
            )
            |> next()
            |> loop_7()
          end

        ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_oninit(ctx) do
    questinfo(ctx, 0, 1, fn ctx ->
      base_level(ctx) <= 14 and not Rathena.truthy?(isbegin_quest(ctx, 7474))
    end)
  end

  defp loop_3(ctx) do
    result =
      try do
        {ctx, v3} =
          select(ctx, [
            "[ Criatura Academy ]",
            "[ Wharf ]",
            "[ Airship (International) ]",
            "[ Arena ]",
            "[ Shop ]",
            "[ Swordman Guild ]",
            "[ Enchant Association ]",
            "[ Blacksmith's Workshop ]",
            "Go back to the previous menu"
          ])

        ctx =
          case v3 do
            1 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("If you are the first time adventurer,")
                |> mes("<NAVI>[Criatura Academy]<INFO>iz_ac01,100,39,</INFO></NAVI>")
                |> mes("can offer a lot of info and help.")
                |> mes("Do you need additonal directions?")
                |> viewpoint(1, 128, 260, 0, 16_765_545)
                |> next()

              throw({:cont_3, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "Through the <NAVI>[Wharf]<INFO>izlude,197,205,</INFO></NAVI> in the north east,"
                )
                |> mes("^8B4513Alberta^000000 or ^8B4513the Byalan Island^000000 can be visted.")
                |> mes("you can go.")
                |> next()
                |> mes("[Information Staff]")
                |> mes(
                  "Byalan Island is the scary place with ^8B4513Izlude dungeon^000000 in it."
                )
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 197, 205, 1, 16_776_960)
                |> next()

              throw({:cont_3, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("To the southeast, the <NAVI>[Airship]<INFO>izlude,206,75,</INFO></NAVI>")
                |> mes(
                  "will be connected with the Capital of the republic of Schwarzwald -^8B4513 Juno^000000, and"
                )
                |> mes("The capital of the Arunapeltsdom -^8B4513 Rachel ^000000.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 210, 73, 2, 16_714_370)
                |> next()

              throw({:cont_3, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("The <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> located in the east")
                |> mes("is for testing your battle ability.")
                |> mes("It's an excellent place.")
                |> mes("I will mark the location on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 213, 161, 3, 16_777_044)
                |> next()

              throw({:cont_3, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Shop]<INFO>izlude,110,182,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 108, 179, 4, 16_755_455)
                |> next()

              throw({:cont_3, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> is the place to manage the job transfer to a swordman."
                )
                |> mes("I will mark the location of the swordman guild on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 52, 172, 5, 16_767_600)
                |> next()

              throw({:cont_3, ctx})

            7 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Enchant Association]<INFO>izlude,97,125,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 97, 125, 6, 16_767_600)
                |> next()

              throw({:cont_3, ctx})

            8 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Blacksmith's Workshop]<INFO>izlude,153,126,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 153, 126, 7, 16_755_455)
                |> next()

              throw({:cont_3, ctx})

            9 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_3, ctx})
      catch
        :throw, {:brk_3, ctx} -> {:done, ctx}
        :throw, {:cont_3, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_3(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_5(ctx) do
    result =
      try do
        {ctx, v4} =
          select(ctx, [
            "[ Eden Group Teleporter ]",
            "[ Kafra Employee ]",
            "[ Mesmerizer ]",
            "[ Wedding Secretary ]",
            "[ Mercenary Guild Official ]",
            "[ Taming Merchant ]",
            "Go back to the previous menu"
          ])

        ctx =
          case v4 do
            1 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("For now, I will mark the location of the")
                |> mes("<NAVI>[Eden Group Teleporter]<INFO>izlude,131,148,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 131, 148, 8, 16_714_370)
                |> next()

              throw({:cont_5, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Kafra Employee]<INFO>izlude,128,148,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 128, 148, 9, 16_777_044)
                |> next()

              throw({:cont_5, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Mesmerizer]<INFO>izlude,124,127,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 125, 127, 10, 16_711_780)
                |> next()

              throw({:cont_5, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "If you want to visit ^8B4513Jawaii^000000 - the resort place for a couple,"
                )
                |> mes(
                  "talk to the <NAVI>[Wedding Secretary]<INFO>izlude,180,224,</INFO></NAVI>."
                )
                |> mes("Just ask the question about it.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 180, 224, 11, 16_776_960)
                |> next()

              throw({:cont_5, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("If you need to know about the Mercenary Guild, go west and speak to the")
                |> mes("<NAVI>[Mercenary Guild Official]<INFO>izlude,47,170,</INFO></NAVI>.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 47, 170, 12, 16_767_600)
                |> next()

              throw({:cont_5, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Taming Merchant]<INFO>izlude,118,163,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 118, 163, 13, 16_711_780)
                |> next()

              throw({:cont_5, ctx})

            7 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_5, ctx})
      catch
        :throw, {:brk_5, ctx} -> {:done, ctx}
        :throw, {:cont_5, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_5(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_1(ctx) do
    {ctx, v2} =
      select(ctx, [
        "[ Main facilities ]",
        "[ Guide & Helper ]",
        "Mini map marking removal",
        "End Conversation"
      ])

    ctx =
      case v2 do
        1 ->
          loop_3(ctx)

        2 ->
          loop_5(ctx)

        3 ->
          ctx
          |> mes("[Information Staff]")
          |> mes("I will erase the marks.")
          |> mes("Do you need additional directions?")
          |> viewpoint(2, 197, 205, 1, 16_711_680)
          |> viewpoint(2, 210, 73, 2, 16_711_680)
          |> viewpoint(2, 213, 161, 3, 16_711_680)
          |> viewpoint(2, 108, 179, 4, 16_711_680)
          |> viewpoint(2, 52, 172, 5, 16_711_680)
          |> viewpoint(2, 97, 125, 6, 16_711_680)
          |> viewpoint(2, 153, 126, 7, 16_711_680)
          |> viewpoint(2, 131, 148, 8, 16_711_680)
          |> viewpoint(2, 128, 148, 9, 16_711_680)
          |> viewpoint(2, 125, 127, 10, 16_711_680)
          |> viewpoint(2, 180, 224, 11, 16_711_680)
          |> viewpoint(2, 47, 170, 12, 16_711_680)
          |> viewpoint(2, 118, 163, 13, 16_711_680)
          |> next()

        4 ->
          ctx =
            ctx
            |> mes("[Information Staff]")
            |> mes("Have a wonderful adventure.")
            |> mes("Good bye~~!")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    loop_1(ctx)
  end

  defp loop_9(ctx) do
    result =
      try do
        {ctx, v7} =
          select(ctx, [
            "[ Criatura Academy ]",
            "[ Wharf ]",
            "[ Airship (International) ]",
            "[ Arena ]",
            "[ Shop ]",
            "[ Swordman Guild ]",
            "[ Enchant Association ]",
            "[ Blacksmith's Workshop ]",
            "Go back to the previous menu"
          ])

        ctx =
          case v7 do
            1 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("If you are the first time adventurer,")
                |> mes("<NAVI>[Criatura Academy]<INFO>iz_ac01,100,39,</INFO></NAVI>")
                |> mes("can offer a lot of info and help.")
                |> mes("Do you need additonal directions?")
                |> viewpoint(1, 128, 260, 0, 16_765_545)
                |> next()

              throw({:cont_9, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "Through the <NAVI>[Wharf]<INFO>izlude,197,205,</INFO></NAVI> in the north east,"
                )
                |> mes("^8B4513Alberta^000000 or ^8B4513the Byalan Island^000000 can be visted.")
                |> mes("you can go.")
                |> next()
                |> mes("[Information Staff]")
                |> mes(
                  "Byalan Island is the scary place with ^8B4513Izlude dungeon^000000 in it."
                )
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 197, 205, 1, 16_776_960)
                |> next()

              throw({:cont_9, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("To the southeast, the <NAVI>[Airship]<INFO>izlude,206,75,</INFO></NAVI>")
                |> mes(
                  "will be connected with the Capital of the republic of Schwarzwald -^8B4513 Juno^000000, and"
                )
                |> mes("The capital of the Arunapeltsdom -^8B4513 Rachel ^000000.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 210, 73, 2, 16_714_370)
                |> next()

              throw({:cont_9, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("The <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> located in the east")
                |> mes("is for testing your battle ability.")
                |> mes("It's an excellent place.")
                |> mes("I will mark the location on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 213, 161, 3, 16_777_044)
                |> next()

              throw({:cont_9, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Shop]<INFO>izlude,110,182,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 108, 179, 4, 16_755_455)
                |> next()

              throw({:cont_9, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> is the place to manage the job transfer to a swordman."
                )
                |> mes("I will mark the location of the swordman guild on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 52, 172, 5, 16_767_600)
                |> next()

              throw({:cont_9, ctx})

            7 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Enchant Association]<INFO>izlude,97,125,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 97, 125, 6, 16_767_600)
                |> next()

              throw({:cont_9, ctx})

            8 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Blacksmith's Workshop]<INFO>izlude,153,126,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 153, 126, 7, 16_755_455)
                |> next()

              throw({:cont_9, ctx})

            9 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_9, ctx})
      catch
        :throw, {:brk_9, ctx} -> {:done, ctx}
        :throw, {:cont_9, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_9(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_11(ctx) do
    result =
      try do
        {ctx, v8} =
          select(ctx, [
            "[ Eden Group Teleporter ]",
            "[ Kafra Employee ]",
            "[ Mesmerizer ]",
            "[ Wedding Secretary ]",
            "[ Mercenary Guild Official ]",
            "[ Taming Merchant ]",
            "Go back to the previous menu"
          ])

        ctx =
          case v8 do
            1 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("For now, I will mark the location of the")
                |> mes("<NAVI>[Eden Group Teleporter]<INFO>izlude,131,148,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 131, 148, 8, 16_714_370)
                |> next()

              throw({:cont_11, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Kafra Employee]<INFO>izlude,128,148,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 128, 148, 9, 16_777_044)
                |> next()

              throw({:cont_11, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Mesmerizer]<INFO>izlude,124,127,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 125, 127, 10, 16_711_780)
                |> next()

              throw({:cont_11, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes(
                  "If you want to visit ^8B4513Jawaii^000000 - the resort place for a couple,"
                )
                |> mes(
                  "talk to the <NAVI>[Wedding Secretary]<INFO>izlude,180,224,</INFO></NAVI>."
                )
                |> mes("Just ask the question about it.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 180, 224, 11, 16_776_960)
                |> next()

              throw({:cont_11, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("If you need to know about the Mercenary Guild, go west and speak to the")
                |> mes("<NAVI>[Mercenary Guild Official]<INFO>izlude,47,170,</INFO></NAVI>.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 47, 170, 12, 16_767_600)
                |> next()

              throw({:cont_11, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Information Staff]")
                |> mes("I will mark the location of the")
                |> mes("<NAVI>[Taming Merchant]<INFO>izlude,118,163,</INFO></NAVI>")
                |> mes("on the mini map.")
                |> mes("Do you need additional directions?")
                |> viewpoint(1, 118, 163, 13, 16_711_780)
                |> next()

              throw({:cont_11, ctx})

            7 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_11, ctx})
      catch
        :throw, {:brk_11, ctx} -> {:done, ctx}
        :throw, {:cont_11, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_11(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_7(ctx) do
    {ctx, v6} =
      select(ctx, [
        "[ Main facilities ]",
        "[ Guide & Helper ]",
        "Mini map marking removal",
        "End Conversation"
      ])

    ctx =
      case v6 do
        1 ->
          loop_9(ctx)

        2 ->
          loop_11(ctx)

        3 ->
          ctx
          |> mes("[Information Staff]")
          |> mes("I will erase the marks.")
          |> mes("Do you need additional directions?")
          |> viewpoint(2, 197, 205, 1, 16_711_680)
          |> viewpoint(2, 210, 73, 2, 16_711_680)
          |> viewpoint(2, 213, 161, 3, 16_711_680)
          |> viewpoint(2, 108, 179, 4, 16_711_680)
          |> viewpoint(2, 52, 172, 5, 16_711_680)
          |> viewpoint(2, 97, 125, 6, 16_711_680)
          |> viewpoint(2, 153, 126, 7, 16_711_680)
          |> viewpoint(2, 131, 148, 8, 16_711_680)
          |> viewpoint(2, 128, 148, 9, 16_711_680)
          |> viewpoint(2, 125, 127, 10, 16_711_680)
          |> viewpoint(2, 180, 224, 11, 16_711_680)
          |> viewpoint(2, 47, 170, 12, 16_711_680)
          |> viewpoint(2, 118, 163, 13, 16_711_680)
          |> next()

        4 ->
          ctx =
            ctx
            |> mes("[Information Staff]")
            |> mes("Have a wonderful adventure.")
            |> mes("Good bye~~!")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    loop_7(ctx)
  end
end
