defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.Locas do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:13236 (Locas#iz).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "izlude",
        x: 155,
        y: 132,
        dir: 3,
        sprite: 84,
        name: "Locas",
        scope: :renewal,
        unique_name: "Locas#iz"
      },
      %{
        map: "izlude_a",
        x: 155,
        y: 132,
        dir: 3,
        sprite: 84,
        name: "Locas",
        scope: :renewal,
        unique_name: "Locas#iz_a"
      },
      %{
        map: "izlude_b",
        x: 155,
        y: 132,
        dir: 3,
        sprite: 84,
        name: "Locas",
        scope: :renewal,
        unique_name: "Locas#iz_b"
      },
      %{
        map: "izlude_c",
        x: 155,
        y: 132,
        dir: 3,
        sprite: 84,
        name: "Locas",
        scope: :renewal,
        unique_name: "Locas#iz_c"
      },
      %{
        map: "izlude_d",
        x: 155,
        y: 132,
        dir: 3,
        sprite: 84,
        name: "Locas",
        scope: :renewal,
        unique_name: "Locas#iz_d"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if not Rathena.truthy?(checkweight(ctx, [{1301, 1}])) do
        ctx =
          ctx
          |> mes("- As you have too many items in your inventory, Quest can't be continued. -")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx =
      if isbegin_quest(ctx, 5155) == 1 do
        {ctx, _} =
          ctx
          |> mes("[Locas]")
          |> mes("You are the one sent by the owner. What did he order me to do?")
          |> next()
          |> select(["You have a lot of complaints, don't you?"])

        ctx =
          ctx
          |> mes("[Locas]")
          |> mes(
            "Yes, I do. Absolutely, the owner will threaten me with his stupid performance ratings."
          )
          |> next()
          |> mes("[Locas]")
          |> mes("He isn't the man he used to be.")
          |> next()
          |> mes("[Locas]")
          |> mes("He thinks if somebody leaves, a replacement will show up immediately.")
          |> next()
          |> mes("[Locas]")
          |> mes(
            "Anyway, the employee should do what the owner wants him to do... Ask me your questions."
          )
          |> next()
          |> loop_1()
          |> mes("[Locas]")
          |> mes(
            "Seems like, you don't have any further questions. Thank you for listening to a long story."
          )
          |> next()
          |> completequest(5155)
          |> mes("[Locas]")
          |> mes(
            "You can say anything to my owner. The performance rating doesn't mean much to our technicians."
          )
          |> close()

        throw({:script_end, ctx})
      else
        ctx
        |> mes("[Locas]")
        |> mes(
          "If you bring me 5 Rough Oridecon or Elunium, I will immediately make them to Oridecon or Elunium."
        )
        |> next()
      end

    {ctx, v3} = select(ctx, ["Refining Oridecon", "Refining Elunium", "Other questions."])

    ctx =
      case v3 do
        1 ->
          {ctx, v4} =
            ctx
            |> mes("[Locas]")
            |> mes("Will you refine 5 Rough Oridecon to one Oridecon?")
            |> next()
            |> select(["Exchange 5 for 1", "Exchange all."])

          if v4 == 1 do
            if count_item(ctx, 756) > 4 do
              ctx =
                ctx
                |> delitem(756, 5)
                |> give_item(984, 1)
                |> mes("[Locas]")
                |> mes("Refined Rough Oridecon to Oridecon.")
                |> close()

              throw({:script_end, ctx})
            else
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Are you kidding me?")
                |> mes("You should bring me 5 Rough Oridecon to refine for one Oridecon.")
                |> close()

              throw({:script_end, ctx})
            end
          else
            if count_item(ctx, 756) > 4 do
              ctx = set_local(ctx, :ston_max, div(count_item(ctx, 756), 5))
              ctx = set_local(ctx, :ston_full, get_local(ctx, :ston_max, 0) * 5)
              ctx = delitem(ctx, 756, get_local(ctx, :ston_full, 0))
              ctx = ctx |> give_item(984, get_local(ctx, :ston_max, 0)) |> mes("[Locas]")

              ctx =
                ctx
                |> mes(
                  Rathena.concat(
                    Rathena.concat(
                      Rathena.concat(
                        Rathena.concat("Refined ", get_local(ctx, :ston_full, 0)),
                        " Rough Oridecon into "
                      ),
                      get_local(ctx, :ston_max, 0)
                    ),
                    " Oridecon. Thank you for your business."
                  )
                )
                |> close()

              throw({:script_end, ctx})
            else
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Are you kidding me?")
                |> mes("You should bring me 5 Rough Oridecon to refine for one Oridecon.")
                |> close()

              throw({:script_end, ctx})
            end
          end

        2 ->
          {ctx, v5} =
            ctx
            |> mes("[Locas]")
            |> mes("Will you refine 5 Rough Elunium to one Elunium?")
            |> next()
            |> select(["Exchange 5 for 1", "Exchange all."])

          if v5 == 1 do
            if count_item(ctx, 757) > 4 do
              ctx =
                ctx
                |> delitem(757, 5)
                |> give_item(985, 1)
                |> mes("[Locas]")
                |> mes("Refined Rough Elunium to Elunium.")
                |> close()

              throw({:script_end, ctx})
            else
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Are you kidding me?")
                |> mes("You should bring me 5 Rough Elunium to refine for one Elunium.")
                |> close()

              throw({:script_end, ctx})
            end
          else
            if count_item(ctx, 757) > 4 do
              ctx = set_local(ctx, :ston_max, div(count_item(ctx, 757), 5))
              ctx = set_local(ctx, :ston_full, get_local(ctx, :ston_max, 0) * 5)
              ctx = delitem(ctx, 757, get_local(ctx, :ston_full, 0))
              ctx = ctx |> give_item(985, get_local(ctx, :ston_max, 0)) |> mes("[Locas]")

              ctx =
                ctx
                |> mes(
                  Rathena.concat(
                    Rathena.concat(
                      Rathena.concat(
                        Rathena.concat("Refined ", get_local(ctx, :ston_full, 0)),
                        " Rough Elunium into "
                      ),
                      get_local(ctx, :ston_max, 0)
                    ),
                    " Elunium. Thank you for your business."
                  )
                )
                |> close()

              throw({:script_end, ctx})
            else
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Are you kidding me?")
                |> mes("You should bring me 5 Rough Elunium to refine for one Elunium.")
                |> close()

              throw({:script_end, ctx})
            end
          end

        3 ->
          ctx =
            ctx
            |> mes("[Locas]")
            |> mes("Do you have any questions about refining?")
            |> next()
            |> mes("[Locas]")
            |> mes("Though I can't explain a lot.... What's your question?")
            |> next()
            |> loop_6()
            |> mes("[Locas]")
            |> mes("Thank you for your listening to a long story. This is all I can explain you.")
            |> next()
            |> mes("[Locas]")
            |> mes(
              "Regarding the levels of weapons and safety refining, consult with Mr. Tadde. He will kindly answer to you."
            )
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  defp loop_3(ctx) do
    result =
      try do
        {ctx, v2} =
          select(ctx, [
            "Level 1 Weapon",
            "Level 2 Weapon",
            "Level 3 Weapon",
            "level 4 Weapon",
            "Armor",
            "Questions Finished"
          ])

        ctx =
          case v2 do
            1 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining of level 1 weapons requires ^3E86C3Phracon and 1000 zeny^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "As Phracon is the most popular metal, you can get it from monsters but also from Tadde at 200 zeny."
                )
                |> next()

              throw({:cont_3, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining level 2 weapons requires ^3E86C3Emveretarcon and 2,000 zeny^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Emveretarcon is also a relatively popular metal. You can get it either from monsters or from Tadde at 1000 zeny."
                )
                |> next()

              throw({:cont_3, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining of level 3 weapons requires ^3E86C3Oridecon and 10,000 zeny.^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes("Oridecon is such a rare metal that I don't sell it... But,")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "If you have 5 Rough Oridecon obtainable from some monsters, you can refine them to make one Oridecon."
                )
                |> next()

              throw({:cont_3, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining level 4 weapons requires ^3E86C3Oridecon and 20,000 zeny.^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Elunium is as rare a metal as Oridecon, like Oridecon, if you bring me 5 Rough Elunium obtainable from some monsters, I will refine them to make a Elunium for you."
                )
                |> next()

              throw({:cont_3, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Refining the Armor requires ^3E86C3Elunium and 20000 zeny.^000000.")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Elunium is as rare a metal as Oridecon, like Oridecon, if you bring me 5 Rough Elunium obtainable from some monsters, I will refine them to make a Elunium for you."
                )
                |> next()

              throw({:cont_3, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("You look like you've had enough explanations about the refining prices.")
                |> next()

              ctx

            _ ->
              ctx
          end

        throw({:brk_3, ctx})
      catch
        :throw, {:brk_3, ctx} -> {:done, ctx}
        :throw, {:cont_3, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_3(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_1(ctx) do
    result =
      try do
        {ctx, v1} = select(ctx, ["Refining Price", "Refining Effect", "End the Conversation."])

        ctx =
          case v1 do
            1 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Perhaps the most important thing my owner thinks is this...")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "From the word itself, refining price is ^3E86C3the charge to refine once^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "But, there are ^3E86C3differences in the essential material according the zeny and weapon level.^000000."
                )
                |> next()
                |> loop_3()

              throw({:cont_1, ctx})

            2 ->
              {ctx, _} =
                ctx
                |> mes("[Locas]")
                |> mes("I think you are now knowledgeable enough about refining.")
                |> next()
                |> mes("[Locas]")
                |> mes("Now I will explain to you about ^3E86C3the effect of refining^000000.")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "This time I won't give you explanations about individual items. It is better you do the physical experiences by yourself instead of verbal explanations."
                )
                |> next()
                |> mes("[Locas]")
                |> mes("Anyway, here are the explanations. From level 1 weapon,")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "1 level weapon has ^A20B09the attacking power increased 2^000000 by each +1 refining. Do you understand?"
                )
                |> next()
                |> select(["Well???"])

              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("I thought my explanations to you were easy, but it wasn't...")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "So, if you refine a knife with 17 attacking power and by +1, it will become 19 attacking power.. Like this."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "In fact, there is no need to talk too much here. You just experience it later."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Level 2 weapon will add ^A20B093^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Level 3 weapon will add ^A20B095^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Lastly, level 4 weapon will add ^A20B097^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Ah, I missed the Armor. The Armor can be add ^A20B091^000000 to the defense power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Well, by now the explanations were only for the effect of the safe refining...."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "You would better learn yourself ^A20B09the effect of over refining^000000 regardless of potential risk."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "If I tell you all the details, it is likely you start reading an epic novel of 10,000 pages, I'll tell you the ending of it."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "One thing to be clear is you should be careful about destroying your equipment if you get over-eager."
                )
                |> next()

              throw({:cont_1, ctx})

            3 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_1, ctx})
      catch
        :throw, {:brk_1, ctx} -> {:done, ctx}
        :throw, {:cont_1, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_1(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_8(ctx) do
    result =
      try do
        {ctx, v7} =
          select(ctx, [
            "Level 1 Weapon",
            "Level 2 Weapon",
            "Level 3 Weapon",
            "Level 4 Weapon",
            "Armor",
            "Question Finished"
          ])

        ctx =
          case v7 do
            1 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining of level 1 weapons requires ^3E86C3Phracon and 1000 zeny^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "As Phracon is the most popular metal, you can get it from monsters but also from Tadde at 200 zeny."
                )
                |> next()

              throw({:cont_8, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining level 2 weapons requires ^3E86C3Emveretarcon and 20,000 zeny^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Emveretarcon is also a relatively popular metal. You can get it either from monsters or from Tadde at 1000 zeny."
                )
                |> next()

              throw({:cont_8, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining of level 3 weapons requires ^3E86C3Oridecon and 10,000 zeny.^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes("Oridecon is such a rare metal that I don't sell it... But,")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "If you have 5 Rough Oridecon obtainable from some monsters, you can refine them to make one Oridecon."
                )
                |> next()

              throw({:cont_8, ctx})

            4 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "Refining level 4 weapons requires ^3E86C3Oridecon and 20,000 zeny.^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Elunium is as rare a metal as Oridecon, like Oridecon, if you bring me 5 Rough Elunium obtainable from some monsters, I will refine them to make a Elunium for you."
                )
                |> next()

              throw({:cont_8, ctx})

            5 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("Refining the Armor requires ^3E86C3Elunium and 20000 zeny.^000000.")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Elunium is as rare a metal as Oridecon, like Oridecon, if you bring me 5 Rough Elunium obtainable from some monsters, I will refine them to make a Elunium for you."
                )
                |> next()

              throw({:cont_8, ctx})

            6 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("You look like you've had enough explanations about the refining prices.")
                |> next()

              ctx

            _ ->
              ctx
          end

        throw({:brk_8, ctx})
      catch
        :throw, {:brk_8, ctx} -> {:done, ctx}
        :throw, {:cont_8, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_8(ctx)
      {:done, ctx} -> ctx
    end
  end

  defp loop_6(ctx) do
    result =
      try do
        {ctx, v6} = select(ctx, ["Refining price", "Refining effect", "Finish the explanation."])

        ctx =
          case v6 do
            1 ->
              ctx =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "From the word itself, refining price is ^3E86C3the price for refining once^000000."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "But, there are differences in the essential material according the (zeny) and weapon level."
                )
                |> next()
                |> loop_8()

              throw({:cont_6, ctx})

            2 ->
              {ctx, _} =
                ctx
                |> mes("[Locas]")
                |> mes(
                  "As I think it would be better for you to experience the effect of refining rather than explantion, I really give you a brief explanation about it."
                )
                |> next()
                |> mes("[Locas]")
                |> mes("Let's start from level 1 weapon.")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "1 level weapon has ^A20B09the attacking power increased 2^000000 by each +1 refining. Do you understand?"
                )
                |> next()
                |> select(["Well???"])

              ctx =
                ctx
                |> mes("[Locas]")
                |> mes("I thought my explanations to you were easy, but it wasn't...")
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "So, if you refine a knife with 17 attacking power and by +1, it will become 19 attacking power.. Like this."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "In fact, there is no need to talk too much here. You just experience it later."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Level 2 weapon will add ^A20B093^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Level 3 weapon will add ^A20B095^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Lastly, level 4 weapon will add ^A20B097^000000 to the attacking power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Ah, I missed the Armor. The Armor can be add ^A20B091^000000 to the defense power per each refining level."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "Well, by now the explanations were only for the effect of the safe refining...."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "You would better learn yourself ^A20B09the effect of over refining^000000 regardless of potential risk."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "If I tell you all the details, it is likely you start reading an epic novel of 10,000 pages, I'll tell you the ending of it."
                )
                |> next()
                |> mes("[Locas]")
                |> mes(
                  "One thing to be clear is you should be careful about destroying your equipment if you get over-eager."
                )
                |> next()

              throw({:cont_6, ctx})

            3 ->
              ctx

            _ ->
              ctx
          end

        throw({:brk_6, ctx})
      catch
        :throw, {:brk_6, ctx} -> {:done, ctx}
        :throw, {:cont_6, ctx} -> {:next, ctx}
      end

    case result do
      {:next, ctx} -> loop_6(ctx)
      {:done, ctx} -> ctx
    end
  end
end
