defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.Npc11 do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:11920 (#nbacStone01).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "iz_ac02", x: 1, y: 1, dir: 0, sprite: 844, name: "", unique_name: "#nbacStone01"},
      %{
        map: "iz_ac02_a",
        x: 1,
        y: 1,
        dir: 0,
        sprite: 844,
        name: "",
        unique_name: "#nbacStone01_a"
      },
      %{
        map: "iz_ac02_b",
        x: 1,
        y: 1,
        dir: 0,
        sprite: 844,
        name: "",
        unique_name: "#nbacStone01_b"
      },
      %{
        map: "iz_ac02_c",
        x: 1,
        y: 1,
        dir: 0,
        sprite: 844,
        name: "",
        unique_name: "#nbacStone01_c"
      },
      %{
        map: "iz_ac02_d",
        x: 1,
        y: 1,
        dir: 0,
        sprite: 844,
        name: "",
        unique_name: "#nbacStone01_d"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  def on_event("OnReset", ctx), do: ev_onreset(ctx)
  def on_event("OnMyMobDead", ctx), do: ev_onmymobdead(ctx)
  def on_event("OnTimer5000", ctx), do: ev_ontimer5000(ctx)
  def on_event("OnSpawn", ctx), do: ev_onspawn(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_oninit(ctx) do
    ctx
    |> donpcevent(Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnSpawn"))
    |> setcell("iz_ac02", 58, 142, 63, 144, :icewall, 1)
  end

  def ev_onreset(ctx) do
    ctx =
      killmonster(
        ctx,
        to_string(strnpcinfo(ctx, 4)),
        Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
      )

    donpcevent(ctx, Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnSpawn"))
  end

  def ev_onmymobdead(ctx) do
    ctx =
      set_local(
        ctx,
        :dead_num,
        mobcount(
          ctx,
          Rathena.concat(Rathena.concat("", strnpcinfo(ctx, 4)), ""),
          Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
        )
      )

    ctx =
      if get_local(ctx, :dead_num, 0) < 1 do
        initnpctimer(ctx)
      else
        ctx
      end

    ctx
  end

  def ev_ontimer5000(ctx) do
    ctx = stopnpctimer(ctx)
    donpcevent(ctx, Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnSpawn"))
  end

  def ev_onspawn(ctx) do
    ctx =
      summon_mob(ctx,
        mob_id: 1725,
        map: to_string(strnpcinfo(ctx, 4)),
        at: {59, 143},
        event: Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
      )

    ctx =
      summon_mob(ctx,
        mob_id: 1725,
        map: to_string(strnpcinfo(ctx, 4)),
        at: {60, 143},
        event: Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
      )

    ctx =
      summon_mob(ctx,
        mob_id: 1725,
        map: to_string(strnpcinfo(ctx, 4)),
        at: {61, 143},
        event: Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
      )

    summon_mob(ctx,
      mob_id: 1725,
      map: to_string(strnpcinfo(ctx, 4)),
      at: {62, 143},
      event: Rathena.concat(Rathena.concat("#", strnpcinfo(ctx, 2)), "::OnMyMobDead")
    )
  end
end
