defmodule Aesir.ZoneServer.Content.Npc.Re.Jobs.Novice.Academy.WoundedSwordsman do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/academy.txt:67 (Wounded Swordsman#intro_npc01_iz_int).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "iz_int",
        x: 56,
        y: 32,
        dir: 3,
        sprite: 687,
        name: "Wounded Swordsman",
        unique_name: "Wounded Swordsman#intro_npc01_iz_int",
        trigger: {5, 5}
      },
      %{
        map: "iz_int01",
        x: 56,
        y: 32,
        dir: 3,
        sprite: 687,
        name: "Wounded Swordsman",
        unique_name: "Wounded Swordsman#intro_npc01_iz_int01",
        trigger: {5, 5}
      },
      %{
        map: "iz_int02",
        x: 56,
        y: 32,
        dir: 3,
        sprite: 687,
        name: "Wounded Swordsman",
        unique_name: "Wounded Swordsman#intro_npc01_iz_int02",
        trigger: {5, 5}
      },
      %{
        map: "iz_int03",
        x: 56,
        y: 32,
        dir: 3,
        sprite: 687,
        name: "Wounded Swordsman",
        unique_name: "Wounded Swordsman#intro_npc01_iz_int03",
        trigger: {5, 5}
      },
      %{
        map: "iz_int04",
        x: 56,
        y: 32,
        dir: 3,
        sprite: 687,
        name: "Wounded Swordsman",
        unique_name: "Wounded Swordsman#intro_npc01_iz_int04",
        trigger: {5, 5}
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  @impl true
  def on_talk(ctx) do
    ctx = ctx |> npctalk("Oh...", target: :self) |> cloakonnpc()
    cloakoffnpcself(ctx, Rathena.concat("Wounded Swordsman#intro_npc02_", strnpcinfo(ctx, 4)))
  end

  def ev_ontouch(ctx) do
    ctx
    |> npctalk("Urgh... please... help me...", target: :self)
    |> sleep2(500)
    |> npctalk("In order to talk with me.. click my body..", target: :self)
  end

  def ev_oninit(ctx) do
    questinfo(ctx, 0, 1, fn ctx ->
      not Rathena.truthy?(isbegin_quest(ctx, 21001)) and class(ctx) == :novice
    end)
  end
end
