defmodule Aesir.ZoneServer.Content.Npc.Cities.Morocc.VolunteerMorocc do
  @moduledoc """
  Transpiled from rAthena cities/morocc.txt:49 (Volunteer - Morocc#01).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "morocc",
        x: 202,
        y: 244,
        dir: 0,
        sprite: 745,
        name: "Volunteer - Morocc",
        scope: :shared,
        unique_name: "Volunteer - Morocc#01"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Morocc Volunteer]")
    |> mes(
      "After that terrible incident wiped out the entire Morocc, Rune-Midgarts Kingdom has gathered us volunteers to help restorations."
    )
    |> next()
    |> mes("[Morocc Volunteer]")
    |> mes(
      "As important as it seems, everyone's being careful but there are always some that really don't realize the situation, don't you think?"
    )
    |> close()
  end
end
