defmodule Aesir.ZoneServer.Npc.Transpiler.Codegen do
  @moduledoc """
  Emits an Elixir NPC module from a parsed rAthena script body.

  Translation model:

  - Statements thread `ctx` by rebinding (`ctx = mes(ctx, "…")`), mirroring
    the hand-written NPC style.
  - `close`/`end` terminate the script by exiting the interaction process
    (`exit(:normal)`), exactly like rAthena stops execution there; the
    interaction Task treats it as a clean end. `close2`/`close3` flush the
    CLOSE frame and continue.
  - Top-level labels split the body into segments. `goto`/`menu` targets
    become private functions that never return (they end in `exit(:normal)`
    or fall through by tail-calling the next segment), which makes `goto`
    safe from any nesting depth. `callsub` targets become subroutines
    returning `{ctx, value}`.
  - Loops become recursive helper functions; `break`/`continue` compile to
    `throw` only when they occur nested below the loop body's top level.
  - Blocking or effectful calls in expression position (`select`,
    `callfunc`, local functions, `++`) are hoisted into bindings above the
    statement, so expression rendering stays pure.
  - Unsupported buildins emit `todo(ctx, name, args)` (statement) or
    `Todo.call!(name, args)` (expression); unresolved constants emit
    `Todo.const!(name)`. All raise `NotImplementedError` when reached.

  The emitter keeps its per-run state (temp counter, deferred function
  definitions, usage flags) in the process dictionary; `generate/2` resets it,
  and transpilation is a single-process mix task.
  """

  alias Aesir.ZoneServer.Npc.Transpiler.Analyzer
  alias Aesir.ZoneServer.Npc.Transpiler.CommandMap
  alias Aesir.ZoneServer.Npc.Transpiler.ModuleName
  alias Aesir.ZoneServer.Npc.Transpiler.Parser
  alias Aesir.ZoneServer.Npc.Transpiler.Resolver

  @comparisons %{==: "==", !=: "!=", <: "<", <=: "<=", >: ">", >=: ">="}
  @arith %{+: "+", -: "-", *: "*"}
  @bitwise %{&: "band", |: "bor", ^: "bxor", shl: "bsl", shr: "bsr"}

  @typedoc """
  Options: `:module` (full module name string), `:spawns` (resolved placement
  maps for the `use` line; `[]` for floating/functions), `:kind`
  (`:script | :floating | :function`), `:functions` (global `callfunc` name →
  module map), `:source` (file:line provenance for the moduledoc).
  """
  @type opts :: map()

  @spec generate(String.t(), opts()) :: {:ok, String.t()} | {:error, term()}
  def generate(body, opts) do
    with {:ok, ast} <- Parser.parse_body(body) do
      analysis = Analyzer.analyze(ast)
      reset_state()

      env = %{
        a: analysis,
        fns: Map.get(opts, :functions, %{}),
        labels: label_fns(analysis),
        sub: opts.kind == :function,
        break: nil,
        loop: nil
      }

      source = build_module(ast, env, opts)
      {:ok, IO.iodata_to_binary(Code.format_string!(source)) <> "\n"}
    end
  rescue
    e -> {:error, {:codegen, Exception.message(e)}}
  end

  # -- module assembly ---------------------------------------------------------

  defp build_module(ast, env, opts) do
    {main, segments} = segment(ast, env)
    {main_lines, main_terminal} = emit_block(main, env)
    main_body = main_lines ++ fall_through(main_terminal, segments, env)

    segment_defs = emit_segments(segments, env)
    deferred = get_defs()

    entry =
      case opts.kind do
        :function -> function_entry(main_body)
        _ -> on_talk_entry(main_body)
      end

    events = for {:event, name, _} <- segments, do: name

    """
    defmodule #{opts.module} do
      @moduledoc \"\"\"
      Transpiled from rAthena #{opts.source}.

      Regenerated by `mix aesir.import.npcs`; hand edits are detected through
      the transpile manifest and future imports land in `_conflicts/` instead
      of overwriting them.
      \"\"\"

      #{header(opts)}
      #{aliases()}
      #{unwired_events(events)}
      #{entry}
      #{Enum.join(segment_defs, "\n\n")}
      #{Enum.join(deferred, "\n\n")}
    end
    """
  end

  defp header(%{kind: :function}), do: "import Aesir.ZoneServer.Script.Dsl"

  defp header(opts) do
    spawns = Enum.map_join(opts.spawns, ",\n", &render_spawn/1)
    "use Aesir.ZoneServer.Npc, spawn: [#{spawns}]"
  end

  defp render_spawn(s) do
    ~s(%{map: #{inspect(s.map)}, x: #{s.x}, y: #{s.y}, dir: #{s.dir}, ) <>
      ~s(sprite: #{s.sprite}, name: #{inspect(s.name)}})
  end

  defp aliases do
    [
      flag?(:rathena) && "alias Aesir.ZoneServer.Script.Rathena",
      flag?(:todo_mod) && "alias Aesir.ZoneServer.Script.Todo"
    ]
    |> Enum.filter(& &1)
    |> Enum.join("\n")
  end

  defp unwired_events([]), do: ""

  defp unwired_events(events) do
    """
    @doc "rAthena event labels present in the source but not wired to engine hooks yet."
    def unwired_events, do: #{inspect(events)}
    """
  end

  defp on_talk_entry(body_lines) do
    """
    @impl true
    def on_talk(#{param(body_lines)}) do
      #{join_body(body_lines)}
    end
    """
  end

  defp function_entry(body_lines) do
    body = join_body(body_lines)
    args = if String.contains?(body, "args"), do: "args", else: "_args"

    """
    @doc "Callable rAthena global function; returns `{ctx, return_value}`."
    def call(#{param(body_lines)}, #{args}) do
      #{body}
    end
    """
  end

  # A `ctx = ...` rebinding whose value is only followed by `exit(:normal)`
  # (the `close2; warp; end` idiom, or an if/case feeding a trailing `end`
  # command) is dead; unbind it to keep generated modules warning-free.
  defp join_body(lines), do: lines |> tidy() |> tidy_block_bind() |> Enum.join("\n")

  defp tidy([<<"ctx = ", expr::binary>>, "exit(:normal)" | rest]),
    do: ["_ = " <> expr, "exit(:normal)" | tidy(rest)]

  defp tidy([line | rest]), do: [line | tidy(rest)]
  defp tidy([]), do: []

  # `ctx = if ... do … end` (or a standalone `ctx =` before `case`/`try`)
  # immediately followed by `exit(:normal)`: locate the block opener by
  # depth-matching the emitted lines and drop the binding.
  defp tidy_block_bind(lines) do
    arr = List.to_tuple(lines)

    0..(tuple_size(arr) - 1)
    |> Enum.filter(fn i ->
      elem(arr, i) == "exit(:normal)" and i > 0 and elem(arr, i - 1) == "end"
    end)
    |> Enum.reduce(lines, fn i, acc ->
      case find_opener(arr, i - 1) do
        nil -> acc
        opener -> unbind_at(acc, arr, opener)
      end
    end)
  end

  defp find_opener(arr, end_idx) do
    Enum.reduce_while((end_idx - 1)..0//-1, 1, fn i, depth ->
      line = elem(arr, i)

      cond do
        line == "end" -> {:cont, depth + 1}
        not String.ends_with?(line, " do") -> {:cont, depth}
        depth == 1 -> {:halt, {:found, i}}
        true -> {:cont, depth - 1}
      end
    end)
    |> case do
      {:found, i} -> i
      _ -> nil
    end
  end

  defp unbind_at(lines, arr, opener) do
    cond do
      String.starts_with?(elem(arr, opener), "ctx = ") ->
        List.update_at(lines, opener, &("_ = " <> String.trim_leading(&1, "ctx = ")))

      opener > 0 and elem(arr, opener - 1) == "ctx =" ->
        List.replace_at(lines, opener - 1, "_ =")

      true ->
        lines
    end
  end

  defp param(body_lines) do
    if Enum.any?(body_lines, &String.contains?(&1, "ctx")), do: "ctx", else: "_ctx"
  end

  # Inside a subroutine/function body, helper functions (loops, label
  # segments) thread the enclosing `args` through so `getarg` keeps working.
  defp helper_call(%{sub: true}), do: ", args"
  defp helper_call(_env), do: ""

  defp helper_params(lines, %{sub: true}) do
    args = if Enum.any?(lines, &String.contains?(&1, "args")), do: "args", else: "_args"
    "#{param(lines)}, #{args}"
  end

  defp helper_params(lines, _env), do: param(lines)

  # -- segmentation ------------------------------------------------------------

  # Splits top-level statements at labels that need their own function:
  # jump targets, callsub targets and event labels. Other labels are inert.
  # A label closes the segment being accumulated and opens its own.
  defp segment(stmts, env) do
    {segs, {kind, name, acc}} =
      Enum.reduce(stmts, {[], {:main, nil, []}}, fn
        {:label, label} = stmt, {segs, {kind, name, acc}} ->
          case segment_kind(label, env.a) do
            nil -> {segs, {kind, name, [stmt | acc]}}
            new_kind -> {[{kind, name, Enum.reverse(acc)} | segs], {new_kind, label, []}}
          end

        stmt, {segs, {kind, name, acc}} ->
          {segs, {kind, name, [stmt | acc]}}
      end)

    [{:main, nil, main} | rest] = Enum.reverse([{kind, name, Enum.reverse(acc)} | segs])
    {main, rest}
  end

  defp segment_kind(name, analysis) do
    cond do
      MapSet.member?(analysis.callsub_targets, name) -> :sub
      MapSet.member?(analysis.jump_targets, name) -> :jump
      String.starts_with?(name, "On") -> :event
      true -> nil
    end
  end

  defp emit_segments(segments, env) do
    segments
    |> Enum.with_index()
    |> Enum.map(fn {{kind, name, stmts}, idx} ->
      next = Enum.at(segments, idx + 1)
      emit_segment(kind, name, stmts, next, env)
    end)
  end

  defp emit_segment(:sub, name, stmts, _next, env) do
    {lines, terminal} = emit_block(stmts, %{env | sub: true})
    lines = lines ++ if terminal == :cont, do: ["{ctx, nil}"], else: []
    args = if Enum.any?(lines, &String.contains?(&1, "args")), do: "args", else: "_args"

    """
    defp #{fn_name(env, name)}(#{param(lines)}, #{args}) do
      #{join_body(lines)}
    end
    """
  end

  defp emit_segment(kind, name, stmts, next, env) do
    {lines, terminal} = emit_block(stmts, env)
    lines = lines ++ fall_through(terminal, List.wrap(next), env)
    visibility = if kind == :event, do: "def", else: "defp"

    """
    #{visibility} #{fn_name(env, name)}(#{helper_params(lines, env)}) do
      #{join_body(lines)}
    end
    """
  end

  # A label function that runs off its end falls through into the next
  # segment; the last one (or a fall into a subroutine) ends the script.
  defp fall_through(terminal, _next, _env) when terminal != :cont, do: []
  defp fall_through(:cont, [], _env), do: ["ctx"]

  defp fall_through(:cont, [{:jump, name, _} | _], env),
    do: ["#{fn_name(env, name)}(ctx#{helper_call(env)})"]

  # Falling into an event label ends normal flow (events run on their own
  # engine triggers, not as dialog continuation).
  defp fall_through(:cont, [{:event, _, _} | _], _env), do: ["ctx"]

  defp fall_through(:cont, [{:sub, name, _} | _], env),
    do: ["{ctx, _} = #{fn_name(env, name)}(ctx, [])", "ctx"]

  # Label → emitted function name, deduplicated case-insensitively.
  defp label_fns(analysis) do
    analysis.labels
    |> Enum.reduce({%{}, MapSet.new()}, fn label, {map, taken} ->
      prefix =
        cond do
          MapSet.member?(analysis.callsub_targets, label) -> "s_"
          String.starts_with?(label, "On") -> "ev_"
          true -> "l_"
        end

      base = prefix <> ModuleName.slug(label)
      name = if MapSet.member?(taken, base), do: base <> "_#{map_size(map)}", else: base
      {Map.put(map, label, name), MapSet.put(taken, name)}
    end)
    |> elem(0)
  end

  defp fn_name(env, label), do: Map.fetch!(env.labels, label)

  # -- statement emission ------------------------------------------------------

  # Emits a statement list; returns `{lines, terminal}` where terminal is
  # `:cont` (flow continues), `:stop` (close/end/goto/return — nothing runs
  # after), `:break` or `:continue` (loop control reached top level).
  # Statements after a terminal are dead code and dropped.
  defp emit_block(stmts, env) do
    Enum.reduce_while(stmts, {[], :cont}, fn stmt, {lines, :cont} ->
      {new_lines, terminal} = emit_stmt(stmt, env)

      case terminal do
        :cont -> {:cont, {lines ++ new_lines, :cont}}
        other -> {:halt, {lines ++ new_lines, other}}
      end
    end)
  end

  defp emit_stmt({:block, stmts}, env), do: emit_block(stmts, env)
  defp emit_stmt({:label, _}, _env), do: {[], :cont}
  defp emit_stmt({:fn_decl, _}, _env), do: {[], :cont}

  # Expression statement: evaluate for effects (hoisting) and discard.
  defp emit_stmt({:expr, expr}, env) do
    {pre, _expr} = hoist(expr, env)
    {pre, :cont}
  end

  defp emit_stmt({:function, name, stmts}, env) do
    {lines, terminal} = emit_block(stmts, %{env | sub: true, break: nil, loop: nil})
    lines = lines ++ if terminal == :cont, do: ["{ctx, nil}"], else: []
    args = if Enum.any?(lines, &String.contains?(&1, "args")), do: "args", else: "_args"

    defer("""
    defp #{local_fn_name(name)}(#{param(lines)}, #{args}) do
      #{join_body(lines)}
    end
    """)

    {[], :cont}
  end

  defp emit_stmt({:goto, label}, env) do
    if Map.has_key?(env.labels, label) do
      {["#{fn_name(env, label)}(ctx#{helper_call(env)})"], :stop}
    else
      flag(:todo_fun)
      {["ctx = todo(ctx, :goto, [#{inspect(label)}])"], :cont}
    end
  end

  defp emit_stmt({:menu, pairs}, env) do
    {pre, texts} = hoist_all(Enum.map(pairs, &elem(&1, 0)), env)
    options = "[" <> Enum.map_join(texts, ", ", &render_str(&1, env)) <> "]"

    clauses =
      pairs
      |> Enum.with_index(1)
      |> Enum.map(fn {{_, label}, idx} ->
        if Map.has_key?(env.labels, label) do
          "#{idx} -> #{fn_name(env, label)}(ctx#{helper_call(env)})"
        else
          flag(:todo_fun)
          "#{idx} -> todo(ctx, :goto, [#{inspect(label)}])"
        end
      end)

    lines =
      pre ++
        ["{ctx, choice} = select(ctx, #{options})", ""] ++
        ["case choice do"] ++ clauses ++ ["_ -> ctx", "end"]

    {lines, :stop}
  end

  defp emit_stmt({:return, expr}, %{sub: true} = env) do
    {pre, expr} = hoist(expr, env)
    {pre ++ ["{ctx, #{if expr, do: render(expr, env), else: "nil"}}"], :stop}
  end

  defp emit_stmt({:return, _}, _env), do: {["exit(:normal)"], :stop}

  defp emit_stmt({:break}, %{break: nil}), do: {[], :cont}
  defp emit_stmt({:break}, %{break: {:throw, tag}}), do: {["throw({:#{tag}, ctx})"], :stop}
  defp emit_stmt({:break}, %{break: :plain}), do: {[], :break}

  defp emit_stmt({:continue}, %{loop: nil}), do: {[], :cont}
  defp emit_stmt({:continue}, %{loop: {:throw, tag}}), do: {["throw({:#{tag}, ctx})"], :stop}
  defp emit_stmt({:continue}, %{loop: :plain}), do: {[], :continue}

  defp emit_stmt({:if, cond_expr, then_stmts, else_stmts}, env) do
    {pre, cond_expr} = hoist(cond_expr, env)
    {then_lines, then_t} = emit_block(then_stmts, env)
    {else_lines, else_t} = emit_block(else_stmts, env)

    then_body = branch_body(then_lines, then_t)
    else_body = branch_body(else_lines, else_t)

    terminal = merge_terminal(then_t, else_t)
    bind = if terminal == :cont, do: "ctx =", else: ""

    lines =
      pre ++
        ["#{bind} if #{cond_str(cond_expr, env)} do"] ++
        then_body ++ ["else"] ++ else_body ++ ["end"]

    {lines, terminal}
  end

  defp emit_stmt({:switch, expr, clauses}, env), do: emit_switch(expr, clauses, env)
  defp emit_stmt({:while, cond_expr, body}, env), do: emit_loop(:while, cond_expr, [], body, env)

  defp emit_stmt({:do_while, body, cond_expr}, env),
    do: emit_loop(:do_while, cond_expr, [], body, env)

  defp emit_stmt({:for, init, cond_expr, step, body}, env) do
    {init_lines, :cont} = emit_block(init, env)
    {loop_lines, terminal} = emit_loop(:while, cond_expr, step, body, env)
    {init_lines ++ loop_lines, terminal}
  end

  defp emit_stmt({:assign, target, expr}, env), do: emit_assign(target, expr, env)

  # -- command statements --

  defp emit_stmt({:cmd, "mes", args}, env) do
    {pre, args} = hoist_all(args, env)
    text = args |> Enum.map(&render_str(&1, env)) |> concat_all()
    {pre ++ ["ctx = mes(ctx, #{text})"], :cont}
  end

  defp emit_stmt({:cmd, "next", _}, _env), do: {["ctx = next(ctx)"], :cont}
  defp emit_stmt({:cmd, "close", _}, _env), do: {["close(ctx)", "exit(:normal)"], :stop}
  defp emit_stmt({:cmd, "end", _}, _env), do: {["exit(:normal)"], :stop}

  defp emit_stmt({:cmd, close2, _}, _env) when close2 in ["close2", "close3"],
    do: {["ctx = close(ctx)"], :cont}

  defp emit_stmt({:cmd, select, args}, env) when select in ["select", "prompt"] do
    {pre, args} = hoist_all(args, env)
    {pre ++ ["{ctx, _} = select(ctx, #{options(args, env)})"], :cont}
  end

  defp emit_stmt({:cmd, "input", [target | _]}, env) do
    kind = if str_target?(target), do: ":string", else: ":int"
    tmp = tmp_var()
    {input_line, :cont} = {["{ctx, #{tmp}} = input(ctx, #{kind})"], :cont}
    {assign_lines, :cont} = emit_assign(target, {:temp, tmp}, env)
    {input_line ++ assign_lines, :cont}
  end

  defp emit_stmt({:cmd, "setarray", [target | values]}, env) do
    {pre, values} = hoist_all(values, env)
    rendered = "[" <> Enum.map_join(values, ", ", &render(&1, env)) <> "]"

    case target do
      {:index, base, {:int, 0}} ->
        {pre ++ [set_var(base, rendered, env)], :cont}

      {:index, base, start} ->
        start = render(start, env)
        flag(:rathena)

        lines =
          values
          |> Enum.with_index()
          |> Enum.map(fn {v, i} ->
            set_var(
              base,
              "Rathena.put_at(#{read_var(base, "[]", env)}, #{start} + #{i}, #{render(v, env)}, 0)",
              env
            )
          end)

        {pre ++ lines, :cont}

      _ ->
        {pre ++ [set_var(target, rendered, env)], :cont}
    end
  end

  defp emit_stmt({:cmd, "callsub", [{:name, label} | args]}, env) do
    {pre, args} = hoist_all(args, env)
    rendered = Enum.map_join(args, ", ", &render(&1, env))
    {pre ++ ["{ctx, _} = #{fn_name(env, label)}(ctx, [#{rendered}])"], :cont}
  end

  defp emit_stmt({:cmd, "callfunc", [{:str, fname} | args]}, env) do
    {pre, args} = hoist_all(args, env)
    rendered = Enum.map_join(args, ", ", &render(&1, env))

    case Map.fetch(env.fns, fname) do
      {:ok, module} ->
        {pre ++ ["{ctx, _} = #{module}.call(ctx, [#{rendered}])"], :cont}

      :error ->
        flag(:todo_fun)
        {pre ++ ["ctx = todo(ctx, :callfunc, [#{inspect(fname)}, #{rendered}])"], :cont}
    end
  end

  defp emit_stmt({:cmd, name, args}, env) do
    cond do
      MapSet.member?(env.a.local_functions, name) ->
        {pre, args} = hoist_all(args, env)
        rendered = Enum.map_join(args, ", ", &render(&1, env))
        {pre ++ ["{ctx, _} = #{local_fn_name(name)}(ctx, [#{rendered}])"], :cont}

      match?({:ok, _}, CommandMap.command(name)) ->
        {:ok, rule} = CommandMap.command(name)
        emit_mapped(name, rule, args, env)

      true ->
        {pre, args} = hoist_all(args, env)
        rendered = Enum.map_join(args, ", ", &render(&1, env))
        {pre ++ ["ctx = todo(ctx, #{atom_lit(name)}, [#{rendered}])"], :cont}
    end
  end

  defp atom_lit(name), do: inspect(String.to_atom(name))

  # -- mapped commands ---------------------------------------------------------

  defp emit_mapped(_name, %{shape: :heal, dsl: dsl}, args, env) do
    {pre, args} = hoist_all(args, env)
    [hp, sp] = (args ++ [{:int, 0}, {:int, 0}]) |> Enum.take(2)
    {pre ++ ["ctx = #{dsl}(ctx, hp: #{render(hp, env)}, sp: #{render(sp, env)})"], :cont}
  end

  defp emit_mapped(_name, %{shape: :warp}, [{:str, target} | rest], env) do
    case CommandMap.warp_target(target) do
      {:ok, atom_form} ->
        {["ctx = warp(ctx, #{atom_form})"], :cont}

      :error ->
        {pre, rest} = hoist_all(rest, env)
        coords = Enum.map_join(rest, ", ", &render(&1, env))
        {pre ++ ["ctx = warp(ctx, #{inspect(target)}, #{coords})"], :cont}
    end
  end

  defp emit_mapped(name, %{shape: :warp}, args, env) do
    {pre, args} = hoist_all(args, env)
    rendered = Enum.map_join(args, ", ", &render(&1, env))
    {pre ++ ["ctx = todo(ctx, #{atom_lit(name)}, [#{rendered}])"], :cont}
  end

  defp emit_mapped(_name, %{dsl: dsl, args: types}, args, env) do
    {pre, args} = hoist_all(args, env)

    rendered =
      args
      |> Enum.zip(types ++ List.duplicate(:int, max(length(args) - length(types), 0)))
      |> Enum.map(fn {arg, type} -> typed_arg(arg, type, env) end)

    {pre ++ ["ctx = #{dsl}(ctx, #{Enum.join(rendered, ", ")})"], :cont}
  end

  defp typed_arg({:int, n}, _type, _env), do: to_string(n)

  defp typed_arg(arg, :item, env) do
    case arg do
      {:str, s} -> resolve_or_const(&Resolver.item/1, s)
      {:name, s} -> resolve_or_const(&Resolver.item/1, s)
      other -> render(other, env)
    end
  end

  defp typed_arg({:name, s}, :status, _env) do
    case Resolver.status(s) do
      {:ok, atom} -> inspect(atom)
      :error -> const_todo(s)
    end
  end

  defp typed_arg(arg, :skill_opts, env), do: render(arg, env)
  defp typed_arg(arg, _type, env), do: render(arg, env)

  defp resolve_or_const(resolver, symbol) do
    case resolver.(symbol) do
      {:ok, value} -> to_string(value)
      :error -> const_todo(symbol)
    end
  end

  defp const_todo(symbol) do
    flag(:todo_mod)
    "Todo.const!(#{inspect(String.to_atom(symbol))})"
  end

  # -- switch ------------------------------------------------------------------

  defp emit_switch(expr, clauses, env) do
    {pre, expr} = hoist(expr, env)
    id = next_id()
    effective = effective_clauses(clauses, env)
    nested_break? = Enum.any?(effective, fn {_, stmts} -> nested_break?(stmts) end)

    clause_env =
      if nested_break?,
        do: %{env | break: {:throw, "brk_#{id}"}},
        else: %{env | break: :plain}

    {clause_lines, terminals} =
      effective
      |> Enum.map(fn {values, stmts} ->
        {lines, terminal} = emit_block(strip_trailing_break(stmts), clause_env)
        {clause_head(values, env) ++ branch_body(lines, terminal), terminal}
      end)
      |> Enum.unzip()

    default? = Enum.any?(effective, fn {values, _} -> :default in values end)
    catch_all = if default?, do: [], else: ["_ -> ctx"]

    {tmp, bindings} =
      case expr do
        {:temp, name} -> {name, []}
        _ -> tmp_var() |> then(fn t -> {t, ["#{t} = #{render(expr, env)}", ""]} end)
      end

    case_lines = ["case #{tmp} do"] ++ List.flatten(clause_lines) ++ catch_all ++ ["end"]

    lines =
      if nested_break? do
        pre ++
          bindings ++
          ["ctx =", "try do"] ++
          case_lines ++ ["catch", ":throw, {:brk_#{id}, ctx} -> ctx", "end"]
      else
        pre ++ bindings ++ ["ctx ="] ++ case_lines
      end

    terminal = if Enum.all?(terminals, &(&1 == :stop)) and default?, do: :stop, else: :cont
    {lines, terminal}
  end

  # C fall-through: a clause body that does not end the flow continues into
  # the next clause's body; materialize that by appending it.
  defp effective_clauses(clauses, _env) do
    clauses
    |> Enum.reverse()
    |> Enum.reduce([], fn {values, stmts}, acc ->
      stmts =
        if falls_through?(stmts) and acc != [] do
          {_, next_stmts} = hd(acc)
          stmts ++ next_stmts
        else
          stmts
        end

      [{values, stmts} | acc]
    end)
  end

  defp falls_through?(stmts) do
    case List.last(stmts) do
      {:break} -> false
      {:cmd, c, _} when c in ["close", "end"] -> false
      {:goto, _} -> false
      {:menu, _} -> false
      {:return, _} -> false
      _ -> true
    end
  end

  defp strip_trailing_break(stmts) do
    case List.last(stmts) do
      {:break} -> Enum.drop(stmts, -1)
      _ -> stmts
    end
  end

  # break below the clause's top level (inside if/blocks) needs a throw;
  # nested loops and switches own their breaks.
  defp nested_break?(stmts), do: Enum.any?(stmts, &stmt_has_nested_break?/1)

  defp stmt_has_nested_break?({:if, _, t, e}),
    do: has_break?(t) or has_break?(e)

  defp stmt_has_nested_break?({:block, stmts}), do: has_break?(stmts)
  defp stmt_has_nested_break?(_), do: false

  defp has_break?(stmts) do
    Enum.any?(stmts, fn
      {:break} -> true
      {:if, _, t, e} -> has_break?(t) or has_break?(e)
      {:block, b} -> has_break?(b)
      _ -> false
    end)
  end

  defp clause_head(values, env) do
    ints = Enum.filter(values, &match?({:int, _}, &1))

    cond do
      :default in values ->
        ["_ ->"]

      length(ints) == length(values) and length(ints) == 1 ->
        ["#{render(hd(ints), env)} ->"]

      length(ints) == length(values) ->
        ["v when v in [#{Enum.map_join(ints, ", ", &render(&1, env))}] ->"]

      true ->
        guards = Enum.map_join(values, " or ", fn v -> "v == #{render(v, env)}" end)
        ["v when #{guards} ->"]
    end
  end

  # -- loops -------------------------------------------------------------------

  defp emit_loop(kind, cond_expr, step, body, env) do
    id = next_id()
    fname = "loop_#{id}"
    needs_try = loop_needs_try?(body)

    loop_env =
      if needs_try do
        %{env | break: {:throw, "brk_#{id}"}, loop: {:throw, "cont_#{id}"}}
      else
        %{env | break: :plain, loop: :plain}
      end

    {body_lines, terminal} = emit_block(body, loop_env)
    {step_lines, :cont} = emit_block(step, env)
    {cond_pre, cond_expr} = hoist(cond_expr, env)

    if cond_pre != [] do
      # A blocking call in a loop condition (e.g. `while(select(...))`) would
      # need re-hoisting per iteration; punt to a stub rather than mistranslate.
      {["ctx = todo(ctx, :loop_with_blocking_condition, [])"], :cont}
    else
      cond_s = cond_str(cond_expr, env)

      # What runs when an iteration completes: while loops step and recurse
      # (the condition guards the body); do-while recurses conditionally.
      recurse = "#{fname}(ctx#{helper_call(env)})"

      on_next =
        case kind do
          :while -> step_lines ++ [recurse]
          :do_while -> ["if #{cond_s} do", recurse, "else", "ctx", "end"]
        end

      body = loop_body(body_lines, terminal, on_next, needs_try, id)

      inner =
        case kind do
          :while -> ["if #{cond_s} do"] ++ body ++ ["else", "ctx", "end"]
          :do_while -> body
        end

      defer("""
      defp #{fname}(#{helper_params(inner, env)}) do
        #{join_body(inner)}
      end
      """)

      {["ctx = #{fname}(ctx#{helper_call(env)})"], :cont}
    end
  end

  defp loop_body(body_lines, terminal, on_next, false = _needs_try, _id) do
    case terminal do
      :break -> body_lines ++ ["ctx"]
      :stop -> body_lines
      _ -> body_lines ++ on_next
    end
  end

  defp loop_body(body_lines, terminal, on_next, true = _needs_try, id) do
    wrapped =
      case terminal do
        :stop -> body_lines
        :break -> body_lines ++ ["{:done, ctx}"]
        _ -> body_lines ++ ["{:next, ctx}"]
      end

    ["result ="] ++
      ["try do"] ++
      wrapped ++
      [
        "catch",
        ":throw, {:brk_#{id}, ctx} -> {:done, ctx}",
        ":throw, {:cont_#{id}, ctx} -> {:next, ctx}",
        "end",
        "",
        "case result do",
        "{:next, ctx} -> " <> Enum.join(on_next, "\n")
      ] ++
      ["{:done, ctx} -> ctx", "end"]
  end

  defp loop_needs_try?(body) do
    Enum.any?(body, fn
      {:break} -> false
      {:continue} -> false
      stmt -> stmt_reaches_loop_ctl?(stmt)
    end)
  end

  defp stmt_reaches_loop_ctl?({:if, _, t, e}), do: any_loop_ctl?(t) or any_loop_ctl?(e)
  defp stmt_reaches_loop_ctl?({:block, b}), do: any_loop_ctl?(b)

  defp stmt_reaches_loop_ctl?({:switch, _, clauses}),
    do: Enum.any?(clauses, fn {_, stmts} -> any_continue?(stmts) end)

  defp stmt_reaches_loop_ctl?(_), do: false

  defp any_loop_ctl?(stmts) do
    Enum.any?(stmts, fn
      {:break} -> true
      {:continue} -> true
      stmt -> stmt_reaches_loop_ctl?(stmt)
    end)
  end

  # switch absorbs break but continue passes through to the loop
  defp any_continue?(stmts) do
    Enum.any?(stmts, fn
      {:continue} -> true
      {:if, _, t, e} -> any_continue?(t) or any_continue?(e)
      {:block, b} -> any_continue?(b)
      {:switch, _, clauses} -> Enum.any?(clauses, fn {_, s} -> any_continue?(s) end)
      _ -> false
    end)
  end

  # -- assignment --------------------------------------------------------------

  defp emit_assign({:name, "Zeny"}, {:bin, :-, {:name, "Zeny"}, amount}, env) do
    {pre, amount} = hoist(amount, env)
    {pre ++ ["ctx = pay_zeny(ctx, #{render(amount, env)})"], :cont}
  end

  defp emit_assign({:name, "Zeny"}, {:bin, :+, {:name, "Zeny"}, amount}, env) do
    {pre, amount} = hoist(amount, env)
    {pre ++ ["ctx = credit_zeny(ctx, #{render(amount, env)})"], :cont}
  end

  defp emit_assign(target, expr, env) do
    {pre, expr} = hoist(expr, env)

    lines =
      case target do
        {:var, _, _, _} ->
          [set_var(target, render(expr, env), env)]

        {:name, name} ->
          case CommandMap.read(name) do
            {:ok, _} ->
              flag(:todo_fun)
              ["ctx = todo(ctx, :set_param, [#{inspect(name)}, #{render(expr, env)}])"]

            :error ->
              [set_var(target, render(expr, env), env)]
          end

        {:index, base, index} ->
          flag(:rathena)

          [
            set_var(
              base,
              "Rathena.put_at(#{read_var(base, "[]", env)}, #{render(index, env)}, " <>
                "#{render(expr, env)}, #{pad_default(base)})",
              env
            )
          ]

        other ->
          flag(:todo_fun)
          ["ctx = todo(ctx, :assign, [#{inspect(inspect(other))}, #{render(expr, env)}])"]
      end

    {pre ++ lines, :cont}
  end

  # Writes routed by scope: local → ctx map, session → player session,
  # bare name → permanent char var, everything else → stub.
  defp set_var({:var, :local, name, type}, value, _env),
    do: "ctx = set_local(ctx, #{var_key(name, type)}, #{value})"

  defp set_var({:var, :session, name, type}, value, _env),
    do: "ctx = set_temp_var(ctx, #{var_key(name, type)}, #{value})"

  defp set_var({:var, scope, name, _type}, value, _env) do
    flag(:todo_fun)
    "ctx = todo(ctx, :set_var, [#{inspect(scope_prefix(scope) <> name)}, #{value}])"
  end

  defp set_var({:name, name}, value, _env),
    do: "ctx = set_char_var(ctx, #{inspect(String.to_atom(name))}, #{value})"

  defp set_var(other, value, _env),
    do: "ctx = todo(ctx, :dynamic_var, [#{inspect(inspect(other))}, #{value}])"

  defp read_var({:var, :local, name, type}, default, _env),
    do: "get_local(ctx, #{var_key(name, type)}, #{default})"

  defp read_var({:var, :session, name, type}, default, _env),
    do: "get_temp_var(ctx, #{var_key(name, type)}, #{default})"

  defp read_var({:var, scope, name, _type}, _default, _env) do
    flag(:todo_mod)
    "Todo.call!(:get_var, [#{inspect(scope_prefix(scope) <> name)}])"
  end

  defp read_var({:name, name}, default, _env),
    do: "get_char_var(ctx, #{inspect(String.to_atom(name))}, #{default})"

  # Dynamic variable references (getd/setd and friends) have no static name.
  defp read_var(other, _default, _env) do
    flag(:todo_mod)
    "Todo.call!(:dynamic_var, [#{inspect(inspect(other))}])"
  end

  defp var_key(name, :str), do: inspect(String.to_atom(name <> "$"))
  defp var_key(name, _), do: inspect(String.to_atom(name))

  defp scope_prefix(:server), do: "$"
  defp scope_prefix(:server_temp), do: "$@"
  defp scope_prefix(:account), do: "#"
  defp scope_prefix(:account_global), do: "##"
  defp scope_prefix(:npc), do: "."
  defp scope_prefix(:instance), do: "'"

  defp pad_default({:var, _, _, :str}), do: ~s("")
  defp pad_default({:name, name}), do: if(String.ends_with?(name, "$"), do: ~s(""), else: "0")
  defp pad_default(_), do: "0"

  defp str_target?({:var, _, _, :str}), do: true
  defp str_target?({:name, name}), do: String.ends_with?(name, "$")
  defp str_target?(_), do: false

  # -- hoisting ----------------------------------------------------------------

  # Pulls blocking/effectful subexpressions (select, callfunc, local function
  # calls, postfix ++/--) out of an expression into `{ctx, vN} =` bindings so
  # rendering stays pure. Returns {pre_lines, expr'}.
  defp hoist(nil, _env), do: {[], nil}

  defp hoist(expr, env) do
    {expr, pre} = hoist_walk(expr, env, [])
    {Enum.reverse(pre), expr}
  end

  defp hoist_all(exprs, env) do
    {pres, exprs} =
      Enum.reduce(exprs, {[], []}, fn expr, {pres, acc} ->
        {pre, expr} = hoist(expr, env)
        {pres ++ pre, acc ++ [expr]}
      end)

    {pres, exprs}
  end

  defp hoist_walk({:call, select, args}, env, pre) when select in ["select", "prompt"] do
    {args, pre} = hoist_list(args, env, pre)
    tmp = tmp_var()
    {{:temp, tmp}, ["{ctx, #{tmp}} = select(ctx, #{options(args, env)})" | pre]}
  end

  defp hoist_walk({:call, "callfunc", [{:str, fname} | args]}, env, pre) do
    {args, pre} = hoist_list(args, env, pre)
    rendered = Enum.map_join(args, ", ", &render(&1, env))
    tmp = tmp_var()

    case Map.fetch(env.fns, fname) do
      {:ok, module} ->
        {{:temp, tmp}, ["{ctx, #{tmp}} = #{module}.call(ctx, [#{rendered}])" | pre]}

      :error ->
        flag(:todo_mod)
        {{:temp, tmp}, ["#{tmp} = Todo.call!(:callfunc, [#{inspect(fname)}, #{rendered}])" | pre]}
    end
  end

  defp hoist_walk({:call, "callsub", [{:name, label} | args]}, env, pre) do
    {args, pre} = hoist_list(args, env, pre)
    rendered = Enum.map_join(args, ", ", &render(&1, env))
    tmp = tmp_var()
    {{:temp, tmp}, ["{ctx, #{tmp}} = #{fn_name(env, label)}(ctx, [#{rendered}])" | pre]}
  end

  defp hoist_walk({:call, name, args}, env, pre) do
    if MapSet.member?(env.a.local_functions, name) do
      {args, pre} = hoist_list(args, env, pre)
      rendered = Enum.map_join(args, ", ", &render(&1, env))
      tmp = tmp_var()
      {{:temp, tmp}, ["{ctx, #{tmp}} = #{local_fn_name(name)}(ctx, [#{rendered}])" | pre]}
    else
      {args, pre} = hoist_list(args, env, pre)
      {{:call, name, args}, pre}
    end
  end

  defp hoist_walk({:post_inc, target}, env, pre), do: hoist_postfix(target, "+", env, pre)
  defp hoist_walk({:post_dec, target}, env, pre), do: hoist_postfix(target, "-", env, pre)

  defp hoist_walk({:bin, op, l, r}, env, pre) do
    {l, pre} = hoist_walk(l, env, pre)
    {r, pre} = hoist_walk(r, env, pre)
    {{:bin, op, l, r}, pre}
  end

  defp hoist_walk({:ternary, c, t, f}, env, pre) do
    {c, pre} = hoist_walk(c, env, pre)
    {t, pre} = hoist_walk(t, env, pre)
    {f, pre} = hoist_walk(f, env, pre)
    {{:ternary, c, t, f}, pre}
  end

  defp hoist_walk({:index, b, i}, env, pre) do
    {b, pre} = hoist_walk(b, env, pre)
    {i, pre} = hoist_walk(i, env, pre)
    {{:index, b, i}, pre}
  end

  defp hoist_walk({:neg, e}, env, pre) do
    {e, pre} = hoist_walk(e, env, pre)
    {{:neg, e}, pre}
  end

  defp hoist_walk({:not, e}, env, pre) do
    {e, pre} = hoist_walk(e, env, pre)
    {{:not, e}, pre}
  end

  defp hoist_walk({:bnot, e}, env, pre) do
    {e, pre} = hoist_walk(e, env, pre)
    {{:bnot, e}, pre}
  end

  defp hoist_walk(leaf, _env, pre), do: {leaf, pre}

  defp hoist_list(exprs, env, pre) do
    Enum.reduce(exprs, {[], pre}, fn expr, {acc, pre} ->
      {expr, pre} = hoist_walk(expr, env, pre)
      {acc ++ [expr], pre}
    end)
  end

  defp hoist_postfix(target, op, env, pre) do
    tmp = tmp_var()
    read = read_var(target, pad_default(target), env)
    set = set_var(target, "#{tmp} #{op} 1", env)
    {{:temp, tmp}, [set, "#{tmp} = #{read}" | pre]}
  end

  # -- expression rendering ----------------------------------------------------

  defp render({:temp, name}, _env), do: name
  defp render({:int, n}, _env), do: to_string(n)
  defp render({:str, s}, _env), do: inspect(s)
  defp render({:neg, e}, env), do: "-(#{render(e, env)})"
  defp render({:bnot, e}, env), do: ":erlang.bnot(#{render(e, env)})"

  defp render({:var, _, _, _} = var, _env), do: read_var(var, var_default(var), nil)

  defp render({:name, name}, env) do
    with :error <- read_name(name),
         :error <- Resolver.constant(name) do
      read_var({:name, name}, name_default(name), env)
    else
      {:ok, rendered} -> rendered
    end
  end

  defp render({:index, base, index}, env),
    do: "Enum.at(#{read_var(base, "[]", env)}, #{render(index, env)}, #{pad_default(base)})"

  defp render({:ternary, c, t, f}, env),
    do: "(if #{cond_str(c, env)}, do: #{render(t, env)}, else: #{render(f, env)})"

  defp render({:not, _} = e, env), do: bool_value(e, env)

  defp render({:bin, op, _, _} = e, env) when is_map_key(@comparisons, op),
    do: bool_value(e, env)

  defp render({:bin, op, _, _} = e, env) when op in [:&&, :||], do: bool_value(e, env)

  defp render({:bin, :+, l, r} = e, env) do
    if stringy?(e) do
      flag(:rathena)
      "Rathena.concat(#{render(l, env)}, #{render(r, env)})"
    else
      "(#{render(l, env)} + #{render(r, env)})"
    end
  end

  defp render({:bin, op, l, r}, env) when is_map_key(@arith, op),
    do: "(#{render(l, env)} #{@arith[op]} #{render(r, env)})"

  defp render({:bin, :/, l, r}, env), do: "div(#{render(l, env)}, #{render(r, env)})"
  defp render({:bin, :%, l, r}, env), do: "rem(#{render(l, env)}, #{render(r, env)})"

  defp render({:bin, op, l, r}, env) when is_map_key(@bitwise, op),
    do: ":erlang.#{@bitwise[op]}(#{render(l, env)}, #{render(r, env)})"

  defp render({:call, "getarg", [index]}, %{sub: true} = env),
    do: "Enum.at(args, #{render(index, env)}, 0)"

  defp render({:call, "getarg", [index, default]}, %{sub: true} = env),
    do: "Enum.at(args, #{render(index, env)}, #{render(default, env)})"

  defp render({:call, "getarg", args}, env) do
    flag(:todo_mod)
    "Todo.call!(:getarg, [#{Enum.map_join(args, ", ", &render(&1, env))}])"
  end

  defp render({:call, "rand", [max]}, env),
    do: ":rand.uniform(#{render(max, env)}) - 1"

  defp render({:call, "rand", [lo, hi]}, env),
    do: "Enum.random(#{render(lo, env)}..#{render(hi, env)})"

  defp render({:call, "getarraysize", [array]}, env),
    do: "length(#{read_var(array, "[]", env)})"

  defp render({:call, name, args}, env) do
    case CommandMap.call_read(name) do
      {:ok, %{dsl: dsl, args: types}} ->
        rendered =
          args
          |> Enum.zip(types ++ List.duplicate(:int, max(length(args) - length(types), 0)))
          |> Enum.map(fn {arg, type} -> typed_arg(arg, type, env) end)

        "#{dsl}(ctx, #{Enum.join(rendered, ", ")})"

      :error ->
        flag(:todo_mod)
        "Todo.call!(#{atom_lit(name)}, [#{Enum.map_join(args, ", ", &render(&1, env))}])"
    end
  end

  # Anything the renderer has no shape for becomes a raising stub, keeping
  # one exotic expression from failing the whole entry.
  defp render(other, _env) do
    flag(:todo_mod)
    "Todo.call!(:expr, [#{inspect(inspect(other))}])"
  end

  defp read_name(name) do
    case CommandMap.read(name) do
      {:ok, fun} -> {:ok, "#{fun}(ctx)"}
      :error -> :error
    end
  end

  defp var_default({:var, _, _, :str}), do: ~s("")
  defp var_default(_), do: "0"

  defp name_default(name), do: if(String.ends_with?(name, "$"), do: ~s(""), else: "0")

  defp bool_value(e, env) do
    flag(:rathena)
    "Rathena.bool_int(#{cond_str(e, env)})"
  end

  # Renders an expression in boolean (condition) position.
  defp cond_str({:bin, op, l, r}, env) when is_map_key(@comparisons, op),
    do: "#{render(l, env)} #{@comparisons[op]} #{render(r, env)}"

  defp cond_str({:bin, :&&, l, r}, env), do: "(#{cond_str(l, env)}) and (#{cond_str(r, env)})"
  defp cond_str({:bin, :||, l, r}, env), do: "(#{cond_str(l, env)}) or (#{cond_str(r, env)})"
  defp cond_str({:not, e}, env), do: "not (#{cond_str(e, env)})"
  defp cond_str({:int, 0}, _env), do: "false"
  defp cond_str({:int, _}, _env), do: "true"

  defp cond_str(e, env) do
    flag(:rathena)
    "Rathena.truthy?(#{render(e, env)})"
  end

  # A string-typed subtree turns `+` into concatenation.
  defp stringy?({:str, _}), do: true
  defp stringy?({:var, _, _, :str}), do: true
  defp stringy?({:name, name}), do: String.ends_with?(name, "$")
  defp stringy?({:bin, :+, l, r}), do: stringy?(l) or stringy?(r)
  defp stringy?({:index, base, _}), do: stringy?(base)
  defp stringy?({:ternary, _, t, f}), do: stringy?(t) or stringy?(f)
  defp stringy?(_), do: false

  defp render_str(e, env) do
    cond do
      stringy?(e) or match?({:temp, _}, e) -> render(e, env)
      match?({:int, _}, e) -> inspect(to_string(elem(e, 1)))
      true -> "to_string(#{render(e, env)})"
    end
  end

  defp concat_all([single]), do: single

  defp concat_all(parts) do
    flag(:rathena)
    Enum.reduce(parts, fn part, acc -> "Rathena.concat(#{acc}, #{part})" end)
  end

  # rAthena select options: each literal argument may itself be a
  # `"a:b:c"`-separated list; dynamic arguments split at runtime.
  defp options(args, env) do
    if Enum.all?(args, &match?({:str, _}, &1)) do
      args
      |> Enum.flat_map(fn {:str, s} -> String.split(s, ":") end)
      |> inspect()
    else
      case args do
        [single] ->
          "String.split(#{render_str(single, env)}, \":\")"

        many ->
          rendered = Enum.map_join(many, ", ", &render_str(&1, env))
          "Enum.flat_map([#{rendered}], &String.split(&1, \":\"))"
      end
    end
  end

  defp branch_body(lines, :cont), do: lines ++ ["ctx"]
  defp branch_body(lines, _terminal), do: lines

  defp merge_terminal(:stop, :stop), do: :stop
  defp merge_terminal(_, _), do: :cont

  defp local_fn_name(name), do: "fn_" <> ModuleName.slug(name)

  # -- emitter state (process dictionary; reset per generate/2) ----------------

  defp reset_state do
    Process.put(:codegen_tmp, 0)
    Process.put(:codegen_id, 0)
    Process.put(:codegen_defs, [])
    Process.put(:codegen_flags, MapSet.new())
  end

  defp tmp_var do
    n = Process.get(:codegen_tmp) + 1
    Process.put(:codegen_tmp, n)
    "v#{n}"
  end

  defp next_id do
    n = Process.get(:codegen_id) + 1
    Process.put(:codegen_id, n)
    n
  end

  defp defer(def_string) do
    Process.put(:codegen_defs, Process.get(:codegen_defs) ++ [def_string])
    :ok
  end

  defp get_defs, do: Process.get(:codegen_defs)

  defp flag(name) do
    Process.put(:codegen_flags, MapSet.put(Process.get(:codegen_flags), name))
    :ok
  end

  defp flag?(name), do: MapSet.member?(Process.get(:codegen_flags), name)
end
