defmodule Aesir.ZoneServer.Content.Npc.Veins.OldLady do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:241 (Old lady#ve1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "veins", x: 232, y: 169, dir: 5, sprite: 942, name: "Old lady"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Old Lady]")
    |> mes("When I look down on")
    |> mes("Veins from here, I've")
    |> mes("come to realize many things.")
    |> mes("I don't think you'd understand")
    |> mes("no matter how much I explained.")
    |> next()
    |> mes("[Old Lady]")
    |> mes("I suppose it's one of those")
    |> mes("things that you learn with age.")
    |> mes("Yes, there's no substitute for")
    |> mes("experience when it comes to")
    |> mes("some things. You'll see.")
    |> mes("^FFFFFFYes, like secret knowledge.^000000")
    |> close()

    exit(:normal)
  end
end
