defmodule Aesir.ZoneServer.Content.Npc.Veins.OldMan16163 do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:498 (Old Man#ve5).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "veins", x: 161, y: 63, dir: 3, sprite: 945, name: "Old Man"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Old Man]")
    |> mes("Oh. You must be")
    |> mes("sightseeing. Um,")
    |> mes("Veins is a small town,")
    |> mes("visit Cheshrumnir Temple?")
    |> next()
    |> mes("[Old Man]")
    |> mes("I hope you enjoy")
    |> mes("your stay. Now if")
    |> mes("you'll excuse me, I'd")
    |> mes("like to continue with")
    |> mes("my prayers to Freya.")
    |> next()
    |> mes("[Old Man]")
    |> mes("Oh, gracious Freya, your")
    |> mes("servant humbly beseeches")
    |> mes("you on bended knee...")
    |> mes("Heal me of this infirmity!")
    |> mes("The body is droopingly limp,")
    |> mes("but the spirit is willing...!")
    |> mes("must be... Cheshrumnir Temple.")
    |> close()

    exit(:normal)
  end
end
