defmodule Aesir.ZoneServer.Content.Npc.Veins.OldMan191134 do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:314 (Old Man#ve3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "veins", x: 191, y: 134, dir: 3, sprite: 945, name: "Old Man"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Old Man]")
    |> mes("Why don't you take")
    |> mes("a look at my goods?")
    |> mes("I've got many things")
    |> mes("that might interest you~")
    |> next()
    |> mes("[Old Man]")
    |> mes("Praise be to Freya,")
    |> mes("who watches over us,")
    |> mes("and blesses us with")
    |> mes("food and drink. Don't")
    |> mes("you think that's great,")
    |> mes("young adventurer?")
    |> close()
  end
end
