defmodule Aesir.ZoneServer.Content.Npc.EinIn01.Rombell do
  @moduledoc """
  Transpiled from rAthena cities/einbroch.txt:661 (Rombell#ein).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "ein_in01", x: 36, y: 204, dir: 3, sprite: 851, name: "Rombell"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Rombell]")
    |> mes("It's great that the")
    |> mes("factory is making good")
    |> mes("business and drawing")
    |> mes("in a lot of profit, but I still")
    |> mes("have one major concern.")
    |> next()
    |> mes("[Rombell]")
    |> mes("The amount of pollution")
    |> mes("that this place is causing")
    |> mes("is horrific! We've got these")
    |> mes("machines blowing out toxic")
    |> mes("gas all day long! The air")
    |> mes("can't be safe for very long...")
    |> next()
    |> mes("[Rombell]")
    |> mes("I mean, the air we're")
    |> mes("breathing right now is")
    |> mes("pretty foul and things")
    |> mes("are only going to get")
    |> mes("worse. How can we")
    |> mes("solve this problem?")
    |> close()
  end
end
