defmodule Aesir.ZoneServer.Content.Npc.Cities.Lighthalzen.Enoz do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:1361 (Enoz#oz).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "lhz_in01",
        x: 139,
        y: 40,
        dir: 7,
        sprite: 53,
        name: "Enoz",
        scope: :shared,
        unique_name: "Enoz#oz"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Enoz]")
    |> mes("So, the novel I ordered from")
    |> mes("the Rune-Midgarts Kingdom")
    |> mes("just recently arrived. It's real good, by the guy who wrote")
    |> mes("''Roda Frog Adventure''")
    |> mes("years ago. Remember?")
    |> next()
    |> mes("[Enoz]")
    |> mes("Anyway, this new book,")
    |> mes("''Where the Red Plant Grows''")
    |> mes("is up for the Yggdrasilberry")
    |> mes("Award. I... I don't know why")
    |> mes("I was compelled to share that")
    |> mes("with you. Seriously, I don't...")
    |> close()
  end
end
