defmodule Aesir.ZoneServer.Content.Npc.Cities.Lighthalzen.Guard do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:1743 (Guard#01::LhzRekGuard).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "lhz_in01",
        x: 173,
        y: 28,
        dir: 4,
        sprite: 868,
        name: "Guard",
        unique_name: "LhzRekGuard"
      },
      %{
        map: "lhz_in01",
        x: 180,
        y: 28,
        dir: 4,
        sprite: 868,
        name: "Guard",
        unique_name: "Guard#03"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Guard]")
    |> mes("This is a")
    |> mes("restricted area.")
    |> mes("Please keep clear")
    |> mes("if you do not have")
    |> mes("special authorization.")
    |> mes("Thank you for your cooperating.")
    |> close()
  end
end
