defmodule Aesir.ZoneServer.Content.Npc.Cities.Lighthalzen.Harp do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:760 (Harp#zen8).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "lhz_in02",
        x: 221,
        y: 276,
        dir: 1,
        sprite: 869,
        name: "Harp",
        scope: :shared,
        unique_name: "Harp#zen8"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Harp]")
    |> mes("Oh sweet jiminy...")
    |> mes("That Kafra Lady is so hot.")
    |> mes("What a body. And those glasses.")
    |> mes("I just gotta ask her out somehow.")
    |> next()
    |> mes("[Harp]")
    |> mes("Hm, but what should")
    |> mes("I do? A love letter? Naw,")
    |> mes("that's kind of outdated.")
    |> mes("Argh, I can't think! Just")
    |> mes("looking at her makes me feel")
    |> mes("so happy! Praise be to Kafra!")
    |> close()
  end
end
