defmodule Aesir.ZoneServer.Content.Npc.Cities.Lighthalzen.Rocky do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:2385 (Rocky#li_house).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "lhz_in03",
        x: 100,
        y: 18,
        dir: 3,
        sprite: 81,
        name: "Rocky",
        scope: :shared,
        unique_name: "Rocky#li_house"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      if Enum.random(1..2) == 1 do
        ctx = ctx |> mes("[Rocky]") |> mes("Woof woof!") |> close()
        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("[Rocky]") |> mes("Grrrrrrr...") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
