defmodule Aesir.ZoneServer.Content.Npc.Cities.Lighthalzen.Ruth do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:91 (Ruth#zen4).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "lighthalzen",
        x: 261,
        y: 112,
        dir: 3,
        sprite: 862,
        name: "Ruth",
        unique_name: "Ruth#zen4"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      ctx
      |> mes("[Ruth]")
      |> mes("Sweety, isn't it")
      |> mes("nice to be together")
      |> mes("under this beautiful")
      |> mes("sunlight? It's perfect")
      |> mes("for our date. Ahhhh~")
      |> next()
      |> mes("[Ruth]")
      |> mes("I'm so happy to be")
      |> mes("with you. I feel like")
      |> mes("I'm just melting with")
      |> mes("happiness. Oh, I love")
      |> mes("you so much, Oyoung.")
      |> next()

    ctx
    |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
    |> mes("Whoa...")
    |> mes("This couple is")
    |> mes("really headed for")
    |> mes("Cloud 9, aren't they?")
    |> close()
  end
end
