Mimic.copy(Aesir.ZoneServer.Unit.MovementEngine)
Mimic.copy(Aesir.ZoneServer.Unit.Movement)
Mimic.copy(Aesir.ZoneServer.Unit.SpatialIndex)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Stats)
Mimic.copy(Aesir.ZoneServer.Unit.Player.PlayerState)
Mimic.copy(Aesir.ZoneServer.Map.MapCache)
Mimic.copy(Aesir.ZoneServer.Map.MapData)
Mimic.copy(Aesir.ZoneServer.Pathfinding)
Mimic.copy(Aesir.ZoneServer.Unit.Player.PlayerSession)
Mimic.copy(Aesir.ZoneServer.Unit.UnitRegistry)
Mimic.copy(Aesir.ZoneServer.Unit.Mob.MobSession)
Mimic.copy(Aesir.ZoneServer.Unit.Mob.MobSupervisor)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusEffect.Interpreter)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusEffect.Helpers)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusStorage)
Mimic.copy(Aesir.ZoneServer.Mmo.Combat)
Mimic.copy(Aesir.ZoneServer.Mmo.Combat.DamageCalculator)
Mimic.copy(Aesir.ZoneServer.Mmo.Combat.MagicDamageCalculator)
Mimic.copy(Aesir.ZoneServer.Mmo.Combat.MiscDamageCalculator)
Mimic.copy(Aesir.ZoneServer.Mmo.Combat.PacketFactory)
Mimic.copy(Aesir.ZoneServer.CharacterPersistence)
Mimic.copy(Aesir.ZoneServer.Unit.Player.StatusSync)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.StatusManager)
Mimic.copy(Aesir.ZoneServer.Unit.Broadcast)
Mimic.copy(Aesir.ZoneServer.Unit.Emote)
Mimic.copy(Aesir.ZoneServer.Mmo.MobSkill.Archetype.ElementalNuke)
Mimic.copy(Aesir.ZoneServer.Mmo.MobSkill.Archetype.GroundNuke)
Mimic.copy(Aesir.ZoneServer.Mmo.Skill.Catalog)
Mimic.copy(Aesir.ZoneServer.Mmo.Skill.Interpreter)
Mimic.copy(Aesir.ZoneServer.Mmo.Skill.Passives)
Mimic.copy(Aesir.ZoneServer.Mmo.Skills.SmProvoke)
Mimic.copy(Aesir.ZoneServer.Mmo.Skill.Unit)
Mimic.copy(Aesir.ZoneServer.Mmo.Skill.Unit.Storage)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemManagement)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemManagement.Items)
Mimic.copy(Aesir.ZoneServer.Mmo.Refine.RefineDatabase)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemDrop.LevelPenalty)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemDrop.DropCalculator)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemDrop.GroundItemStore)
Mimic.copy(Aesir.ZoneServer.Map.Coordinator)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.ExperienceHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.InventoryManager)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.InventoryOps)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.CartOps)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.CartHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.WarpHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.MovementHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Cart)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusEffect.Registry)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusEffect.StatusDisplay)
Mimic.copy(Aesir.ZoneServer.Unit.SpecialEffect)
Mimic.copy(Aesir.ZoneServer.Npc.Registry)
Mimic.copy(Aesir.ZoneServer.Npc.Warps)
Mimic.copy(Aesir.ZoneServer.Npc.Events)
Mimic.copy(Aesir.ZoneServer.Npc.Verifier)
Mimic.copy(Aesir.ZoneServer.Npc.Shops)
Mimic.copy(Aesir.ZoneServer.Npc.ShopVerifier)
Mimic.copy(Aesir.ZoneServer.Mmo.ItemManagement.ScriptCompiler)
Mimic.copy(Aesir.Commons.Utils.ServerTick)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.SkillHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.SkillLearningHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.ItemHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.PickupHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.EquipmentHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.CombatActionHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.VendingHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.PartyHandler)
Mimic.copy(Aesir.ZoneServer.Party.Manager)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.StorageOps)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.StorageHandler)
Mimic.copy(Aesir.ZoneServer.Unit.Storage.Persistence)
Mimic.copy(Aesir.ZoneServer.Unit.Player.Handlers.RefineOps)
Mimic.copy(Aesir.ZoneServer.Unit.Player.QuestPersistence)

Mimic.copy(Aesir.ZoneServer.Mmo.MobSkill.Db)
Mimic.copy(Aesir.Commons.InterServer.PubSub)
Mimic.copy(Aesir.ZoneServer.Announcement)
Mimic.copy(Aesir.ZoneServer.Mmo.Leveling)
Mimic.copy(Aesir.ZoneServer.Mmo.StatusEffect.ModifierCalculator)

# Integration tests (tagged `:integration`, mostly via `Aesir.ZoneServer.IntegrationCase`)
# are excluded from the default run. Run them explicitly with:
#   mix test --include integration      # unit + integration
#   mix test --only integration         # integration only
# Bump the default `assert_receive`/`refute_receive` timeout (100ms) to absorb
# timing jitter in the full-stack integration tests (e.g. npc_events warp flakes).
ExUnit.start(exclude: [:integration], assert_receive_timeout: 500)
