defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Other.BaPw.Npc7149 do
  @moduledoc """
  Transpiled from rAthena re/warps/other/ba_pw.txt:22 (#ep172_pw2_to_pw1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "ba_pw02",
        x: 7,
        y: 149,
        dir: 0,
        sprite: 45,
        name: "",
        unique_name: "#ep172_pw2_to_pw1",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx) do
    ev_ontouch(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if get_char_var(ctx, :ep17_2_main, 0) < 4 do
        ctx =
          ctx
          |> mes("There is still some work to be done here. Let's look around more.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    warp(ctx, "ba_pw01", 13, 115)
  end
end
