defmodule Aesir.ZoneServer.Content.Npc.ManIn01.Scientist do
  @moduledoc """
  Transpiled from rAthena cities/manuk.txt:552 (Scientist#ep13bs).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "man_in01", x: 227, y: 280, dir: 5, sprite: 449, name: "Scientist"}]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) == 1 do
      ctx |> mes("[Scientist]") |> mes("Is there only one way we can survive..?") |> close()
      exit(:normal)
    else
      ctx |> mes("[Apti]") |> mes("Dso piey pioit ioep ") |> close()
      exit(:normal)
    end
  end
end
