defmodule Aesir.ZoneServer.Content.Npc.Re.Guides.GuidesMora.RaffleGuide do
  @moduledoc """
  Transpiled from rAthena re/guides/guides_mora.txt:16 (Raffle Guide#north).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "mora",
        x: 25,
        y: 158,
        dir: 5,
        sprite: 516,
        name: "Raffle Guide",
        scope: :renewal,
        unique_name: "Raffle Guide#north"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  alias Aesir.ZoneServer.Script.Todo

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Raffoh]")
      |> mes("Laoh~!")
      |> mes("Welcome to the Village of Mora.")
      |> mes("I can tell you whatever you want to know about the village~!")
      |> todo(:F_Navi, ["[Raffoh]"])
      |> next()
      |> select([
        "[ Inn ]",
        "[ Residences ]",
        "[ Stores ]",
        "[ Warehouse ]",
        "Remove markers from the mini-map",
        "Quit"
      ])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~!")
            |> mes(
              Rathena.concat(
                Rathena.concat("We have an ", Todo.call!(:F_Navi, ["Inn", "mora,44,138"])),
                " but we can't make travelers sleep like Raffles..."
              )
            )
            |> mes("Get some rest!")
            |> viewpoint(1, 44, 134, 0, 688_895)
            |> close()

          throw({:script_end, ctx})

        2 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~!")
            |> mes(
              Rathena.concat(
                Todo.call!(:F_Navi, ["This", "mora,119,170"]),
                " is where Raffles' houses are..."
              )
            )
            |> mes("But keep the noise down because people are asleep~!")
            |> viewpoint(1, 119, 170, 1, 11_206_400)
            |> close()

          throw({:script_end, ctx})

        3 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~!")
            |> mes(
              Rathena.concat(
                Rathena.concat(
                  "If you are looking for souvenirs, you can buy some in this ",
                  Todo.call!(:F_Navi, ["district", "mora,112,110"])
                ),
                "."
              )
            )
            |> viewpoint(1, 112, 110, 2, 14_315_734)
            |> close()

          throw({:script_end, ctx})

        4 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~!")
            |> mes(
              Rathena.concat(
                Todo.call!(:F_Navi, ["This", "mora,182,161"]),
                " is where they keep all kinds of packages and groceries."
              )
            )
            |> mes("There are many things that don't belong to the Raffles, so be careful!")
            |> viewpoint(1, 182, 161, 3, 16_716_947)
            |> close()

          throw({:script_end, ctx})

        5 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~! I'm removing them all~!")
            |> viewpoint(2, 1, 1, 0, 16_776_960)
            |> viewpoint(2, 1, 1, 1, 16_776_960)
            |> viewpoint(2, 1, 1, 2, 16_776_960)
            |> viewpoint(2, 1, 1, 3, 16_776_960)
            |> close()

          throw({:script_end, ctx})

        6 ->
          ctx =
            ctx
            |> mes("[Raffoh]")
            |> mes("Laoh~!")
            |> mes("What kinds of sports are popular in your homeland?")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
