defmodule Aesir.ZoneServer.Content.Npc.Cities.Einbroch.Teinz do
  @moduledoc """
  Transpiled from rAthena cities/einbroch.txt:503 (Teinz#ein).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "ein_in01",
        x: 113,
        y: 211,
        dir: 3,
        sprite: 851,
        name: "Teinz",
        scope: :shared,
        unique_name: "Teinz#ein"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Teinz]")
    |> mes("If you just pay me money,")
    |> mes("I'll be your slave! There's")
    |> mes("nothing I won't do! Anything")
    |> mes("is fair game. Hell, I'll get buck naked if you pay me enough.")
    |> next()
    |> mes("[Teinz]")
    |> mes("If you pay me what I'm")
    |> mes("worth, I'll work hard at")
    |> mes("any task you set me to.")
    |> mes("Sure, mining's rough, but")
    |> mes("as long as the zeny's coming")
    |> mes("in, I'm happy. Heh heh heh~")
    |> close()
  end
end
