defmodule Aesir.ZoneServer.Content.Npc.Cities.Einbroch.YoungMan do
  @moduledoc """
  Transpiled from rAthena cities/einbroch.txt:454 (Young Man#air).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "airport",
        x: 174,
        y: 41,
        dir: 6,
        sprite: 99,
        name: "Young Man",
        scope: :shared,
        unique_name: "Young Man#air"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Runnan]")
    |> mes("...And that's why")
    |> mes("I travel around the")
    |> mes("globe. My bosses have")
    |> mes("a keen eye for the most")
    |> mes("exotic goods, so I acquire")
    |> mes("them and make deliveries.")
    |> next()
    |> mes("[Runnan]")
    |> mes("There even was a time")
    |> mes("when they had me collect")
    |> mes("Jellopy, though that stuff is")
    |> mes("pretty common nowadays.")
    |> mes("Now that I think about it, why")
    |> mes("did they need so much stuff?")
    |> close()
  end
end
