defmodule Aesir.ZoneServer.Content.Npc.Einbech.Mogan do
  @moduledoc """
  Transpiled from rAthena cities/einbech.txt:119 (Mogan#ein).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "einbech", x: 128, y: 238, dir: 5, sprite: 848, name: "Mogan"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Mogan]")
    |> mes("Recently, there were a few")
    |> mes("cave-ins where many miners")
    |> mes("were injured. It was discussed")
    |> mes("in the Town Council and in my")
    |> mes("opinion, I think the miners dug")
    |> mes("too deep and disturbed... ^FF0000it^000000.")
    |> next()
    |> mes("[Mogan]")
    |> mes("Yes, they awoke Ungoliant,")
    |> mes("the master of the caves that")
    |> mes("has existed since ancient time.")
    |> mes("I don't know how many more will")
    |> mes("be victimized by Ungoliant in the")
    |> mes("future. There's no telling...")
    |> next()
    |> mes("[Mogan]")
    |> mes("Adventurer, be careful")
    |> mes("if you travel inside the")
    |> mes("mines, lest your footsteps")
    |> mes("disturb Ungoliant's slumber.")
    |> close()
  end
end
