defmodule Aesir.ZoneServer.Content.Npc.Splendide.Fairy275141 do
  @moduledoc """
  Transpiled from rAthena cities/splendide.txt:186 (Fairy#13_2_7).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "splendide", x: 275, y: 141, dir: 3, sprite: 447, name: "Fairy"}]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) == 1 and get_char_var(ctx, :ep13_2_rhea, 0) == 100 do
      ctx =
        ctx
        |> mes("[Fairy]")
        |> mes("Don't talk to me. What do you want?")
        |> mes("I know you will blame something on me right?")
        |> next()
        |> mes("[Fairy]")
        |> mes("I don't want to listen to other people...")
        |> mes("I am perfect as I am!")
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Fairy]")
        |> mes("narnahNoh Di WehRiniLars Yee ModAnu")
        |> mes("LuAlahNe Or FarAnduOsa No AgolKo")
        |> next()
        |> mes("[Fairy]")
        |> mes("LarsVilDim No WhaVilFus Ha Ash")
        |> mes("ReLarsShar Mu AnduLoLon Ie Nufftas")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
