defmodule Aesir.ZoneServer.Content.Npc.Cities.Louyang.Trainee274133 do
  @moduledoc """
  Transpiled from rAthena cities/louyang.txt:233 (Trainee#4lou).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "louyang",
        x: 274,
        y: 133,
        dir: 0,
        sprite: 819,
        name: "Trainee",
        scope: :shared,
        unique_name: "Trainee#4lou"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx |> mes("[Trainee]") |> mes("Dergh!") |> mes("Dergh!") |> mes("Schwa--!") |> close()
  end
end
