defmodule Aesir.ZoneServer.Content.Npc.PreRe.Guides.GuidesLouyang.Representative do
  @moduledoc """
  Transpiled from rAthena pre-re/guides/guides_louyang.txt:130 (Representative#lou).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :pre_renewal,
    spawn: [
      %{
        map: "louyang",
        x: 224,
        y: 104,
        dir: 3,
        sprite: 818,
        name: "Representative",
        scope: :pre_renewal,
        unique_name: "Representative#lou"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Representative]")
      |> mes("Welcome to Luoyang,")
      |> mes("an ancient land with")
      |> mes("a history full of tales")
      |> mes("of bravery.")
      |> next()
      |> mes("[Representative]")
      |> mes(
        "We now provide an ocean lane to accomodate foreign travelers and intercultural exchange from which all can benefit."
      )
      |> next()
      |> mes("[Representative]")
      |> mes("Luoyang is famous for")
      |> mes(
        "its elaborate history, as well as specialties that are unique to this nation. Please take your time and enjoy your stay."
      )
      |> next()
      |> select(["Ask Building Locations.", "Remove all marks from mini-map.", "Cancel."])

    ctx =
      case v1 do
        1 ->
          {ctx, v2} =
            ctx
            |> set_local(:compass_check, 1)
            |> mes("[Representative]")
            |> mes("Where would you like to go?")
            |> next()
            |> select([
              "Dragon Castle",
              "Doctor's Office",
              "City Hall",
              "Weapon Shop",
              "Tool Shop",
              "Tavern",
              "Cancel"
            ])

          ctx =
            case v2 do
              1 ->
                ctx
                |> mes("[Representative]")
                |> mes(
                  "The Dragon Castle is located at ^FF3355+^000000. It is where all the nobles reside, including our lord."
                )
                |> next()
                |> mes("[Representative]")
                |> mes(
                  "Since you're an outsider, I guess it would be appropriate for you to visit our lord first."
                )
                |> viewpoint(1, 218, 255, 2, 16_777_011)

              2 ->
                ctx
                |> mes("[Representative]")
                |> mes("We have a very skillful doctor.")
                |> mes("You can find her office at ^CE6300+^000000.")
                |> next()
                |> mes("[Representative]")
                |> mes("It is said that there")
                |> mes(
                  "is no disease she cannot cure. Well, I can't guarantee if that's true or not."
                )
                |> viewpoint(1, 263, 94, 3, 16_764_515)

              3 ->
                ctx
                |> mes("[Representative]")
                |> mes("We have a City Hall where the federal government operates.")
                |> mes("It is located at ^A5BAAD+^000000.")
                |> next()
                |> mes("[Representative]")
                |> mes("If you have any problems,")
                |> mes("you should talk with the")
                |> mes("employees in City Hall.")
                |> viewpoint(1, 309, 80, 4, 16_711_935)

              4 ->
                ctx
                |> mes("[Representative]")
                |> mes("The Weapon Shop is located at ^55FF33+^000000.")
                |> next()
                |> mes("[Representative]")
                |> mes("You will see")
                |> mes("marvelous weapons forged")
                |> mes("by the well-experienced")
                |> mes("blacksmiths of Luoyang.")
                |> viewpoint(1, 145, 174, 5, 16_733_695)

              5 ->
                ctx
                |> mes("[Representative]")
                |> mes("The Tool Shop is located at ^3355FF+^000000.")
                |> next()
                |> mes("[Representative]")
                |> mes("Knowing your enemy")
                |> mes("is half the battle!")
                |> mes(
                  "It's also safer to prepare yourself than to be sorry later. Why don't you go check their supplies?"
                )
                |> viewpoint(1, 135, 98, 6, 16_724_821)

              6 ->
                ctx
                |> mes("[Representative]")
                |> mes(
                  "When you get tired during your trip, I suggest that you visit the Tavern. It's located at ^00FF00+^000000."
                )
                |> next()
                |> mes("[Soldier]")
                |> mes("The Tavern is a good place")
                |> mes(
                  "to meet other tourists, as well as to hear of any news that may be helpful to know."
                )
                |> viewpoint(1, 280, 167, 7, 16_711_935)

              7 ->
                ctx =
                  ctx
                  |> mes("[Representative]")
                  |> mes("If you wish to remove all marks")
                  |> mes(
                    "on your mini-map, please choose 'Remove all marks from mini-map.' from the menu."
                  )

                ctx

              _ ->
                ctx
            end

          ctx

        2 ->
          ctx
          |> viewpoint(2, 218, 255, 2, 16_711_935)
          |> viewpoint(2, 263, 94, 3, 16_711_935)
          |> viewpoint(2, 309, 80, 4, 16_711_935)
          |> viewpoint(2, 145, 174, 5, 16_711_935)
          |> viewpoint(2, 135, 98, 6, 16_711_935)
          |> viewpoint(2, 280, 167, 7, 16_711_935)
          |> mes("[Representative]")
          |> mes(
            "Done! All the marks on your mini-map are erased. Feel free to ask me about building locations whenever you need to."
          )

        3 ->
          ctx =
            ctx
            |> mes("[Representative]")
            |> mes("I understand that you want to explore Luoyang and see the")
            |> mes("sights for yourself. Alright then, take care!")

          ctx

        _ ->
          ctx
      end

    close(ctx)
  end
end
