defmodule Aesir.ZoneServer.Content.Npc.Cities.Aldebaran.KafraService91244 do
  @moduledoc """
  Transpiled from rAthena cities/aldebaran.txt:1025 (Kafra Service#4alde).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "aldeba_in",
        x: 91,
        y: 244,
        dir: 4,
        sprite: 112,
        name: "Kafra Service",
        scope: :shared,
        unique_name: "Kafra Service#4alde"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> cutin("kafra_06", 2)
      |> mes("[Kafra Curly Sue]")
      |> mes("Hello, hello!!")
      |> mes("I'm Curly Sue,")
      |> mes("the newest member")
      |> mes("of the Kafra Staff!")
      |> next()
      |> mes("[Kafra Curly Sue]")
      |> mes(
        "I may still need to learn more about serving our customers, but I'm always doing my best!"
      )
      |> next()
      |> select(["Where's your mommy, kid?", "End conversation."])

    ctx =
      if v1 == 1 do
        ctx =
          ctx
          |> mes("[Kafra Curly Sue]")
          |> mes("Waaaaaaah~!")
          |> mes("I'm not a kid!")
          |> close()
          |> cutin("", 255)

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("[Kafra Curly Sue]")
    |> mes(
      "Here at Kafra Corporation, we are all doing our very best to give you the excellent service that you expect from us."
    )
    |> close()
    |> cutin("", 255)
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
