defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22e.Soullinker.AlchemistSpirit do
  @moduledoc """
  Transpiled from rAthena jobs/2-2e/SoulLinker.txt:590 (Alchemist Spirit#link7).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "job_soul",
        x: 25,
        y: 30,
        dir: 5,
        sprite: 744,
        name: "Alchemist Spirit",
        scope: :shared,
        unique_name: "Alchemist Spirit#link7"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      if get_char_var(ctx, :SOUL_Q, 0) == 2 do
        ctx =
          ctx
          |> mes("[Alchemist Spirit]")
          |> mes("Oh! I really want to")
          |> mes("speak to you, but what")
          |> mes("I have to say won't make")
          |> mes("much sense unless you")
          |> mes("talk to Maia first. But yes,")
          |> mes("I really need your help.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          if get_char_var(ctx, :SOUL_Q, 0) > 2 do
            ctx =
              ctx
              |> mes("[Alchemist Spirit]")
              |> mes("Without exagerrating, I was")
              |> mes("the fastest Alchemist in my")
              |> mes("time. In fact, I may even be")
              |> mes("the fastest Alchemist ever.")
              |> mes("But then I grew arrogant, and")
              |> mes("killed myself in an accident.")
              |> next()
              |> mes("[Alchemist Spirit]")
              |> mes("But death would not stifle")
              |> mes("my skill. In fact, I've even")
              |> mes("improved my skill since I've")
              |> mes("passed away. I cannot go")
              |> mes("on to the next world until I've")
              |> mes("passed on my techniques...")
              |> set_char_var(:SOUL_Q, 4)

            ctx =
              if checkquest(ctx, 6008) == -1 do
                changequest(ctx, 6007, 6008)
              else
                ctx
              end

            ctx =
              ctx
              |> next()
              |> mes("[Alchemist Spirit]")
              |> mes("I'm powerless as a spirit,")
              |> mes("but with your help, I can")
              |> mes("influence the Alchemists of")
              |> mes("today and help them refine")
              |> mes("their skills. I beseech you,")
              |> mes("please give me this chance...")
              |> close()

            throw({:script_end, ctx})
          else
            ctx
          end

        ctx
      end

    ctx |> mes("[Alchemist Spirit]") |> mes("...") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
