defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22e.Soullinker.Timer do
  @moduledoc """
  Transpiled from rAthena jobs/2-2e/SoulLinker.txt:636 (Timer#link3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "job_soul",
        x: 1,
        y: 5,
        dir: 0,
        sprite: 111,
        name: "Timer",
        scope: :shared,
        unique_name: "Timer#link3"
      }
    ]

  @impl true
  def on_event("OnEnable", ctx), do: ev_onenable(ctx)
  def on_event("OnDisable", ctx), do: ev_ondisable(ctx)
  def on_event("OnTimer60000", ctx), do: ev_ontimer60000(ctx)
  def on_event("OnTimer120000", ctx), do: ev_ontimer120000(ctx)
  def on_event("OnTimer180000", ctx), do: ev_ontimer180000(ctx)
  def on_event("OnTimer181000", ctx), do: ev_ontimer181000(ctx)
  def on_event("OnTimer182000", ctx), do: ev_ontimer182000(ctx)
  def on_event("OnTimer183000", ctx), do: ev_ontimer183000(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_onenable(ctx) do
    initnpctimer(ctx)
  end

  def ev_ondisable(ctx) do
    ctx |> stopnpctimer() |> set_npc_var_of("SoulLinkerTest", "Kid#link1", 0)
  end

  def ev_ontimer60000(ctx) do
    ctx
  end

  def ev_ontimer120000(ctx) do
    ctx =
      if getmapusers(ctx, "job_soul") == 0 do
        ctx |> stopnpctimer() |> set_npc_var_of("SoulLinkerTest", "Kid#link1", 0)
      else
        ctx
      end

    ctx
  end

  def ev_ontimer180000(ctx) do
    ctx
  end

  def ev_ontimer181000(ctx) do
    ctx
  end

  def ev_ontimer182000(ctx) do
    mapwarp(ctx, "job_soul", "morocc", 157, 47)
  end

  def ev_ontimer183000(ctx) do
    ctx
    |> mapwarp("job_soul", "morocc", 157, 47)
    |> set_npc_var_of("SoulLinkerTest", "Kid#link1", 0)
    |> stopnpctimer()
  end
end
