defmodule Aesir.ZoneServer.Content.Npc.Cities.Jawaii.Employee112173 do
  @moduledoc """
  Transpiled from rAthena cities/jawaii.txt:346 (Employee#villroom).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "jawaii",
        x: 112,
        y: 173,
        dir: 7,
        sprite: 93,
        name: "Employee",
        scope: :shared,
        unique_name: "Employee#villroom"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Larks Rania]")
      |> mes("Hello dear,")
      |> mes("how are you?")
      |> mes("Are you looking for")
      |> mes("a room to stay in?")
      |> next()
      |> mes("[Larks Rania]")
      |> mes("This is called the Villa Room.")
      |> mes("I recommend this room to people")
      |> mes("who prefer to stay in a place with")
      |> mes("a comfortable atmosphere")
      |> mes("much like home.")
      |> next()
      |> mes("[Larks Rania]")
      |> mes("Just like all the other rooms,")
      |> mes("the lodging charge is 1,000 zeny.")
      |> mes("I can guide you to the Villa Room")
      |> mes("right now, if you wish. Would you")
      |> mes("like to stay?")
      |> next()
      |> select(["Use.", "Cancel."])

    ctx =
      if v1 == 1 do
        ctx = mes(ctx, "[Larks Rania]")

        ctx =
          if zeny(ctx) > 999 do
            ctx =
              ctx
              |> mes("Thank you~")
              |> mes("Enjoy your stay.")
              |> close()
              |> pay_zeny(1000)
              |> warp("jawaii_in", 87, 75)

            throw({:script_end, ctx})
          else
            ctx
          end

        ctx =
          ctx
          |> mes("Oh what a shame!")
          |> mes("You don't seem")
          |> mes("to have enough money...?")
          |> mes("Why don't you ask your")
          |> mes("partner to help you")
          |> mes("with the charge?")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("[Larks Rania]")
    |> mes("No problem~")
    |> mes(
      "If you like, you may wish to check the Honey Room. Although the roomkeeper, Sharkie, is a shy girl, the room is really beautiful."
    )
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
