defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.LimpyPiom do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:579 (Limpy Piom#a).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dicastes01",
        x: 164,
        y: 180,
        dir: 4,
        sprite: 489,
        name: "Limpy Piom",
        unique_name: "Limpy Piom#a"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Limpy Piom]")

    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("They say there is a")
          |> mes("war going on with the Splendide in Manuk.")
          |> mes("I hope everything goes well.")
          |> mes("I hope it doesn't come all")
          |> mes("the way to the capital city here.")
          |> emotion(:think)
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("?????? ?? ????")
    |> mes("?????? ?? ??")
    |> mes("?????? ?? ??????")
    |> mes("?????? ?? ??????")
    |> mes("?????? ?? ???? ?? ????")
    |> emotion(:think)
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
