defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.ManukPiom do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:486 (Manuk Piom#a).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dic_in01",
        x: 387,
        y: 30,
        dir: 1,
        sprite: 454,
        name: "Manuk Piom",
        unique_name: "Manuk Piom#a"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Manuk Piom]")

    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("You! We met in Manuk, didn't we?")
          |> mes("I've come to pick up the weapon I ordered.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("?????? ?? ?????? ?? ????") |> mes("?????? ?? ?????? ?? ?????? ????") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
