defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.RestingGalten365197 do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:210 (Resting Galten#in_6).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dic_in01",
        x: 365,
        y: 197,
        dir: 1,
        sprite: 492,
        name: "Resting Galten",
        unique_name: "Resting Galten#in_6"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("[Resting Galten]")
          |> mes("Galten can also rest while standing up like this.")
          |> next()
          |> mes("[Resting Galten]")
          |> mes("You say I don't look like I'm resting? But I'm already used to this.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("[?????? ?? ??]")
    |> mes("???ï¢¤ ?? ?????? ?? ??????")
    |> mes("?ï¢£?? ?? ?????? ?? ?Ð¡??? ?? ?Ð¡??? ?? ??")
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
