defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.RestingPiom29119 do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:229 (Resting Piom#04).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dic_in01",
        x: 29,
        y: 119,
        dir: 4,
        sprite: 489,
        name: "Resting Piom",
        unique_name: "Resting Piom#04"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("[Resting Piom]")
          |> mes("Why is it so noisy when I'm trying to get rest?")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("[?????? ?? ??]") |> mes("?????? ?? ?????? ?? ????") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
