defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.RestingGalten do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:199 (Resting Galten#in_5).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "dic_in01",
        x: 354,
        y: 219,
        dir: 4,
        sprite: 492,
        name: "Resting Galten",
        scope: :renewal,
        unique_name: "Resting Galten#in_5"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx = ctx |> mes("[Resting Galten]") |> mes("Resting is always so sweet.") |> close()
        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("[?????? ?? ??]") |> mes("?????? ?? ?????? ?? ??") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
