defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dicastes.WorriedPiom do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:689 (Worried Piom#a).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dic_in01",
        x: 98,
        y: 110,
        dir: 5,
        sprite: 489,
        name: "Worried Piom",
        unique_name: "Worried Piom#a"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("[Worried Piom]")
          |> mes("I haven't seen my friends for the last few hours.")
          |> mes("It's about time for them to have")
          |> mes("their Bradium. Hmm..")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("[Worried Piom]")
    |> mes("?????? ?? ?????? ?? ??????")
    |> mes("?????? ?? ?????? ?? ??")
    |> mes("?????? ?? ??")
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
