defmodule Aesir.ZoneServer.Content.Npc.Floating.Npc do
  @moduledoc """
  Transpiled from rAthena re/cities/mora.txt:911 (#mora_traveler).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "mora", x: 140, y: 72, dir: 4, sprite: 513, name: "Traveler"},
      %{map: "mora", x: 138, y: 72, dir: 6, sprite: 513, name: "Traveler"},
      %{map: "mora", x: 139, y: 73, dir: 4, sprite: 513, name: "Traveler"}
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Upset Traveler]")
      |> mes("You... you dare play a game with me?")
      |> emotion(:anger)
      |> next()
      |> mes("[Traveler That Posed the Question]")
      |> mes("What...? Do you have proof?")
      |> mes("Do you have proof?!!")
      |> emotion(:fret)
      |> next()
      |> mes("[Traveler Trying to Stop the Fight]")
      |> mes("Look, stop it, just stop it!")
      |> mes("I'm afraid it will turn into a big fight...")
      |> emotion(:profusely_sweat)
      |> next()
      |> mes("[Traveler Trying to Stop the Fight]")
      |> mes("Oh! Why don't we ask")
      |> mes("that person there...?")
      |> next()
      |> mes("[Upset Traveler]")
      |> mes("Oh, yes! That's a great idea.")
      |> mes("Well~ Hello there~")
      |> mes("You there, traveler!")
      |> emotion(:aha)
      |> next()
      |> mes("They seem to be calling out to you.")
      |> next()
      |> select(["See what the matter is.", "I have nothing to do with it."])

    ctx =
      if v1 == 2 do
        ctx =
          ctx
          |> mes("You went on your way")
          |> mes("leaving the travelers behind you.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    {ctx, v2} =
      ctx
      |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
      |> mes("What's happening here?")
      |> emotion(:question)
      |> next()
      |> mes("[Upset Traveler]")
      |> mes("I'll tell you what.")
      |> mes("Rose's mother had 10 sons.")
      |> mes("The eldest son is called Roseone,")
      |> mes("the second Rosetwo,")
      |> mes("the third Rosethree...")
      |> mes("the ninth Rosenine...")
      |> mes("you get how it works, right?")
      |> emotion(:anger)
      |> next()
      |> mes("[Traveler That Posed the Question]")
      |> mes("Right, that's how it works.")
      |> mes("So I asked what the youngest one would be called,")
      |> mes("and when I told him the answer,")
      |> mes("he got all upset and started cursing me.")
      |> emotion(:fret)
      |> next()
      |> mes("[Upset Traveler]")
      |> mes("You... you bastard!")
      |> mes("Hey there, what do you think")
      |> mes("the answer to the question is?")
      |> emotion(:anger)
      |> next()
      |> select(["Roseten.", "Rose.", "How would I know that?"])

    ctx =
      case v2 do
        1 ->
          ctx
          |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
          |> mes("The answer to the question is Roseten.")
          |> mes("Why are you fighting over such a trivial matter?")
          |> next()
          |> mes("[Upset Traveler]")
          |> mes("See? Even this traveler says")
          |> mes("Roseten is the answer.")
          |> mes("How dare you try to play tricks on me?")
          |> emotion(:kik)
          |> next()
          |> mes("[Traveler That Posed the Question]")
          |> mes("You idiot... you don't have the slightest clue!")
          |> emotion(:fret)

        2 ->
          ctx
          |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
          |> mes("The answer to the question is Rose.")
          |> mes("You said Rose's mother had 10 sons.")
          |> mes("So even if the other sons' names are")
          |> mes("Roseone, Rosetwo, ... Rosenine,")
          |> mes("the youngest one must be Rose,")
          |> mes("or she wouldn't be called Rose's mother.")
          |> next()
          |> mes("[Traveler That Posed the Question]")
          |> mes("That's exactly what I mean!")
          |> mes("I can't hang around with him.")
          |> mes("I guess we live in two different worlds.")
          |> emotion(:ok)
          |> next()
          |> mes("[Upset Traveler]")
          |> mes("You bastard... What did you")
          |> mes("get from this guy...?")
          |> emotion(:anger)

        3 ->
          ctx =
            ctx
            |> mes(Rathena.concat(Rathena.concat("[", char_name(ctx, 0)), "]"))
            |> mes("I have no idea.")
            |> mes("Try to sort it out yourselves.")
            |> next()
            |> mes("[Traveler Trying to Stop the Fight]")
            |> mes("You good-for-nothing bastard,")
            |> mes("you're trying to leave this mess to me?")
            |> emotion(:fret)

          ctx

        _ ->
          ctx
      end

    ctx =
      ctx
      |> next()
      |> mes("*thud*")
      |> mes("You feel a sudden impact on the back of your head.")
      |> mes("Your sight is going blurry.")
      |> specialeffect2(:hit1)
      |> sc_start(:sc_blind, 20000, 0)
      |> next()
      |> mes("You feel somebody rummaging through your pockets before you pass out.")

    ctx =
      if zeny(ctx) >= 5000 do
        pay_zeny(ctx, 5000)
      else
        todo(ctx, :set_param, ["Zeny", 0])
      end

    ctx |> close() |> percent_heal(hp: -99, sp: 0) |> warp("mora", 31, 132)
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
