defmodule Aesir.ZoneServer.Content.Npc.Floating.PrOfficerMoscovia do
  @moduledoc """
  Transpiled from rAthena cities/moscovia.txt:19 (::PR_Officer_moscovia).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "alberta",
        x: 246,
        y: 51,
        dir: 4,
        sprite: 960,
        name: "Moscovia P.R. Officer",
        scope: :renewal,
        unique_name: "Moscovia P.R. Officer#1"
      },
      %{
        map: "alberta",
        x: 245,
        y: 66,
        dir: 4,
        sprite: 960,
        name: "Moscovia P.R. Officer",
        scope: :pre_renewal,
        unique_name: "Moscovia P.R. Officer#1"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Moscovia P.R. Officer]")
      |> mes("Moscovia! Do you know Moscovia?")
      |> mes("the paradise spreading on the endless seas...")
      |> mes("Welcome to Moscovia")
      |> mes("It's adventurous and mystic.")
      |> next()
      |> select(["About Moscovia...", "Go to Moscovia.", "Cancel"])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Moscovia P.R. Officer]")
            |> mes("Moscovia is a beautiful kingdom")
            |> mes("on an island located north of Rune-")
            |> mes("Midgarts.")
            |> next()
            |> mes("[Moscovia P.R. Officer]")
            |> mes("I'm sure that you will be")
            |> mes("absolutely fascinated")
            |> mes("by Moscovia's beautiful scenery")
            |> mes("and gorgeous palace.")
            |> next()
            |> mes("[Moscovia P.R. Officer]")
            |> mes("Now that our long winter has")
            |> mes("passed,")
            |> mes("I'm happy that I can now show you")
            |> mes("our gorgeous hometown.")
            |> next()
            |> mes("[Moscovia P.R. Officer]")
            |> mes("If you feel like visiting Moscovia")
            |> mes("take the chance now!")
            |> mes("I'll help you to have a nice trip")
            |> mes("to Moscovia!")
            |> close()

          throw({:script_end, ctx})

        2 ->
          {ctx, v2} =
            ctx
            |> mes("[Moscovia P.R. Officer]")
            |> mes("Ok then, let us start now.")
            |> mes("You should pay me 10,000 zeny")
            |> mes("to go to Moscovia.")
            |> mes("But when you come back,")
            |> mes("you don't have to pay.")
            |> next()
            |> mes("[Moscovia P.R. Officer]")
            |> mes("Can we leave now?")
            |> next()
            |> select(["Let's go!", "Cancel"])

          ctx =
            if v2 == 2 do
              ctx =
                ctx
                |> mes("[Moscovia P.R. Officer]")
                |> mes("If you're too busy now,")
                |> mes("please tell me again whenever you want.")
                |> mes("I'm always ready to guide anyone to Moscovia.")
                |> close()

              throw({:script_end, ctx})
            else
              ctx
            end

          if zeny(ctx) < 10000 do
            ctx =
              ctx
              |> mes("[Moscovia P.R. Officer]")
              |> mes("I'm sorry but you don't have")
              |> mes("enough zeny now")
              |> mes("You need 10,000 zeny")
              |> mes("to go to Moscovia")
              |> mes("Thank you.")
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              ctx
              |> mes("[Moscovia P.R. Officer]")
              |> mes("Ok then, we're leaving now.")
              |> close()
              |> pay_zeny(10000)
              |> warp("moscovia", 163, 55)

            throw({:script_end, ctx})
          end

        3 ->
          ctx =
            ctx
            |> mes("[Moscovia P.R. Officer]")
            |> mes("If you're too busy now,")
            |> mes("please tell me again whenever you want.")
            |> mes("I'm always ready to guide anyone to Moscovia.")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
