defmodule Aesir.ZoneServer.Content.Npc.Floating.Sprakki0 do
  @moduledoc """
  Transpiled from rAthena re/jobs/novice/novice.txt:89 (Sprakki#newbe05::NvSprakkiB).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "new_1-2",
        x: 100,
        y: 29,
        dir: 4,
        sprite: 90,
        name: "Sprakki",
        unique_name: "Sprakki#nv1b"
      },
      %{
        map: "new_2-2",
        x: 100,
        y: 29,
        dir: 4,
        sprite: 90,
        name: "Sprakki",
        unique_name: "Sprakki#nv2b"
      },
      %{
        map: "new_3-2",
        x: 100,
        y: 29,
        dir: 4,
        sprite: 90,
        name: "Sprakki",
        unique_name: "Sprakki#nv3b"
      },
      %{
        map: "new_4-2",
        x: 100,
        y: 29,
        dir: 4,
        sprite: 90,
        name: "Sprakki",
        unique_name: "Sprakki#nv4b"
      },
      %{
        map: "new_5-2",
        x: 100,
        y: 29,
        dir: 4,
        sprite: 90,
        name: "Sprakki",
        unique_name: "Sprakki#nv5b"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      if get_char_var(ctx, :job_novice_q, 0) == 0 do
        ctx =
          ctx
          |> mes("[Sprakki]")
          |> mes("Hello there! Welcome to the World of Ragnarok Online.")
          |> mes("My name is Sprakki and I'm in charge of giving you basic gameplay tips.")
          |> mes("Click on the [Next] button or press [Enter] key to continue.")
          |> next()
          |> mes("[Sprakki]")
          |> mes("First you need to learn the very basics of controlling your character.")
          |> mes(
            "All the basic ^4d4dffmoves, selection of items, and attacks^000000 use the ^4d4dff left click of the mouse^000000."
          )
          |> next()
          |> cutin("tutorial01", 3)
          |> mes("-! Info !-")
          |> mes("Click on the ground to move the character.")
          |> mes(
            "Attacking monsters and conversations with the people of this world can be done by simply clicking on them."
          )
          |> next()
          |> cutin("", 255)
          |> mes("[Sprakki]")
          |> mes("Well then, I will give you a quest to talk to me.")
          |> mes("After the conversation is over, talk to me again by left-clicking on me.")
          |> set_char_var(:job_novice_q, 1)
          |> setquest(7117)
          |> next()
          |> cutin("tutorial02", 3)
          |> mes("-! Info !-")
          |> mes("You've received a quest from Sprakki.")
          |> mes(
            "You can check the contents of the quest in the Quest Info Window by pressing the ^4d4dffAlt + U^000000 keys at the same time."
          )
          |> next()
          |> cutin("", 255)
          |> mes("[Sprakki]")
          |> mes("Have you checked the Quest Info Window?")
          |> mes("Well, talk to me again.")
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          if get_char_var(ctx, :job_novice_q, 0) < 3 do
            ctx =
              if get_char_var(ctx, :job_novice_q, 0) == 1 do
                ctx
                |> mes("[Sprakki]")
                |> mes("Great!")
                |> mes("Now you know how to move and talk to others, right?")
                |> set_char_var(:job_novice_q, 2)
                |> getexp(600, 5)
                |> completequest(7117)
                |> next()
              else
                ctx
              end

            {ctx, v1} =
              ctx
              |> mes("[Sprakki]")
              |> mes("The Training Center is prepared for novices just like you.")
              |> mes("You are going to be trained to get used to the basics of the Game.")
              |> next()
              |> mes("[Sprakki]")
              |> mes(
                "Of course, this Training Process is optional, if you want to go straight to town, that's also fine."
              )
              |> mes("But, you will miss all the advantages you can get in the Training Center.")
              |> next()
              |> select(["Begin Training.", "Start the game right away."])

            ctx =
              case v1 do
                1 ->
                  ctx =
                    ctx
                    |> mes("[Sprakki]")
                    |> mes("I will guide you to the Novice Training Center.")
                    |> mes("Inside, Instructor 'Brade' will be waiting to speak to you.")
                    |> next()
                    |> mes("[Sprakki]")
                    |> mes("Instructor 'Brade' will help you afterwards.")
                    |> mes("Please, Go see him.")
                    |> setquest(7118)
                    |> next()
                    |> mes(
                      "^4d4dff- You received a quest 'Novice Training Ground -1' from Sprakki."
                    )
                    |> mes("Please check the Quest Info Window. -^000000")
                    |> close()

                  ctx = savepoint(ctx, strnpcinfo(ctx, 4), 100, 100)
                  ctx = warp(ctx, strnpcinfo(ctx, 4), 100, 100)
                  throw({:script_end, ctx})

                2 ->
                  {ctx, v2} =
                    ctx
                    |> set_char_var(:nov_1st_cos, 0)
                    |> set_char_var(:nov_2nd_cos, 0)
                    |> set_char_var(:nov_3_swordman, 0)
                    |> set_char_var(:nov_3_archer, 0)
                    |> set_char_var(:nov_3_thief, 0)
                    |> set_char_var(:nov_3_magician, 0)
                    |> set_char_var(:nov_3_acolyte, 0)
                    |> set_char_var(:nov_3_merchant, 0)
                    |> mes("[Sprakki]")
                    |> mes("Ok, You want to start right away.")
                    |> mes("Which Town do you want to start at?")
                    |> next()
                    |> select(["Prontera", "Morocc", "Geffen", "Payon", "Alberta", "Izlude"])

                  {ctx, _} =
                    ctx
                    |> set_local(:select, v2)
                    |> mes("[Sprakki]")
                    |> mes("I see.")
                    |> mes(
                      "Go ahead and grow stronger! Look toward a brighter future ahead of you."
                    )
                    |> Aesir.ZoneServer.Content.Npc.Functions.FNverase.call([])

                  ctx = close(ctx)
                  v3 = get_local(ctx, :select, 0)

                  ctx =
                    case v3 do
                      1 ->
                        ctx |> savepoint("prontera", 273, 354) |> warp("prontera", 273, 354)

                      2 ->
                        ctx |> savepoint("morocc", 160, 94) |> warp("morocc", 160, 94)

                      3 ->
                        ctx |> savepoint("geffen", 120, 100) |> warp("geffen", 120, 100)

                      4 ->
                        ctx |> savepoint("payon", 70, 100) |> warp("payon", 70, 100)

                      5 ->
                        ctx |> savepoint("alberta", 116, 57) |> warp("alberta", 116, 57)

                      6 ->
                        ctx = ctx |> savepoint("izlude", 128, 98) |> warp("izlude", 128, 98)
                        ctx

                      _ ->
                        ctx
                    end

                  throw({:script_end, ctx})

                _ ->
                  ctx
              end

            ctx
          else
            ctx =
              ctx
              |> mes("[Sprakki]")
              |> mes("These are the Novice Training Grounds.")
              |> mes("I will guide you to the Novice Training Center.")
              |> close()

            ctx = savepoint(ctx, strnpcinfo(ctx, 4), 100, 100)
            ctx = warp(ctx, strnpcinfo(ctx, 4), 100, 100)
            throw({:script_end, ctx})
          end

        ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
