defmodule Aesir.ZoneServer.Content.Npc.PayArche.KafraEmployeeKafPayon3 do
  @moduledoc """
  Transpiled from rAthena kafras/kafras.txt:217 (Kafra Employee::kaf_payon3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "pay_arche",
        x: 55,
        y: 123,
        dir: 0,
        sprite: 117,
        name: "Kafra Employee::kaf_payon3",
        unique_name: "kaf_payon3"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, _} =
      ctx |> cutin("kafra_03", 2) |> Aesir.ZoneServer.Content.Npc.Functions.FKafset.call([])

    {ctx, _} =
      ctx
      |> mes("[Kafra Employee]")
      |> mes("Welcome to the")
      |> mes("Kafra Corporation.")
      |> mes("The Kafra services")
      |> mes("are always on your side.")
      |> mes("How may I assist you?")
      |> Aesir.ZoneServer.Content.Npc.Functions.FKafra.call([5, 5, 1, 90, 1200])

    {ctx, _} =
      ctx
      |> savepoint("pay_arche", 49, 144)
      |> Aesir.ZoneServer.Content.Npc.Functions.FKafend.call([0, 1, "at the Payon Dungeon"])

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
