defmodule Aesir.ZoneServer.Content.Npc.Cities.Rachel.ChildFollower127117 do
  @moduledoc """
  Transpiled from rAthena cities/rachel.txt:544 (Child Follower#2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "rachel",
        x: 127,
        y: 117,
        dir: 4,
        sprite: 914,
        name: "Child Follower",
        unique_name: "Child Follower#2"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Deno]")
    |> mes("Although we pray to")
    |> mes("the goddess Freya and")
    |> mes("ask her for all sorts of")
    |> mes("things, we can't expect")
    |> mes("her to do everything for us.")
    |> next()
    |> mes("[Deno]")
    |> mes("As humans, it is our")
    |> mes("responsibility to do all")
    |> mes("in our power to conceive")
    |> mes("our own happiness. We")
    |> mes("believe that if it is Freya's")
    |> mes("will, then it shall be realized.")
    |> next()
    |> emotion(:question)
    |> mes("[Deno]")
    |> mes("I know it might seem")
    |> mes("a little confusing to")
    |> mes("an outsider, the idea of")
    |> mes("being reliant on our goddess")
    |> mes("while relying our ourselves.")
    |> close()
  end
end
