defmodule Aesir.ZoneServer.Content.Npc.Cities.Payon.Woman246158 do
  @moduledoc """
  Transpiled from rAthena cities/payon.txt:182 (Woman#2payon).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "payon",
        x: 246,
        y: 158,
        dir: 5,
        sprite: 66,
        name: "Woman",
        unique_name: "Woman#2payon",
        trigger: {0, 0}
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      ctx
      |> mes("[Jim's Mother]")
      |> mes("Oh boy~")
      |> mes("There she goes again.")
      |> mes("Without a doubt, that")
      |> mes("woman is the town gossip.")
      |> next()
      |> mes("[Jim's Mother]")
      |> mes("Please don't judge the rest")
      |> mes(
        "of the people living in Payon by her behavior. She's the only loudmouth. I guess she's just too excited about what the fortune teller told her."
      )
      |> next()
      |> mes("[Jim's Mother]")

    ctx =
      if sex(ctx) == get_char_var(ctx, :SEX_MALE, 0) do
        ctx
        |> mes("Ooh...!")
        |> mes("You've got")
        |> mes("such broad shoulders!")
        |> mes("Will you go out with me?")
        |> mes("I'll treat you to")
        |> mes("a nice dinner~")
      else
        ctx
        |> mes("My, you're a pretty girl!")
        |> mes("I'm sure you're always busy")
        |> mes("beating the boys away with a stick...")
        |> mes("Or a well timed insult joke.")
      end

    {ctx, v1} = ctx |> next() |> select(["Fortune Teller...? ", "Well, see you later~"])

    ctx =
      if v1 == 1 do
        ctx =
          ctx
          |> mes("[Jim's Mother]")
          |> mes("Oh yes...")
          |> mes(
            "There's an extraordinary fortune teller in the Central Palace of Payon. The more Zeny you pay her, the better fortune you'll get!"
          )
          |> next()
          |> mes("[Jim's Mother]")
          |> mes("She told me")
          |> mes("I would meet")
          |> mes("a nice guy this month.")
          |> mes("Hohohoho~ ")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("[Jim's Mother]")
    |> mes("Mmmm...?")
    |> mes("You don't have")
    |> mes("any time to stay")
    |> mes("and chit-chat with me?")
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
