defmodule Aesir.ZoneServer.Content.Npc.Warps.Dungeons.CTower.Clt015r do
  @moduledoc """
  Transpiled from rAthena warps/dungeons/c_tower.txt:61 (clt015r).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "c_tower3", x: 240, y: 7, dir: 4, sprite: 45, name: "clt015r", trigger: {1, 1}}
    ]

  @impl true
  def on_talk(ctx) do
    v1 = :rand.uniform(3) - 1

    ctx =
      case v1 do
        0 ->
          ctx = warp(ctx, "c_tower2", 13, 282)
          throw({:script_end, ctx})

        1 ->
          ctx = warp(ctx, "alde_dun03", 175, 131)
          throw({:script_end, ctx})

        2 ->
          ctx = warp(ctx, "c_tower3", 235, 7)
          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
