defmodule Aesir.ZoneServer.Content.Npc.MocPara01.KafraTeleportation do
  @moduledoc """
  Transpiled from rAthena re/kafras/Kafra_Teleportation_Services.txt:225 (Kafra Teleportation#eden).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "moc_para01", x: 35, y: 23, dir: 3, sprite: 10242, name: "Kafra Teleportation"}
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      ctx
      |> cutin("kafra_do01", 2)
      |> mes("[Kafra Employee]")
      |> mes("Welcome.")
      |> mes("The Kafra services are always on your side.")
      |> next()
      |> mes("[Kafra Employee]")
      |> mes(
        "To reward adventurer support, the Kafra Corporation in cooperation with the Eden Group provides free services for ^ff0000Beginner Adventurers Below Level 39^000000."
      )
      |> next()

    ctx =
      if base_level(ctx) > 40 do
        ctx
        |> mes("[Kafra Employee]")
        |> mes(
          "We do not offer free teleportation services for adventurers ^ff0000above level 40^000000."
        )
        |> mes("Search for Kafra Teleportation services in the city.")
        |> close()
        |> cutin("", 255)
      else
        ctx
      end

    {ctx, v1} =
      ctx
      |> mes("[Kafra Employee]")
      |> mes("Please choose your destination.")
      |> next()
      |> select([
        "Prontera West Field",
        "Prontera Southwestern Field",
        "Prontera Lake Field",
        "Payon Dungeon Entrance",
        "Southwest Izlude Field",
        "Cancel."
      ])

    ctx =
      case v1 do
        1 ->
          {ctx, _} =
            ctx
            |> mes("[Kafra Employee]")
            |> mes("Prontera Field :")
            |> mes(
              "The Prontera West Field is a mountainous field that you can also access the ^ff0000Prontera Sewer^000000."
            )
            |> mes("^ff0000Hornets^000000 live there, so novice adventurers should beware!")
            |> next()
            |> s_s_zone([])

          ctx = warp(ctx, "prt_fild05", 276, 241)
          throw({:script_end, ctx})

        2 ->
          {ctx, _} =
            ctx
            |> mes("[Kafra Employee]")
            |> mes("Prontera Field :")
            |> mes("Southwestern Prontera Field is a place where ^ff0000Rockers^000000 live.")
            |> next()
            |> s_s_zone([])

          ctx = warp(ctx, "prt_fild07", 250, 257)
          throw({:script_end, ctx})

        3 ->
          {ctx, _} =
            ctx
            |> mes("[Kafra Employee]")
            |> mes("Prontera Field :")
            |> mes("Prontera Lake Field is a place where the ^ff0000Ambernites^000000 live.")
            |> next()
            |> s_s_zone([])

          ctx = warp(ctx, "prt_fild04", 204, 109)
          throw({:script_end, ctx})

        4 ->
          {ctx, _} =
            ctx
            |> mes("[Kafra Employee]")
            |> mes("Archer's Village :")
            |> mes(
              "Payon's Cave is a scary place with lots of ^ff0000Zombies^000000 and ^ff0000Skeletons^000000."
            )
            |> next()
            |> s_s_zone([])

          ctx = warp(ctx, "pay_arche", 69, 130)
          throw({:script_end, ctx})

        5 ->
          {ctx, _} =
            ctx
            |> mes("[Kafra Employee]")
            |> mes("Sograt Desert :")
            |> mes(
              "Southwest of Prontera and Southwest of Izlude, this place is full of ^ff0000Mukas^000000 and ^ff0000Peco Pecos^000000."
            )
            |> next()
            |> s_s_zone([])

          ctx = warp(ctx, "moc_fild01", 232, 250)
          throw({:script_end, ctx})

        6 ->
          {ctx, _} = Aesir.ZoneServer.Content.Npc.Functions.FKafend.call(ctx, [0, 0])
          ctx

        _ ->
          ctx
      end

    {ctx, _} = s_s_zone(ctx, [])
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  defp s_s_zone(ctx, _args) do
    try do
      {ctx, v2} = select(ctx, ["I wish to go.", "I want to stay."])

      ctx =
        case v2 do
          1 ->
            throw({:script_return, {ctx, nil}})

          2 ->
            ctx =
              ctx
              |> mes("[Kafra Employee]")
              |> mes("Want to check out our other services?")
              |> close()
              |> cutin("", 255)

            ctx

          _ ->
            ctx
        end

      {ctx, nil}
    catch
      :throw, {:script_return, result} -> result
    end
  end
end
