defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.AbyssChaser do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4260,
      name: :abyss_chaser,
      base_hp: Tables.BasepointsAbyssChaser.base_hp(),
      base_sp: Tables.BasepointsAbyssChaser.base_sp(),
      base_ap: Tables.BasepointsAbyssChaser.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, luk: 1, pow: 1},
        2 => %Job.BonusStats{level: 2, str: 1, spl: 1},
        3 => %Job.BonusStats{level: 3, dex: 1},
        4 => %Job.BonusStats{level: 4, luk: 1},
        5 => %Job.BonusStats{level: 5, str: 1, int: 1},
        6 => %Job.BonusStats{level: 6, int: 1},
        7 => %Job.BonusStats{level: 7, luk: 1, pow: 1},
        8 => %Job.BonusStats{level: 8, agi: 1, sta: 1},
        9 => %Job.BonusStats{level: 9, dex: 1, con: 1},
        10 => %Job.BonusStats{level: 10, vit: 1, int: 1},
        11 => %Job.BonusStats{level: 11, vit: 1, con: 1},
        12 => %Job.BonusStats{level: 12, str: 1},
        13 => %Job.BonusStats{level: 13, str: 1, int: 1},
        14 => %Job.BonusStats{level: 14, luk: 1},
        15 => %Job.BonusStats{level: 15, spl: 1},
        16 => %Job.BonusStats{level: 16, dex: 1, crt: 1},
        17 => %Job.BonusStats{level: 17, agi: 1, wis: 1},
        18 => %Job.BonusStats{level: 18, vit: 1},
        19 => %Job.BonusStats{level: 19, int: 1, wis: 1},
        20 => %Job.BonusStats{level: 20, vit: 1, sta: 1},
        21 => %Job.BonusStats{level: 21, str: 1, int: 1},
        22 => %Job.BonusStats{level: 22, vit: 1, dex: 1},
        23 => %Job.BonusStats{level: 23, agi: 1, sta: 1},
        24 => %Job.BonusStats{level: 24, luk: 1},
        25 => %Job.BonusStats{level: 25, agi: 1, vit: 1},
        26 => %Job.BonusStats{level: 26, luk: 1},
        27 => %Job.BonusStats{level: 27, str: 1, agi: 1},
        28 => %Job.BonusStats{level: 28, agi: 1},
        29 => %Job.BonusStats{level: 29, agi: 1, vit: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 31, str: 1, agi: 1},
        32 => %Job.BonusStats{level: 32, str: 1},
        33 => %Job.BonusStats{level: 33, vit: 1},
        34 => %Job.BonusStats{level: 34, pow: 1, wis: 1},
        35 => %Job.BonusStats{level: 35, spl: 1},
        36 => %Job.BonusStats{level: 36, pow: 1},
        37 => %Job.BonusStats{level: 37, sta: 1, con: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 39, crt: 1},
        40 => %Job.BonusStats{level: 40, crt: 1},
        41 => %Job.BonusStats{level: 41, agi: 1, sta: 1},
        42 => %Job.BonusStats{level: 42, pow: 1},
        43 => %Job.BonusStats{level: 43, crt: 1},
        44 => %Job.BonusStats{level: 44, pow: 1},
        45 => %Job.BonusStats{level: 45, spl: 1, crt: 1},
        46 => %Job.BonusStats{level: 46, spl: 1},
        47 => %Job.BonusStats{level: 47, wis: 1},
        48 => %Job.BonusStats{level: 48, spl: 1, con: 1},
        49 => %Job.BonusStats{level: 49, sta: 1},
        50 => %Job.BonusStats{level: 50, pow: 1, spl: 1},
        51 => %Job.BonusStats{level: 51, pow: 1},
        52 => %Job.BonusStats{level: 52, crt: 1},
        53 => %Job.BonusStats{level: 52, crt: 1},
        54 => %Job.BonusStats{level: 54, sta: 1},
        55 => %Job.BonusStats{level: 55, sta: 1, con: 1},
        56 => %Job.BonusStats{level: 56, spl: 1},
        57 => %Job.BonusStats{level: 56, spl: 1},
        58 => %Job.BonusStats{level: 56, spl: 1},
        59 => %Job.BonusStats{level: 59, pow: 1},
        60 => %Job.BonusStats{level: 59, pow: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 43, one_handed_sword: 47, bow: 47, shield: 4},
      hp_factor: 85,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
