defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.ArchMage do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4255,
      name: :arch_mage,
      base_hp: Tables.BasepointsArchMage.base_hp(),
      base_sp: Tables.BasepointsArchMage.base_sp(),
      base_ap: Tables.BasepointsArchMage.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1, spl: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 3, wis: 1},
        4 => %Job.BonusStats{level: 4, vit: 1, spl: 1},
        5 => %Job.BonusStats{level: 5, vit: 1, int: 1},
        6 => %Job.BonusStats{level: 6, luk: 1},
        7 => %Job.BonusStats{level: 7, wis: 1, con: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, str: 1, agi: 1},
        10 => %Job.BonusStats{level: 10, wis: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 12, vit: 1, int: 1},
        13 => %Job.BonusStats{level: 13, dex: 1, spl: 1},
        14 => %Job.BonusStats{level: 14, sta: 1, con: 1},
        15 => %Job.BonusStats{level: 15, luk: 1},
        16 => %Job.BonusStats{level: 16, agi: 1, int: 1},
        17 => %Job.BonusStats{level: 17, sta: 1},
        18 => %Job.BonusStats{level: 18, int: 1, dex: 1},
        19 => %Job.BonusStats{level: 19, int: 1},
        20 => %Job.BonusStats{level: 20, vit: 1, int: 1},
        21 => %Job.BonusStats{level: 21, luk: 1, spl: 1},
        22 => %Job.BonusStats{level: 22, con: 1},
        23 => %Job.BonusStats{level: 23, agi: 1, sta: 1},
        24 => %Job.BonusStats{level: 24, dex: 1},
        25 => %Job.BonusStats{level: 25, int: 1, dex: 1},
        26 => %Job.BonusStats{level: 26, int: 1, spl: 1},
        27 => %Job.BonusStats{level: 27, con: 1},
        28 => %Job.BonusStats{level: 28, agi: 1},
        29 => %Job.BonusStats{level: 29, luk: 1, spl: 1},
        30 => %Job.BonusStats{level: 30, crt: 1},
        31 => %Job.BonusStats{level: 31, agi: 1, dex: 1},
        32 => %Job.BonusStats{level: 32, dex: 1},
        33 => %Job.BonusStats{level: 33, con: 1},
        34 => %Job.BonusStats{level: 34, int: 1, con: 1},
        35 => %Job.BonusStats{level: 35, int: 1},
        36 => %Job.BonusStats{level: 36, spl: 1},
        37 => %Job.BonusStats{level: 37, vit: 1, spl: 1},
        38 => %Job.BonusStats{level: 38, agi: 1, int: 1},
        39 => %Job.BonusStats{level: 39, dex: 1},
        40 => %Job.BonusStats{level: 40, vit: 1},
        41 => %Job.BonusStats{level: 41, vit: 1, sta: 1},
        42 => %Job.BonusStats{level: 42, con: 1},
        43 => %Job.BonusStats{level: 43, vit: 1, spl: 1},
        44 => %Job.BonusStats{level: 44, int: 1, sta: 1},
        45 => %Job.BonusStats{level: 45, wis: 1},
        46 => %Job.BonusStats{level: 46, int: 1, spl: 1},
        47 => %Job.BonusStats{level: 47, spl: 1},
        48 => %Job.BonusStats{level: 48, sta: 1, wis: 1},
        49 => %Job.BonusStats{level: 49, con: 1},
        50 => %Job.BonusStats{level: 50, sta: 1, wis: 1},
        51 => %Job.BonusStats{level: 50, sta: 1, wis: 1},
        52 => %Job.BonusStats{level: 52, spl: 1},
        53 => %Job.BonusStats{level: 53, con: 1},
        54 => %Job.BonusStats{level: 54, sta: 1, wis: 1},
        55 => %Job.BonusStats{level: 55, spl: 1},
        56 => %Job.BonusStats{level: 55, spl: 1},
        57 => %Job.BonusStats{level: 57, wis: 1},
        58 => %Job.BonusStats{level: 57, wis: 1},
        59 => %Job.BonusStats{level: 59, spl: 1},
        60 => %Job.BonusStats{level: 59, spl: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 45,
        dagger: 52,
        one_handed_sword: 60,
        staff: 50,
        two_handed_staff: 56,
        shield: 5
      },
      hp_factor: 55,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 40_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
