defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.AssassinCross do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4013,
      name: :assassin_cross,
      base_hp: Tables.BasepointsAssassin.base_hp(),
      base_sp: Tables.BasepointsAssassin.base_sp(),
      base_ap: Tables.BasepointsAssassin.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, str: 1},
        3 => %Job.BonusStats{level: 3, luk: 1},
        4 => %Job.BonusStats{level: 4, agi: 1},
        5 => %Job.BonusStats{level: 5, agi: 1},
        6 => %Job.BonusStats{level: 5, agi: 1},
        7 => %Job.BonusStats{level: 7, str: 1},
        8 => %Job.BonusStats{level: 8, luk: 1},
        9 => %Job.BonusStats{level: 9, vit: 1},
        10 => %Job.BonusStats{level: 10, dex: 1},
        11 => %Job.BonusStats{level: 10, dex: 1},
        12 => %Job.BonusStats{level: 12, str: 1},
        13 => %Job.BonusStats{level: 12, str: 1},
        14 => %Job.BonusStats{level: 12, str: 1},
        15 => %Job.BonusStats{level: 15, agi: 1},
        16 => %Job.BonusStats{level: 16, luk: 1},
        17 => %Job.BonusStats{level: 16, luk: 1},
        18 => %Job.BonusStats{level: 18, luk: 1},
        19 => %Job.BonusStats{level: 18, luk: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 21, str: 1},
        22 => %Job.BonusStats{level: 21, str: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 25, agi: 1},
        26 => %Job.BonusStats{level: 26, luk: 1},
        27 => %Job.BonusStats{level: 26, luk: 1},
        28 => %Job.BonusStats{level: 26, luk: 1},
        29 => %Job.BonusStats{level: 29, str: 1},
        30 => %Job.BonusStats{level: 29, str: 1},
        31 => %Job.BonusStats{level: 31, agi: 1},
        32 => %Job.BonusStats{level: 32, agi: 1},
        33 => %Job.BonusStats{level: 33, agi: 1},
        34 => %Job.BonusStats{level: 34, luk: 1},
        35 => %Job.BonusStats{level: 34, luk: 1},
        36 => %Job.BonusStats{level: 34, luk: 1},
        37 => %Job.BonusStats{level: 37, dex: 1},
        38 => %Job.BonusStats{level: 38, str: 1},
        39 => %Job.BonusStats{level: 39, dex: 1},
        40 => %Job.BonusStats{level: 39, dex: 1},
        41 => %Job.BonusStats{level: 39, dex: 1},
        42 => %Job.BonusStats{level: 42, agi: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 43, dex: 1},
        45 => %Job.BonusStats{level: 43, dex: 1},
        46 => %Job.BonusStats{level: 46, agi: 1},
        47 => %Job.BonusStats{level: 47, vit: 1},
        48 => %Job.BonusStats{level: 48, luk: 1},
        49 => %Job.BonusStats{level: 48, luk: 1},
        50 => %Job.BonusStats{level: 50, str: 1},
        51 => %Job.BonusStats{level: 51, agi: 1},
        52 => %Job.BonusStats{level: 51, agi: 1},
        53 => %Job.BonusStats{level: 53, dex: 1},
        54 => %Job.BonusStats{level: 54, str: 1},
        55 => %Job.BonusStats{level: 54, str: 1},
        56 => %Job.BonusStats{level: 56, agi: 1},
        57 => %Job.BonusStats{level: 57, dex: 1},
        58 => %Job.BonusStats{level: 57, dex: 1},
        59 => %Job.BonusStats{level: 57, dex: 1},
        60 => %Job.BonusStats{level: 57, dex: 1},
        61 => %Job.BonusStats{level: 61, dex: 1},
        62 => %Job.BonusStats{level: 62, agi: 1},
        63 => %Job.BonusStats{level: 62, agi: 1},
        64 => %Job.BonusStats{level: 64, dex: 1},
        65 => %Job.BonusStats{level: 65, luk: 1},
        66 => %Job.BonusStats{level: 66, str: 1},
        67 => %Job.BonusStats{level: 66, str: 1},
        68 => %Job.BonusStats{level: 66, str: 1},
        69 => %Job.BonusStats{level: 69, vit: 1},
        70 => %Job.BonusStats{level: 70, dex: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 42,
        one_handed_sword: 50,
        one_handed_axe: 51,
        katar: 42,
        huuma: 110,
        shield: 6
      },
      hp_factor: 110,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 24_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
