defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabyRoyalGuard do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4102,
      name: :baby_royal_guard,
      base_hp: Tables.BasepointsBabyRoyalGuard.base_hp(),
      base_sp: Tables.BasepointsBabyRoyalGuard.base_sp(),
      base_ap: Tables.BasepointsBabyRoyalGuard.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        2 => %Job.BonusStats{level: 2, vit: 1},
        3 => %Job.BonusStats{level: 3, int: 1},
        4 => %Job.BonusStats{level: 4, str: 1},
        5 => %Job.BonusStats{level: 5, int: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 6, dex: 1},
        8 => %Job.BonusStats{level: 6, dex: 1},
        9 => %Job.BonusStats{level: 9, vit: 1},
        10 => %Job.BonusStats{level: 9, vit: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 11, int: 1},
        13 => %Job.BonusStats{level: 13, str: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 14, dex: 1},
        16 => %Job.BonusStats{level: 16, luk: 1},
        17 => %Job.BonusStats{level: 16, luk: 1},
        18 => %Job.BonusStats{level: 16, luk: 1},
        19 => %Job.BonusStats{level: 19, int: 1},
        20 => %Job.BonusStats{level: 20, dex: 1},
        21 => %Job.BonusStats{level: 20, dex: 1},
        22 => %Job.BonusStats{level: 20, dex: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, int: 1},
        25 => %Job.BonusStats{level: 24, int: 1},
        26 => %Job.BonusStats{level: 26, int: 1},
        27 => %Job.BonusStats{level: 27, vit: 1},
        28 => %Job.BonusStats{level: 27, vit: 1},
        29 => %Job.BonusStats{level: 27, vit: 1},
        30 => %Job.BonusStats{level: 30, str: 1},
        31 => %Job.BonusStats{level: 31, dex: 1},
        32 => %Job.BonusStats{level: 31, dex: 1},
        33 => %Job.BonusStats{level: 33, luk: 1},
        34 => %Job.BonusStats{level: 34, agi: 1},
        35 => %Job.BonusStats{level: 34, agi: 1},
        36 => %Job.BonusStats{level: 34, agi: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 38, int: 1},
        40 => %Job.BonusStats{level: 40, str: 1},
        41 => %Job.BonusStats{level: 41, vit: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 42, vit: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 46, int: 1},
        47 => %Job.BonusStats{level: 46, int: 1},
        48 => %Job.BonusStats{level: 48, str: 1},
        49 => %Job.BonusStats{level: 49, dex: 1},
        50 => %Job.BonusStats{level: 49, dex: 1},
        51 => %Job.BonusStats{level: 51, agi: 1},
        52 => %Job.BonusStats{level: 51, agi: 1},
        53 => %Job.BonusStats{level: 53, vit: 1},
        54 => %Job.BonusStats{level: 54, luk: 1},
        55 => %Job.BonusStats{level: 54, luk: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 56, dex: 1},
        58 => %Job.BonusStats{level: 58, str: 1},
        59 => %Job.BonusStats{level: 59, vit: 1},
        60 => %Job.BonusStats{level: 60, int: 1},
        61 => %Job.BonusStats{level: 60, int: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, vit: 1},
        65 => %Job.BonusStats{level: 65, str: 1},
        66 => %Job.BonusStats{level: 65, str: 1},
        67 => %Job.BonusStats{level: 67, dex: 1},
        68 => %Job.BonusStats{level: 67, dex: 1},
        69 => %Job.BonusStats{level: 69, vit: 1},
        70 => %Job.BonusStats{level: 70, str: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 47,
        one_handed_sword: 45,
        two_handed_sword: 53,
        one_handed_spear: 50,
        two_handed_spear: 50,
        one_handed_axe: 48,
        two_handed_axe: 52,
        mace: 44,
        two_handed_mace: 50,
        shield: 5
      },
      hp_factor: 110,
      hp_increase: 700,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
