defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabyRebellion do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4229,
      name: :baby_rebellion,
      base_hp: Tables.BasepointsBabyRebellion.base_hp(),
      base_sp: Tables.BasepointsBabyRebellion.base_sp(),
      base_ap: Tables.BasepointsBabyRebellion.base_ap(),
      base_exp: Tables.ExpBabyKagerou.base_exp(),
      job_exp: Tables.ExpBabyKagerou.job_exp(),
      bonus_stats: %{
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 2, dex: 1},
        4 => %Job.BonusStats{level: 4, int: 1},
        5 => %Job.BonusStats{level: 4, int: 1},
        6 => %Job.BonusStats{level: 6, vit: 1},
        7 => %Job.BonusStats{level: 7, dex: 1},
        8 => %Job.BonusStats{level: 8, int: 1},
        9 => %Job.BonusStats{level: 9, agi: 1},
        10 => %Job.BonusStats{level: 10, luk: 1},
        11 => %Job.BonusStats{level: 10, luk: 1},
        12 => %Job.BonusStats{level: 10, luk: 1},
        13 => %Job.BonusStats{level: 13, vit: 1},
        14 => %Job.BonusStats{level: 14, int: 1},
        15 => %Job.BonusStats{level: 14, int: 1},
        16 => %Job.BonusStats{level: 16, agi: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, int: 1},
        19 => %Job.BonusStats{level: 19, vit: 1},
        20 => %Job.BonusStats{level: 20, luk: 1},
        21 => %Job.BonusStats{level: 20, luk: 1},
        22 => %Job.BonusStats{level: 20, luk: 1},
        23 => %Job.BonusStats{level: 23, vit: 1},
        24 => %Job.BonusStats{level: 24, dex: 1},
        25 => %Job.BonusStats{level: 25, str: 1},
        26 => %Job.BonusStats{level: 26, int: 1},
        27 => %Job.BonusStats{level: 27, agi: 1},
        28 => %Job.BonusStats{level: 27, agi: 1},
        29 => %Job.BonusStats{level: 27, agi: 1},
        30 => %Job.BonusStats{level: 30, luk: 1},
        31 => %Job.BonusStats{level: 31, vit: 1},
        32 => %Job.BonusStats{level: 31, vit: 1},
        33 => %Job.BonusStats{level: 33, dex: 1},
        34 => %Job.BonusStats{level: 34, int: 1},
        35 => %Job.BonusStats{level: 35, str: 1},
        36 => %Job.BonusStats{level: 35, str: 1},
        37 => %Job.BonusStats{level: 35, str: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 38, dex: 1},
        40 => %Job.BonusStats{level: 40, agi: 1},
        41 => %Job.BonusStats{level: 41, luk: 1},
        42 => %Job.BonusStats{level: 41, luk: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 44, vit: 1},
        45 => %Job.BonusStats{level: 45, int: 1},
        46 => %Job.BonusStats{level: 45, int: 1},
        47 => %Job.BonusStats{level: 45, int: 1},
        48 => %Job.BonusStats{level: 45, int: 1},
        49 => %Job.BonusStats{level: 45, int: 1},
        50 => %Job.BonusStats{level: 50, str: 1},
        51 => %Job.BonusStats{level: 51, agi: 1},
        52 => %Job.BonusStats{level: 52, luk: 1},
        53 => %Job.BonusStats{level: 52, luk: 1},
        54 => %Job.BonusStats{level: 54, int: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 55, dex: 1},
        57 => %Job.BonusStats{level: 57, agi: 1},
        58 => %Job.BonusStats{level: 57, agi: 1},
        59 => %Job.BonusStats{level: 57, agi: 1},
        60 => %Job.BonusStats{level: 60, dex: 1},
        61 => %Job.BonusStats{level: 60, dex: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, luk: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, dex: 1},
        67 => %Job.BonusStats{level: 66, dex: 1},
        68 => %Job.BonusStats{level: 66, dex: 1},
        69 => %Job.BonusStats{level: 69, agi: 1},
        70 => %Job.BonusStats{level: 70, luk: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 54,
        revolver: 49,
        rifle: 59,
        gatling: 54,
        shotgun: 94,
        grenade: 104,
        shield: 6
      },
      hp_factor: 90,
      hp_increase: 650,
      sp_factor: 0,
      sp_increase: 469,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
