defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabySummoner do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4220,
      name: :baby_summoner,
      base_hp: Tables.BasepointsBabySummoner.base_hp(),
      base_sp: Tables.BasepointsBabySummoner.base_sp(),
      base_ap: Tables.BasepointsBabySummoner.base_ap(),
      base_exp: Tables.ExpBabySummoner.base_exp(),
      job_exp: Tables.ExpBabySummoner.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, vit: 1},
        4 => %Job.BonusStats{level: 3, vit: 1},
        5 => %Job.BonusStats{level: 5, dex: 1},
        6 => %Job.BonusStats{level: 6, vit: 1},
        7 => %Job.BonusStats{level: 6, vit: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, int: 1},
        10 => %Job.BonusStats{level: 9, int: 1},
        11 => %Job.BonusStats{level: 11, agi: 1},
        12 => %Job.BonusStats{level: 12, int: 1},
        13 => %Job.BonusStats{level: 13, dex: 1},
        14 => %Job.BonusStats{level: 13, dex: 1},
        15 => %Job.BonusStats{level: 15, agi: 1},
        16 => %Job.BonusStats{level: 16, int: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 17, dex: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, int: 1},
        21 => %Job.BonusStats{level: 21, dex: 1},
        22 => %Job.BonusStats{level: 21, dex: 1},
        23 => %Job.BonusStats{level: 23, luk: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 25, dex: 1},
        26 => %Job.BonusStats{level: 25, dex: 1},
        27 => %Job.BonusStats{level: 27, agi: 1},
        28 => %Job.BonusStats{level: 27, agi: 1},
        29 => %Job.BonusStats{level: 29, luk: 1},
        30 => %Job.BonusStats{level: 29, luk: 1},
        31 => %Job.BonusStats{level: 31, int: 1},
        32 => %Job.BonusStats{level: 32, dex: 1},
        33 => %Job.BonusStats{level: 32, dex: 1},
        34 => %Job.BonusStats{level: 34, luk: 1},
        35 => %Job.BonusStats{level: 34, luk: 1},
        36 => %Job.BonusStats{level: 36, int: 1},
        37 => %Job.BonusStats{level: 37, luk: 1},
        38 => %Job.BonusStats{level: 37, luk: 1},
        39 => %Job.BonusStats{level: 39, agi: 1},
        40 => %Job.BonusStats{level: 39, agi: 1},
        41 => %Job.BonusStats{level: 41, dex: 1},
        42 => %Job.BonusStats{level: 42, int: 1},
        43 => %Job.BonusStats{level: 43, vit: 1},
        44 => %Job.BonusStats{level: 43, vit: 1},
        45 => %Job.BonusStats{level: 45, dex: 1},
        46 => %Job.BonusStats{level: 46, luk: 1},
        47 => %Job.BonusStats{level: 47, vit: 1},
        48 => %Job.BonusStats{level: 48, agi: 1},
        49 => %Job.BonusStats{level: 48, agi: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 50, dex: 1},
        52 => %Job.BonusStats{level: 50, dex: 1},
        53 => %Job.BonusStats{level: 53, int: 1},
        54 => %Job.BonusStats{level: 53, int: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 55, dex: 1},
        57 => %Job.BonusStats{level: 55, dex: 1},
        58 => %Job.BonusStats{level: 58, int: 1},
        59 => %Job.BonusStats{level: 58, int: 1},
        60 => %Job.BonusStats{level: 60, dex: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, staff: 60, shield: 7},
      hp_factor: 100,
      hp_increase: 700,
      sp_factor: 0,
      sp_increase: 200,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 0,
      max_base_level: 200,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
