defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabySoulReaper do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4242,
      name: :baby_soul_reaper,
      base_hp: Tables.BasepointsBabySoulReaper.base_hp(),
      base_sp: Tables.BasepointsBabySoulReaper.base_sp(),
      base_ap: Tables.BasepointsBabySoulReaper.base_ap(),
      base_exp: Tables.ExpBabyKagerou.base_exp(),
      job_exp: Tables.ExpBabyKagerou.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 2, dex: 1},
        4 => %Job.BonusStats{level: 2, dex: 1},
        5 => %Job.BonusStats{level: 5, int: 1},
        6 => %Job.BonusStats{level: 6, vit: 1},
        7 => %Job.BonusStats{level: 7, dex: 1},
        8 => %Job.BonusStats{level: 7, dex: 1},
        9 => %Job.BonusStats{level: 7, dex: 1},
        10 => %Job.BonusStats{level: 7, dex: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, int: 1},
        13 => %Job.BonusStats{level: 13, agi: 1},
        14 => %Job.BonusStats{level: 13, agi: 1},
        15 => %Job.BonusStats{level: 15, dex: 1},
        16 => %Job.BonusStats{level: 16, int: 1},
        17 => %Job.BonusStats{level: 17, vit: 1},
        18 => %Job.BonusStats{level: 17, vit: 1},
        19 => %Job.BonusStats{level: 19, str: 1},
        20 => %Job.BonusStats{level: 20, dex: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 21, agi: 1},
        23 => %Job.BonusStats{level: 21, agi: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 25, int: 1},
        26 => %Job.BonusStats{level: 26, dex: 1},
        27 => %Job.BonusStats{level: 26, dex: 1},
        28 => %Job.BonusStats{level: 28, str: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 31, int: 1},
        32 => %Job.BonusStats{level: 31, int: 1},
        33 => %Job.BonusStats{level: 31, int: 1},
        34 => %Job.BonusStats{level: 34, dex: 1},
        35 => %Job.BonusStats{level: 35, agi: 1},
        36 => %Job.BonusStats{level: 35, agi: 1},
        37 => %Job.BonusStats{level: 37, vit: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 39, int: 1},
        40 => %Job.BonusStats{level: 39, int: 1},
        41 => %Job.BonusStats{level: 41, agi: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 43, str: 1},
        44 => %Job.BonusStats{level: 44, int: 1},
        45 => %Job.BonusStats{level: 45, dex: 1},
        46 => %Job.BonusStats{level: 45, dex: 1},
        47 => %Job.BonusStats{level: 47, agi: 1},
        48 => %Job.BonusStats{level: 47, agi: 1},
        49 => %Job.BonusStats{level: 49, int: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 50, dex: 1},
        52 => %Job.BonusStats{level: 52, agi: 1},
        53 => %Job.BonusStats{level: 52, agi: 1},
        54 => %Job.BonusStats{level: 54, int: 1},
        55 => %Job.BonusStats{level: 54, int: 1},
        56 => %Job.BonusStats{level: 54, int: 1},
        57 => %Job.BonusStats{level: 54, int: 1},
        58 => %Job.BonusStats{level: 54, int: 1},
        59 => %Job.BonusStats{level: 59, int: 1},
        60 => %Job.BonusStats{level: 59, int: 1},
        61 => %Job.BonusStats{level: 59, int: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, vit: 1},
        65 => %Job.BonusStats{level: 65, luk: 1},
        66 => %Job.BonusStats{level: 65, luk: 1},
        67 => %Job.BonusStats{level: 67, dex: 1},
        68 => %Job.BonusStats{level: 67, dex: 1},
        69 => %Job.BonusStats{level: 69, vit: 1},
        70 => %Job.BonusStats{level: 70, luk: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 50, dagger: 50, staff: 53, two_handed_staff: 55, shield: 8},
      hp_factor: 75,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 24_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
