defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabyRanger2 do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4111,
      name: :baby_ranger2,
      base_hp: Tables.BasepointsBabyRanger.base_hp(),
      base_sp: Tables.BasepointsBabyRanger.base_sp(),
      base_ap: Tables.BasepointsBabyRanger.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, int: 1},
        3 => %Job.BonusStats{level: 3, int: 1},
        4 => %Job.BonusStats{level: 4, agi: 1},
        5 => %Job.BonusStats{level: 4, agi: 1},
        6 => %Job.BonusStats{level: 4, agi: 1},
        7 => %Job.BonusStats{level: 7, agi: 1},
        8 => %Job.BonusStats{level: 8, dex: 1},
        9 => %Job.BonusStats{level: 9, int: 1},
        10 => %Job.BonusStats{level: 9, int: 1},
        11 => %Job.BonusStats{level: 9, int: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 13, vit: 1},
        14 => %Job.BonusStats{level: 14, vit: 1},
        15 => %Job.BonusStats{level: 14, vit: 1},
        16 => %Job.BonusStats{level: 14, vit: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, agi: 1},
        19 => %Job.BonusStats{level: 18, agi: 1},
        20 => %Job.BonusStats{level: 18, agi: 1},
        21 => %Job.BonusStats{level: 21, int: 1},
        22 => %Job.BonusStats{level: 22, vit: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 23, dex: 1},
        25 => %Job.BonusStats{level: 23, dex: 1},
        26 => %Job.BonusStats{level: 26, str: 1},
        27 => %Job.BonusStats{level: 27, str: 1},
        28 => %Job.BonusStats{level: 27, str: 1},
        29 => %Job.BonusStats{level: 27, str: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 31, agi: 1},
        32 => %Job.BonusStats{level: 32, vit: 1},
        33 => %Job.BonusStats{level: 32, vit: 1},
        34 => %Job.BonusStats{level: 32, vit: 1},
        35 => %Job.BonusStats{level: 32, vit: 1},
        36 => %Job.BonusStats{level: 36, int: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 39, agi: 1},
        40 => %Job.BonusStats{level: 39, agi: 1},
        41 => %Job.BonusStats{level: 39, agi: 1},
        42 => %Job.BonusStats{level: 39, agi: 1},
        43 => %Job.BonusStats{level: 43, agi: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 45, agi: 1},
        46 => %Job.BonusStats{level: 45, agi: 1},
        47 => %Job.BonusStats{level: 45, agi: 1},
        48 => %Job.BonusStats{level: 45, agi: 1},
        49 => %Job.BonusStats{level: 49, int: 1},
        50 => %Job.BonusStats{level: 50, agi: 1},
        51 => %Job.BonusStats{level: 51, luk: 1},
        52 => %Job.BonusStats{level: 52, dex: 1},
        53 => %Job.BonusStats{level: 52, dex: 1},
        54 => %Job.BonusStats{level: 54, int: 1},
        55 => %Job.BonusStats{level: 55, agi: 1},
        56 => %Job.BonusStats{level: 55, agi: 1},
        57 => %Job.BonusStats{level: 57, vit: 1},
        58 => %Job.BonusStats{level: 58, luk: 1},
        59 => %Job.BonusStats{level: 59, dex: 1},
        60 => %Job.BonusStats{level: 60, agi: 1},
        61 => %Job.BonusStats{level: 61, agi: 1},
        62 => %Job.BonusStats{level: 61, agi: 1},
        63 => %Job.BonusStats{level: 63, vit: 1},
        64 => %Job.BonusStats{level: 63, vit: 1},
        65 => %Job.BonusStats{level: 65, luk: 1},
        66 => %Job.BonusStats{level: 66, agi: 1},
        67 => %Job.BonusStats{level: 66, agi: 1},
        68 => %Job.BonusStats{level: 68, vit: 1},
        69 => %Job.BonusStats{level: 68, vit: 1},
        70 => %Job.BonusStats{level: 70, luk: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 50, bow: 49, shield: 8},
      hp_factor: 85,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 27_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
