defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.BabyMinstrel do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4104,
      name: :baby_minstrel,
      base_hp: Tables.BasepointsBabyMinstrel.base_hp(),
      base_sp: Tables.BasepointsBabyMinstrel.base_sp(),
      base_ap: Tables.BasepointsBabyMinstrel.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 1, int: 1},
        3 => %Job.BonusStats{level: 3, vit: 1},
        4 => %Job.BonusStats{level: 3, vit: 1},
        5 => %Job.BonusStats{level: 5, dex: 1},
        6 => %Job.BonusStats{level: 5, dex: 1},
        7 => %Job.BonusStats{level: 7, int: 1},
        8 => %Job.BonusStats{level: 8, int: 1},
        9 => %Job.BonusStats{level: 8, int: 1},
        10 => %Job.BonusStats{level: 10, vit: 1},
        11 => %Job.BonusStats{level: 11, vit: 1},
        12 => %Job.BonusStats{level: 11, vit: 1},
        13 => %Job.BonusStats{level: 11, vit: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 15, dex: 1},
        16 => %Job.BonusStats{level: 15, dex: 1},
        17 => %Job.BonusStats{level: 15, dex: 1},
        18 => %Job.BonusStats{level: 18, str: 1},
        19 => %Job.BonusStats{level: 19, str: 1},
        20 => %Job.BonusStats{level: 19, str: 1},
        21 => %Job.BonusStats{level: 19, str: 1},
        22 => %Job.BonusStats{level: 22, int: 1},
        23 => %Job.BonusStats{level: 22, int: 1},
        24 => %Job.BonusStats{level: 24, str: 1},
        25 => %Job.BonusStats{level: 24, str: 1},
        26 => %Job.BonusStats{level: 26, agi: 1},
        27 => %Job.BonusStats{level: 27, agi: 1},
        28 => %Job.BonusStats{level: 28, str: 1},
        29 => %Job.BonusStats{level: 28, str: 1},
        30 => %Job.BonusStats{level: 28, str: 1},
        31 => %Job.BonusStats{level: 28, str: 1},
        32 => %Job.BonusStats{level: 32, int: 1},
        33 => %Job.BonusStats{level: 32, int: 1},
        34 => %Job.BonusStats{level: 34, vit: 1},
        35 => %Job.BonusStats{level: 34, vit: 1},
        36 => %Job.BonusStats{level: 36, dex: 1},
        37 => %Job.BonusStats{level: 36, dex: 1},
        38 => %Job.BonusStats{level: 38, agi: 1},
        39 => %Job.BonusStats{level: 39, agi: 1},
        40 => %Job.BonusStats{level: 40, int: 1},
        41 => %Job.BonusStats{level: 41, int: 1},
        42 => %Job.BonusStats{level: 41, int: 1},
        43 => %Job.BonusStats{level: 41, int: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 45, vit: 1},
        46 => %Job.BonusStats{level: 46, str: 1},
        47 => %Job.BonusStats{level: 46, str: 1},
        48 => %Job.BonusStats{level: 46, str: 1},
        49 => %Job.BonusStats{level: 49, int: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 51, agi: 1},
        52 => %Job.BonusStats{level: 52, vit: 1},
        53 => %Job.BonusStats{level: 53, str: 1},
        54 => %Job.BonusStats{level: 54, luk: 1},
        55 => %Job.BonusStats{level: 54, luk: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 57, vit: 1},
        58 => %Job.BonusStats{level: 58, str: 1},
        59 => %Job.BonusStats{level: 59, int: 1},
        60 => %Job.BonusStats{level: 60, dex: 1},
        61 => %Job.BonusStats{level: 61, agi: 1},
        62 => %Job.BonusStats{level: 61, agi: 1},
        63 => %Job.BonusStats{level: 63, dex: 1},
        64 => %Job.BonusStats{level: 63, dex: 1},
        65 => %Job.BonusStats{level: 65, luk: 1},
        66 => %Job.BonusStats{level: 66, agi: 1},
        67 => %Job.BonusStats{level: 66, agi: 1},
        68 => %Job.BonusStats{level: 68, dex: 1},
        69 => %Job.BonusStats{level: 68, dex: 1},
        70 => %Job.BonusStats{level: 70, luk: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 52, bow: 49, musical: 44, shield: 7},
      hp_factor: 75,
      hp_increase: 300,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 27_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
