defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Biolo do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4259,
      name: :biolo,
      base_hp: Tables.BasepointsBiolo.base_hp(),
      base_sp: Tables.BasepointsBiolo.base_sp(),
      base_ap: Tables.BasepointsBiolo.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, int: 1, crt: 1},
        3 => %Job.BonusStats{level: 3, dex: 1},
        4 => %Job.BonusStats{level: 4, sta: 1, spl: 1},
        5 => %Job.BonusStats{level: 5, vit: 1},
        6 => %Job.BonusStats{level: 6, spl: 1, con: 1},
        7 => %Job.BonusStats{level: 7, dex: 1},
        8 => %Job.BonusStats{level: 8, vit: 1, int: 1},
        9 => %Job.BonusStats{level: 9, agi: 1},
        10 => %Job.BonusStats{level: 10, wis: 1},
        11 => %Job.BonusStats{level: 11, vit: 1, con: 1},
        12 => %Job.BonusStats{level: 12, crt: 1},
        13 => %Job.BonusStats{level: 13, int: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 15, spl: 1, crt: 1},
        16 => %Job.BonusStats{level: 16, vit: 1},
        17 => %Job.BonusStats{level: 17, luk: 1},
        18 => %Job.BonusStats{level: 18, str: 1, pow: 1},
        19 => %Job.BonusStats{level: 19, vit: 1, con: 1},
        20 => %Job.BonusStats{level: 20, dex: 1},
        21 => %Job.BonusStats{level: 21, agi: 1, pow: 1},
        22 => %Job.BonusStats{level: 22, con: 1},
        23 => %Job.BonusStats{level: 23, sta: 1},
        24 => %Job.BonusStats{level: 24, int: 1, crt: 1},
        25 => %Job.BonusStats{level: 25, vit: 1, pow: 1},
        26 => %Job.BonusStats{level: 26, vit: 1},
        27 => %Job.BonusStats{level: 27, pow: 1, wis: 1},
        28 => %Job.BonusStats{level: 28, crt: 1},
        29 => %Job.BonusStats{level: 29, dex: 1, crt: 1},
        30 => %Job.BonusStats{level: 30, agi: 1},
        31 => %Job.BonusStats{level: 31, con: 1},
        32 => %Job.BonusStats{level: 32, luk: 1, crt: 1},
        33 => %Job.BonusStats{level: 33, pow: 1},
        34 => %Job.BonusStats{level: 34, spl: 1},
        35 => %Job.BonusStats{level: 35, str: 1, int: 1},
        36 => %Job.BonusStats{level: 36, str: 1, int: 1},
        37 => %Job.BonusStats{level: 37, int: 1, dex: 1},
        38 => %Job.BonusStats{level: 38, pow: 1},
        39 => %Job.BonusStats{level: 39, wis: 1, crt: 1},
        40 => %Job.BonusStats{level: 40, agi: 1, dex: 1},
        41 => %Job.BonusStats{level: 41, str: 1, agi: 1},
        42 => %Job.BonusStats{level: 42, vit: 1, int: 1},
        43 => %Job.BonusStats{level: 43, luk: 1, wis: 1},
        44 => %Job.BonusStats{level: 44, dex: 1, crt: 1},
        45 => %Job.BonusStats{level: 45, int: 1},
        46 => %Job.BonusStats{level: 46, int: 1},
        47 => %Job.BonusStats{level: 47, con: 1},
        48 => %Job.BonusStats{level: 48, agi: 1, int: 1},
        49 => %Job.BonusStats{level: 49, luk: 1, sta: 1},
        50 => %Job.BonusStats{level: 50, str: 1, crt: 1},
        51 => %Job.BonusStats{level: 51, crt: 1},
        52 => %Job.BonusStats{level: 52, sta: 1},
        53 => %Job.BonusStats{level: 53, pow: 1, crt: 1},
        54 => %Job.BonusStats{level: 53, pow: 1, crt: 1},
        55 => %Job.BonusStats{level: 55, con: 1},
        56 => %Job.BonusStats{level: 56, sta: 1},
        57 => %Job.BonusStats{level: 56, sta: 1},
        58 => %Job.BonusStats{level: 56, sta: 1},
        59 => %Job.BonusStats{level: 59, pow: 1},
        60 => %Job.BonusStats{level: 59, pow: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 44,
        one_handed_axe: 48,
        two_handed_axe: 51,
        mace: 44,
        two_handed_mace: 48,
        shield: 4
      },
      hp_factor: 90,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
