defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Champion do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4016,
      name: :champion,
      base_hp: Tables.BasepointsBabyMonk.base_hp(),
      base_sp: Tables.BasepointsBabyMonk.base_sp(),
      base_ap: Tables.BasepointsBabyMonk.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1},
        2 => %Job.BonusStats{level: 2, int: 1},
        3 => %Job.BonusStats{level: 3, vit: 1},
        4 => %Job.BonusStats{level: 4, agi: 1},
        5 => %Job.BonusStats{level: 4, agi: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 6, dex: 1},
        8 => %Job.BonusStats{level: 6, dex: 1},
        9 => %Job.BonusStats{level: 9, str: 1},
        10 => %Job.BonusStats{level: 9, str: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 13, luk: 1},
        14 => %Job.BonusStats{level: 13, luk: 1},
        15 => %Job.BonusStats{level: 15, vit: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 17, str: 1},
        18 => %Job.BonusStats{level: 17, str: 1},
        19 => %Job.BonusStats{level: 17, str: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 22, dex: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 24, vit: 1},
        26 => %Job.BonusStats{level: 24, vit: 1},
        27 => %Job.BonusStats{level: 27, str: 1},
        28 => %Job.BonusStats{level: 27, str: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 30, dex: 1},
        32 => %Job.BonusStats{level: 30, dex: 1},
        33 => %Job.BonusStats{level: 33, int: 1},
        34 => %Job.BonusStats{level: 34, luk: 1},
        35 => %Job.BonusStats{level: 34, luk: 1},
        36 => %Job.BonusStats{level: 34, luk: 1},
        37 => %Job.BonusStats{level: 37, str: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 39, vit: 1},
        40 => %Job.BonusStats{level: 39, vit: 1},
        41 => %Job.BonusStats{level: 39, vit: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 42, vit: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 45, agi: 1},
        46 => %Job.BonusStats{level: 46, luk: 1},
        47 => %Job.BonusStats{level: 47, int: 1},
        48 => %Job.BonusStats{level: 48, str: 1},
        49 => %Job.BonusStats{level: 48, str: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 50, dex: 1},
        52 => %Job.BonusStats{level: 52, agi: 1},
        53 => %Job.BonusStats{level: 53, dex: 1},
        54 => %Job.BonusStats{level: 53, dex: 1},
        55 => %Job.BonusStats{level: 53, dex: 1},
        56 => %Job.BonusStats{level: 56, int: 1},
        57 => %Job.BonusStats{level: 56, int: 1},
        58 => %Job.BonusStats{level: 58, vit: 1},
        59 => %Job.BonusStats{level: 59, str: 1},
        60 => %Job.BonusStats{level: 60, dex: 1},
        61 => %Job.BonusStats{level: 60, dex: 1},
        62 => %Job.BonusStats{level: 62, agi: 1},
        63 => %Job.BonusStats{level: 62, agi: 1},
        64 => %Job.BonusStats{level: 64, int: 1},
        65 => %Job.BonusStats{level: 65, str: 1},
        66 => %Job.BonusStats{level: 66, str: 1},
        67 => %Job.BonusStats{level: 67, dex: 1},
        68 => %Job.BonusStats{level: 68, vit: 1},
        69 => %Job.BonusStats{level: 69, int: 1},
        70 => %Job.BonusStats{level: 70, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        mace: 43,
        two_handed_mace: 48,
        staff: 60,
        knuckle: 40,
        two_handed_staff: 58,
        shield: 5
      },
      hp_factor: 90,
      hp_increase: 650,
      sp_factor: 0,
      sp_increase: 470,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 26_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
