defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Clown do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4020,
      name: :clown,
      base_hp: Tables.BasepointsBabyBard.base_hp(),
      base_sp: Tables.BasepointsBabyBard.base_sp(),
      base_ap: Tables.BasepointsBabyBard.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 2, dex: 1},
        4 => %Job.BonusStats{level: 4, agi: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 5, str: 1},
        7 => %Job.BonusStats{level: 7, dex: 1},
        8 => %Job.BonusStats{level: 8, int: 1},
        9 => %Job.BonusStats{level: 9, agi: 1},
        10 => %Job.BonusStats{level: 10, str: 1},
        11 => %Job.BonusStats{level: 11, luk: 1},
        12 => %Job.BonusStats{level: 11, luk: 1},
        13 => %Job.BonusStats{level: 13, agi: 1},
        14 => %Job.BonusStats{level: 13, agi: 1},
        15 => %Job.BonusStats{level: 15, dex: 1},
        16 => %Job.BonusStats{level: 16, vit: 1},
        17 => %Job.BonusStats{level: 16, vit: 1},
        18 => %Job.BonusStats{level: 18, luk: 1},
        19 => %Job.BonusStats{level: 19, str: 1},
        20 => %Job.BonusStats{level: 19, str: 1},
        21 => %Job.BonusStats{level: 21, int: 1},
        22 => %Job.BonusStats{level: 21, int: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 24, agi: 1},
        26 => %Job.BonusStats{level: 26, luk: 1},
        27 => %Job.BonusStats{level: 26, luk: 1},
        28 => %Job.BonusStats{level: 28, int: 1},
        29 => %Job.BonusStats{level: 28, int: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 30, dex: 1},
        32 => %Job.BonusStats{level: 32, agi: 1},
        33 => %Job.BonusStats{level: 33, str: 1},
        34 => %Job.BonusStats{level: 33, str: 1},
        35 => %Job.BonusStats{level: 33, str: 1},
        36 => %Job.BonusStats{level: 36, agi: 1},
        37 => %Job.BonusStats{level: 36, agi: 1},
        38 => %Job.BonusStats{level: 36, agi: 1},
        39 => %Job.BonusStats{level: 39, dex: 1},
        40 => %Job.BonusStats{level: 40, dex: 1},
        41 => %Job.BonusStats{level: 41, int: 1},
        42 => %Job.BonusStats{level: 41, int: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 43, dex: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 45, str: 1},
        47 => %Job.BonusStats{level: 47, luk: 1},
        48 => %Job.BonusStats{level: 47, luk: 1},
        49 => %Job.BonusStats{level: 49, agi: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 50, dex: 1},
        52 => %Job.BonusStats{level: 50, dex: 1},
        53 => %Job.BonusStats{level: 53, agi: 1},
        54 => %Job.BonusStats{level: 54, str: 1},
        55 => %Job.BonusStats{level: 54, str: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 57, dex: 1},
        58 => %Job.BonusStats{level: 58, agi: 1},
        59 => %Job.BonusStats{level: 59, vit: 1},
        60 => %Job.BonusStats{level: 59, vit: 1},
        61 => %Job.BonusStats{level: 61, dex: 1},
        62 => %Job.BonusStats{level: 62, str: 1},
        63 => %Job.BonusStats{level: 63, dex: 1},
        64 => %Job.BonusStats{level: 63, dex: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, dex: 1},
        67 => %Job.BonusStats{level: 66, dex: 1},
        68 => %Job.BonusStats{level: 68, agi: 1},
        69 => %Job.BonusStats{level: 69, int: 1},
        70 => %Job.BonusStats{level: 70, str: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 53, bow: 48, musical: 45, shield: 7},
      hp_factor: 75,
      hp_increase: 300,
      sp_factor: 0,
      sp_increase: 600,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 27_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
