defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Crusader do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 14,
      name: :crusader,
      base_hp: Tables.BasepointsBabyCrusader.base_hp(),
      base_sp: Tables.BasepointsBabyCrusader.base_sp(),
      base_ap: Tables.BasepointsBabyCrusader.base_ap(),
      base_exp: Tables.ExpAlchemist.base_exp(),
      job_exp: Tables.ExpAlchemist.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, luk: 1},
        2 => %Job.BonusStats{level: 2, luk: 1},
        3 => %Job.BonusStats{level: 3, luk: 1},
        4 => %Job.BonusStats{level: 4, luk: 1},
        5 => %Job.BonusStats{level: 5, luk: 1},
        6 => %Job.BonusStats{level: 5, luk: 1},
        7 => %Job.BonusStats{level: 7, str: 1},
        8 => %Job.BonusStats{level: 7, str: 1},
        9 => %Job.BonusStats{level: 9, int: 1},
        10 => %Job.BonusStats{level: 9, int: 1},
        11 => %Job.BonusStats{level: 11, str: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 12, vit: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 15, vit: 1},
        16 => %Job.BonusStats{level: 15, vit: 1},
        17 => %Job.BonusStats{level: 17, str: 1},
        18 => %Job.BonusStats{level: 17, str: 1},
        19 => %Job.BonusStats{level: 17, str: 1},
        20 => %Job.BonusStats{level: 20, int: 1},
        21 => %Job.BonusStats{level: 21, int: 1},
        22 => %Job.BonusStats{level: 22, vit: 1},
        23 => %Job.BonusStats{level: 23, str: 1},
        24 => %Job.BonusStats{level: 23, str: 1},
        25 => %Job.BonusStats{level: 25, str: 1},
        26 => %Job.BonusStats{level: 25, str: 1},
        27 => %Job.BonusStats{level: 25, str: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 28, dex: 1},
        30 => %Job.BonusStats{level: 30, agi: 1},
        31 => %Job.BonusStats{level: 30, agi: 1},
        32 => %Job.BonusStats{level: 32, str: 1},
        33 => %Job.BonusStats{level: 32, str: 1},
        34 => %Job.BonusStats{level: 34, dex: 1},
        35 => %Job.BonusStats{level: 35, int: 1},
        36 => %Job.BonusStats{level: 36, agi: 1},
        37 => %Job.BonusStats{level: 36, agi: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 38, int: 1},
        40 => %Job.BonusStats{level: 40, vit: 1},
        41 => %Job.BonusStats{level: 41, vit: 1},
        42 => %Job.BonusStats{level: 41, vit: 1},
        43 => %Job.BonusStats{level: 41, vit: 1},
        44 => %Job.BonusStats{level: 44, int: 1},
        45 => %Job.BonusStats{level: 44, int: 1},
        46 => %Job.BonusStats{level: 46, vit: 1},
        47 => %Job.BonusStats{level: 46, vit: 1},
        48 => %Job.BonusStats{level: 48, str: 1},
        49 => %Job.BonusStats{level: 48, str: 1},
        50 => %Job.BonusStats{level: 50, vit: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 48,
        one_handed_sword: 43,
        two_handed_sword: 55,
        one_handed_spear: 53,
        two_handed_spear: 52,
        one_handed_axe: 50,
        two_handed_axe: 55,
        mace: 45,
        two_handed_mace: 50,
        shield: 5
      },
      hp_factor: 110,
      hp_increase: 700,
      sp_factor: 0,
      sp_increase: 470,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 99,
      max_job_level: 50,
      max_stats: nil
    }
  end
end
