defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.DragonKnight do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4252,
      name: :dragon_knight,
      base_hp: Tables.BasepointsDragonKnight.base_hp(),
      base_sp: Tables.BasepointsDragonKnight.base_sp(),
      base_ap: Tables.BasepointsDragonKnight.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1, pow: 1},
        2 => %Job.BonusStats{level: 2, dex: 1, spl: 1},
        3 => %Job.BonusStats{level: 3, agi: 1, crt: 1},
        4 => %Job.BonusStats{level: 4, dex: 1},
        5 => %Job.BonusStats{level: 5, agi: 1, vit: 1, con: 1},
        6 => %Job.BonusStats{level: 5, agi: 1, vit: 1, con: 1},
        7 => %Job.BonusStats{level: 7, luk: 1, spl: 1},
        8 => %Job.BonusStats{level: 8, int: 1, sta: 1},
        9 => %Job.BonusStats{level: 9, str: 1, crt: 1},
        10 => %Job.BonusStats{level: 10, dex: 1},
        11 => %Job.BonusStats{level: 11, int: 1, con: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 12, agi: 1},
        14 => %Job.BonusStats{level: 14, vit: 1, luk: 1},
        15 => %Job.BonusStats{level: 14, vit: 1, luk: 1},
        16 => %Job.BonusStats{level: 16, str: 1, pow: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, int: 1, con: 1},
        19 => %Job.BonusStats{level: 19, agi: 1, vit: 1},
        20 => %Job.BonusStats{level: 20, spl: 1},
        21 => %Job.BonusStats{level: 21, luk: 1},
        22 => %Job.BonusStats{level: 22, sta: 1},
        23 => %Job.BonusStats{level: 23, agi: 1, dex: 1},
        24 => %Job.BonusStats{level: 24, str: 1, spl: 1},
        25 => %Job.BonusStats{level: 25, vit: 1, crt: 1},
        26 => %Job.BonusStats{level: 26, int: 1, pow: 1},
        27 => %Job.BonusStats{level: 27, dex: 1},
        28 => %Job.BonusStats{level: 28, luk: 1},
        29 => %Job.BonusStats{level: 29, pow: 1, con: 1},
        30 => %Job.BonusStats{level: 30, str: 1},
        31 => %Job.BonusStats{level: 31, int: 1, luk: 1},
        32 => %Job.BonusStats{level: 32, vit: 1, wis: 1},
        33 => %Job.BonusStats{level: 33, agi: 1},
        34 => %Job.BonusStats{level: 34, crt: 1},
        35 => %Job.BonusStats{level: 35, dex: 1, con: 1},
        36 => %Job.BonusStats{level: 36, str: 1, pow: 1},
        37 => %Job.BonusStats{level: 37, int: 1, sta: 1},
        38 => %Job.BonusStats{level: 38, agi: 1},
        39 => %Job.BonusStats{level: 39, spl: 1},
        40 => %Job.BonusStats{level: 40, luk: 1, sta: 1},
        41 => %Job.BonusStats{level: 40, luk: 1, sta: 1},
        42 => %Job.BonusStats{level: 42, vit: 1, crt: 1},
        43 => %Job.BonusStats{level: 43, int: 1, pow: 1},
        44 => %Job.BonusStats{level: 44, dex: 1, wis: 1},
        45 => %Job.BonusStats{level: 45, sta: 1},
        46 => %Job.BonusStats{level: 46, pow: 1, con: 1},
        47 => %Job.BonusStats{level: 47, int: 1, wis: 1},
        48 => %Job.BonusStats{level: 47, int: 1, wis: 1},
        49 => %Job.BonusStats{level: 49, agi: 1, crt: 1},
        50 => %Job.BonusStats{level: 50, vit: 1, pow: 1},
        51 => %Job.BonusStats{level: 51, crt: 1},
        52 => %Job.BonusStats{level: 52, pow: 1},
        53 => %Job.BonusStats{level: 52, pow: 1},
        54 => %Job.BonusStats{level: 54, pow: 1, crt: 1},
        55 => %Job.BonusStats{level: 55, sta: 1},
        56 => %Job.BonusStats{level: 56, sta: 1},
        57 => %Job.BonusStats{level: 56, sta: 1},
        58 => %Job.BonusStats{level: 58, con: 1},
        59 => %Job.BonusStats{level: 58, con: 1},
        60 => %Job.BonusStats{level: 58, con: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 52,
        two_handed_sword: 55,
        one_handed_spear: 60,
        two_handed_spear: 58,
        one_handed_axe: 48,
        two_handed_axe: 52,
        mace: 45,
        two_handed_mace: 52,
        shield: 5
      },
      hp_factor: 150,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 300,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 45_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
