defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.ElementalMaster do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4261,
      name: :elemental_master,
      base_hp: Tables.BasepointsElementalMaster.base_hp(),
      base_sp: Tables.BasepointsElementalMaster.base_sp(),
      base_ap: Tables.BasepointsElementalMaster.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1, spl: 1},
        2 => %Job.BonusStats{level: 2, int: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, vit: 1, dex: 1},
        4 => %Job.BonusStats{level: 4, str: 1, vit: 1},
        5 => %Job.BonusStats{level: 5, int: 1, spl: 1},
        6 => %Job.BonusStats{level: 6, int: 1, pow: 1},
        7 => %Job.BonusStats{level: 7, agi: 1, spl: 1},
        8 => %Job.BonusStats{level: 8, int: 1},
        9 => %Job.BonusStats{level: 9, str: 1, con: 1},
        10 => %Job.BonusStats{level: 10, dex: 1, crt: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 13, dex: 1},
        14 => %Job.BonusStats{level: 14, vit: 1, int: 1},
        15 => %Job.BonusStats{level: 15, int: 1, pow: 1},
        16 => %Job.BonusStats{level: 16, vit: 1},
        17 => %Job.BonusStats{level: 17, luk: 1},
        18 => %Job.BonusStats{level: 18, int: 1, pow: 1},
        19 => %Job.BonusStats{level: 19, dex: 1, luk: 1},
        20 => %Job.BonusStats{level: 20, agi: 1, luk: 1},
        21 => %Job.BonusStats{level: 21, agi: 1, int: 1},
        22 => %Job.BonusStats{level: 22, dex: 1, wis: 1},
        23 => %Job.BonusStats{level: 23, vit: 1},
        24 => %Job.BonusStats{level: 24, str: 1, dex: 1},
        25 => %Job.BonusStats{level: 25, luk: 1, sta: 1},
        26 => %Job.BonusStats{level: 26, con: 1},
        27 => %Job.BonusStats{level: 27, vit: 1, sta: 1},
        28 => %Job.BonusStats{level: 28, int: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 30, dex: 1, luk: 1},
        31 => %Job.BonusStats{level: 31, agi: 1, int: 1},
        32 => %Job.BonusStats{level: 32, spl: 1},
        33 => %Job.BonusStats{level: 33, int: 1},
        34 => %Job.BonusStats{level: 34, dex: 1},
        35 => %Job.BonusStats{level: 35, str: 1},
        36 => %Job.BonusStats{level: 36, spl: 1},
        37 => %Job.BonusStats{level: 37, con: 1},
        38 => %Job.BonusStats{level: 38, crt: 1},
        39 => %Job.BonusStats{level: 39, con: 1, crt: 1},
        40 => %Job.BonusStats{level: 40, con: 1},
        41 => %Job.BonusStats{level: 41, wis: 1, spl: 1},
        42 => %Job.BonusStats{level: 42, spl: 1},
        43 => %Job.BonusStats{level: 43, wis: 1},
        44 => %Job.BonusStats{level: 44, sta: 1},
        45 => %Job.BonusStats{level: 45, sta: 1, wis: 1},
        46 => %Job.BonusStats{level: 46, wis: 1},
        47 => %Job.BonusStats{level: 47, sta: 1, spl: 1},
        48 => %Job.BonusStats{level: 48, spl: 1},
        49 => %Job.BonusStats{level: 49, sta: 1},
        50 => %Job.BonusStats{level: 50, wis: 1, spl: 1},
        51 => %Job.BonusStats{level: 51, spl: 1},
        52 => %Job.BonusStats{level: 52, sta: 1},
        53 => %Job.BonusStats{level: 53, sta: 1},
        54 => %Job.BonusStats{level: 54, wis: 1},
        55 => %Job.BonusStats{level: 55, spl: 1},
        56 => %Job.BonusStats{level: 56, wis: 1},
        57 => %Job.BonusStats{level: 56, wis: 1},
        58 => %Job.BonusStats{level: 56, wis: 1},
        59 => %Job.BonusStats{level: 59, con: 1},
        60 => %Job.BonusStats{level: 59, con: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 50,
        staff: 45,
        book: 45,
        two_handed_staff: 55,
        shield: 5
      },
      hp_factor: 75,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 40_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
