defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.GuillotineCross do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4059,
      name: :guillotine_cross,
      base_hp: Tables.BasepointsBabyGuillotineCross.base_hp(),
      base_sp: Tables.BasepointsBabyGuillotineCross.base_sp(),
      base_ap: Tables.BasepointsBabyGuillotineCross.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 2, dex: 1},
        4 => %Job.BonusStats{level: 4, str: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 5, str: 1},
        7 => %Job.BonusStats{level: 5, str: 1},
        8 => %Job.BonusStats{level: 5, str: 1},
        9 => %Job.BonusStats{level: 9, str: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 11, dex: 1},
        13 => %Job.BonusStats{level: 11, dex: 1},
        14 => %Job.BonusStats{level: 14, vit: 1},
        15 => %Job.BonusStats{level: 15, vit: 1},
        16 => %Job.BonusStats{level: 16, str: 1},
        17 => %Job.BonusStats{level: 16, str: 1},
        18 => %Job.BonusStats{level: 16, str: 1},
        19 => %Job.BonusStats{level: 19, vit: 1},
        20 => %Job.BonusStats{level: 20, str: 1},
        21 => %Job.BonusStats{level: 20, str: 1},
        22 => %Job.BonusStats{level: 20, str: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 25, dex: 1},
        26 => %Job.BonusStats{level: 25, dex: 1},
        27 => %Job.BonusStats{level: 25, dex: 1},
        28 => %Job.BonusStats{level: 28, int: 1},
        29 => %Job.BonusStats{level: 29, int: 1},
        30 => %Job.BonusStats{level: 30, str: 1},
        31 => %Job.BonusStats{level: 31, vit: 1},
        32 => %Job.BonusStats{level: 31, vit: 1},
        33 => %Job.BonusStats{level: 31, vit: 1},
        34 => %Job.BonusStats{level: 31, vit: 1},
        35 => %Job.BonusStats{level: 35, agi: 1},
        36 => %Job.BonusStats{level: 36, dex: 1},
        37 => %Job.BonusStats{level: 37, dex: 1},
        38 => %Job.BonusStats{level: 37, dex: 1},
        39 => %Job.BonusStats{level: 37, dex: 1},
        40 => %Job.BonusStats{level: 37, dex: 1},
        41 => %Job.BonusStats{level: 41, int: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 43, agi: 1},
        44 => %Job.BonusStats{level: 44, agi: 1},
        45 => %Job.BonusStats{level: 44, agi: 1},
        46 => %Job.BonusStats{level: 44, agi: 1},
        47 => %Job.BonusStats{level: 44, agi: 1},
        48 => %Job.BonusStats{level: 48, int: 1},
        49 => %Job.BonusStats{level: 49, dex: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 51, luk: 1},
        52 => %Job.BonusStats{level: 52, str: 1},
        53 => %Job.BonusStats{level: 53, agi: 1},
        54 => %Job.BonusStats{level: 54, vit: 1},
        55 => %Job.BonusStats{level: 54, vit: 1},
        56 => %Job.BonusStats{level: 56, int: 1},
        57 => %Job.BonusStats{level: 56, int: 1},
        58 => %Job.BonusStats{level: 58, str: 1},
        59 => %Job.BonusStats{level: 59, luk: 1},
        60 => %Job.BonusStats{level: 60, agi: 1},
        61 => %Job.BonusStats{level: 60, agi: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, luk: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 65, agi: 1},
        67 => %Job.BonusStats{level: 67, dex: 1},
        68 => %Job.BonusStats{level: 67, dex: 1},
        69 => %Job.BonusStats{level: 69, luk: 1},
        70 => %Job.BonusStats{level: 70, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 42,
        one_handed_sword: 65,
        one_handed_axe: 80,
        katar: 42,
        rifle: 95,
        gatling: 120,
        shotgun: 90,
        grenade: 100,
        huuma: 110,
        shield: 9
      },
      hp_factor: 110,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 32_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
