defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Gunslinger do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 24,
      name: :gunslinger,
      base_hp: Tables.BasepointsBabyGunslinger.base_hp(),
      base_sp: Tables.BasepointsBabyGunslinger.base_sp(),
      base_ap: Tables.BasepointsBabyGunslinger.base_ap(),
      base_exp: Tables.ExpBabyGunslinger.base_exp(),
      job_exp: Tables.ExpBabyGunslinger.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, luk: 1},
        3 => %Job.BonusStats{level: 2, luk: 1},
        4 => %Job.BonusStats{level: 4, luk: 1},
        5 => %Job.BonusStats{level: 4, luk: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 6, dex: 1},
        8 => %Job.BonusStats{level: 6, dex: 1},
        9 => %Job.BonusStats{level: 6, dex: 1},
        10 => %Job.BonusStats{level: 6, dex: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, luk: 1},
        13 => %Job.BonusStats{level: 12, luk: 1},
        14 => %Job.BonusStats{level: 12, luk: 1},
        15 => %Job.BonusStats{level: 12, luk: 1},
        16 => %Job.BonusStats{level: 12, luk: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 17, dex: 1},
        19 => %Job.BonusStats{level: 17, dex: 1},
        20 => %Job.BonusStats{level: 17, dex: 1},
        21 => %Job.BonusStats{level: 21, luk: 1},
        22 => %Job.BonusStats{level: 21, luk: 1},
        23 => %Job.BonusStats{level: 21, luk: 1},
        24 => %Job.BonusStats{level: 21, luk: 1},
        25 => %Job.BonusStats{level: 25, dex: 1},
        26 => %Job.BonusStats{level: 25, dex: 1},
        27 => %Job.BonusStats{level: 25, dex: 1},
        28 => %Job.BonusStats{level: 25, dex: 1},
        29 => %Job.BonusStats{level: 25, dex: 1},
        30 => %Job.BonusStats{level: 25, dex: 1},
        31 => %Job.BonusStats{level: 31, luk: 1},
        32 => %Job.BonusStats{level: 32, str: 1},
        33 => %Job.BonusStats{level: 32, str: 1},
        34 => %Job.BonusStats{level: 32, str: 1},
        35 => %Job.BonusStats{level: 35, dex: 1},
        36 => %Job.BonusStats{level: 35, dex: 1},
        37 => %Job.BonusStats{level: 35, dex: 1},
        38 => %Job.BonusStats{level: 35, dex: 1},
        39 => %Job.BonusStats{level: 35, dex: 1},
        40 => %Job.BonusStats{level: 35, dex: 1},
        41 => %Job.BonusStats{level: 41, str: 1},
        42 => %Job.BonusStats{level: 41, str: 1},
        43 => %Job.BonusStats{level: 41, str: 1},
        44 => %Job.BonusStats{level: 41, str: 1},
        45 => %Job.BonusStats{level: 45, dex: 1},
        46 => %Job.BonusStats{level: 45, dex: 1},
        47 => %Job.BonusStats{level: 45, dex: 1},
        48 => %Job.BonusStats{level: 45, dex: 1},
        49 => %Job.BonusStats{level: 45, dex: 1},
        50 => %Job.BonusStats{level: 50, str: 1},
        51 => %Job.BonusStats{level: 51, luk: 1},
        52 => %Job.BonusStats{level: 52, int: 1},
        53 => %Job.BonusStats{level: 52, int: 1},
        54 => %Job.BonusStats{level: 52, int: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 55, dex: 1},
        57 => %Job.BonusStats{level: 55, dex: 1},
        58 => %Job.BonusStats{level: 55, dex: 1},
        59 => %Job.BonusStats{level: 59, agi: 1},
        60 => %Job.BonusStats{level: 60, vit: 1},
        61 => %Job.BonusStats{level: 61, int: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 63, luk: 1},
        64 => %Job.BonusStats{level: 64, str: 1},
        65 => %Job.BonusStats{level: 64, str: 1},
        66 => %Job.BonusStats{level: 64, str: 1},
        67 => %Job.BonusStats{level: 64, str: 1},
        68 => %Job.BonusStats{level: 64, str: 1},
        69 => %Job.BonusStats{level: 64, str: 1},
        70 => %Job.BonusStats{level: 64, str: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 54,
        revolver: 49,
        rifle: 59,
        gatling: 54,
        shotgun: 94,
        grenade: 104,
        shield: 6
      },
      hp_factor: 90,
      hp_increase: 650,
      sp_factor: 0,
      sp_increase: 469,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
