defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.HighPriest do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4009,
      name: :high_priest,
      base_hp: Tables.BasepointsBabyPriest.base_hp(),
      base_sp: Tables.BasepointsBabyPriest.base_sp(),
      base_ap: Tables.BasepointsBabyPriest.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 1, int: 1},
        3 => %Job.BonusStats{level: 3, agi: 1},
        4 => %Job.BonusStats{level: 4, vit: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 5, str: 1},
        7 => %Job.BonusStats{level: 7, int: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 8, agi: 1},
        10 => %Job.BonusStats{level: 8, agi: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 12, str: 1},
        13 => %Job.BonusStats{level: 13, dex: 1},
        14 => %Job.BonusStats{level: 13, dex: 1},
        15 => %Job.BonusStats{level: 13, dex: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 16, dex: 1},
        18 => %Job.BonusStats{level: 16, dex: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, int: 1},
        21 => %Job.BonusStats{level: 21, str: 1},
        22 => %Job.BonusStats{level: 22, vit: 1},
        23 => %Job.BonusStats{level: 23, int: 1},
        24 => %Job.BonusStats{level: 24, int: 1},
        25 => %Job.BonusStats{level: 24, int: 1},
        26 => %Job.BonusStats{level: 26, dex: 1},
        27 => %Job.BonusStats{level: 26, dex: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 30, vit: 1},
        31 => %Job.BonusStats{level: 31, str: 1},
        32 => %Job.BonusStats{level: 31, str: 1},
        33 => %Job.BonusStats{level: 31, str: 1},
        34 => %Job.BonusStats{level: 34, int: 1},
        35 => %Job.BonusStats{level: 34, int: 1},
        36 => %Job.BonusStats{level: 34, int: 1},
        37 => %Job.BonusStats{level: 37, dex: 1},
        38 => %Job.BonusStats{level: 38, str: 1},
        39 => %Job.BonusStats{level: 38, str: 1},
        40 => %Job.BonusStats{level: 40, luk: 1},
        41 => %Job.BonusStats{level: 40, luk: 1},
        42 => %Job.BonusStats{level: 42, agi: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 43, dex: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 46, dex: 1},
        47 => %Job.BonusStats{level: 47, int: 1},
        48 => %Job.BonusStats{level: 47, int: 1},
        49 => %Job.BonusStats{level: 49, luk: 1},
        50 => %Job.BonusStats{level: 50, vit: 1},
        51 => %Job.BonusStats{level: 51, vit: 1},
        52 => %Job.BonusStats{level: 51, vit: 1},
        53 => %Job.BonusStats{level: 51, vit: 1},
        54 => %Job.BonusStats{level: 51, vit: 1},
        55 => %Job.BonusStats{level: 55, agi: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 57, int: 1},
        58 => %Job.BonusStats{level: 58, vit: 1},
        59 => %Job.BonusStats{level: 58, vit: 1},
        60 => %Job.BonusStats{level: 60, str: 1},
        61 => %Job.BonusStats{level: 61, int: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 62, dex: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, int: 1},
        67 => %Job.BonusStats{level: 67, vit: 1},
        68 => %Job.BonusStats{level: 68, agi: 1},
        69 => %Job.BonusStats{level: 68, agi: 1},
        70 => %Job.BonusStats{level: 70, int: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        mace: 43,
        two_handed_mace: 48,
        staff: 60,
        knuckle: 60,
        book: 44,
        two_handed_staff: 60,
        shield: 5
      },
      hp_factor: 75,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 800,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 26_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
