defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.HighWizard do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4010,
      name: :high_wizard,
      base_hp: Tables.BasepointsBabyWizard.base_hp(),
      base_sp: Tables.BasepointsBabyWizard.base_sp(),
      base_ap: Tables.BasepointsBabyWizard.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 3, vit: 1},
        4 => %Job.BonusStats{level: 3, vit: 1},
        5 => %Job.BonusStats{level: 5, int: 1},
        6 => %Job.BonusStats{level: 5, int: 1},
        7 => %Job.BonusStats{level: 5, int: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, dex: 1},
        10 => %Job.BonusStats{level: 10, int: 1},
        11 => %Job.BonusStats{level: 10, int: 1},
        12 => %Job.BonusStats{level: 12, luk: 1},
        13 => %Job.BonusStats{level: 12, luk: 1},
        14 => %Job.BonusStats{level: 14, int: 1},
        15 => %Job.BonusStats{level: 14, int: 1},
        16 => %Job.BonusStats{level: 14, int: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, agi: 1},
        19 => %Job.BonusStats{level: 19, int: 1},
        20 => %Job.BonusStats{level: 20, str: 1},
        21 => %Job.BonusStats{level: 20, str: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 24, int: 1},
        25 => %Job.BonusStats{level: 24, int: 1},
        26 => %Job.BonusStats{level: 26, agi: 1},
        27 => %Job.BonusStats{level: 26, agi: 1},
        28 => %Job.BonusStats{level: 28, int: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 29, vit: 1},
        31 => %Job.BonusStats{level: 31, dex: 1},
        32 => %Job.BonusStats{level: 32, int: 1},
        33 => %Job.BonusStats{level: 32, int: 1},
        34 => %Job.BonusStats{level: 34, agi: 1},
        35 => %Job.BonusStats{level: 34, agi: 1},
        36 => %Job.BonusStats{level: 34, agi: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 39, int: 1},
        40 => %Job.BonusStats{level: 40, str: 1},
        41 => %Job.BonusStats{level: 41, luk: 1},
        42 => %Job.BonusStats{level: 41, luk: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 43, dex: 1},
        45 => %Job.BonusStats{level: 43, dex: 1},
        46 => %Job.BonusStats{level: 46, int: 1},
        47 => %Job.BonusStats{level: 47, vit: 1},
        48 => %Job.BonusStats{level: 47, vit: 1},
        49 => %Job.BonusStats{level: 49, int: 1},
        50 => %Job.BonusStats{level: 50, agi: 1},
        51 => %Job.BonusStats{level: 50, agi: 1},
        52 => %Job.BonusStats{level: 50, agi: 1},
        53 => %Job.BonusStats{level: 53, vit: 1},
        54 => %Job.BonusStats{level: 53, vit: 1},
        55 => %Job.BonusStats{level: 55, int: 1},
        56 => %Job.BonusStats{level: 56, agi: 1},
        57 => %Job.BonusStats{level: 57, luk: 1},
        58 => %Job.BonusStats{level: 57, luk: 1},
        59 => %Job.BonusStats{level: 59, int: 1},
        60 => %Job.BonusStats{level: 60, str: 1},
        61 => %Job.BonusStats{level: 61, dex: 1},
        62 => %Job.BonusStats{level: 62, int: 1},
        63 => %Job.BonusStats{level: 62, int: 1},
        64 => %Job.BonusStats{level: 62, int: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, vit: 1},
        67 => %Job.BonusStats{level: 67, dex: 1},
        68 => %Job.BonusStats{level: 67, dex: 1},
        69 => %Job.BonusStats{level: 69, agi: 1},
        70 => %Job.BonusStats{level: 70, int: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 50, dagger: 54, staff: 53, two_handed_staff: 53, shield: 8},
      hp_factor: 55,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 24_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
