defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.HyperNovice do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4307,
      name: :hyper_novice,
      base_hp: Tables.BasepointsHyperNovice.base_hp(),
      base_sp: Tables.BasepointsHyperNovice.base_sp(),
      base_ap: Tables.BasepointsHyperNovice.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, int: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, vit: 1},
        4 => %Job.BonusStats{level: 4, luk: 1},
        5 => %Job.BonusStats{level: 5, str: 1, agi: 1, pow: 1},
        6 => %Job.BonusStats{level: 6, int: 1, dex: 1, spl: 1},
        7 => %Job.BonusStats{level: 7, vit: 1},
        8 => %Job.BonusStats{level: 8, luk: 1, con: 1},
        9 => %Job.BonusStats{level: 9, dex: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, sta: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 13, int: 1, luk: 1, wis: 1},
        14 => %Job.BonusStats{level: 14, int: 1},
        15 => %Job.BonusStats{level: 15, str: 1},
        16 => %Job.BonusStats{level: 16, crt: 1},
        17 => %Job.BonusStats{level: 17, str: 1, vit: 1, con: 1},
        18 => %Job.BonusStats{level: 18, str: 1},
        19 => %Job.BonusStats{level: 19, int: 1, spl: 1},
        20 => %Job.BonusStats{level: 20, str: 1, pow: 1},
        21 => %Job.BonusStats{level: 21, crt: 1},
        22 => %Job.BonusStats{level: 22, int: 1, spl: 1},
        23 => %Job.BonusStats{level: 23, int: 1},
        24 => %Job.BonusStats{level: 24, pow: 1, sta: 1},
        25 => %Job.BonusStats{level: 25, str: 1},
        26 => %Job.BonusStats{level: 26, agi: 1},
        27 => %Job.BonusStats{level: 27, con: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 30, pow: 1, spl: 1},
        31 => %Job.BonusStats{level: 31, vit: 1},
        32 => %Job.BonusStats{level: 32, wis: 1},
        33 => %Job.BonusStats{level: 33, pow: 1, spl: 1},
        34 => %Job.BonusStats{level: 34, sta: 1},
        35 => %Job.BonusStats{level: 35, str: 1, int: 1},
        36 => %Job.BonusStats{level: 36, con: 1},
        37 => %Job.BonusStats{level: 37, luk: 1},
        38 => %Job.BonusStats{level: 38, crt: 1},
        39 => %Job.BonusStats{level: 39, wis: 1, spl: 1},
        40 => %Job.BonusStats{level: 40, pow: 1, con: 1},
        41 => %Job.BonusStats{level: 41, str: 1},
        42 => %Job.BonusStats{level: 42, int: 1},
        43 => %Job.BonusStats{level: 43, pow: 1, sta: 1},
        44 => %Job.BonusStats{level: 44, luk: 1},
        45 => %Job.BonusStats{level: 45, wis: 1, spl: 1},
        46 => %Job.BonusStats{level: 46, luk: 1},
        47 => %Job.BonusStats{level: 47, con: 1},
        48 => %Job.BonusStats{level: 48, str: 1, int: 1},
        49 => %Job.BonusStats{level: 49, pow: 1, spl: 1},
        50 => %Job.BonusStats{level: 50, agi: 1, dex: 1},
        51 => %Job.BonusStats{level: 51, con: 1},
        52 => %Job.BonusStats{level: 52, pow: 1, con: 1},
        53 => %Job.BonusStats{level: 53, sta: 1},
        54 => %Job.BonusStats{level: 53, sta: 1},
        55 => %Job.BonusStats{level: 55, spl: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 57, pow: 1},
        58 => %Job.BonusStats{level: 57, pow: 1},
        59 => %Job.BonusStats{level: 59, spl: 1},
        60 => %Job.BonusStats{level: 59, spl: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 55,
        one_handed_sword: 57,
        one_handed_axe: 50,
        mace: 50,
        two_handed_mace: 55,
        staff: 65,
        two_handed_staff: 65,
        shield: 10
      },
      hp_factor: 55,
      hp_increase: 900,
      sp_factor: 0,
      sp_increase: 600,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 40_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
