defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.ImperialGuard do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4258,
      name: :imperial_guard,
      base_hp: Tables.BasepointsImperialGuard.base_hp(),
      base_sp: Tables.BasepointsImperialGuard.base_sp(),
      base_ap: Tables.BasepointsImperialGuard.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, pow: 1},
        2 => %Job.BonusStats{level: 2, str: 1, int: 1},
        3 => %Job.BonusStats{level: 3, vit: 1, dex: 1},
        4 => %Job.BonusStats{level: 4, dex: 1, spl: 1},
        5 => %Job.BonusStats{level: 5, str: 1, vit: 1},
        6 => %Job.BonusStats{level: 6, vit: 1, dex: 1},
        7 => %Job.BonusStats{level: 7, str: 1, spl: 1},
        8 => %Job.BonusStats{level: 8, dex: 1},
        9 => %Job.BonusStats{level: 9, str: 1, spl: 1},
        10 => %Job.BonusStats{level: 10, int: 1, con: 1},
        11 => %Job.BonusStats{level: 11, luk: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 13, luk: 1, pow: 1},
        14 => %Job.BonusStats{level: 14, agi: 1, int: 1},
        15 => %Job.BonusStats{level: 15, int: 1},
        16 => %Job.BonusStats{level: 16, vit: 1, pow: 1},
        17 => %Job.BonusStats{level: 17, str: 1, int: 1},
        18 => %Job.BonusStats{level: 18, vit: 1},
        19 => %Job.BonusStats{level: 19, str: 1, int: 1},
        20 => %Job.BonusStats{level: 20, int: 1, dex: 1},
        21 => %Job.BonusStats{level: 21, int: 1},
        22 => %Job.BonusStats{level: 22, str: 1, vit: 1},
        23 => %Job.BonusStats{level: 23, sta: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 25, int: 1},
        26 => %Job.BonusStats{level: 26, str: 1, int: 1},
        27 => %Job.BonusStats{level: 27, pow: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 30, pow: 1},
        31 => %Job.BonusStats{level: 31, str: 1, luk: 1},
        32 => %Job.BonusStats{level: 32, dex: 1, spl: 1},
        33 => %Job.BonusStats{level: 33, dex: 1, spl: 1},
        34 => %Job.BonusStats{level: 34, sta: 1},
        35 => %Job.BonusStats{level: 35, vit: 1, sta: 1},
        36 => %Job.BonusStats{level: 36, spl: 1},
        37 => %Job.BonusStats{level: 37, dex: 1, wis: 1},
        38 => %Job.BonusStats{level: 38, agi: 1, wis: 1},
        39 => %Job.BonusStats{level: 39, sta: 1},
        40 => %Job.BonusStats{level: 40, wis: 1},
        41 => %Job.BonusStats{level: 41, sta: 1, crt: 1},
        42 => %Job.BonusStats{level: 42, wis: 1, con: 1},
        43 => %Job.BonusStats{level: 43, crt: 1},
        44 => %Job.BonusStats{level: 44, sta: 1},
        45 => %Job.BonusStats{level: 45, spl: 1},
        46 => %Job.BonusStats{level: 46, wis: 1},
        47 => %Job.BonusStats{level: 47, crt: 1},
        48 => %Job.BonusStats{level: 48, sta: 1, con: 1},
        49 => %Job.BonusStats{level: 49, sta: 1},
        50 => %Job.BonusStats{level: 50, pow: 1, sta: 1},
        51 => %Job.BonusStats{level: 51, pow: 1},
        52 => %Job.BonusStats{level: 52, sta: 1},
        53 => %Job.BonusStats{level: 53, sta: 1},
        54 => %Job.BonusStats{level: 53, sta: 1},
        55 => %Job.BonusStats{level: 55, wis: 1, con: 1},
        56 => %Job.BonusStats{level: 55, wis: 1, con: 1},
        57 => %Job.BonusStats{level: 57, pow: 1},
        58 => %Job.BonusStats{level: 57, pow: 1},
        59 => %Job.BonusStats{level: 59, spl: 1},
        60 => %Job.BonusStats{level: 59, spl: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 47,
        one_handed_sword: 45,
        two_handed_sword: 53,
        one_handed_spear: 50,
        two_handed_spear: 50,
        one_handed_axe: 48,
        two_handed_axe: 52,
        mace: 44,
        two_handed_mace: 50,
        shield: 5
      },
      hp_factor: 110,
      hp_increase: 700,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 45_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
