defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Inquisitor do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4262,
      name: :inquisitor,
      base_hp: Tables.BasepointsInquisitor.base_hp(),
      base_sp: Tables.BasepointsInquisitor.base_sp(),
      base_ap: Tables.BasepointsInquisitor.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, agi: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, str: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, int: 1, pow: 1},
        4 => %Job.BonusStats{level: 4, str: 2},
        5 => %Job.BonusStats{level: 5, str: 1, pow: 1},
        6 => %Job.BonusStats{level: 6, str: 1},
        7 => %Job.BonusStats{level: 7, dex: 1, pow: 1},
        8 => %Job.BonusStats{level: 8, agi: 1, int: 1},
        9 => %Job.BonusStats{level: 9, str: 1, dex: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, dex: 1, sta: 1},
        12 => %Job.BonusStats{level: 12, agi: 1, vit: 1},
        13 => %Job.BonusStats{level: 13, wis: 1},
        14 => %Job.BonusStats{level: 14, agi: 1, vit: 1},
        15 => %Job.BonusStats{level: 15, int: 1, luk: 1},
        16 => %Job.BonusStats{level: 16, str: 1, sta: 1},
        17 => %Job.BonusStats{level: 17, vit: 1, int: 1},
        18 => %Job.BonusStats{level: 18, str: 1, int: 1},
        19 => %Job.BonusStats{level: 19, vit: 1, dex: 1},
        20 => %Job.BonusStats{level: 20, vit: 1, dex: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, str: 1, agi: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, dex: 1},
        25 => %Job.BonusStats{level: 25, agi: 1},
        26 => %Job.BonusStats{level: 26, str: 1},
        27 => %Job.BonusStats{level: 27, crt: 1},
        28 => %Job.BonusStats{level: 28, con: 1},
        29 => %Job.BonusStats{level: 29, crt: 1},
        30 => %Job.BonusStats{level: 30, int: 1, pow: 1},
        31 => %Job.BonusStats{level: 31, pow: 1},
        32 => %Job.BonusStats{level: 32, wis: 1, crt: 1},
        33 => %Job.BonusStats{level: 33, spl: 1},
        34 => %Job.BonusStats{level: 34, spl: 1},
        35 => %Job.BonusStats{level: 35, pow: 1},
        36 => %Job.BonusStats{level: 36, sta: 1},
        37 => %Job.BonusStats{level: 37, con: 1},
        38 => %Job.BonusStats{level: 38, con: 1},
        39 => %Job.BonusStats{level: 39, crt: 1},
        40 => %Job.BonusStats{level: 40, con: 1},
        41 => %Job.BonusStats{level: 41, spl: 1},
        42 => %Job.BonusStats{level: 42, int: 1, crt: 1},
        43 => %Job.BonusStats{level: 43, agi: 1, pow: 1},
        44 => %Job.BonusStats{level: 44, con: 1},
        45 => %Job.BonusStats{level: 45, int: 1, sta: 1},
        46 => %Job.BonusStats{level: 46, sta: 1},
        47 => %Job.BonusStats{level: 47, vit: 1, wis: 1},
        48 => %Job.BonusStats{level: 48, crt: 1},
        49 => %Job.BonusStats{level: 49, pow: 1, sta: 1},
        50 => %Job.BonusStats{level: 50, pow: 1, wis: 1},
        51 => %Job.BonusStats{level: 51, pow: 1},
        52 => %Job.BonusStats{level: 52, sta: 1},
        53 => %Job.BonusStats{level: 53, sta: 1},
        54 => %Job.BonusStats{level: 53, sta: 1},
        55 => %Job.BonusStats{level: 55, pow: 1, wis: 1},
        56 => %Job.BonusStats{level: 55, pow: 1, wis: 1},
        57 => %Job.BonusStats{level: 57, wis: 1},
        58 => %Job.BonusStats{level: 57, wis: 1},
        59 => %Job.BonusStats{level: 59, con: 1},
        60 => %Job.BonusStats{level: 59, con: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 38,
        mace: 43,
        two_handed_mace: 45,
        staff: 48,
        knuckle: 39,
        two_handed_staff: 50,
        shield: 5
      },
      hp_factor: 90,
      hp_increase: 650,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
