defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.LordKnight do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4008,
      name: :lord_knight,
      base_hp: Tables.BasepointsBabyKnight.base_hp(),
      base_sp: Tables.BasepointsBabyKnight.base_sp(),
      base_ap: Tables.BasepointsBabyKnight.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1},
        2 => %Job.BonusStats{level: 2, agi: 1},
        3 => %Job.BonusStats{level: 3, luk: 1},
        4 => %Job.BonusStats{level: 4, dex: 1},
        5 => %Job.BonusStats{level: 5, vit: 1},
        6 => %Job.BonusStats{level: 6, str: 1},
        7 => %Job.BonusStats{level: 7, str: 1},
        8 => %Job.BonusStats{level: 8, str: 1},
        9 => %Job.BonusStats{level: 8, str: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 13, int: 1},
        14 => %Job.BonusStats{level: 14, agi: 1},
        15 => %Job.BonusStats{level: 14, agi: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 17, agi: 1},
        18 => %Job.BonusStats{level: 17, agi: 1},
        19 => %Job.BonusStats{level: 19, str: 1},
        20 => %Job.BonusStats{level: 19, str: 1},
        21 => %Job.BonusStats{level: 19, str: 1},
        22 => %Job.BonusStats{level: 22, vit: 1},
        23 => %Job.BonusStats{level: 22, vit: 1},
        24 => %Job.BonusStats{level: 22, vit: 1},
        25 => %Job.BonusStats{level: 25, str: 1},
        26 => %Job.BonusStats{level: 25, str: 1},
        27 => %Job.BonusStats{level: 27, luk: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 29, vit: 1},
        31 => %Job.BonusStats{level: 31, dex: 1},
        32 => %Job.BonusStats{level: 31, dex: 1},
        33 => %Job.BonusStats{level: 33, str: 1},
        34 => %Job.BonusStats{level: 33, str: 1},
        35 => %Job.BonusStats{level: 33, str: 1},
        36 => %Job.BonusStats{level: 36, dex: 1},
        37 => %Job.BonusStats{level: 37, agi: 1},
        38 => %Job.BonusStats{level: 38, luk: 1},
        39 => %Job.BonusStats{level: 38, luk: 1},
        40 => %Job.BonusStats{level: 40, vit: 1},
        41 => %Job.BonusStats{level: 41, str: 1},
        42 => %Job.BonusStats{level: 41, str: 1},
        43 => %Job.BonusStats{level: 43, vit: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 44, dex: 1},
        46 => %Job.BonusStats{level: 46, str: 1},
        47 => %Job.BonusStats{level: 47, str: 1},
        48 => %Job.BonusStats{level: 47, str: 1},
        49 => %Job.BonusStats{level: 49, dex: 1},
        50 => %Job.BonusStats{level: 49, dex: 1},
        51 => %Job.BonusStats{level: 49, dex: 1},
        52 => %Job.BonusStats{level: 52, str: 1},
        53 => %Job.BonusStats{level: 53, agi: 1},
        54 => %Job.BonusStats{level: 53, agi: 1},
        55 => %Job.BonusStats{level: 53, agi: 1},
        56 => %Job.BonusStats{level: 56, str: 1},
        57 => %Job.BonusStats{level: 57, str: 1},
        58 => %Job.BonusStats{level: 58, vit: 1},
        59 => %Job.BonusStats{level: 58, vit: 1},
        60 => %Job.BonusStats{level: 60, agi: 1},
        61 => %Job.BonusStats{level: 60, agi: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, str: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 65, agi: 1},
        67 => %Job.BonusStats{level: 67, int: 1},
        68 => %Job.BonusStats{level: 68, vit: 1},
        69 => %Job.BonusStats{level: 68, vit: 1},
        70 => %Job.BonusStats{level: 70, str: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 49,
        one_handed_sword: 45,
        two_handed_sword: 52,
        one_handed_spear: 55,
        two_handed_spear: 60,
        one_handed_axe: 50,
        two_handed_axe: 55,
        mace: 45,
        two_handed_mace: 50,
        shield: 5
      },
      hp_factor: 150,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 300,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
