defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.MechanicT2 do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4087,
      name: :mechanic_t2,
      base_hp: Tables.BasepointsBabyMechanic.base_hp(),
      base_sp: Tables.BasepointsBabyMechanic.base_sp(),
      base_ap: Tables.BasepointsBabyMechanic.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, luk: 1},
        2 => %Job.BonusStats{level: 2, str: 1},
        3 => %Job.BonusStats{level: 2, str: 1},
        4 => %Job.BonusStats{level: 2, str: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 5, str: 1},
        7 => %Job.BonusStats{level: 7, luk: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, dex: 1},
        10 => %Job.BonusStats{level: 10, int: 1},
        11 => %Job.BonusStats{level: 10, int: 1},
        12 => %Job.BonusStats{level: 10, int: 1},
        13 => %Job.BonusStats{level: 13, int: 1},
        14 => %Job.BonusStats{level: 14, luk: 1},
        15 => %Job.BonusStats{level: 14, luk: 1},
        16 => %Job.BonusStats{level: 14, luk: 1},
        17 => %Job.BonusStats{level: 17, agi: 1},
        18 => %Job.BonusStats{level: 17, agi: 1},
        19 => %Job.BonusStats{level: 19, vit: 1},
        20 => %Job.BonusStats{level: 20, vit: 1},
        21 => %Job.BonusStats{level: 21, int: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 22, dex: 1},
        24 => %Job.BonusStats{level: 22, dex: 1},
        25 => %Job.BonusStats{level: 25, vit: 1},
        26 => %Job.BonusStats{level: 26, luk: 1},
        27 => %Job.BonusStats{level: 26, luk: 1},
        28 => %Job.BonusStats{level: 26, luk: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 29, vit: 1},
        31 => %Job.BonusStats{level: 31, str: 1},
        32 => %Job.BonusStats{level: 32, str: 1},
        33 => %Job.BonusStats{level: 33, vit: 1},
        34 => %Job.BonusStats{level: 34, luk: 1},
        35 => %Job.BonusStats{level: 34, luk: 1},
        36 => %Job.BonusStats{level: 34, luk: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 38, int: 1},
        40 => %Job.BonusStats{level: 38, int: 1},
        41 => %Job.BonusStats{level: 38, int: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 43, vit: 1},
        44 => %Job.BonusStats{level: 44, str: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 45, str: 1},
        47 => %Job.BonusStats{level: 45, str: 1},
        48 => %Job.BonusStats{level: 48, dex: 1},
        49 => %Job.BonusStats{level: 49, agi: 1},
        50 => %Job.BonusStats{level: 49, agi: 1},
        51 => %Job.BonusStats{level: 51, luk: 1},
        52 => %Job.BonusStats{level: 52, str: 1},
        53 => %Job.BonusStats{level: 53, dex: 1},
        54 => %Job.BonusStats{level: 53, dex: 1},
        55 => %Job.BonusStats{level: 55, int: 1},
        56 => %Job.BonusStats{level: 56, vit: 1},
        57 => %Job.BonusStats{level: 57, agi: 1},
        58 => %Job.BonusStats{level: 57, agi: 1},
        59 => %Job.BonusStats{level: 59, dex: 1},
        60 => %Job.BonusStats{level: 60, str: 1},
        61 => %Job.BonusStats{level: 61, str: 1},
        62 => %Job.BonusStats{level: 61, str: 1},
        63 => %Job.BonusStats{level: 61, str: 1},
        64 => %Job.BonusStats{level: 64, vit: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, str: 1},
        67 => %Job.BonusStats{level: 66, str: 1},
        68 => %Job.BonusStats{level: 66, str: 1},
        69 => %Job.BonusStats{level: 69, vit: 1},
        70 => %Job.BonusStats{level: 70, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 60,
        one_handed_sword: 65,
        one_handed_axe: 45,
        two_handed_axe: 48,
        mace: 48,
        two_handed_mace: 50,
        shield: 6
      },
      hp_factor: 90,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 38_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
