defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.NightWatch do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4306,
      name: :night_watch,
      base_hp: Tables.BasepointsNightWatch.base_hp(),
      base_sp: Tables.BasepointsNightWatch.base_sp(),
      base_ap: Tables.BasepointsNightWatch.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1, sta: 1},
        2 => %Job.BonusStats{level: 2, str: 1, agi: 1},
        3 => %Job.BonusStats{level: 3, vit: 1, luk: 1},
        4 => %Job.BonusStats{level: 4, int: 1, luk: 1},
        5 => %Job.BonusStats{level: 5, vit: 1, int: 1},
        6 => %Job.BonusStats{level: 6, vit: 1, dex: 1},
        7 => %Job.BonusStats{level: 7, dex: 1, pow: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, luk: 1},
        10 => %Job.BonusStats{level: 10, luk: 1, wis: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, agi: 1, dex: 1},
        13 => %Job.BonusStats{level: 13, agi: 1, luk: 1},
        14 => %Job.BonusStats{level: 14, int: 1, dex: 1},
        15 => %Job.BonusStats{level: 15, luk: 1, sta: 1},
        16 => %Job.BonusStats{level: 16, vit: 1, int: 1},
        17 => %Job.BonusStats{level: 17, int: 1},
        18 => %Job.BonusStats{level: 18, dex: 1},
        19 => %Job.BonusStats{level: 19, int: 1, dex: 1},
        20 => %Job.BonusStats{level: 20, agi: 1, vit: 1},
        21 => %Job.BonusStats{level: 21, dex: 1, pow: 1},
        22 => %Job.BonusStats{level: 22, dex: 1, wis: 1},
        23 => %Job.BonusStats{level: 23, agi: 1, pow: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 25, agi: 1, luk: 1},
        26 => %Job.BonusStats{level: 26, int: 1, con: 1},
        27 => %Job.BonusStats{level: 27, dex: 1, crt: 1},
        28 => %Job.BonusStats{level: 28, con: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 30, str: 1, int: 1},
        31 => %Job.BonusStats{level: 31, dex: 1, con: 1},
        32 => %Job.BonusStats{level: 32, pow: 1},
        33 => %Job.BonusStats{level: 33, sta: 1, crt: 1},
        34 => %Job.BonusStats{level: 34, crt: 1},
        35 => %Job.BonusStats{level: 35, pow: 1},
        36 => %Job.BonusStats{level: 36, con: 1, crt: 1},
        37 => %Job.BonusStats{level: 36, con: 1, crt: 1},
        38 => %Job.BonusStats{level: 38, wis: 1, con: 1},
        39 => %Job.BonusStats{level: 38, wis: 1, con: 1},
        40 => %Job.BonusStats{level: 40, pow: 1},
        41 => %Job.BonusStats{level: 41, sta: 1, con: 1},
        42 => %Job.BonusStats{level: 42, sta: 1},
        43 => %Job.BonusStats{level: 43, crt: 1},
        44 => %Job.BonusStats{level: 44, pow: 1},
        45 => %Job.BonusStats{level: 45, con: 1},
        46 => %Job.BonusStats{level: 46, pow: 1, sta: 1},
        47 => %Job.BonusStats{level: 47, con: 1},
        48 => %Job.BonusStats{level: 48, wis: 1},
        49 => %Job.BonusStats{level: 49, con: 1},
        50 => %Job.BonusStats{level: 50, pow: 1},
        51 => %Job.BonusStats{level: 51, con: 1},
        52 => %Job.BonusStats{level: 51, con: 1},
        53 => %Job.BonusStats{level: 53, pow: 1, con: 1},
        54 => %Job.BonusStats{level: 54, wis: 1},
        55 => %Job.BonusStats{level: 55, pow: 1},
        56 => %Job.BonusStats{level: 56, wis: 1},
        57 => %Job.BonusStats{level: 56, wis: 1},
        58 => %Job.BonusStats{level: 56, wis: 1},
        59 => %Job.BonusStats{level: 59, crt: 1},
        60 => %Job.BonusStats{level: 59, crt: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 54,
        revolver: 49,
        rifle: 59,
        gatling: 54,
        shotgun: 94,
        grenade: 104,
        shield: 6
      },
      hp_factor: 75,
      hp_increase: 1800,
      sp_factor: 0,
      sp_increase: 800,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 48_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
