defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Ninja do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 25,
      name: :ninja,
      base_hp: Tables.BasepointsBabyNinja.base_hp(),
      base_sp: Tables.BasepointsBabyNinja.base_sp(),
      base_ap: Tables.BasepointsBabyNinja.base_ap(),
      base_exp: Tables.ExpBabyGunslinger.base_exp(),
      job_exp: Tables.ExpBabyGunslinger.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, agi: 1},
        3 => %Job.BonusStats{level: 2, agi: 1},
        4 => %Job.BonusStats{level: 2, agi: 1},
        5 => %Job.BonusStats{level: 2, agi: 1},
        6 => %Job.BonusStats{level: 2, agi: 1},
        7 => %Job.BonusStats{level: 2, agi: 1},
        8 => %Job.BonusStats{level: 2, agi: 1},
        9 => %Job.BonusStats{level: 2, agi: 1},
        10 => %Job.BonusStats{level: 10, dex: 1},
        11 => %Job.BonusStats{level: 11, agi: 1},
        12 => %Job.BonusStats{level: 11, agi: 1},
        13 => %Job.BonusStats{level: 11, agi: 1},
        14 => %Job.BonusStats{level: 11, agi: 1},
        15 => %Job.BonusStats{level: 11, agi: 1},
        16 => %Job.BonusStats{level: 11, agi: 1},
        17 => %Job.BonusStats{level: 11, agi: 1},
        18 => %Job.BonusStats{level: 11, agi: 1},
        19 => %Job.BonusStats{level: 11, agi: 1},
        20 => %Job.BonusStats{level: 20, int: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 22, dex: 1},
        24 => %Job.BonusStats{level: 22, dex: 1},
        25 => %Job.BonusStats{level: 22, dex: 1},
        26 => %Job.BonusStats{level: 22, dex: 1},
        27 => %Job.BonusStats{level: 22, dex: 1},
        28 => %Job.BonusStats{level: 22, dex: 1},
        29 => %Job.BonusStats{level: 29, int: 1},
        30 => %Job.BonusStats{level: 30, luk: 1},
        31 => %Job.BonusStats{level: 31, agi: 1},
        32 => %Job.BonusStats{level: 32, dex: 1},
        33 => %Job.BonusStats{level: 32, dex: 1},
        34 => %Job.BonusStats{level: 32, dex: 1},
        35 => %Job.BonusStats{level: 32, dex: 1},
        36 => %Job.BonusStats{level: 32, dex: 1},
        37 => %Job.BonusStats{level: 32, dex: 1},
        38 => %Job.BonusStats{level: 32, dex: 1},
        39 => %Job.BonusStats{level: 32, dex: 1},
        40 => %Job.BonusStats{level: 40, luk: 1},
        41 => %Job.BonusStats{level: 41, agi: 1},
        42 => %Job.BonusStats{level: 42, int: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 43, dex: 1},
        45 => %Job.BonusStats{level: 43, dex: 1},
        46 => %Job.BonusStats{level: 43, dex: 1},
        47 => %Job.BonusStats{level: 43, dex: 1},
        48 => %Job.BonusStats{level: 43, dex: 1},
        49 => %Job.BonusStats{level: 43, dex: 1},
        50 => %Job.BonusStats{level: 50, int: 1},
        51 => %Job.BonusStats{level: 51, agi: 1},
        52 => %Job.BonusStats{level: 52, luk: 1},
        53 => %Job.BonusStats{level: 53, dex: 1},
        54 => %Job.BonusStats{level: 53, dex: 1},
        55 => %Job.BonusStats{level: 53, dex: 1},
        56 => %Job.BonusStats{level: 53, dex: 1},
        57 => %Job.BonusStats{level: 53, dex: 1},
        58 => %Job.BonusStats{level: 53, dex: 1},
        59 => %Job.BonusStats{level: 59, str: 1},
        60 => %Job.BonusStats{level: 60, vit: 1},
        61 => %Job.BonusStats{level: 61, agi: 1},
        62 => %Job.BonusStats{level: 62, int: 1},
        63 => %Job.BonusStats{level: 63, dex: 1},
        64 => %Job.BonusStats{level: 64, luk: 1},
        65 => %Job.BonusStats{level: 64, luk: 1},
        66 => %Job.BonusStats{level: 64, luk: 1},
        67 => %Job.BonusStats{level: 64, luk: 1},
        68 => %Job.BonusStats{level: 64, luk: 1},
        69 => %Job.BonusStats{level: 64, luk: 1},
        70 => %Job.BonusStats{level: 64, luk: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 43, huuma: 55, shield: 6},
      hp_factor: 75,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 540,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 26_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
