defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Paladin do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4015,
      name: :paladin,
      base_hp: Tables.BasepointsBabyCrusader.base_hp(),
      base_sp: Tables.BasepointsBabyCrusader.base_sp(),
      base_ap: Tables.BasepointsBabyCrusader.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, vit: 1},
        2 => %Job.BonusStats{level: 2, str: 1},
        3 => %Job.BonusStats{level: 3, agi: 1},
        4 => %Job.BonusStats{level: 3, agi: 1},
        5 => %Job.BonusStats{level: 3, agi: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 7, int: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 9, vit: 1},
        10 => %Job.BonusStats{level: 10, str: 1},
        11 => %Job.BonusStats{level: 10, str: 1},
        12 => %Job.BonusStats{level: 12, dex: 1},
        13 => %Job.BonusStats{level: 12, dex: 1},
        14 => %Job.BonusStats{level: 14, int: 1},
        15 => %Job.BonusStats{level: 15, vit: 1},
        16 => %Job.BonusStats{level: 16, agi: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, str: 1},
        19 => %Job.BonusStats{level: 18, str: 1},
        20 => %Job.BonusStats{level: 18, str: 1},
        21 => %Job.BonusStats{level: 21, vit: 1},
        22 => %Job.BonusStats{level: 21, vit: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 24, agi: 1},
        26 => %Job.BonusStats{level: 26, str: 1},
        27 => %Job.BonusStats{level: 26, str: 1},
        28 => %Job.BonusStats{level: 26, str: 1},
        29 => %Job.BonusStats{level: 29, int: 1},
        30 => %Job.BonusStats{level: 30, vit: 1},
        31 => %Job.BonusStats{level: 30, vit: 1},
        32 => %Job.BonusStats{level: 30, vit: 1},
        33 => %Job.BonusStats{level: 33, str: 1},
        34 => %Job.BonusStats{level: 33, str: 1},
        35 => %Job.BonusStats{level: 33, str: 1},
        36 => %Job.BonusStats{level: 36, dex: 1},
        37 => %Job.BonusStats{level: 37, agi: 1},
        38 => %Job.BonusStats{level: 37, agi: 1},
        39 => %Job.BonusStats{level: 39, luk: 1},
        40 => %Job.BonusStats{level: 40, str: 1},
        41 => %Job.BonusStats{level: 40, str: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 43, int: 1},
        44 => %Job.BonusStats{level: 43, int: 1},
        45 => %Job.BonusStats{level: 45, dex: 1},
        46 => %Job.BonusStats{level: 45, dex: 1},
        47 => %Job.BonusStats{level: 45, dex: 1},
        48 => %Job.BonusStats{level: 48, str: 1},
        49 => %Job.BonusStats{level: 49, vit: 1},
        50 => %Job.BonusStats{level: 49, vit: 1},
        51 => %Job.BonusStats{level: 49, vit: 1},
        52 => %Job.BonusStats{level: 52, agi: 1},
        53 => %Job.BonusStats{level: 53, vit: 1},
        54 => %Job.BonusStats{level: 54, int: 1},
        55 => %Job.BonusStats{level: 55, str: 1},
        56 => %Job.BonusStats{level: 55, str: 1},
        57 => %Job.BonusStats{level: 57, dex: 1},
        58 => %Job.BonusStats{level: 57, dex: 1},
        59 => %Job.BonusStats{level: 59, luk: 1},
        60 => %Job.BonusStats{level: 60, agi: 1},
        61 => %Job.BonusStats{level: 61, int: 1},
        62 => %Job.BonusStats{level: 61, int: 1},
        63 => %Job.BonusStats{level: 63, vit: 1},
        64 => %Job.BonusStats{level: 64, str: 1},
        65 => %Job.BonusStats{level: 65, int: 1},
        66 => %Job.BonusStats{level: 65, int: 1},
        67 => %Job.BonusStats{level: 67, luk: 1},
        68 => %Job.BonusStats{level: 68, dex: 1},
        69 => %Job.BonusStats{level: 69, vit: 1},
        70 => %Job.BonusStats{level: 70, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 48,
        one_handed_sword: 43,
        two_handed_sword: 55,
        one_handed_spear: 53,
        two_handed_spear: 52,
        one_handed_axe: 50,
        two_handed_axe: 55,
        mace: 45,
        two_handed_mace: 50,
        shield: 5
      },
      hp_factor: 110,
      hp_increase: 700,
      sp_factor: 0,
      sp_increase: 470,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
