defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Professor do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4017,
      name: :professor,
      base_hp: Tables.BasepointsBabySage.base_hp(),
      base_sp: Tables.BasepointsBabySage.base_sp(),
      base_ap: Tables.BasepointsBabySage.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, int: 1},
        3 => %Job.BonusStats{level: 3, agi: 1},
        4 => %Job.BonusStats{level: 3, agi: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 5, str: 1},
        7 => %Job.BonusStats{level: 7, vit: 1},
        8 => %Job.BonusStats{level: 8, dex: 1},
        9 => %Job.BonusStats{level: 8, dex: 1},
        10 => %Job.BonusStats{level: 8, dex: 1},
        11 => %Job.BonusStats{level: 11, int: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 12, agi: 1},
        14 => %Job.BonusStats{level: 14, int: 1},
        15 => %Job.BonusStats{level: 14, int: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 16, dex: 1},
        18 => %Job.BonusStats{level: 18, str: 1},
        19 => %Job.BonusStats{level: 18, str: 1},
        20 => %Job.BonusStats{level: 20, dex: 1},
        21 => %Job.BonusStats{level: 21, luk: 1},
        22 => %Job.BonusStats{level: 22, int: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 24, vit: 1},
        26 => %Job.BonusStats{level: 26, dex: 1},
        27 => %Job.BonusStats{level: 27, str: 1},
        28 => %Job.BonusStats{level: 27, str: 1},
        29 => %Job.BonusStats{level: 29, dex: 1},
        30 => %Job.BonusStats{level: 30, int: 1},
        31 => %Job.BonusStats{level: 30, int: 1},
        32 => %Job.BonusStats{level: 32, agi: 1},
        33 => %Job.BonusStats{level: 32, agi: 1},
        34 => %Job.BonusStats{level: 34, dex: 1},
        35 => %Job.BonusStats{level: 34, dex: 1},
        36 => %Job.BonusStats{level: 36, str: 1},
        37 => %Job.BonusStats{level: 37, dex: 1},
        38 => %Job.BonusStats{level: 38, int: 1},
        39 => %Job.BonusStats{level: 39, vit: 1},
        40 => %Job.BonusStats{level: 39, vit: 1},
        41 => %Job.BonusStats{level: 41, int: 1},
        42 => %Job.BonusStats{level: 41, int: 1},
        43 => %Job.BonusStats{level: 43, agi: 1},
        44 => %Job.BonusStats{level: 43, agi: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 46, dex: 1},
        47 => %Job.BonusStats{level: 46, dex: 1},
        48 => %Job.BonusStats{level: 46, dex: 1},
        49 => %Job.BonusStats{level: 49, int: 1},
        50 => %Job.BonusStats{level: 50, agi: 1},
        51 => %Job.BonusStats{level: 50, agi: 1},
        52 => %Job.BonusStats{level: 52, dex: 1},
        53 => %Job.BonusStats{level: 52, dex: 1},
        54 => %Job.BonusStats{level: 54, agi: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 56, str: 1},
        57 => %Job.BonusStats{level: 57, int: 1},
        58 => %Job.BonusStats{level: 57, int: 1},
        59 => %Job.BonusStats{level: 57, int: 1},
        60 => %Job.BonusStats{level: 60, agi: 1},
        61 => %Job.BonusStats{level: 60, agi: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 63, vit: 1},
        64 => %Job.BonusStats{level: 64, int: 1},
        65 => %Job.BonusStats{level: 64, int: 1},
        66 => %Job.BonusStats{level: 66, luk: 1},
        67 => %Job.BonusStats{level: 66, luk: 1},
        68 => %Job.BonusStats{level: 68, int: 1},
        69 => %Job.BonusStats{level: 69, agi: 1},
        70 => %Job.BonusStats{level: 70, int: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 45,
        dagger: 53,
        one_handed_sword: 60,
        staff: 55,
        book: 43,
        two_handed_staff: 55,
        shield: 5
      },
      hp_factor: 75,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 700,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 24_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
