defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.RuneKnightT2 do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4081,
      name: :rune_knight_t2,
      base_hp: Tables.BasepointsBabyRuneKnight.base_hp(),
      base_sp: Tables.BasepointsBabyRuneKnight.base_sp(),
      base_ap: Tables.BasepointsBabyRuneKnight.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, int: 1},
        3 => %Job.BonusStats{level: 3, dex: 1},
        4 => %Job.BonusStats{level: 4, vit: 1},
        5 => %Job.BonusStats{level: 5, int: 1},
        6 => %Job.BonusStats{level: 5, int: 1},
        7 => %Job.BonusStats{level: 5, int: 1},
        8 => %Job.BonusStats{level: 5, int: 1},
        9 => %Job.BonusStats{level: 5, int: 1},
        10 => %Job.BonusStats{level: 10, str: 1},
        11 => %Job.BonusStats{level: 11, str: 1},
        12 => %Job.BonusStats{level: 12, int: 1},
        13 => %Job.BonusStats{level: 13, int: 1},
        14 => %Job.BonusStats{level: 14, vit: 1},
        15 => %Job.BonusStats{level: 15, dex: 1},
        16 => %Job.BonusStats{level: 15, dex: 1},
        17 => %Job.BonusStats{level: 15, dex: 1},
        18 => %Job.BonusStats{level: 15, dex: 1},
        19 => %Job.BonusStats{level: 19, dex: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, int: 1},
        23 => %Job.BonusStats{level: 23, vit: 1},
        24 => %Job.BonusStats{level: 24, dex: 1},
        25 => %Job.BonusStats{level: 24, dex: 1},
        26 => %Job.BonusStats{level: 24, dex: 1},
        27 => %Job.BonusStats{level: 24, dex: 1},
        28 => %Job.BonusStats{level: 24, dex: 1},
        29 => %Job.BonusStats{level: 24, dex: 1},
        30 => %Job.BonusStats{level: 30, int: 1},
        31 => %Job.BonusStats{level: 31, dex: 1},
        32 => %Job.BonusStats{level: 32, vit: 1},
        33 => %Job.BonusStats{level: 33, str: 1},
        34 => %Job.BonusStats{level: 33, str: 1},
        35 => %Job.BonusStats{level: 33, str: 1},
        36 => %Job.BonusStats{level: 33, str: 1},
        37 => %Job.BonusStats{level: 33, str: 1},
        38 => %Job.BonusStats{level: 33, str: 1},
        39 => %Job.BonusStats{level: 39, int: 1},
        40 => %Job.BonusStats{level: 40, dex: 1},
        41 => %Job.BonusStats{level: 41, agi: 1},
        42 => %Job.BonusStats{level: 41, agi: 1},
        43 => %Job.BonusStats{level: 41, agi: 1},
        44 => %Job.BonusStats{level: 44, dex: 1},
        45 => %Job.BonusStats{level: 45, vit: 1},
        46 => %Job.BonusStats{level: 46, int: 1},
        47 => %Job.BonusStats{level: 47, luk: 1},
        48 => %Job.BonusStats{level: 48, luk: 1},
        49 => %Job.BonusStats{level: 49, luk: 1},
        50 => %Job.BonusStats{level: 50, int: 1},
        51 => %Job.BonusStats{level: 51, str: 1},
        52 => %Job.BonusStats{level: 51, str: 1},
        53 => %Job.BonusStats{level: 53, agi: 1},
        54 => %Job.BonusStats{level: 53, agi: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 55, dex: 1},
        57 => %Job.BonusStats{level: 57, luk: 1},
        58 => %Job.BonusStats{level: 57, luk: 1},
        59 => %Job.BonusStats{level: 59, vit: 1},
        60 => %Job.BonusStats{level: 60, str: 1},
        61 => %Job.BonusStats{level: 61, vit: 1},
        62 => %Job.BonusStats{level: 61, vit: 1},
        63 => %Job.BonusStats{level: 63, agi: 1},
        64 => %Job.BonusStats{level: 63, agi: 1},
        65 => %Job.BonusStats{level: 65, luk: 1},
        66 => %Job.BonusStats{level: 66, dex: 1},
        67 => %Job.BonusStats{level: 66, dex: 1},
        68 => %Job.BonusStats{level: 68, agi: 1},
        69 => %Job.BonusStats{level: 68, agi: 1},
        70 => %Job.BonusStats{level: 70, str: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 52,
        two_handed_sword: 55,
        one_handed_spear: 60,
        two_handed_spear: 58,
        one_handed_axe: 48,
        two_handed_axe: 52,
        mace: 45,
        two_handed_mace: 52,
        shield: 5
      },
      hp_factor: 150,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 300,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 35_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
