defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.ShadowCross do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4254,
      name: :shadow_cross,
      base_hp: Tables.BasepointsShadowCross.base_hp(),
      base_sp: Tables.BasepointsShadowCross.base_sp(),
      base_ap: Tables.BasepointsShadowCross.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1, agi: 1},
        2 => %Job.BonusStats{level: 2, str: 1, agi: 1},
        3 => %Job.BonusStats{level: 3, agi: 1, dex: 1},
        4 => %Job.BonusStats{level: 4, str: 1, luk: 1},
        5 => %Job.BonusStats{level: 5, pow: 1},
        6 => %Job.BonusStats{level: 6, agi: 1, int: 1},
        7 => %Job.BonusStats{level: 7, str: 1, vit: 1},
        8 => %Job.BonusStats{level: 8, dex: 1, pow: 1},
        9 => %Job.BonusStats{level: 9, int: 1, luk: 1},
        10 => %Job.BonusStats{level: 10, sta: 1},
        11 => %Job.BonusStats{level: 11, agi: 1, dex: 1},
        12 => %Job.BonusStats{level: 12, pow: 1},
        13 => %Job.BonusStats{level: 13, agi: 1, vit: 1},
        14 => %Job.BonusStats{level: 14, vit: 1},
        15 => %Job.BonusStats{level: 15, str: 1, agi: 1},
        16 => %Job.BonusStats{level: 16, pow: 1},
        17 => %Job.BonusStats{level: 17, str: 1, int: 1},
        18 => %Job.BonusStats{level: 18, pow: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, dex: 1, sta: 1},
        21 => %Job.BonusStats{level: 21, vit: 1, dex: 1},
        22 => %Job.BonusStats{level: 22, int: 1},
        23 => %Job.BonusStats{level: 23, vit: 1, dex: 1},
        24 => %Job.BonusStats{level: 24, dex: 1, con: 1},
        25 => %Job.BonusStats{level: 25, str: 1, dex: 1},
        26 => %Job.BonusStats{level: 26, dex: 1},
        27 => %Job.BonusStats{level: 27, str: 1, agi: 1},
        28 => %Job.BonusStats{level: 28, luk: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 30, int: 1, luk: 1},
        31 => %Job.BonusStats{level: 31, pow: 1},
        32 => %Job.BonusStats{level: 32, con: 1},
        33 => %Job.BonusStats{level: 33, pow: 1},
        34 => %Job.BonusStats{level: 34, sta: 1},
        35 => %Job.BonusStats{level: 35, con: 1, crt: 1},
        36 => %Job.BonusStats{level: 36, agi: 1},
        37 => %Job.BonusStats{level: 37, pow: 1, con: 1},
        38 => %Job.BonusStats{level: 38, crt: 1},
        39 => %Job.BonusStats{level: 39, sta: 1, wis: 1},
        40 => %Job.BonusStats{level: 40, pow: 1, sta: 1},
        41 => %Job.BonusStats{level: 41, wis: 1},
        42 => %Job.BonusStats{level: 42, pow: 1},
        43 => %Job.BonusStats{level: 43, vit: 1},
        44 => %Job.BonusStats{level: 44, sta: 1},
        45 => %Job.BonusStats{level: 45, sta: 1, wis: 1},
        46 => %Job.BonusStats{level: 46, crt: 1},
        47 => %Job.BonusStats{level: 47, con: 1},
        48 => %Job.BonusStats{level: 48, crt: 1},
        49 => %Job.BonusStats{level: 49, wis: 1, con: 1},
        50 => %Job.BonusStats{level: 50, pow: 1, crt: 1},
        51 => %Job.BonusStats{level: 51, pow: 1},
        52 => %Job.BonusStats{level: 51, pow: 1},
        53 => %Job.BonusStats{level: 53, con: 1},
        54 => %Job.BonusStats{level: 54, sta: 1, crt: 1},
        55 => %Job.BonusStats{level: 55, crt: 1},
        56 => %Job.BonusStats{level: 55, crt: 1},
        57 => %Job.BonusStats{level: 57, con: 1},
        58 => %Job.BonusStats{level: 57, con: 1},
        59 => %Job.BonusStats{level: 59, crt: 1},
        60 => %Job.BonusStats{level: 59, crt: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 42,
        one_handed_sword: 65,
        one_handed_axe: 80,
        katar: 42,
        rifle: 95,
        gatling: 120,
        shotgun: 90,
        grenade: 100,
        huuma: 110,
        shield: 9
      },
      hp_factor: 110,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
