defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Shinkiro do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4304,
      name: :shinkiro,
      base_hp: Tables.BasepointsShinkiro.base_hp(),
      base_sp: Tables.BasepointsShinkiro.base_sp(),
      base_ap: Tables.BasepointsShinkiro.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1, dex: 1, sta: 1},
        2 => %Job.BonusStats{level: 2, str: 1, pow: 1, sta: 1},
        3 => %Job.BonusStats{level: 3, agi: 1, int: 1, dex: -1},
        4 => %Job.BonusStats{level: 4, str: 1, agi: 1, dex: 2, sta: 1},
        5 => %Job.BonusStats{level: 5, str: 1, int: 1, pow: 1, sta: 1},
        6 => %Job.BonusStats{level: 6, str: 1, sta: 1},
        7 => %Job.BonusStats{level: 7, str: 1, dex: 1, sta: 1},
        8 => %Job.BonusStats{level: 8, dex: 1, crt: 1},
        9 => %Job.BonusStats{level: 9, agi: 1, vit: 1},
        10 => %Job.BonusStats{level: 10, dex: 1},
        11 => %Job.BonusStats{level: 11, vit: 1, int: 1},
        12 => %Job.BonusStats{level: 12, str: 1, luk: 1, sta: 1},
        13 => %Job.BonusStats{level: 13, str: 1, vit: 1, sta: 1},
        14 => %Job.BonusStats{level: 14, crt: 1},
        15 => %Job.BonusStats{level: 15, wis: 1},
        16 => %Job.BonusStats{level: 16, str: 1, sta: 1},
        17 => %Job.BonusStats{level: 17, str: 1, agi: 1, sta: 1},
        18 => %Job.BonusStats{level: 17, str: 1, agi: 1, sta: 1},
        19 => %Job.BonusStats{level: 19, pow: 1},
        20 => %Job.BonusStats{level: 20, str: 1, sta: 1},
        21 => %Job.BonusStats{level: 21, dex: 1},
        22 => %Job.BonusStats{level: 22, agi: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, str: 1, dex: 1, sta: 1},
        25 => %Job.BonusStats{level: 25, agi: 1},
        26 => %Job.BonusStats{level: 26, dex: 1, luk: 1},
        27 => %Job.BonusStats{level: 27, con: 1},
        28 => %Job.BonusStats{level: 28, agi: 1, pow: 1},
        29 => %Job.BonusStats{level: 29, vit: 1, dex: 1},
        30 => %Job.BonusStats{level: 30, luk: 1, con: 1},
        31 => %Job.BonusStats{level: 31, agi: 1, vit: 1},
        32 => %Job.BonusStats{level: 32, agi: 1},
        33 => %Job.BonusStats{level: 33, vit: 1},
        34 => %Job.BonusStats{level: 34, pow: 1},
        35 => %Job.BonusStats{level: 35, con: 1},
        36 => %Job.BonusStats{level: 36, pow: 1},
        37 => %Job.BonusStats{level: 37, con: 1},
        38 => %Job.BonusStats{level: 38, crt: 1},
        39 => %Job.BonusStats{level: 38, crt: 1},
        40 => %Job.BonusStats{level: 40, pow: 1},
        41 => %Job.BonusStats{level: 41, pow: 1},
        42 => %Job.BonusStats{level: 42, crt: 1},
        43 => %Job.BonusStats{level: 42, crt: 1},
        44 => %Job.BonusStats{level: 44, pow: 1},
        45 => %Job.BonusStats{level: 45, crt: 1},
        46 => %Job.BonusStats{level: 46, crt: 1},
        47 => %Job.BonusStats{level: 47, pow: 1, wis: 1},
        48 => %Job.BonusStats{level: 47, pow: 1, wis: 1},
        49 => %Job.BonusStats{level: 49, con: 1},
        50 => %Job.BonusStats{level: 50, pow: 1, crt: 1},
        51 => %Job.BonusStats{level: 51, crt: 1},
        52 => %Job.BonusStats{level: 52, con: 1},
        53 => %Job.BonusStats{level: 53, wis: 1},
        54 => %Job.BonusStats{level: 54, sta: 1},
        55 => %Job.BonusStats{level: 55, sta: 1},
        56 => %Job.BonusStats{level: 56, int: 1, dex: 1},
        57 => %Job.BonusStats{level: 57, wis: 1},
        58 => %Job.BonusStats{level: 57, wis: 1},
        59 => %Job.BonusStats{level: 59, int: 1, spl: 1},
        60 => %Job.BonusStats{level: 59, int: 1, spl: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 45, huuma: 50, shield: 3},
      hp_factor: 98,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 540,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 45_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
