defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Sniper do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4012,
      name: :sniper,
      base_hp: Tables.BasepointsBabyHunter.base_hp(),
      base_sp: Tables.BasepointsBabyHunter.base_sp(),
      base_ap: Tables.BasepointsBabyHunter.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, agi: 1},
        3 => %Job.BonusStats{level: 3, dex: 1},
        4 => %Job.BonusStats{level: 4, dex: 1},
        5 => %Job.BonusStats{level: 5, int: 1},
        6 => %Job.BonusStats{level: 6, agi: 1},
        7 => %Job.BonusStats{level: 6, agi: 1},
        8 => %Job.BonusStats{level: 8, str: 1},
        9 => %Job.BonusStats{level: 8, str: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, agi: 1},
        12 => %Job.BonusStats{level: 12, vit: 1},
        13 => %Job.BonusStats{level: 12, vit: 1},
        14 => %Job.BonusStats{level: 14, luk: 1},
        15 => %Job.BonusStats{level: 14, luk: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 17, dex: 1},
        19 => %Job.BonusStats{level: 17, dex: 1},
        20 => %Job.BonusStats{level: 20, int: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 22, dex: 1},
        24 => %Job.BonusStats{level: 24, str: 1},
        25 => %Job.BonusStats{level: 25, luk: 1},
        26 => %Job.BonusStats{level: 26, dex: 1},
        27 => %Job.BonusStats{level: 26, dex: 1},
        28 => %Job.BonusStats{level: 28, agi: 1},
        29 => %Job.BonusStats{level: 28, agi: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 31, luk: 1},
        32 => %Job.BonusStats{level: 32, vit: 1},
        33 => %Job.BonusStats{level: 33, agi: 1},
        34 => %Job.BonusStats{level: 33, agi: 1},
        35 => %Job.BonusStats{level: 35, dex: 1},
        36 => %Job.BonusStats{level: 36, luk: 1},
        37 => %Job.BonusStats{level: 36, luk: 1},
        38 => %Job.BonusStats{level: 38, agi: 1},
        39 => %Job.BonusStats{level: 38, agi: 1},
        40 => %Job.BonusStats{level: 40, dex: 1},
        41 => %Job.BonusStats{level: 40, dex: 1},
        42 => %Job.BonusStats{level: 42, int: 1},
        43 => %Job.BonusStats{level: 43, agi: 1},
        44 => %Job.BonusStats{level: 43, agi: 1},
        45 => %Job.BonusStats{level: 45, str: 1},
        46 => %Job.BonusStats{level: 46, dex: 1},
        47 => %Job.BonusStats{level: 46, dex: 1},
        48 => %Job.BonusStats{level: 48, agi: 1},
        49 => %Job.BonusStats{level: 48, agi: 1},
        50 => %Job.BonusStats{level: 50, luk: 1},
        51 => %Job.BonusStats{level: 51, dex: 1},
        52 => %Job.BonusStats{level: 51, dex: 1},
        53 => %Job.BonusStats{level: 51, dex: 1},
        54 => %Job.BonusStats{level: 54, int: 1},
        55 => %Job.BonusStats{level: 55, vit: 1},
        56 => %Job.BonusStats{level: 55, vit: 1},
        57 => %Job.BonusStats{level: 57, luk: 1},
        58 => %Job.BonusStats{level: 58, agi: 1},
        59 => %Job.BonusStats{level: 58, agi: 1},
        60 => %Job.BonusStats{level: 60, dex: 1},
        61 => %Job.BonusStats{level: 61, str: 1},
        62 => %Job.BonusStats{level: 62, luk: 1},
        63 => %Job.BonusStats{level: 62, luk: 1},
        64 => %Job.BonusStats{level: 62, luk: 1},
        65 => %Job.BonusStats{level: 65, int: 1},
        66 => %Job.BonusStats{level: 65, int: 1},
        67 => %Job.BonusStats{level: 65, int: 1},
        68 => %Job.BonusStats{level: 65, int: 1},
        69 => %Job.BonusStats{level: 69, dex: 1},
        70 => %Job.BonusStats{level: 70, luk: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 53, bow: 48, shield: 9},
      hp_factor: 85,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 27_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
