defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.SoulAscetic do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4303,
      name: :soul_ascetic,
      base_hp: Tables.BasepointsSoulAscetic.base_hp(),
      base_sp: Tables.BasepointsSoulAscetic.base_sp(),
      base_ap: Tables.BasepointsSoulAscetic.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, vit: 1, int: 1},
        2 => %Job.BonusStats{level: 2, int: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, agi: 1, spl: 1},
        4 => %Job.BonusStats{level: 4, int: 1, dex: 1},
        5 => %Job.BonusStats{level: 5, int: 1, dex: 1},
        6 => %Job.BonusStats{level: 6, dex: 1, spl: 1},
        7 => %Job.BonusStats{level: 7, int: 1, dex: 1},
        8 => %Job.BonusStats{level: 8, vit: 1, dex: 1},
        9 => %Job.BonusStats{level: 9, int: 1, spl: 1},
        10 => %Job.BonusStats{level: 10, vit: 1, dex: 1},
        11 => %Job.BonusStats{level: 11, agi: 1, int: 1},
        12 => %Job.BonusStats{level: 12, int: 1, dex: 1},
        13 => %Job.BonusStats{level: 13, wis: 1, con: 1},
        14 => %Job.BonusStats{level: 14, int: 1, luk: 1},
        15 => %Job.BonusStats{level: 15, vit: 1, int: 1},
        16 => %Job.BonusStats{level: 16, vit: 1, crt: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 18, con: 1},
        19 => %Job.BonusStats{level: 19, wis: 1},
        20 => %Job.BonusStats{level: 19, wis: 1},
        21 => %Job.BonusStats{level: 21, dex: 1},
        22 => %Job.BonusStats{level: 22, dex: 1, spl: 1},
        23 => %Job.BonusStats{level: 23, int: 1, luk: 1},
        24 => %Job.BonusStats{level: 23, int: 1, luk: 1},
        25 => %Job.BonusStats{level: 25, agi: 1},
        26 => %Job.BonusStats{level: 26, spl: 1},
        27 => %Job.BonusStats{level: 27, str: 1, sta: 1},
        28 => %Job.BonusStats{level: 28, agi: 1, vit: 1},
        29 => %Job.BonusStats{level: 29, str: 1, agi: 1, sta: 1},
        30 => %Job.BonusStats{level: 30, spl: 1},
        31 => %Job.BonusStats{level: 31, wis: 1},
        32 => %Job.BonusStats{level: 32, agi: 1, dex: 1},
        33 => %Job.BonusStats{level: 33, con: 1},
        34 => %Job.BonusStats{level: 34, agi: 1},
        35 => %Job.BonusStats{level: 35, vit: 1, dex: 1},
        36 => %Job.BonusStats{level: 36, str: 1, sta: 1},
        37 => %Job.BonusStats{level: 37, spl: 1},
        38 => %Job.BonusStats{level: 37, spl: 1},
        39 => %Job.BonusStats{level: 37, spl: 1},
        40 => %Job.BonusStats{level: 40, crt: 1},
        41 => %Job.BonusStats{level: 40, crt: 1},
        42 => %Job.BonusStats{level: 40, crt: 1},
        43 => %Job.BonusStats{level: 43, wis: 1, con: 1},
        44 => %Job.BonusStats{level: 44, wis: 1, spl: 1},
        45 => %Job.BonusStats{level: 45, spl: 1},
        46 => %Job.BonusStats{level: 46, con: 1},
        47 => %Job.BonusStats{level: 47, spl: 1},
        48 => %Job.BonusStats{level: 48, crt: 1},
        49 => %Job.BonusStats{level: 49, con: 1},
        50 => %Job.BonusStats{level: 50, wis: 1, spl: 1},
        51 => %Job.BonusStats{level: 51, spl: 1},
        52 => %Job.BonusStats{level: 52, con: 1},
        53 => %Job.BonusStats{level: 53, wis: 1},
        54 => %Job.BonusStats{level: 54, sta: 1},
        55 => %Job.BonusStats{level: 55, spl: 1},
        56 => %Job.BonusStats{level: 56, wis: 1},
        57 => %Job.BonusStats{level: 56, wis: 1},
        58 => %Job.BonusStats{level: 56, wis: 1},
        59 => %Job.BonusStats{level: 59, con: 1},
        60 => %Job.BonusStats{level: 59, con: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 50, dagger: 50, staff: 53, two_handed_staff: 55, shield: 8},
      hp_factor: 75,
      hp_increase: 850,
      sp_factor: 0,
      sp_increase: 860,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
