defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.SpiritHandler do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4308,
      name: :spirit_handler,
      base_hp: Tables.BasepointsSpiritHandler.base_hp(),
      base_sp: Tables.BasepointsSpiritHandler.base_sp(),
      base_ap: Tables.BasepointsSpiritHandler.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1, sta: 1},
        2 => %Job.BonusStats{level: 2, int: 1, dex: 1},
        3 => %Job.BonusStats{level: 3, int: 1, crt: 1},
        4 => %Job.BonusStats{level: 4, str: 1, sta: 1},
        5 => %Job.BonusStats{level: 5, vit: 1, dex: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 7, agi: 1},
        8 => %Job.BonusStats{level: 8, int: 1, luk: 1},
        9 => %Job.BonusStats{level: 9, agi: 1, spl: 1},
        10 => %Job.BonusStats{level: 10, str: 1, pow: 1},
        11 => %Job.BonusStats{level: 11, dex: 1, crt: 1},
        12 => %Job.BonusStats{level: 12, vit: 1, con: 1},
        13 => %Job.BonusStats{level: 13, agi: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 15, int: 1, spl: 1},
        16 => %Job.BonusStats{level: 16, dex: 1},
        17 => %Job.BonusStats{level: 17, int: 1},
        18 => %Job.BonusStats{level: 18, dex: 1, wis: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, agi: 1, pow: 1},
        21 => %Job.BonusStats{level: 21, dex: 1},
        22 => %Job.BonusStats{level: 22, vit: 1, spl: 1},
        23 => %Job.BonusStats{level: 23, str: 1},
        24 => %Job.BonusStats{level: 24, int: 1, con: 1},
        25 => %Job.BonusStats{level: 25, int: 1, crt: 1},
        26 => %Job.BonusStats{level: 26, vit: 1, sta: 1},
        27 => %Job.BonusStats{level: 27, luk: 1, wis: 1},
        28 => %Job.BonusStats{level: 28, luk: 1},
        29 => %Job.BonusStats{level: 29, dex: 1},
        30 => %Job.BonusStats{level: 30, int: 1, spl: 1},
        31 => %Job.BonusStats{level: 31, str: 1},
        32 => %Job.BonusStats{level: 32, dex: 1, con: 1},
        33 => %Job.BonusStats{level: 33, agi: 1, pow: 1},
        34 => %Job.BonusStats{level: 34, vit: 1},
        35 => %Job.BonusStats{level: 35, dex: 1},
        36 => %Job.BonusStats{level: 36, str: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, luk: 1, spl: 1},
        39 => %Job.BonusStats{level: 39, pow: 1, con: 1},
        40 => %Job.BonusStats{level: 40, luk: 1},
        41 => %Job.BonusStats{level: 41, pow: 1},
        42 => %Job.BonusStats{level: 42, wis: 1, spl: 1},
        43 => %Job.BonusStats{level: 43, agi: 1},
        44 => %Job.BonusStats{level: 44, pow: 1},
        45 => %Job.BonusStats{level: 45, spl: 1, con: 1},
        46 => %Job.BonusStats{level: 46, sta: 1},
        47 => %Job.BonusStats{level: 47, wis: 1, con: 1},
        48 => %Job.BonusStats{level: 48, sta: 1},
        49 => %Job.BonusStats{level: 49, crt: 1},
        50 => %Job.BonusStats{level: 50, pow: 1},
        51 => %Job.BonusStats{level: 51, con: 1},
        52 => %Job.BonusStats{level: 52, pow: 1},
        53 => %Job.BonusStats{level: 53, spl: 1},
        54 => %Job.BonusStats{level: 54, wis: 1},
        55 => %Job.BonusStats{level: 55, sta: 1},
        56 => %Job.BonusStats{level: 55, sta: 1},
        57 => %Job.BonusStats{level: 57, spl: 1},
        58 => %Job.BonusStats{level: 57, spl: 1},
        59 => %Job.BonusStats{level: 59, pow: 1},
        60 => %Job.BonusStats{level: 59, pow: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, staff: 60, shield: 7},
      hp_factor: 80,
      hp_increase: 1150,
      sp_factor: 0,
      sp_increase: 730,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
