defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.StarEmperor do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4239,
      name: :star_emperor,
      base_hp: Tables.BasepointsBabyStarEmperor.base_hp(),
      base_sp: Tables.BasepointsBabyStarEmperor.base_sp(),
      base_ap: Tables.BasepointsBabyStarEmperor.base_ap(),
      base_exp: Tables.ExpBabyKagerou.base_exp(),
      job_exp: Tables.ExpBabyKagerou.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1},
        2 => %Job.BonusStats{level: 2, dex: 1},
        3 => %Job.BonusStats{level: 2, dex: 1},
        4 => %Job.BonusStats{level: 2, dex: 1},
        5 => %Job.BonusStats{level: 5, agi: 1},
        6 => %Job.BonusStats{level: 5, agi: 1},
        7 => %Job.BonusStats{level: 7, int: 1},
        8 => %Job.BonusStats{level: 8, str: 1},
        9 => %Job.BonusStats{level: 9, luk: 1},
        10 => %Job.BonusStats{level: 9, luk: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, str: 1},
        13 => %Job.BonusStats{level: 13, agi: 1},
        14 => %Job.BonusStats{level: 13, agi: 1},
        15 => %Job.BonusStats{level: 15, int: 1},
        16 => %Job.BonusStats{level: 16, luk: 1},
        17 => %Job.BonusStats{level: 17, vit: 1},
        18 => %Job.BonusStats{level: 17, vit: 1},
        19 => %Job.BonusStats{level: 19, str: 1},
        20 => %Job.BonusStats{level: 20, dex: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 21, agi: 1},
        23 => %Job.BonusStats{level: 23, str: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 25, int: 1},
        26 => %Job.BonusStats{level: 25, int: 1},
        27 => %Job.BonusStats{level: 27, dex: 1},
        28 => %Job.BonusStats{level: 27, dex: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 30, dex: 1},
        31 => %Job.BonusStats{level: 31, str: 1},
        32 => %Job.BonusStats{level: 31, str: 1},
        33 => %Job.BonusStats{level: 31, str: 1},
        34 => %Job.BonusStats{level: 34, dex: 1},
        35 => %Job.BonusStats{level: 35, agi: 1},
        36 => %Job.BonusStats{level: 36, luk: 1},
        37 => %Job.BonusStats{level: 37, vit: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 39, str: 1},
        40 => %Job.BonusStats{level: 39, str: 1},
        41 => %Job.BonusStats{level: 41, agi: 1},
        42 => %Job.BonusStats{level: 42, vit: 1},
        43 => %Job.BonusStats{level: 43, str: 1},
        44 => %Job.BonusStats{level: 43, str: 1},
        45 => %Job.BonusStats{level: 45, dex: 1},
        46 => %Job.BonusStats{level: 45, dex: 1},
        47 => %Job.BonusStats{level: 47, agi: 1},
        48 => %Job.BonusStats{level: 48, str: 1},
        49 => %Job.BonusStats{level: 48, str: 1},
        50 => %Job.BonusStats{level: 50, dex: 1},
        51 => %Job.BonusStats{level: 50, dex: 1},
        52 => %Job.BonusStats{level: 50, dex: 1},
        53 => %Job.BonusStats{level: 50, dex: 1},
        54 => %Job.BonusStats{level: 50, dex: 1},
        55 => %Job.BonusStats{level: 50, dex: 1},
        56 => %Job.BonusStats{level: 56, str: 1},
        57 => %Job.BonusStats{level: 56, str: 1},
        58 => %Job.BonusStats{level: 56, str: 1},
        59 => %Job.BonusStats{level: 59, agi: 1},
        60 => %Job.BonusStats{level: 59, agi: 1},
        61 => %Job.BonusStats{level: 61, str: 1},
        62 => %Job.BonusStats{level: 61, str: 1},
        63 => %Job.BonusStats{level: 61, str: 1},
        64 => %Job.BonusStats{level: 64, vit: 1},
        65 => %Job.BonusStats{level: 65, agi: 1},
        66 => %Job.BonusStats{level: 66, vit: 1},
        67 => %Job.BonusStats{level: 66, vit: 1},
        68 => %Job.BonusStats{level: 66, vit: 1},
        69 => %Job.BonusStats{level: 69, str: 1},
        70 => %Job.BonusStats{level: 70, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 50,
        two_handed_sword: 50,
        one_handed_spear: 50,
        two_handed_spear: 50,
        one_handed_axe: 50,
        two_handed_axe: 50,
        mace: 50,
        two_handed_mace: 50,
        staff: 50,
        bow: 50,
        knuckle: 50,
        musical: 50,
        whip: 50,
        book: 50,
        katar: 50,
        revolver: 50,
        rifle: 50,
        gatling: 50,
        shotgun: 50,
        grenade: 50,
        huuma: 50,
        two_handed_staff: 50,
        shield: 6
      },
      hp_factor: 90,
      hp_increase: 650,
      sp_factor: 0,
      sp_increase: 470,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
