defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.SuperBabyE do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4191,
      name: :super_baby_e,
      base_hp: Tables.BasepointsSuperBaby.base_hp(),
      base_sp: Tables.BasepointsSuperBaby.base_sp(),
      base_ap: Tables.BasepointsSuperBaby.base_ap(),
      base_exp: Tables.ExpBabyKagerou.base_exp(),
      job_exp: Tables.ExpBabyKagerou.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1},
        2 => %Job.BonusStats{level: 2, agi: 1},
        3 => %Job.BonusStats{level: 2, agi: 1},
        4 => %Job.BonusStats{level: 4, vit: 1},
        5 => %Job.BonusStats{level: 4, vit: 1},
        6 => %Job.BonusStats{level: 6, int: 1},
        7 => %Job.BonusStats{level: 7, dex: 1},
        8 => %Job.BonusStats{level: 7, dex: 1},
        9 => %Job.BonusStats{level: 9, luk: 1},
        10 => %Job.BonusStats{level: 9, luk: 1},
        11 => %Job.BonusStats{level: 11, str: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 12, agi: 1},
        14 => %Job.BonusStats{level: 14, vit: 1},
        15 => %Job.BonusStats{level: 14, vit: 1},
        16 => %Job.BonusStats{level: 16, int: 1},
        17 => %Job.BonusStats{level: 17, dex: 1},
        18 => %Job.BonusStats{level: 17, dex: 1},
        19 => %Job.BonusStats{level: 19, luk: 1},
        20 => %Job.BonusStats{level: 19, luk: 1},
        21 => %Job.BonusStats{level: 21, str: 1},
        22 => %Job.BonusStats{level: 22, agi: 1},
        23 => %Job.BonusStats{level: 22, agi: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 24, vit: 1},
        26 => %Job.BonusStats{level: 26, int: 1},
        27 => %Job.BonusStats{level: 27, dex: 1},
        28 => %Job.BonusStats{level: 27, dex: 1},
        29 => %Job.BonusStats{level: 29, luk: 1},
        30 => %Job.BonusStats{level: 29, luk: 1},
        31 => %Job.BonusStats{level: 31, str: 1},
        32 => %Job.BonusStats{level: 32, agi: 1},
        33 => %Job.BonusStats{level: 32, agi: 1},
        34 => %Job.BonusStats{level: 34, vit: 1},
        35 => %Job.BonusStats{level: 34, vit: 1},
        36 => %Job.BonusStats{level: 36, int: 1},
        37 => %Job.BonusStats{level: 37, dex: 1},
        38 => %Job.BonusStats{level: 37, dex: 1},
        39 => %Job.BonusStats{level: 39, luk: 1},
        40 => %Job.BonusStats{level: 39, luk: 1},
        41 => %Job.BonusStats{level: 41, str: 1},
        42 => %Job.BonusStats{level: 42, agi: 1},
        43 => %Job.BonusStats{level: 42, agi: 1},
        44 => %Job.BonusStats{level: 44, vit: 1},
        45 => %Job.BonusStats{level: 44, vit: 1},
        46 => %Job.BonusStats{level: 46, int: 1},
        47 => %Job.BonusStats{level: 47, dex: 1},
        48 => %Job.BonusStats{level: 47, dex: 1},
        49 => %Job.BonusStats{level: 49, luk: 1},
        50 => %Job.BonusStats{level: 49, luk: 1},
        51 => %Job.BonusStats{level: 51, str: 1},
        52 => %Job.BonusStats{level: 52, agi: 1},
        53 => %Job.BonusStats{level: 52, agi: 1},
        54 => %Job.BonusStats{level: 54, vit: 1},
        55 => %Job.BonusStats{level: 54, vit: 1},
        56 => %Job.BonusStats{level: 56, int: 1},
        57 => %Job.BonusStats{level: 57, dex: 1},
        58 => %Job.BonusStats{level: 57, dex: 1},
        59 => %Job.BonusStats{level: 59, luk: 1},
        60 => %Job.BonusStats{level: 59, luk: 1},
        61 => %Job.BonusStats{level: 61, str: 1},
        62 => %Job.BonusStats{level: 62, agi: 1},
        63 => %Job.BonusStats{level: 63, int: 1},
        64 => %Job.BonusStats{level: 64, dex: 1},
        65 => %Job.BonusStats{level: 64, dex: 1},
        66 => %Job.BonusStats{level: 66, str: 1},
        67 => %Job.BonusStats{level: 67, agi: 1},
        68 => %Job.BonusStats{level: 68, int: 1},
        69 => %Job.BonusStats{level: 68, int: 1},
        70 => %Job.BonusStats{level: 70, dex: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 55,
        one_handed_sword: 57,
        one_handed_axe: 50,
        mace: 50,
        two_handed_mace: 55,
        staff: 65,
        two_handed_staff: 65,
        shield: 10
      },
      hp_factor: 0,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 0,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 0,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
