defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Taekwon do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4046,
      name: :taekwon,
      base_hp: Tables.BasepointsBabyTaekwon.base_hp(),
      base_sp: Tables.BasepointsBabyTaekwon.base_sp(),
      base_ap: Tables.BasepointsBabyTaekwon.base_ap(),
      base_exp: Tables.ExpAcolyte.base_exp(),
      job_exp: Tables.ExpAcolyte.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, str: 1},
        2 => %Job.BonusStats{level: 2, str: 1},
        3 => %Job.BonusStats{level: 3, str: 1},
        4 => %Job.BonusStats{level: 4, str: 1},
        5 => %Job.BonusStats{level: 5, str: 1},
        6 => %Job.BonusStats{level: 6, str: 1},
        7 => %Job.BonusStats{level: 6, str: 1},
        8 => %Job.BonusStats{level: 6, str: 1},
        9 => %Job.BonusStats{level: 6, str: 1},
        10 => %Job.BonusStats{level: 10, dex: 1},
        11 => %Job.BonusStats{level: 11, dex: 1},
        12 => %Job.BonusStats{level: 12, dex: 1},
        13 => %Job.BonusStats{level: 13, dex: 1},
        14 => %Job.BonusStats{level: 14, dex: 1},
        15 => %Job.BonusStats{level: 15, dex: 1},
        16 => %Job.BonusStats{level: 15, dex: 1},
        17 => %Job.BonusStats{level: 15, dex: 1},
        18 => %Job.BonusStats{level: 15, dex: 1},
        19 => %Job.BonusStats{level: 15, dex: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 21, agi: 1},
        22 => %Job.BonusStats{level: 22, agi: 1},
        23 => %Job.BonusStats{level: 23, agi: 1},
        24 => %Job.BonusStats{level: 24, agi: 1},
        25 => %Job.BonusStats{level: 25, agi: 1},
        26 => %Job.BonusStats{level: 25, agi: 1},
        27 => %Job.BonusStats{level: 25, agi: 1},
        28 => %Job.BonusStats{level: 25, agi: 1},
        29 => %Job.BonusStats{level: 25, agi: 1},
        30 => %Job.BonusStats{level: 25, agi: 1},
        31 => %Job.BonusStats{level: 25, agi: 1},
        32 => %Job.BonusStats{level: 25, agi: 1},
        33 => %Job.BonusStats{level: 25, agi: 1},
        34 => %Job.BonusStats{level: 25, agi: 1},
        35 => %Job.BonusStats{level: 25, agi: 1},
        36 => %Job.BonusStats{level: 25, agi: 1},
        37 => %Job.BonusStats{level: 25, agi: 1},
        38 => %Job.BonusStats{level: 25, agi: 1},
        39 => %Job.BonusStats{level: 25, agi: 1},
        40 => %Job.BonusStats{level: 25, agi: 1},
        41 => %Job.BonusStats{level: 25, agi: 1},
        42 => %Job.BonusStats{level: 25, agi: 1},
        43 => %Job.BonusStats{level: 25, agi: 1},
        44 => %Job.BonusStats{level: 25, agi: 1},
        45 => %Job.BonusStats{level: 25, agi: 1},
        46 => %Job.BonusStats{level: 25, agi: 1},
        47 => %Job.BonusStats{level: 25, agi: 1},
        48 => %Job.BonusStats{level: 25, agi: 1},
        49 => %Job.BonusStats{level: 25, agi: 1},
        50 => %Job.BonusStats{level: 25, agi: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 50,
        two_handed_sword: 50,
        one_handed_spear: 50,
        two_handed_spear: 50,
        one_handed_axe: 50,
        two_handed_axe: 50,
        mace: 50,
        two_handed_mace: 50,
        staff: 50,
        bow: 50,
        knuckle: 50,
        musical: 50,
        whip: 50,
        book: 50,
        katar: 50,
        revolver: 50,
        rifle: 50,
        gatling: 50,
        shotgun: 50,
        grenade: 50,
        huuma: 50,
        two_handed_staff: 50,
        shield: 6
      },
      hp_factor: 70,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 200,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 28_000,
      max_base_level: 99,
      max_job_level: 50,
      max_stats: nil
    }
  end
end
