defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.WarlockT do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4061,
      name: :warlock_t,
      base_hp: Tables.BasepointsBabyWarlock.base_hp(),
      base_sp: Tables.BasepointsBabyWarlock.base_sp(),
      base_ap: Tables.BasepointsBabyWarlock.base_ap(),
      base_exp: Tables.ExpArchBishop.base_exp(),
      job_exp: Tables.ExpArchBishop.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, int: 1},
        2 => %Job.BonusStats{level: 2, int: 1},
        3 => %Job.BonusStats{level: 3, dex: 1},
        4 => %Job.BonusStats{level: 3, dex: 1},
        5 => %Job.BonusStats{level: 3, dex: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 7, int: 1},
        8 => %Job.BonusStats{level: 8, agi: 1},
        9 => %Job.BonusStats{level: 8, agi: 1},
        10 => %Job.BonusStats{level: 8, agi: 1},
        11 => %Job.BonusStats{level: 8, agi: 1},
        12 => %Job.BonusStats{level: 12, int: 1},
        13 => %Job.BonusStats{level: 13, dex: 1},
        14 => %Job.BonusStats{level: 13, dex: 1},
        15 => %Job.BonusStats{level: 15, vit: 1},
        16 => %Job.BonusStats{level: 15, vit: 1},
        17 => %Job.BonusStats{level: 15, vit: 1},
        18 => %Job.BonusStats{level: 18, vit: 1},
        19 => %Job.BonusStats{level: 19, dex: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 20, agi: 1},
        22 => %Job.BonusStats{level: 20, agi: 1},
        23 => %Job.BonusStats{level: 23, int: 1},
        24 => %Job.BonusStats{level: 24, vit: 1},
        25 => %Job.BonusStats{level: 25, vit: 1},
        26 => %Job.BonusStats{level: 25, vit: 1},
        27 => %Job.BonusStats{level: 25, vit: 1},
        28 => %Job.BonusStats{level: 28, dex: 1},
        29 => %Job.BonusStats{level: 29, agi: 1},
        30 => %Job.BonusStats{level: 29, agi: 1},
        31 => %Job.BonusStats{level: 31, luk: 1},
        32 => %Job.BonusStats{level: 31, luk: 1},
        33 => %Job.BonusStats{level: 31, luk: 1},
        34 => %Job.BonusStats{level: 34, str: 1},
        35 => %Job.BonusStats{level: 35, int: 1},
        36 => %Job.BonusStats{level: 36, int: 1},
        37 => %Job.BonusStats{level: 36, int: 1},
        38 => %Job.BonusStats{level: 36, int: 1},
        39 => %Job.BonusStats{level: 39, dex: 1},
        40 => %Job.BonusStats{level: 40, agi: 1},
        41 => %Job.BonusStats{level: 41, int: 1},
        42 => %Job.BonusStats{level: 41, int: 1},
        43 => %Job.BonusStats{level: 41, int: 1},
        44 => %Job.BonusStats{level: 44, int: 1},
        45 => %Job.BonusStats{level: 45, int: 1},
        46 => %Job.BonusStats{level: 45, int: 1},
        47 => %Job.BonusStats{level: 47, agi: 1},
        48 => %Job.BonusStats{level: 47, agi: 1},
        49 => %Job.BonusStats{level: 47, agi: 1},
        50 => %Job.BonusStats{level: 50, int: 1},
        51 => %Job.BonusStats{level: 51, dex: 1},
        52 => %Job.BonusStats{level: 52, vit: 1},
        53 => %Job.BonusStats{level: 53, luk: 1},
        54 => %Job.BonusStats{level: 54, agi: 1},
        55 => %Job.BonusStats{level: 55, int: 1},
        56 => %Job.BonusStats{level: 55, int: 1},
        57 => %Job.BonusStats{level: 57, vit: 1},
        58 => %Job.BonusStats{level: 58, agi: 1},
        59 => %Job.BonusStats{level: 59, dex: 1},
        60 => %Job.BonusStats{level: 60, int: 1},
        61 => %Job.BonusStats{level: 60, int: 1},
        62 => %Job.BonusStats{level: 62, int: 1},
        63 => %Job.BonusStats{level: 63, luk: 1},
        64 => %Job.BonusStats{level: 63, luk: 1},
        65 => %Job.BonusStats{level: 65, vit: 1},
        66 => %Job.BonusStats{level: 65, vit: 1},
        67 => %Job.BonusStats{level: 67, int: 1},
        68 => %Job.BonusStats{level: 68, luk: 1},
        69 => %Job.BonusStats{level: 68, luk: 1},
        70 => %Job.BonusStats{level: 70, vit: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 45,
        dagger: 52,
        one_handed_sword: 60,
        staff: 50,
        two_handed_staff: 56,
        shield: 5
      },
      hp_factor: 55,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 900,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 30_000,
      max_base_level: 200,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
