defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Whitesmith do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4011,
      name: :whitesmith,
      base_hp: Tables.BasepointsAlchemist.base_hp(),
      base_sp: Tables.BasepointsAlchemist.base_sp(),
      base_ap: Tables.BasepointsAlchemist.base_ap(),
      base_exp: Tables.ExpAssassinCross.base_exp(),
      job_exp: Tables.ExpAssassinCross.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, str: 1},
        3 => %Job.BonusStats{level: 3, str: 1},
        4 => %Job.BonusStats{level: 4, int: 1},
        5 => %Job.BonusStats{level: 4, int: 1},
        6 => %Job.BonusStats{level: 6, dex: 1},
        7 => %Job.BonusStats{level: 7, agi: 1},
        8 => %Job.BonusStats{level: 8, luk: 1},
        9 => %Job.BonusStats{level: 9, vit: 1},
        10 => %Job.BonusStats{level: 9, vit: 1},
        11 => %Job.BonusStats{level: 9, vit: 1},
        12 => %Job.BonusStats{level: 12, dex: 1},
        13 => %Job.BonusStats{level: 13, vit: 1},
        14 => %Job.BonusStats{level: 13, vit: 1},
        15 => %Job.BonusStats{level: 15, int: 1},
        16 => %Job.BonusStats{level: 16, luk: 1},
        17 => %Job.BonusStats{level: 17, str: 1},
        18 => %Job.BonusStats{level: 17, str: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, agi: 1},
        21 => %Job.BonusStats{level: 20, agi: 1},
        22 => %Job.BonusStats{level: 22, int: 1},
        23 => %Job.BonusStats{level: 23, dex: 1},
        24 => %Job.BonusStats{level: 23, dex: 1},
        25 => %Job.BonusStats{level: 23, dex: 1},
        26 => %Job.BonusStats{level: 26, str: 1},
        27 => %Job.BonusStats{level: 26, str: 1},
        28 => %Job.BonusStats{level: 28, luk: 1},
        29 => %Job.BonusStats{level: 29, vit: 1},
        30 => %Job.BonusStats{level: 29, vit: 1},
        31 => %Job.BonusStats{level: 31, agi: 1},
        32 => %Job.BonusStats{level: 32, dex: 1},
        33 => %Job.BonusStats{level: 33, str: 1},
        34 => %Job.BonusStats{level: 34, int: 1},
        35 => %Job.BonusStats{level: 34, int: 1},
        36 => %Job.BonusStats{level: 36, agi: 1},
        37 => %Job.BonusStats{level: 36, agi: 1},
        38 => %Job.BonusStats{level: 38, dex: 1},
        39 => %Job.BonusStats{level: 39, luk: 1},
        40 => %Job.BonusStats{level: 39, luk: 1},
        41 => %Job.BonusStats{level: 41, dex: 1},
        42 => %Job.BonusStats{level: 41, dex: 1},
        43 => %Job.BonusStats{level: 41, dex: 1},
        44 => %Job.BonusStats{level: 44, luk: 1},
        45 => %Job.BonusStats{level: 45, luk: 1},
        46 => %Job.BonusStats{level: 45, luk: 1},
        47 => %Job.BonusStats{level: 47, dex: 1},
        48 => %Job.BonusStats{level: 48, vit: 1},
        49 => %Job.BonusStats{level: 48, vit: 1},
        50 => %Job.BonusStats{level: 50, int: 1},
        51 => %Job.BonusStats{level: 50, int: 1},
        52 => %Job.BonusStats{level: 52, str: 1},
        53 => %Job.BonusStats{level: 52, str: 1},
        54 => %Job.BonusStats{level: 52, str: 1},
        55 => %Job.BonusStats{level: 55, dex: 1},
        56 => %Job.BonusStats{level: 56, dex: 1},
        57 => %Job.BonusStats{level: 56, dex: 1},
        58 => %Job.BonusStats{level: 58, agi: 1},
        59 => %Job.BonusStats{level: 58, agi: 1},
        60 => %Job.BonusStats{level: 60, vit: 1},
        61 => %Job.BonusStats{level: 61, int: 1},
        62 => %Job.BonusStats{level: 62, dex: 1},
        63 => %Job.BonusStats{level: 62, dex: 1},
        64 => %Job.BonusStats{level: 64, agi: 1},
        65 => %Job.BonusStats{level: 65, vit: 1},
        66 => %Job.BonusStats{level: 66, luk: 1},
        67 => %Job.BonusStats{level: 67, luk: 1},
        68 => %Job.BonusStats{level: 67, luk: 1},
        69 => %Job.BonusStats{level: 67, luk: 1},
        70 => %Job.BonusStats{level: 70, dex: 1}
      },
      base_aspd: %Job.BaseAspd{
        fist: 40,
        dagger: 50,
        one_handed_sword: 50,
        one_handed_axe: 46,
        two_handed_axe: 53,
        mace: 48,
        two_handed_mace: 53,
        shield: 5
      },
      hp_factor: 90,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 30_000,
      max_base_level: 99,
      max_job_level: 70,
      max_stats: nil
    }
  end
end
