defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs.Windhawk2 do
  @moduledoc false
  use Aesir.ZoneServer.Mmo.JobManagement.Definition

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Tables

  @impl true
  def job do
    %Job{
      id: 4278,
      name: :windhawk2,
      base_hp: Tables.BasepointsWindhawk.base_hp(),
      base_sp: Tables.BasepointsWindhawk.base_sp(),
      base_ap: Tables.BasepointsWindhawk.base_ap(),
      base_exp: Tables.ExpAbyssChaser.base_exp(),
      job_exp: Tables.ExpAbyssChaser.job_exp(),
      bonus_stats: %{
        1 => %Job.BonusStats{level: 1, dex: 1},
        2 => %Job.BonusStats{level: 2, vit: 1},
        3 => %Job.BonusStats{level: 3, agi: 1, con: 1},
        4 => %Job.BonusStats{level: 4, int: 1},
        5 => %Job.BonusStats{level: 5, agi: 1, pow: 1},
        6 => %Job.BonusStats{level: 6, vit: 1},
        7 => %Job.BonusStats{level: 7, con: 1},
        8 => %Job.BonusStats{level: 8, dex: 1, spl: 1},
        9 => %Job.BonusStats{level: 9, vit: 1, wis: 1},
        10 => %Job.BonusStats{level: 10, agi: 1},
        11 => %Job.BonusStats{level: 11, vit: 1, con: 1},
        12 => %Job.BonusStats{level: 12, agi: 1},
        13 => %Job.BonusStats{level: 13, agi: 1, pow: 1},
        14 => %Job.BonusStats{level: 14, luk: 1, con: 1},
        15 => %Job.BonusStats{level: 15, dex: 1, spl: 1},
        16 => %Job.BonusStats{level: 16, int: 1, sta: 1},
        17 => %Job.BonusStats{level: 17, crt: 1},
        18 => %Job.BonusStats{level: 18, luk: 1, con: 1},
        19 => %Job.BonusStats{level: 19, agi: 1},
        20 => %Job.BonusStats{level: 20, vit: 1},
        21 => %Job.BonusStats{level: 21, int: 1, wis: 1},
        22 => %Job.BonusStats{level: 22, dex: 1},
        23 => %Job.BonusStats{level: 23, str: 1, sta: 1},
        24 => %Job.BonusStats{level: 24, pow: 1},
        25 => %Job.BonusStats{level: 25, vit: 1},
        26 => %Job.BonusStats{level: 26, agi: 1, int: 1},
        27 => %Job.BonusStats{level: 27, luk: 1},
        28 => %Job.BonusStats{level: 28, con: 1},
        29 => %Job.BonusStats{level: 29, dex: 1, con: 1},
        30 => %Job.BonusStats{level: 30, sta: 1},
        31 => %Job.BonusStats{level: 31, luk: 1, crt: 1},
        32 => %Job.BonusStats{level: 32, spl: 1},
        33 => %Job.BonusStats{level: 33, agi: 1, wis: 1},
        34 => %Job.BonusStats{level: 34, int: 1, pow: 1},
        35 => %Job.BonusStats{level: 35, vit: 1},
        36 => %Job.BonusStats{level: 36, dex: 1, wis: 1},
        37 => %Job.BonusStats{level: 37, int: 1},
        38 => %Job.BonusStats{level: 38, agi: 1, int: 1},
        39 => %Job.BonusStats{level: 39, agi: 1},
        40 => %Job.BonusStats{level: 40, pow: 1, crt: 1},
        41 => %Job.BonusStats{level: 41, agi: 1, spl: 1},
        42 => %Job.BonusStats{level: 42, pow: 1, sta: 1},
        43 => %Job.BonusStats{level: 43, dex: 1},
        44 => %Job.BonusStats{level: 44, wis: 1, con: 1},
        45 => %Job.BonusStats{level: 45, str: 1, int: 1},
        46 => %Job.BonusStats{level: 46, crt: 1},
        47 => %Job.BonusStats{level: 47, agi: 1, pow: 1},
        48 => %Job.BonusStats{level: 48, int: 1},
        49 => %Job.BonusStats{level: 49, vit: 1},
        50 => %Job.BonusStats{level: 50, dex: 1, con: 1},
        51 => %Job.BonusStats{level: 51, con: 1},
        52 => %Job.BonusStats{level: 52, pow: 1, con: 1},
        53 => %Job.BonusStats{level: 53, sta: 1},
        54 => %Job.BonusStats{level: 53, sta: 1},
        55 => %Job.BonusStats{level: 55, pow: 1},
        56 => %Job.BonusStats{level: 55, pow: 1},
        57 => %Job.BonusStats{level: 57, crt: 1},
        58 => %Job.BonusStats{level: 57, crt: 1},
        59 => %Job.BonusStats{level: 59, pow: 1},
        60 => %Job.BonusStats{level: 59, pow: 1}
      },
      base_aspd: %Job.BaseAspd{fist: 40, dagger: 50, bow: 49, shield: 8},
      hp_factor: 85,
      hp_increase: 0,
      sp_factor: 0,
      sp_increase: 400,
      ap_factor: 0,
      ap_increase: 0,
      max_weight: 42_000,
      max_base_level: 275,
      max_job_level: 60,
      max_stats: nil
    }
  end
end
