defmodule Aesir.ZoneServer.Mmo.Option do
  @moduledoc """
  e_option (OPTION_*) sprite effect-state bitmask ids.

  Generated by `mix aesir.gen.constants` from the rAthena headers. Do not
  edit by hand; re-run the task to regenerate.
  """

  @ids %{
    :nothing => 0,
    :sight => 1,
    :hide => 2,
    :cloak => 4,
    :cart1 => 8,
    :falcon => 16,
    :riding => 32,
    :invisible => 64,
    :cart2 => 128,
    :cart3 => 256,
    :cart4 => 512,
    :cart5 => 1024,
    :orcish => 2048,
    :wedding => 4096,
    :ruwach => 8192,
    :chasewalk => 16_384,
    :flying => 32_768,
    :xmas => 65_536,
    :transform => 131_072,
    :summer => 262_144,
    :dragon1 => 524_288,
    :wug => 1_048_576,
    :wugrider => 2_097_152,
    :madogear => 4_194_304,
    :dragon2 => 8_388_608,
    :dragon3 => 16_777_216,
    :dragon4 => 33_554_432,
    :dragon5 => 67_108_864,
    :hanbok => 134_217_728,
    :oktoberfest => 268_435_456,
    :summer2 => 536_870_912,
    :max => 536_870_913
  }

  @doc """
  Resolves a constant atom to its rAthena numeric id, or `nil` when unknown.
  """
  @spec id(atom()) :: integer() | nil
  def id(atom) when is_atom(atom), do: Map.get(@ids, atom)
end
