defmodule Aesir.ZoneServer.Content.Npc.Re.Guides.GuidesWoeTe.DefoltyOfKafragarten do
  @moduledoc """
  Transpiled from rAthena re/guides/guides_woe_te.txt:136 (Defolty of Kafragarten).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "alde_gld",
        x: 224,
        y: 185,
        dir: 5,
        sprite: 117,
        name: "Defolty of Kafragarten",
        scope: :renewal
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Defolty]")
    |> mes(
      "Kafragarten is like a mirrored image of Luina, so its structure is exactly the same as that of Luina."
    )
    |> next()
    |> mes("[Defolty]")
    |> mes("You can travel by these warps here.")
    |> mes("You can travel to Kafragarten using warp.")
    |> close()
  end
end
