defmodule Aesir.ZoneServer.Content.Npc.Cities.Veins.Towner do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:19 (Towner#ve1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "veins",
        x: 162,
        y: 34,
        dir: 5,
        sprite: 943,
        name: "Towner",
        unique_name: "Towner#ve1"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Towner]")
    |> mes("I love cacti. They're")
    |> mes("the most beautiful plants")
    |> mes("in the desert. Sometimes,")
    |> mes("they're the only signs of")
    |> mes("life in a barren land.")
    |> next()
    |> mes("[Towner]")
    |> mes("If you feel a stirring")
    |> mes("in your heart when you")
    |> mes("look at a cactus, you")
    |> mes("must appreciate the")
    |> mes("desert's true beauty.")
    |> next()
    |> mes("[Towner]")
    |> mes("Well, I don't know if")
    |> mes("I can find anyone that")
    |> mes("finds the desert as")
    |> mes("wonderful and enchanting")
    |> mes("as I do. It's a pity, really.")
    |> close()
  end
end
