defmodule Aesir.ZoneServer.Content.Npc.Cities.Veins.Towner239135 do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:763 (Towner#ve27).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "ve_in",
        x: 239,
        y: 135,
        dir: 5,
        sprite: 946,
        name: "Towner",
        unique_name: "Towner#ve27"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Towner]")
    |> mes("Isn't the sun so hot?")
    |> mes("Doesn't it make you feel")
    |> mes("so thirsty? Well, you may")
    |> mes("want to consider quenching")
    |> mes("that nasty thirst with liquor!")
    |> next()
    |> mes("[Towner]")
    |> mes("My job is to serve")
    |> mes("delicious, life giving")
    |> mes("liquor to my customers to")
    |> mes("relieve their parched throats.")
    |> mes("Seeing their drunken smiles")
    |> mes("really makes my day~")
    |> close()
  end
end
