defmodule Aesir.ZoneServer.Content.Npc.Cities.Veins.Towner90298 do
  @moduledoc """
  Transpiled from rAthena cities/veins.txt:596 (Towner#ve17).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "ve_in",
        x: 90,
        y: 298,
        dir: 3,
        sprite: 849,
        name: "Towner",
        unique_name: "Towner#ve17"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Towner]")
    |> mes("It's too hot...")
    |> next()
    |> mes("[Towner]")
    |> mes("So sweaty...")
    |> close()
  end
end
