defmodule Aesir.ZoneServer.Content.Npc.Re.Guides.GuidesGeffen.Guide do
  @moduledoc """
  Transpiled from rAthena re/guides/guides_geffen.txt:18 (Guide#01geffen::GuideGeffen).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "geffen",
        x: 203,
        y: 116,
        dir: 4,
        sprite: 705,
        name: "Guide",
        scope: :renewal,
        unique_name: "GuideGeffen"
      },
      %{
        map: "geffen",
        x: 118,
        y: 62,
        dir: 0,
        sprite: 705,
        name: "Guide",
        scope: :renewal,
        unique_name: "Guide#02geffen"
      },
      %{
        map: "geffen",
        x: 36,
        y: 123,
        dir: 6,
        sprite: 705,
        name: "Guide",
        scope: :renewal,
        unique_name: "Guide#03geffen"
      },
      %{
        map: "geffen",
        x: 123,
        y: 203,
        dir: 4,
        sprite: 705,
        name: "Guide",
        scope: :renewal,
        unique_name: "Guide#04geffen"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  alias Aesir.ZoneServer.Script.Todo

  @impl true
  def on_talk(ctx) do
    ctx
    |> cutin("gef_soldier", 2)
    |> mes("[Geffen Guide]")
    |> mes("Welcome to ^8B4513Geffen^000000,")
    |> mes("the City of Magic.")
    |> mes("Do you need help navigating the city?")
    |> todo(:F_Navi, ["[Geffen Guide]"])
    |> next()
    |> loop_1()
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  defp s_l_mark(ctx, args) do
    ctx =
      ctx
      |> mes("[Geffen Guide]")
      |> mes("Let me mark the location of the")
      |> mes(Rathena.concat(Enum.at(args, 0, 0), "^000000"))
      |> mes("on your mini-map.")
      |> mes("Would you like to check any other locations?")

    {ctx, nil}
  end

  defp loop_3(ctx) do
    if Rathena.truthy?(get_local(ctx, :loop, 0)) do
      {ctx, v2} =
        select(ctx, [
          "[ Magic Academy ]",
          "[ Geffen Tower ]",
          "[ Fountain ]",
          "[ Tool Shop ]",
          "[ Buy & Repair Equipment ]",
          "[ Inn ]",
          "[ Tavern ]",
          "[ Christopher's Forge ]",
          "Previous Menu"
        ])

      ctx =
        case v2 do
          1 ->
            ctx
            |> mes("[Geffen Guide]")
            |> mes(
              Rathena.concat(
                "The ",
                Todo.call!(:F_Navi, ["Magic Academy", "geffen,61,180", "^B9062F"])
              )
            )
            |> mes("handles all magic-related affairs,")
            |> mes("including job changes.")
            |> mes("Let me mark its location")
            |> mes("on your mini-map.")
            |> mes("Would you like to check any other locations?")
            |> viewpoint(1, 61, 180, 0, 16_711_680)
            |> next()

          2 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Geffen Tower", "geffen,120,114", "^0000FF"])])

            ctx |> viewpoint(1, 120, 114, 1, 255) |> next()

          3 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Fountain", "geffen,126,48", "^FF5400"])])

            ctx |> viewpoint(1, 126, 48, 2, 16_757_760) |> next()

          4 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Tool Shop", "geffen,44,86", "^006400"])])

            ctx |> viewpoint(1, 44, 86, 3, 11_206_400) |> next()

          5 ->
            ctx
            |> mes("[Geffen Guide]")
            |> mes("If you'd like to ")
            |> mes(
              to_string(
                Todo.call!(:F_Navi, ["Buy or Repair Equipment", "geffen,99,140", "^7F3300"])
              )
            )
            |> mes("then this is the place you'll want to visit.")
            |> mes("Let me mark its location")
            |> mes("on your mini-map.")
            |> mes("Would you like to check any other locations?")
            |> viewpoint(1, 99, 140, 4, 13_789_470)
            |> next()

          6 ->
            {ctx, _} = s_l_mark(ctx, [Todo.call!(:F_Navi, ["Inn", "geffen,172,174", "^800080"])])
            ctx |> viewpoint(1, 172, 174, 5, 14_315_734) |> next()

          7 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Tavern", "geffen,138,138", "^B9062F"])])

            ctx |> viewpoint(1, 138, 138, 6, 16_711_680) |> next()

          8 ->
            ctx
            |> mes("[Geffen Guide]")
            |> mes(
              Rathena.concat(
                Todo.call!(:F_Navi, ["Christopher's Forge", "geffen,182,59", "^0000FF"]),
                " is"
              )
            )
            |> mes("where you can purchase")
            |> mes("Refining materials.")
            |> mes("It used to be the old Blacksmith Guild.")
            |> viewpoint(1, 182, 59, 6, 255)
            |> next()

          9 ->
            ctx = set_local(ctx, :loop, 0)
            ctx

          _ ->
            ctx
        end

      loop_3(ctx)
    else
      ctx
    end
  end

  defp loop_5(ctx) do
    if Rathena.truthy?(get_local(ctx, :loop, 0)) do
      {ctx, v3} =
        select(ctx, [
          "[ Eden Teleport Officer ]",
          "[ Kafra Employee ]",
          "[ Pet Groomer ]",
          "[ Chef Assistant ]",
          "[ Dimensional Arcanist Guide ]",
          "Previous Menu"
        ])

      ctx =
        case v3 do
          1 ->
            {ctx, _} =
              s_l_mark(ctx, [
                Todo.call!(:F_Navi, ["Eden Teleport Officers", "geffen,132,66", "^B9062F"])
              ])

            ctx
            |> viewpoint(1, 61, 180, 7, 16_711_680)
            |> viewpoint(1, 132, 66, 8, 16_711_680)
            |> next()

          2 ->
            {ctx, _} = s_l_mark(ctx, ["^FF5400Kafra Employees^000000"])

            ctx
            |> viewpoint(1, 203, 123, 10, 16_757_760)
            |> viewpoint(1, 120, 62, 11, 16_757_760)
            |> next()

          3 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Pet Groomer", "geffen,193,152", "^006400"])])

            ctx |> viewpoint(1, 193, 152, 12, 11_206_400) |> next()

          4 ->
            {ctx, _} =
              s_l_mark(ctx, [Todo.call!(:F_Navi, ["Chef Assistant", "geffen,196,111", "^7F3300"])])

            ctx |> viewpoint(1, 196, 111, 13, 13_789_470) |> next()

          5 ->
            {ctx, _} =
              s_l_mark(ctx, [
                Todo.call!(:F_Navi, ["Dimensional Arcanist Guide", "geffen,140,196", "^800080"])
              ])

            ctx |> viewpoint(1, 140, 196, 14, 14_315_734) |> next()

          6 ->
            ctx = set_local(ctx, :loop, 0)
            ctx

          _ ->
            ctx
        end

      loop_5(ctx)
    else
      ctx
    end
  end

  defp loop_1(ctx) do
    {ctx, v1} =
      select(ctx, [
        "[ Main Facilities ]",
        "[ Merchants & Helpers ]",
        "Remove Marks from Mini-Map",
        "Cancel"
      ])

    ctx =
      case v1 do
        1 ->
          ctx |> set_local(:loop, 1) |> loop_3()

        2 ->
          ctx |> set_local(:loop, 1) |> loop_5()

        3 ->
          ctx
          |> mes("[Geffen Guide]")
          |> mes("Sure, I'll remove all marks from your mini-map.")
          |> mes("Is there anything else I can do for you?")
          |> viewpoint(2, 1, 1, 0, 16_776_960)
          |> viewpoint(2, 1, 1, 1, 0)
          |> viewpoint(2, 1, 1, 2, 16_711_680)
          |> viewpoint(2, 1, 1, 3, 16_776_960)
          |> viewpoint(2, 1, 1, 4, 16_776_960)
          |> viewpoint(2, 1, 1, 5, 16_776_960)
          |> viewpoint(2, 1, 1, 6, 16_776_960)
          |> viewpoint(2, 1, 1, 7, 16_776_960)
          |> viewpoint(2, 1, 1, 8, 16_776_960)
          |> viewpoint(2, 1, 1, 9, 16_776_960)
          |> viewpoint(2, 1, 1, 10, 16_776_960)
          |> viewpoint(2, 1, 1, 11, 16_776_960)
          |> viewpoint(2, 1, 1, 12, 16_776_960)
          |> viewpoint(2, 1, 1, 13, 16_776_960)
          |> viewpoint(2, 1, 1, 14, 16_776_960)
          |> next()

        4 ->
          ctx =
            ctx
            |> mes("[Geffen Guide]")
            |> mes("Enjoy your stay.")
            |> close()
            |> cutin("gef_soldier", 255)

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    loop_1(ctx)
  end
end
