defmodule Aesir.ZoneServer.Content.Npc.Jobs.M21.Assassin.StandbyRoom do
  @moduledoc """
  Transpiled from rAthena jobs/2-1/assassin.txt:1099 (Standby Room#ASNTEST).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "in_moc_16",
        x: 21,
        y: 165,
        dir: 2,
        sprite: 725,
        name: "Standby Room",
        unique_name: "Standby Room#ASNTEST"
      }
    ]

  @impl true
  def on_event("OnInit", ctx) do
    ev_oninit(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnStartArena", ctx) do
    ev_onstartarena(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnStart", ctx) do
    ev_onstart(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_oninit(ctx) do
    ctx
    |> hideonnpc("Standby Room#ASNTEST")
    |> waitingroom("Standby Room", 10, "Standby Room#ASNTEST::OnStartArena", 1)
    |> enablewaitingroomevent()
  end

  def ev_onstartarena(ctx) do
    ctx = warpwaitingpc(ctx, "in_moc_16", 66, 151)
    {ctx, _} = attachrid(ctx, Enum.at(get_server_temp_var(ctx, "warpwaitingpc", []), 0, 0))

    ctx =
      if get_char_var(ctx, :ASSIN_Q2, 0) < 5 do
        ctx = warpchar(ctx, "in_moc_16", 20, 145, getcharid(ctx, 0))
        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> donpcevent("Beholder#ASNTEST::OnEnable")
    |> donpcevent("Keeper of the Door#ASN::OnDisable")
    |> set_npc_var_of("DisableTraps", "Beholder#ASNTEST", 0)
    |> disablewaitingroomevent()
  end

  def ev_onstart(ctx) do
    enablewaitingroomevent(ctx)
  end
end
