defmodule Aesir.ZoneServer.Content.Npc.Cities.Splendide.LaphineStaff154207 do
  @moduledoc """
  Transpiled from rAthena cities/splendide.txt:718 (Laphine Staff#ep13_2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "spl_in01",
        x: 154,
        y: 207,
        dir: 5,
        sprite: 440,
        name: "Laphine Staff",
        scope: :shared,
        unique_name: "Laphine Staff#ep13_2"
      }
    ]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) > 0 and get_char_var(ctx, :ep13_2_rhea, 0) > 99 do
      ctx =
        ctx
        |> mes("[Laphine Staff]")
        |> mes("his camp serves a military purpose. But we also have a need for bars.")
        |> next()
        |> mes("[Laphine Staff]")
        |> mes("How else can a soldier release stress if not through drinking...")
        |> next()
        |> mes("[Laphine Staff]")
        |> mes(
          "We are here to support the laphine soldier by giving good drinks and entertainment."
        )
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Laphine Staff]")
        |> mes("NorVerNuff Ee Re!")
        |> mes("remuDurOdes Mu AshFus~!")
        |> mes("OdesTalWeh Ur??? ")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
