defmodule Aesir.ZoneServer.Content.Npc.Cities.Splendide.SplendideSoldier20176 do
  @moduledoc """
  Transpiled from rAthena cities/splendide.txt:350 (Splendide Soldier#tre2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "splendide",
        x: 201,
        y: 76,
        dir: 3,
        sprite: 461,
        name: "Splendide Soldier",
        scope: :shared,
        unique_name: "Splendide Soldier#tre2"
      }
    ]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) == 1 and get_char_var(ctx, :ep13_2_rhea, 0) == 100 do
      ctx =
        ctx
        |> mes("[Splendide Soldier]")
        |> mes("This is Splendide, the garrison base of the Laphine.")
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Splendide Soldier]")
        |> mes("SeAshLu Di YurDiebTing Ee VeModTur No NuffLarsVa No ")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
