defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Malaya.InnKeeper do
  @moduledoc """
  Transpiled from rAthena re/cities/malaya.txt:95 (Inn Keeper#ma).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "ma_in01",
        x: 30,
        y: 94,
        dir: 4,
        sprite: 583,
        name: "Inn Keeper",
        unique_name: "Inn Keeper#ma"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      if get_char_var(ctx, :malaya_hi, 0) < 10 do
        ctx =
          ctx
          |> mes("[Inn Keeper]")
          |> mes("Oh my! Visiting?")
          |> mes(
            "What bad timing. The village is a bit unorganized at the moment so I'm actually closed. Sorry."
          )
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          if get_char_var(ctx, :malaya_hi, 0) < 20 do
            ctx
            |> mes("[Inn Keeper]")
            |> mes(
              "So you are the adventurer villagers are talking about? I reopened my inn thanks to you. Thank you."
            )
            |> next()
          else
            ctx
            |> mes("[Inn Keeper]")
            |> mes("Welcome.")
            |> mes("This is Port Malaya's best inn, 'Cabin in the City'.")
            |> next()
          end

        ctx
      end

    {ctx, v1} =
      ctx
      |> mes("[Inn Keeper]")
      |> mes("Come for a rest? Lodging will be 5,000 Zeny.")
      |> next()
      |> select(["Store.", "Lodge. - 5,000z", "Cancel."])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Inn Keeper]")
            |> mes("Successfully stored. See you next time.")
            |> savepoint("ma_in01", 43, 98)
            |> close()

          throw({:script_end, ctx})

        2 ->
          ctx =
            if zeny(ctx) < 5000 do
              ctx =
                ctx
                |> mes("[Inn Keeper]")
                |> mes("Sorry. I think you are a bit short.")
                |> close()

              throw({:script_end, ctx})
            else
              ctx
            end

          ctx =
            ctx
            |> mes("[Inn Keeper]")
            |> mes("Hope you enjoy your stay.")
            |> close()
            |> pay_zeny(5000)
            |> percent_heal(hp: 100, sp: 100)
            |> warp("ma_in01", 43, 98)

          throw({:script_end, ctx})

        3 ->
          ctx = close(ctx)
          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
