defmodule Aesir.ZoneServer.Content.Npc.Cities.Einbech.Gushenmu do
  @moduledoc """
  Transpiled from rAthena cities/einbech.txt:168 (Gushenmu#ein).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "einbech",
        x: 105,
        y: 218,
        dir: 5,
        sprite: 848,
        name: "Gushenmu",
        unique_name: "Gushenmu#ein"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Gushenmu]")
    |> mes("I've lived here a long time")
    |> mes("and, believe it or not, things")
    |> mes("weren't as tough in the past")
    |> mes("as they are right now.")
    |> next()
    |> mes("[Gushenmu]")
    |> mes("For lots of different reasons,")
    |> mes("the work is more dangerous")
    |> mes("and we're running real low on")
    |> mes("manpower. And the factories in")
    |> mes("Einbroch make so much smog,")
    |> mes("we can't even see sunlight here.")
    |> next()
    |> mes("[Gushenmu]")
    |> mes("The sad reality of mining")
    |> mes("life right now is that we")
    |> mes("wake up, go to work, and at")
    |> mes("the end of the day, some of us")
    |> mes("are injured while a few others never come to work the next day.")
    |> next()
    |> mes("[Gushenmu]")
    |> mes("And as Einbech and Einbroch")
    |> mes("have grown, I hear more and")
    |> mes("more rumors that unfamiliar")
    |> mes("monsters are beginning to")
    |> mes("swarm outside of town. This")
    |> mes("is really Einbech's worst time...")
    |> close()
  end
end
