defmodule Aesir.ZoneServer.Content.Npc.Cities.Einbech.TrainStationStaff do
  @moduledoc """
  Transpiled from rAthena cities/einbech.txt:200 (Train Station Staff#ein3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "einbech",
        x: 39,
        y: 215,
        dir: 5,
        sprite: 852,
        name: "Train Station Staff",
        scope: :shared,
        unique_name: "Train Station Staff#ein3"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Staff]")
      |> mes("Welcome to")
      |> mes("the Train Station.")
      |> mes("The fare to take the")
      |> mes("train to Einbroch is")
      |> mes("200 zeny. Would")
      |> mes("you like to ride?")
      |> next()
      |> select(["Yes.", "No."])

    ctx =
      case v1 do
        1 ->
          if zeny(ctx) > 199 do
            ctx =
              ctx
              |> mes("[Staff]")
              |> mes("Thank you and")
              |> mes("we hope you enjoy")
              |> mes("the ride. All aboard!")
              |> close()
              |> pay_zeny(200)
              |> warp("einbroch", 226, 276)

            throw({:script_end, ctx})
          else
            ctx =
              ctx
              |> mes("[Staff]")
              |> mes("I'm sorry,")
              |> mes("but you don't")
              |> mes("have enough zeny")
              |> mes("to pay the train fare.")
              |> close()

            throw({:script_end, ctx})
          end

        2 ->
          ctx =
            ctx
            |> mes("[Staff]")
            |> mes("Please enjoy")
            |> mes("your stay here")
            |> mes("in Einbech.")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
