defmodule Aesir.ZoneServer.Content.Npc.Cities.Comodo.Daeguro do
  @moduledoc """
  Transpiled from rAthena cities/comodo.txt:282 (Daeguro#cmd).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "cmd_fild04",
        x: 267,
        y: 137,
        dir: 4,
        sprite: 703,
        name: "Daeguro",
        scope: :shared,
        unique_name: "Daeguro#cmd"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Daeguro]")
    |> mes("I love playing in")
    |> mes("the sand-- it's so soft")
    |> mes("and clean and pretty!")
    |> mes("But when I grow up,")
    |> mes("I wanna go to Alberta")
    |> mes("and see everything I can!")
    |> close()
  end
end
