defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22.Alchemist.AlchemistGuildsman do
  @moduledoc """
  Transpiled from rAthena jobs/2-2/alchemist.txt:23 (Alchemist Guildsman#am).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "alde_alche",
        x: 27,
        y: 185,
        dir: 5,
        sprite: 744,
        name: "Alchemist Guildsman",
        unique_name: "Alchemist Guildsman#am"
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Parmy Gianino]")

    ctx =
      if get_char_var(ctx, :Upper, 0) == 1 do
        ctx =
          ctx
          |> mes("Welcome to the")
          |> mes("Alchemist Unio--")
          |> mes("I-Impossible! How c-can")
          |> mes("something like this happen?")
          |> next()
          |> mes("[Parmy Gianino]")
          |> mes("Wait, wait...")
          |> mes("I'm sorry. I was confused,")
          |> mes("that's all. You look just like")
          |> mes("someone I used to know. ")
          |> mes("Still, I get this weird")
          |> mes("feeling about you...")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx =
      if base_job(ctx) != :merchant do
        ctx =
          if base_job(ctx) == :alchemist do
            ctx =
              ctx
              |> mes(Rathena.concat(Rathena.concat("Welcome, ", char_name(ctx, 0)), "."))
              |> mes("The Alchemist Union")
              |> mes("is busy today, like always.")
              |> next()
              |> mes("[Parmy Gianino]")
              |> mes("Everyone is busy with their")
              |> mes(
                "own research, but recently, some headway has been made in the field of biotechnology."
              )
              |> next()
              |> mes("[Parmy Gianino]")
              |> mes(
                "Everyone is hoping that the biotechnological studies will yield positive results. Speaking of which, I wonder how the Alchemists working on artificial life are doing..."
              )
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              if base_class(ctx) == :novice do
                ctx =
                  ctx
                  |> mes("Welcome to the")
                  |> mes("Alchemist Union.")
                  |> mes("We are recruiting")
                  |> mes("talented people")
                  |> mes("with novel ideas.")
                  |> next()
                  |> mes("[Parmy Gianino]")
                  |> mes(
                    "If you're interested in working with chemistry, visit us later when you become more knowledgable."
                  )
                  |> next()
                  |> mes("[Parmy Gianino]")
                  |> mes("Just one thing:")
                  |> mes("You've got to have")
                  |> mes("knowledge of items")
                  |> mes("as a Merchant first.")
                  |> close()

                throw({:script_end, ctx})
              else
                ctx
              end

            ctx
          end

        ctx =
          ctx
          |> mes("Welcome to the")
          |> mes("Alchemist Union.")
          |> mes("We are recruiting")
          |> mes("talented people")
          |> mes("with novel ideas.")
          |> next()
          |> mes("[Parmy Gianino]")
          |> mes(
            "If you know any exceptional Merchants, by all means, please refer them to us. Those types of people tend to have a talent for Alchemy and experimentation~"
          )
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx =
      if get_char_var(ctx, :ALCH_Q, 0) == 0 do
        {ctx, v1} =
          ctx
          |> mes("Welcome to the")
          |> mes("Alchemist Union.")
          |> mes("How may I help you?")
          |> next()
          |> select([
            "I would like to learn about Alchemists.",
            "I want to become an Alchemist.",
            "Nothing."
          ])

        ctx =
          case v1 do
            1 ->
              ctx =
                ctx
                |> mes("[Parmy Gianino]")
                |> mes(
                  "Alchemists study and create new substances and items out of existing materials. Our knowledge allows us to change the properties of chemicals at the atomic level."
                )
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("Most people think our final goal")
                |> mes(
                  "is to create gold, but that's not the entire truth. We also want to create things like medicines"
                )
                |> mes("and new materials.")
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("A few of us research the")
                |> mes(
                  "creation of life, although many of us consider that god's territory. That field is so complex, most of us deal with slightly less complicated projects anyway."
                )
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes(
                  "If you are interested in becoming an Alchemist, I recommend that you first get a lot of experience as a Merchant. Being a Merchant is a great opportunity to learn about materials as you deal with them."
                )
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("Whether or not you try to become")
                |> mes(
                  "an Alchemist is your decision. The road to becoming an Alchemist is very challenging, and you'll need to focus on experimentation and research, instead of commerce."
                )
                |> close()

              throw({:script_end, ctx})

            2 ->
              {ctx, v2} =
                ctx
                |> mes("[Parmy Gianino]")
                |> mes("Is that so?")
                |> mes("Nice to meet you.")
                |> mes("My name is Parmy Gianino")
                |> mes("of the Alchemist Union.")
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("If you join our Union and")
                |> mes("complete the training, you")
                |> mes("will be officially recognized")
                |> mes("as an Alchemist and be able")
                |> mes("to contribute to our research.")
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("But we don't accept everyone.")
                |> mes("You must have a lot of tenacity")
                |> mes("and sincere devotion in exploring")
                |> mes("the various fields of science.")
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("There are a couple")
                |> mes("of requirements to join")
                |> mes("the Alchemist Union, but")
                |> mes("we'll discuss that")
                |> mes("after you apply.")
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes("Well then, would")
                |> mes("you like to apply")
                |> mes("for registration?")
                |> next()
                |> select(["I would like to apply.", "I'll do it later."])

              ctx =
                if v2 == 1 do
                  ctx =
                    if job_level(ctx) < 40 do
                      ctx =
                        ctx
                        |> mes("[Parmy Gianino]")
                        |> mes("Hmmm...")
                        |> mes("Just a moment.")
                        |> mes("I'm sorry to say that")
                        |> mes("you're not experienced")
                        |> mes("enough as a Merchant to")
                        |> mes("join us right now.")
                        |> next()
                        |> mes("[Parmy Gianino]")
                        |> mes("You must be at least")
                        |> mes("^551A8BJob Level 40^000000 to become")
                        |> mes("an Alchemist. Come back")
                        |> mes("later when you meet the")
                        |> mes("Job Level requirement, okay?")
                        |> close()

                      throw({:script_end, ctx})
                    else
                      ctx
                    end

                  ctx =
                    ctx
                    |> mes("[Parmy Gianino]")
                    |> mes(
                      "Alright, your application has been accepted. Now, you must pay the 50,000 Zeny application fee and bring some items before you can begin your formal training."
                    )
                    |> next()
                    |> mes("[Parmy Gianino]")
                    |> mes(
                      "But if you bring an ^551A8BOld Magic Book^000000 and ^551A8BHammer of Blacksmith^000000,"
                    )
                    |> mes("we will accept that as a substitute for the item requirement.")
                    |> next()
                    |> mes("[Parmy Gianino]")
                    |> mes("Now...")
                    |> mes("Please sign")
                    |> mes("the application.")
                    |> next()

                  {ctx, _} = select(ctx, String.split(to_string(char_name(ctx, 0)), ":"))

                  ctx =
                    ctx
                    |> mes("[Parmy Gianino]")
                    |> mes("Good, good. Now, if you have")
                    |> mes(
                      "the Zeny for your application fee ready, I will tell you which items you will need to bring. Now, pay attention."
                    )
                    |> next()

                  ctx =
                    if zeny(ctx) < 50000 do
                      ctx =
                        ctx
                        |> mes("[Parmy Gianino]")
                        |> mes("Uh oh. You don't")
                        |> mes("seem to have enough Zeny.")
                        |> mes(
                          "Come back to me when you have 50,000 Zeny, otherwise we can't process your application."
                        )
                        |> close()

                      throw({:script_end, ctx})
                    else
                      ctx
                    end

                  ctx = ctx |> pay_zeny(50000) |> mes("[Parmy Gianino]") |> mes("Let's see.")

                  ctx =
                    ctx |> mes(Rathena.concat("", char_name(ctx, 0))) |> mes("needs to bring...")

                  v3 = Enum.random(1..3)

                  ctx =
                    case v3 do
                      1 ->
                        ctx
                        |> set_char_var(:ALCH_Q, 1)
                        |> setquest(2028)
                        |> mes("^551A8B7 Berserk Potions^000000.")

                      2 ->
                        ctx
                        |> set_char_var(:ALCH_Q, 2)
                        |> setquest(2029)
                        |> mes("^551A8B100 Mini Furnaces^000000.")

                      3 ->
                        ctx =
                          ctx
                          |> set_char_var(:ALCH_Q, 3)
                          |> setquest(2030)
                          |> mes("^551A8B7,500 Fire Arrows^000000.")

                        ctx

                      _ ->
                        ctx
                    end

                  ctx =
                    ctx
                    |> next()
                    |> mes("[Parmy Gianino]")
                    |> mes("Once you've gathered")
                    |> mes("those items, come back")
                    |> mes("to me and your training")
                    |> mes("as an Alchemist will begin.")
                    |> mes("See you soon~")
                    |> close()

                  throw({:script_end, ctx})
                else
                  ctx
                end

              ctx =
                ctx
                |> mes("[Parmy Gianino]")
                |> mes("Talented Merchants")
                |> mes("are always welcome here.")
                |> mes("Please come back soon.")
                |> close()

              throw({:script_end, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Parmy Gianino]")
                |> mes("Umm...")
                |> mes("Please let me know")
                |> mes("if you need anything.")
                |> close()

              throw({:script_end, ctx})

            _ ->
              ctx
          end

        ctx
      else
        if get_char_var(ctx, :ALCH_Q, 0) >= 1 and get_char_var(ctx, :ALCH_Q, 0) <= 3 do
          ctx =
            if count_item(ctx, 1006) > 0 and count_item(ctx, 1005) > 0 do
              ctx =
                ctx
                |> mes("Well now~!")
                |> mes("You've brought an")
                |> mes("Old Magic Book and")
                |> mes("a Hammer of Blacksmith.")
                |> mes("We'll put these items")
                |> mes("to good use.")
                |> next()
                |> delitem(1006, 1)
                |> delitem(1005, 1)
                |> mes("[Parmy Gianino]")
                |> mes("Okay, now you need to learn")
                |> mes(
                  "the basics to being an Alchemist and learn the procedures for mixing chemicals and medicines."
                )
                |> set_char_var(:ALCH_Q, 4)

              ctx =
                if checkquest(ctx, 2028) != -1 do
                  changequest(ctx, 2028, 2031)
                else
                  ctx =
                    if checkquest(ctx, 2029) != -1 do
                      changequest(ctx, 2029, 2031)
                    else
                      changequest(ctx, 2030, 2031)
                    end

                  ctx
                end

              ctx =
                ctx
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes(
                  "But before all of that, you need to speak to Raspuchin. I'm not really sure what you'll be talking about with him..."
                )
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes(
                  "It shouldn't be anything extraordinary, but you're still required to speak to Raspuchin, since apparently he's a part of the Alchemist selection process."
                )
                |> close()

              throw({:script_end, ctx})
            else
              ctx
            end

          v4 = get_char_var(ctx, :ALCH_Q, 0)

          ctx =
            case v4 do
              1 ->
                set_local(ctx, :items, [657, 7])

              2 ->
                set_local(ctx, :items, [612, 100])

              3 ->
                ctx = set_local(ctx, :items, [1752, 7500])
                ctx

              _ ->
                ctx
            end

          ctx =
            if count_item(ctx, Enum.at(get_local(ctx, :items, []), 0, 0)) >=
                 Enum.at(get_local(ctx, :items, []), 1, 0) do
              ctx =
                ctx
                |> mes("Seems like")
                |> mes("you're all ready.")
                |> mes("The Union will put")
                |> mes("these items to good use.")
                |> next()

              ctx =
                ctx
                |> delitem(
                  Enum.at(get_local(ctx, :items, []), 0, 0),
                  Enum.at(get_local(ctx, :items, []), 1, 0)
                )
                |> mes("[Parmy Gianino]")
                |> mes("Okay, now you need to learn")
                |> mes(
                  "the basics to being an Alchemist and learn the procedures for mixing chemicals and medicines."
                )
                |> set_char_var(:ALCH_Q, 4)

              ctx =
                if checkquest(ctx, 2028) != -1 do
                  changequest(ctx, 2028, 2031)
                else
                  ctx =
                    if checkquest(ctx, 2029) != -1 do
                      changequest(ctx, 2029, 2031)
                    else
                      changequest(ctx, 2030, 2031)
                    end

                  ctx
                end

              ctx =
                ctx
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes(
                  "But before all of that, you need to speak to Raspuchin. I'm not really sure what you'll be talking about with him..."
                )
                |> next()
                |> mes("[Parmy Gianino]")
                |> mes(
                  "It shouldn't be anything extraordinary, but you're still required to speak to Raspuchin, since apparently he's a part of the Alchemist selection process."
                )
                |> close()

              throw({:script_end, ctx})
            else
              ctx
            end

          ctx =
            ctx |> mes("Aren't you ready?") |> mes("Like I said before,") |> mes("you must bring")

          {ctx, v5} =
            Aesir.ZoneServer.Content.Npc.Functions.FInsertplural.call(ctx, [
              Enum.at(get_local(ctx, :items, []), 1, 0),
              Rathena.getitemname(Enum.at(get_local(ctx, :items, []), 0, 0))
            ])

          ctx =
            ctx
            |> mes(Rathena.concat(Rathena.concat("^551A8B", v5), "^000000."))
            |> next()
            |> mes("[Parmy Gianino]")
            |> mes("Come back when you")
            |> mes("have prepared the")
            |> mes("required items.")
            |> close()

          throw({:script_end, ctx})
        else
          if get_char_var(ctx, :ALCH_Q, 0) == 4 do
            ctx =
              ctx
              |> mes("Go and talk to")
              |> mes("Mr. Raspuchin.")
              |> mes("He's involved in the")
              |> mes("Alchemist selection process, whatever that might mean.")
              |> next()
              |> mes("[Parmy Gianino]")
              |> mes("Hopefully, it")
              |> mes("won't be too much of")
              |> mes("a problem. I guess he'll just interview you, and ask you")
              |> mes("some simple questions.")
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              ctx
              |> mes("Ah, I'm sorry, but")
              |> mes("I'm busy right now~")
              |> next()
              |> mes("[Parmy Gianino]")
              |> mes("Why don't you ask")
              |> mes("someone else if you're")
              |> mes("not sure who to visit")
              |> mes("next? Good luck~")
              |> close()

            throw({:script_end, ctx})
          end
        end
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
