defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22.Alchemist.FastidiousAlchemist do
  @moduledoc """
  Transpiled from rAthena jobs/2-2/alchemist.txt:326 (Fastidious Alchemist#am).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "alde_alche",
        x: 175,
        y: 107,
        dir: 3,
        sprite: 749,
        name: "Fastidious Alchemist",
        scope: :shared,
        unique_name: "Fastidious Alchemist#am"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Raspuchin Gregory]")

    ctx =
      if base_job(ctx) != :merchant do
        if base_job(ctx) == :alchemist do
          ctx =
            ctx
            |> mes("Heeheehee")
            |> mes("keheheh~!")
            |> mes("Eh? What do you want?!")
            |> next()
            |> mes("[Raspuchin Gregory]")
            |> mes(
              "You're not here to steal my experimental results or plagiarize my work, are you? How dare you consider intellectual theft!"
            )
            |> next()
            |> mes("[Raspuchin Gregory]")
            |> mes("You're not, are you?")
            |> mes("Well, as a colleague,")
            |> mes("let me just warn you")
            |> mes("that such tricks aren't")
            |> mes("tolerated here in the")
            |> mes("Alchemist Union!")
            |> close()

          throw({:script_end, ctx})
        else
          if base_class(ctx) == :novice do
            ctx =
              ctx
              |> mes("Heeheehee")
              |> mes("keheheh~!")
              |> mes("How cute, you've come")
              |> mes("all this way just to play...")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes("I'll let you")
              |> mes("go this time...")
              |> mes("But next time, don't")
              |> mes("expect to leave so easily...")
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              ctx
              |> mes("What is it?!")
              |> mes("You're curious as")
              |> mes("to what I'm doing?")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes("Heehee")
              |> mes("keheheh~!")
              |> mes("Why, I'm busy")
              |> mes("researching,")
              |> mes("of course!")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes("Once this")
              |> mes("potion is complete...")
              |> mes("You can use it to take")
              |> mes("over an entire nation!")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes("Hee hee hee!")
              |> mes("Something this")
              |> mes("dangerous has to")
              |> mes("be kept a secret!")
              |> mes("Understand?")
              |> close()

            throw({:script_end, ctx})
          end
        end
      else
        ctx
      end

    ctx =
      if get_char_var(ctx, :ALCH_Q, 0) == 0 do
        ctx =
          ctx
          |> mes("Heeheehee")
          |> mes("keheheh~!")
          |> mes("What do you")
          |> mes("want, kid?")
          |> next()
          |> mes("[Raspuchin Gregory]")
          |> mes(
            "A Merchant should go and set up shop and vend items. Why are you wandering in a place like this?"
          )
          |> next()
          |> mes("[Raspuchin Gregory]")
          |> mes("Heheheh~!")
          |> mes("Go vend somwhere else!")
          |> mes("And leave me to my")
          |> mes("dark enterprise!")
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          if get_char_var(ctx, :ALCH_Q, 0) >= 1 and get_char_var(ctx, :ALCH_Q, 0) <= 3 do
            ctx =
              ctx
              |> mes("Heeheehee")
              |> mes("keheheh~!")
              |> mes("What do you")
              |> mes("want, kid?")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes("What...?")
              |> mes("Learn Alchemy?!")
              |> mes("Don't even speak")
              |> mes("such nonsense!")
              |> next()
              |> mes("[Raspuchin Gregory]")
              |> mes(
                "Even if you tried studying for a thousand years, maybe even more, it'd be useless to you! Forget about it and just worry about your store!"
              )
              |> close()

            throw({:script_end, ctx})
          else
            ctx =
              if get_char_var(ctx, :ALCH_Q, 0) == 4 or get_char_var(ctx, :ALCH_Q, 0) == 5 do
                ctx =
                  if get_char_var(ctx, :ALCH_Q, 0) == 4 do
                    ctx =
                      ctx
                      |> mes("Heeheehee")
                      |> mes("keheheh~!")
                      |> mes("What do you")
                      |> mes("want, kid?")
                      |> next()
                      |> mes("[Raspuchin Gregory]")
                      |> mes("What...?")
                      |> mes("Join the Union!?")
                      |> mes("I don't like it...")
                      |> mes("I just don't...!")
                      |> next()
                      |> mes("[Raspuchin Gregory]")
                      |> mes("Nowadays, anyone thinks they can")
                      |> mes(
                        "be Alchemists just by knowing how to mix a few herbs. That's why my interview is necessary."
                      )
                      |> next()
                      |> mes("[Raspuchin Gregory]")
                      |> mes("Heeheehee")
                      |> mes("keheheh~!")
                      |> mes("I plan on weeding out all the dumb and incompetent, and chase them")
                      |> mes("all away! We don't need morons!")
                      |> next()

                    ctx =
                      if job_level(ctx) == 50 do
                        ctx =
                          ctx
                          |> mes("[Raspuchin Gregory]")
                          |> mes("Wait...")
                          |> mes("Maybe I've")
                          |> mes("misjudged you.")

                        ctx =
                          if sex(ctx) == get_char_var(ctx, :SEX_MALE, 0) do
                            ctx
                            |> mes("You might be a pretty boy,")
                            |> mes("but I can tell you're smart")
                            |> mes("from your eyes.")
                          else
                            ctx
                            |> mes("Huh. You're a cutie alright,")
                            |> mes("but I can tell you've got brains.")
                          end

                        ctx =
                          ctx
                          |> next()
                          |> mes("[Raspuchin Gregory]")
                          |> mes("You're not just some stupid kid.")
                          |> mes(
                            "I can tell youve gone through some rough times as a Merchant. Excellent. Keh heh heh~"
                          )
                          |> next()
                          |> mes("[Raspuchin Gregory]")
                          |> mes(
                            "Fine, just so we don't insult each other's intelligence, I'll just let you pass the interview."
                          )
                          |> next()
                          |> mes("[Raspuchin Gregory]")
                          |> mes(
                            "So hurry up, become an Alchemist, do some good research, and you might turn out to be of some help to me. Hahahahahaha~!"
                          )
                          |> next()
                          |> mes("[Raspuchin Gregory]")
                          |> mes("Now go to Darwin!")
                          |> mes("He'll teach you how to do the experiments. Just tell him that")
                          |> mes("I sent you.")
                          |> set_char_var(:ALCH_Q, 6)
                          |> changequest(2031, 2032)
                          |> close()

                        throw({:script_end, ctx})
                      else
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("Surprised, are you?")
                        |> mes("Keheheh~ If you thought")
                        |> mes("becoming an Alchemist was")
                        |> mes("just a matter of changing")
                        |> mes("your clothes, then you're")
                        |> mes("sadly mistaken.")
                        |> next()
                        |> mes("[Raspuchin Gregory]")
                        |> mes("Now, try solving")
                        |> mes("all these problems.")
                        |> mes("Let's see how smart")
                        |> mes("really are.")
                      end

                    ctx
                  else
                    ctx =
                      if get_char_var(ctx, :ALCH_Q, 0) == 5 do
                        ctx
                        |> mes("What...?!")
                        |> mes("You want to take")
                        |> mes("the test again?!")
                        |> mes("I thought I told")
                        |> mes("you to leave!")
                        |> next()
                        |> mes("[Raspuchin Gregory]")
                        |> mes("I don't like it...")
                        |> mes("I don't like this!")
                        |> next()
                        |> mes("[Raspuchin Gregory]")
                        |> mes("Fine...")
                        |> mes("I'll try to overlook your pitiful performance last time and give")
                        |> mes("you another chance. Don't screw")
                        |> mes("up again, got it?")
                        |> next()
                        |> mes("[Raspuchin Gregory]")
                        |> mes("Now then,")
                        |> mes("give me all the")
                        |> mes("^551A8Bright^000000 answers")
                        |> mes("this time.")
                      else
                        ctx
                      end

                    ctx
                  end

                ctx = next(ctx)
                v32 = Enum.random(1..3)

                ctx =
                  case v32 do
                    1 ->
                      {ctx, v1} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("12 + 23 + 34 + 45 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v1)

                      ctx =
                        if get_local(ctx, :input, 0) != 114 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v2} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("1000 - 36 - 227 - 348 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v2)

                      ctx =
                        if get_local(ctx, :input, 0) != 389 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v3} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("14 * 17 * 3 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v3)

                      ctx =
                        if get_local(ctx, :input, 0) != 714 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v4} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("9765 / 3 / 5 / 7 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v4)

                      ctx =
                        if get_local(ctx, :input, 0) != 93 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v5} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(47 * 28) - (1376 / 4) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v5)

                      ctx =
                        if get_local(ctx, :input, 0) != 972 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v6} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(2646 / 7) + (13 * 28) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v6)

                      ctx =
                        if get_local(ctx, :input, 0) != 742 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v7} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("How much do")
                        |> mes("12 Red Potions,")
                        |> mes("1 Butterfly Wing")
                        |> mes("and 5 Fly Wings cost")
                        |> mes("after a 24 % discount?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v7)

                      ctx =
                        if get_local(ctx, :input, 0) != 909 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v8} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total weight of")
                        |> mes("3 Scimiters, 2 Helms")
                        |> mes("and 1 Long Coat?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v8)

                      ctx =
                        if get_local(ctx, :input, 0) != 450 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v9} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total defense of")
                        |> mes("a Biretta, Mantle,")
                        |> mes("Opera Mask, Ribbon,")
                        |> mes("Muffler, Boots, and")
                        |> mes("Ear Muffs?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v9)

                      ctx =
                        if get_local(ctx, :input, 0) != 20 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v10} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("If you buy 5 Helms")
                        |> mes("with a 24 % discount")
                        |> mes("and sell it at 20")
                        |> mes("how much profit")
                        |> mes("do you earn?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v10)

                      ctx =
                        if get_local(ctx, :input, 0) != 8800 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      ctx

                    2 ->
                      {ctx, v11} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("13 + 25 + 37 + 48 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v11)

                      ctx =
                        if get_local(ctx, :input, 0) != 123 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v12} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("1000 - 58 - 214 - 416 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v12)

                      ctx =
                        if get_local(ctx, :input, 0) != 312 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v13} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("12 * 24 * 3 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v13)

                      ctx =
                        if get_local(ctx, :input, 0) != 864 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v14} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("10530 / 3 / 5 / 2 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v14)

                      ctx =
                        if get_local(ctx, :input, 0) != 351 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v15} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(35 * 19) - (1792 / 7) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v15)

                      ctx =
                        if get_local(ctx, :input, 0) != 409 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v16} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(2368 / 8) + (24 * 17) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v16)

                      ctx =
                        if get_local(ctx, :input, 0) != 704 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v17} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(2646 / 7) + (13 * 28) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v17)

                      ctx =
                        if get_local(ctx, :input, 0) != 742 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v18} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total price of")
                        |> mes("15 Green Potions,")
                        |> mes("6 Magnifiers and")
                        |> mes("4 Traps after")
                        |> mes("a 24 % discount?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v18)

                      ctx =
                        if get_local(ctx, :input, 0) != 934 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v19} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total weight of")
                        |> mes("3 Ring Pommel Sabers,")
                        |> mes("4 Caps, and 2 Boots?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v19)

                      ctx =
                        if get_local(ctx, :input, 0) != 550 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v20} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total defense of")
                        |> mes("a Buckler, Long Coat,")
                        |> mes("Gas Mask, Big Ribbon,")
                        |> mes("Cute Ribbon, Sakkat,")
                        |> mes("and Glasses?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v20)

                      ctx =
                        if get_local(ctx, :input, 0) != 16 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v21} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("How much profit do you")
                        |> mes("make if you buy Tights")
                        |> mes("at a 24 % discount and")
                        |> mes("sell it at 20 % of")
                        |> mes("the normal price?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v21)

                      ctx =
                        if get_local(ctx, :input, 0) != 8520 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      ctx

                    3 ->
                      {ctx, v22} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("12 + 23 + 34 + 45 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v22)

                      ctx =
                        if get_local(ctx, :input, 0) != 114 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v23} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("1000 - 58 - 214 - 416 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v23)

                      ctx =
                        if get_local(ctx, :input, 0) != 312 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v24} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("14 * 17 * 3 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v24)

                      ctx =
                        if get_local(ctx, :input, 0) != 714 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v25} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("10530 / 3 / 5 / 2 = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v25)

                      ctx =
                        if get_local(ctx, :input, 0) != 351 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v26} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(47 * 28) - (1376 / 4) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v26)

                      ctx =
                        if get_local(ctx, :input, 0) != 972 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v27} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("(2646 / 7) + (13 * 28) = ?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v27)

                      ctx =
                        if get_local(ctx, :input, 0) != 742 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v28} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total cost of")
                        |> mes("6 Red Potions,")
                        |> mes("7 Green Potions,")
                        |> mes("and 8 Fly Wings")
                        |> mes("after a 24 % discount?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v28)

                      ctx =
                        if get_local(ctx, :input, 0) != 798 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v29} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total weight of")
                        |> mes("2 Ring Pommel Sabers,")
                        |> mes("3 Caps, and 3 boots?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v29)

                      ctx =
                        if get_local(ctx, :input, 0) != 480 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v30} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("What is the")
                        |> mes("total defense of")
                        |> mes(
                          "a Mirror Shield, Mr. Smile, Leather Jacket, Silk Robe, Wedding Veil, Muffler, and Eye Patch?"
                        )
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v30)

                      ctx =
                        if get_local(ctx, :input, 0) != 12 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      {ctx, v31} =
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("If you buy 4 Padded Armors")
                        |> mes("at a 24% discount and sell")
                        |> mes("them at 20% of the original")
                        |> mes("price, how much profit would")
                        |> mes("you make from this sale?")
                        |> next()
                        |> input(:int)

                      ctx = set_local(ctx, :input, v31)

                      ctx =
                        if get_local(ctx, :input, 0) != 7680 do
                          set_local(ctx, :w_point, get_local(ctx, :w_point, 0) + 1)
                        else
                          ctx
                        end

                      ctx

                    _ ->
                      ctx
                  end

                ctx =
                  if get_local(ctx, :w_point, 0) == 0 do
                    ctx
                    |> mes("[Raspuchin Gregory]")
                    |> mes("Ooh...")
                    |> mes("Excellent! Great!")
                    |> mes("You got them all correct!?")
                    |> mes("Keheheh, I have no choice but to acknowledge you...")
                    |> next()
                  else
                    ctx =
                      if get_local(ctx, :w_point, 0) == 1 do
                        ctx
                        |> mes("[Raspuchin Gregory]")
                        |> mes("You got one wrong!")
                        |> mes("But I'll let it slide.")
                        |> mes("You pass the interview!")
                        |> next()
                      else
                        ctx =
                          if get_local(ctx, :w_point, 0) == 2 and
                               get_char_var(ctx, :ALCH_Q, 0) == 5 do
                            ctx
                            |> mes("[Raspuchin Gregory]")
                            |> mes("You've got serious")
                            |> mes("weaknesses in math,")
                            |> mes("but I'll let you go this time...")
                            |> next()
                          else
                            ctx =
                              ctx
                              |> set_char_var(:ALCH_Q, 5)
                              |> mes("[Raspuchin Gregory]")
                              |> mes("Keheheh! Idiot!")
                              |> mes("Just listening to your")
                              |> mes("answers is making me feel")
                              |> mes("stupider! You might as well")
                              |> mes("have got them all wrong!")
                              |> next()
                              |> mes("[Raspuchin Gregory]")
                              |> mes("How can a person that")
                              |> mes("can't even answer all of")
                              |> mes("these simple questions think")
                              |> mes("of becoming an Alchemist?!")
                              |> next()
                              |> mes("[Raspuchin Gregory]")
                              |> mes("Hm...?")
                              |> mes("Did you get")
                              |> mes("any right?")
                              |> next()
                              |> mes("[Raspuchin Gregory]")
                              |> mes(
                                "Fool! Even if you make one little mistake, everything goes wrong"
                              )
                              |> mes("in Alchemy! Now get out of here!")
                              |> mes("You make me sick!")
                              |> close()

                            throw({:script_end, ctx})
                          end

                        ctx
                      end

                    ctx
                  end

                ctx =
                  ctx
                  |> mes("[Raspuchin Gregory]")
                  |> mes(
                    "So hurry up, become an Alchemist, do some good research, and you might turn out to be of some help to me. Hahahahahaha~!"
                  )
                  |> next()
                  |> mes("[Raspuchin Gregory]")
                  |> mes("Now go to Darwin!")
                  |> mes("He'll teach you how to do the experiments. Just tell him that")
                  |> mes("I sent you.")
                  |> set_char_var(:ALCH_Q, 6)
                  |> changequest(2031, 2032)
                  |> close()

                throw({:script_end, ctx})
              else
                ctx =
                  if get_char_var(ctx, :ALCH_Q, 0) == 6 do
                    ctx =
                      ctx
                      |> mes("What are you doing?")
                      |> mes("Go and find Darwin now.")
                      |> next()
                      |> mes("[Raspuchin Gregory]")
                      |> mes("Keheheheheheheheh~")
                      |> mes("Don't think this is the end of it!")
                      |> close()

                    throw({:script_end, ctx})
                  else
                    ctx
                  end

                ctx
              end

            ctx
          end

        ctx
      end

    ctx |> mes("Keheheheheheheheh~") |> mes("Don't think this is the end of it!") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
