defmodule Aesir.ZoneServer.Npc.Transpiler.CodegenTest do
  use ExUnit.Case, async: true

  alias Aesir.ZoneServer.Npc.Transpiler.Codegen

  defp gen!(body, opts \\ []) do
    opts =
      Map.merge(
        %{
          module: "Aesir.ZoneServer.Content.Npc.Payon.TestNpc",
          kind: :script,
          source: "test.txt:1",
          spawns: [%{map: "payon", x: 1, y: 2, dir: 3, sprite: 58, name: "Test"}],
          functions: %{}
        },
        Map.new(opts)
      )

    {:ok, src} = Codegen.generate(body, opts)
    assert {:ok, _} = Code.string_to_quoted(src)
    src
  end

  test "simple dialog module snapshot" do
    src =
      gen!("""
      mes "Hello!";
      close;
      """)

    assert src == """
           defmodule Aesir.ZoneServer.Content.Npc.Payon.TestNpc do
             @moduledoc \"\"\"
             Transpiled from rAthena test.txt:1.

             Regenerated by `mix aesir.import.npcs`; hand edits are detected through
             the transpile manifest and future imports land in `_conflicts/` instead
             of overwriting them.
             \"\"\"

             use Aesir.ZoneServer.Npc, spawn: [%{map: "payon", x: 1, y: 2, dir: 3, sprite: 58, name: "Test"}]

             @impl true
             def on_talk(ctx) do
               ctx |> mes("Hello!") |> close()
               exit(:normal)
             end
           end
           """
  end

  test "consecutive ctx-threading calls collapse into a pipe chain" do
    src =
      gen!("""
      mes "a";
      mes "b";
      next;
      mes "c";
      close;
      """)

    assert src =~ ~S{ctx |> mes("a") |> mes("b") |> next() |> mes("c") |> close()}
  end

  test "a call reading ctx in its arguments opens a chain but never joins one" do
    src =
      gen!("""
      mes "a";
      mes strcharinfo(0);
      close;
      """)

    assert src =~ ~S{ctx = mes(ctx, "a")}
    assert src =~ ~S{ctx |> mes(to_string(char_name(ctx, 0))) |> close()}
  end

  test "branch bodies pipe; a lone rebind just drops the dead binding" do
    src =
      gen!("""
      if (BaseLevel > 10) {
        mes "big";
        next;
      }
      if (BaseLevel > 20) mes "huge";
      mes "done";
      close;
      """)

    assert src =~ ~S{ctx |> mes("big") |> next()}
    assert src =~ ~S{mes(ctx, "huge")}
    refute src =~ ~S{ctx = mes(ctx, "huge")}
    assert src =~ ~S{ctx |> mes("done") |> close()}
  end

  test "a trailing effect run before end loses the dead rebinding" do
    src =
      gen!("""
      close2;
      warp "prontera",155,180;
      end;
      """)

    assert src =~ ~S{ctx |> close() |> warp("prontera", 155, 180)}
    refute src =~ "ctx = ctx |> close()"
  end

  test "switch(select) with supported commands, char vars and zeny" do
    src =
      gen!("""
      mes "Want it?";
      next;
      switch (select("Yes:No")) {
      case 1:
        if (Zeny < 500) { mes "Too poor"; close; }
        Zeny -= 500;
        getitem 2278, 1;
        sphmask_q = 1;
        close;
      case 2:
        close;
      }
      """)

    assert src =~ "{ctx, v1} = ctx |> mes(\"Want it?\") |> next() |> select([\"Yes\", \"No\"])"
    assert src =~ "case v1 do"
    assert src =~ "if zeny(ctx) < 500 do"
    assert src =~ "|> pay_zeny(500)"
    assert src =~ "|> give_item(2278, 1)"
    assert src =~ "|> set_char_var(:sphmask_q, 1)"
    assert src =~ "_ ->"
  end

  test "unsupported buildins become todo stubs, expressions become Todo.call!" do
    src =
      gen!("""
      showscript "hi";
      if (getcharid(0) == 0) close;
      close;
      """)

    assert src =~ ~S|ctx = todo(ctx, :showscript, ["hi"])|
    assert src =~ "Todo.call!(:getcharid, [0]) == 0"
    assert src =~ "alias Aesir.ZoneServer.Script.Todo"
  end

  test "goto labels become never-returning functions with fall-through" do
    src =
      gen!("""
      mes "start";
      goto L_End;
      L_Mid:
      mes "mid";
      L_End:
      mes "bye";
      close;
      """)

    assert src =~ ~S{ctx |> mes("start") |> l_l_end()}
    assert src =~ "defp l_l_end(ctx) do"
    refute src =~ "defp l_l_mid"
  end

  test "label references resolve case-insensitively like rAthena" do
    src =
      gen!("""
      callsub S_Warpchar, 1;
      goto L_end;
      L_End:
      mes "bye";
      close;
      S_WarpChar:
      return;
      """)

    assert src =~ "{ctx, _} = s_s_warpchar(ctx, [1])"
    assert src =~ "defp s_s_warpchar"
    assert src =~ "l_l_end(ctx)"
    assert src =~ "defp l_l_end(ctx) do"
    refute src =~ "todo(ctx, :goto"
  end

  test "menu dispatches to label functions" do
    src =
      gen!("""
      menu "Buy",L_Buy,"Bye",L_Bye;
      L_Buy:
      close;
      L_Bye:
      close;
      """)

    assert src =~ ~S|{ctx, choice} = select(ctx, ["Buy", "Bye"])|
    assert src =~ "1 -> l_l_buy(ctx)"
    assert src =~ "2 -> l_l_bye(ctx)"
  end

  test "callsub returns {ctx, value} and getarg reads args" do
    src =
      gen!("""
      callsub S_Give, 5;
      close;
      S_Give:
      return getarg(0) + 1;
      """)

    assert src =~ "{ctx, _} = s_s_give(ctx, [5])"
    assert src =~ "defp s_s_give(ctx, args) do"
    assert src =~ "{ctx, Enum.at(args, 0, 0) + 1}"
  end

  test "while loop with plain body recurses; nested break uses throw" do
    plain =
      gen!("""
      while (.@i < 3) .@i++;
      close;
      """)

    assert plain =~ ~S{ctx |> loop_1() |> close()}
    assert plain =~ "defp loop_1(ctx) do"
    refute plain =~ "throw"

    thrown =
      gen!("""
      while (1) {
        if (.@i > 2) break;
        .@i++;
      }
      close;
      """)

    assert thrown =~ "throw({:brk_1, ctx})"
    assert thrown =~ ":throw, {:brk_1, ctx} -> {:done, ctx}"
  end

  test "for loop runs init before and step on iteration" do
    src =
      gen!("""
      for (.@i = 0; .@i < 10; .@i++) mes "x";
      close;
      """)

    assert src =~ "|> set_local(:i, 0)"
    assert src =~ "get_local(ctx, :i, 0) + 1"
  end

  test "local and session vars, arrays, dialog input" do
    src =
      gen!("""
      input .@name$;
      @step = 2;
      setarray .@list[0], 1, 2, 3;
      mes .@list[1] + "x" + @step;
      close;
      """)

    assert src =~ "{ctx, v1} = input(ctx, :string)"
    assert src =~ ~S{|> set_local(:"name$", v1)}
    assert src =~ "|> set_temp_var(:step, 2)"
    assert src =~ "|> set_local(:list, [1, 2, 3])"
    assert src =~ "Enum.at(get_local(ctx, :list, []), 1, 0)"
  end

  test "server and account scopes route to their store DSL ops" do
    src =
      gen!("""
      $server_var = 1;
      mes "" + #account_var;
      close;
      """)

    assert src =~ ~S{set_server_var(ctx, "server_var", 1)}
    assert src =~ ~S{get_account_var(ctx, "#account_var", 0)}
    refute src =~ "todo(:set_var"
    refute src =~ ~S{Todo.call!(:get_var}
  end

  test "On* labels wire to on_event/2 clauses; the macro derives events/0" do
    src =
      gen!(
        """
        mes "hi";
        close;

        OnInit:
        end;

        OnTimer1000:
        end;
        """,
        module: "Aesir.ZoneServer.Content.Npc.Payon.TestNpcOnEvents"
      )

    assert src =~ ~S|def on_event("OnInit", ctx), do: ev_oninit(ctx)|
    assert src =~ ~S|def on_event("OnTimer1000", ctx), do: ev_ontimer1000(ctx)|
    refute src =~ "unwired_events"

    [{module, _}] = Code.compile_string(src)
    assert module.events() == ["OnInit", "OnTimer1000"]
  end

  test "OnTouch_ normalizes to the OnTouch head the engine dispatches, deduping with OnTouch" do
    src =
      gen!(
        """
        mes "hi";
        close;

        OnTouch:
        end;

        OnTouch_:
        end;
        """,
        module: "Aesir.ZoneServer.Content.Npc.Payon.TestNpcOnTouchDedupe"
      )

    assert src =~ ~S|def on_event("OnTouch", ctx), do: ev_ontouch(ctx)|
    refute src =~ "OnTouch_"

    [{module, _}] = Code.compile_string(src)
    assert module.events() == ["OnTouch"]
  end

  test "npc session/event buildins map to DSL calls" do
    src =
      gen!("""
      donpcevent "Boss::OnDead";
      doevent "Boss::OnRespawn";
      initnpctimer;
      initnpctimer "Boss";
      stopnpctimer;
      stopnpctimer "Boss";
      npctalk "hi!";
      enablenpc "Boss";
      disablenpc "Boss";
      hideonnpc "Boss";
      hideoffnpc "Boss";
      close;
      """)

    assert src =~ ~S{|> donpcevent("Boss::OnDead")}
    assert src =~ ~S{|> doevent("Boss::OnRespawn")}
    assert src =~ "|> initnpctimer()"
    assert src =~ ~S{|> initnpctimer("Boss")}
    assert src =~ "|> stopnpctimer()"
    assert src =~ ~S{|> stopnpctimer("Boss")}
    assert src =~ ~S{|> npctalk("hi!")}
    assert src =~ ~S{|> enablenpc("Boss")}
    assert src =~ ~S{|> disablenpc("Boss")}
    assert src =~ ~S{|> hideonnpc("Boss")}
    assert src =~ ~S{|> hideoffnpc("Boss")}
    assert src =~ "|> close()"
  end

  test "getnpctimer type 0 reads elapsed ms; other types and arities stay stubs" do
    src =
      gen!("""
      if (getnpctimer(0) > 500) close;
      .@t = getnpctimer(0, "Boss");
      if (getnpctimer(1) > 0) close;
      npctalk "hi", 1;
      close;
      """)

    assert src =~ "getnpctimer(ctx) > 500"
    assert src =~ ~S{set_local(ctx, :t, getnpctimer(ctx, "Boss"))}
    assert src =~ ~S|Todo.call!(:getnpctimer, [1])|
    assert src =~ ~S|todo(:npctalk, ["hi", 1])|
  end

  test "monster maps onto summon_mob with map, coords, amount and event" do
    src =
      gen!("""
      monster "prontera",155,180,"Poring",1002,1;
      monster "prontera",0,0,"P",1002,5,"B::OnD";
      monster "this",10,20,"Poring",1002,1;
      monster "gefenia",-1,-1,"D",PORING,2,"B::OnD";
      close;
      """)

    assert src =~ ~S|summon_mob(mob_id: 1002, map: "prontera", at: {155, 180})|

    assert src =~
             ~S|summon_mob(mob_id: 1002, map: "prontera", at: :random, amount: 5, event: "B::OnD")|

    assert src =~ ~S|summon_mob(mob_id: 1002, at: {10, 20})|

    assert src =~
             ~S|summon_mob(mob_name: "PORING", map: "gefenia", at: :random, amount: 2, event: "B::OnD")|
  end

  test "monster case variant and dynamic args render; wrong arity stays a stub" do
    src =
      gen!("""
      Monster .@map$,.@x,.@y," ",1002,.@n,.@label$;
      monster "prontera",155,180;
      close;
      """)

    assert src =~ ~S|mob_id: 1002|
    assert src =~ ~S|map: get_local(ctx, :"map$", "")|
    assert src =~ ~S|at: {get_local(ctx, :x, 0), get_local(ctx, :y, 0)}|
    assert src =~ ~S|amount: get_local(ctx, :n, 0)|
    assert src =~ ~S|event: get_local(ctx, :"label$", "")|
    assert src =~ ~S|todo(:monster, ["prontera", 155, 180])|
  end

  test "spawn placements render optional trigger and unique_name" do
    src =
      gen!(
        """
        mes "hi";
        close;
        """,
        spawns: [
          %{
            map: "payon",
            x: 1,
            y: 2,
            dir: 3,
            sprite: 58,
            name: "Guard",
            unique_name: "GuardEx",
            trigger: {2, 2}
          }
        ]
      )

    assert src =~ ~S|unique_name: "GuardEx"|
    assert src =~ "trigger: {2, 2}"
  end

  test "global function modules take args and return {ctx, value}" do
    src =
      gen!(
        """
        if (getarg(0) > 5) return 1;
        return 0;
        """,
        kind: :function,
        module: "Aesir.ZoneServer.Content.Npc.Functions.FCheck",
        spawns: []
      )

    assert src =~ "def call(ctx, args) do"
    assert src =~ "{ctx, 1}"
    assert src =~ "{ctx, 0}"
    refute src =~ "use Aesir.ZoneServer.Npc"
  end

  test "first-job buildins and global functions map to DSL primitives" do
    src =
      gen!("""
      if (callfunc("F_CanChangeJob")) close;
      callfunc "Job_Change", Job_Thief;
      savepoint "prt_fild03",361,255,1,1;
      mes strcharinfo(0);
      mes jobname(Class);
      close;
      """)

    assert src =~ "= can_change_job?(ctx)"
    assert src =~ "|> jobchange(:thief)"
    assert src =~ ~S{|> savepoint("prt_fild03", 361, 255)}
    assert src =~ "char_name(ctx, 0)"
    assert src =~ "job_name(ctx, class(ctx))"
    refute src =~ "todo(ctx, :savepoint"
    refute src =~ "todo(:savepoint"
    refute src =~ ~S|Todo.call!(:callfunc, ["Job_Change"|
  end

  test "emotion maps to the self-form DSL op; a target arg is dropped" do
    src =
      gen!("""
      emotion ET_MONEY;
      emotion ET_MONEY, getcharid(3);
      close;
      """)

    assert Regex.scan(~r/emotion\(:money\)/, src) |> length() == 2
    refute src =~ "todo(ctx, :emotion"
  end

  test "an unresolvable ET_* token becomes a const todo" do
    src =
      gen!("""
      emotion ET_NOPE;
      close;
      """)

    assert src =~ "emotion(Todo.const!(:ET_NOPE))"
  end

  test "callfunc resolves through the functions map or stubs" do
    functions = %{"F_Check" => "Aesir.ZoneServer.Content.Npc.Functions.FCheck"}

    src =
      gen!(
        """
        callfunc "F_Check", 1;
        if (callfunc("F_Missing") == 1) close;
        close;
        """,
        functions: functions
      )

    assert src =~ "{ctx, _} = Aesir.ZoneServer.Content.Npc.Functions.FCheck.call(ctx, [1])"
    assert src =~ ~S|Todo.call!(:callfunc, ["F_Missing"])|
  end

  test "a callfunc binding right before end drops the dead {ctx, _} binding" do
    functions = %{"F_Check" => "Aesir.ZoneServer.Content.Npc.Functions.FCheck"}

    piped =
      gen!(
        """
        mes "hi";
        callfunc "F_Check", 1;
        end;
        """,
        functions: functions
      )

    bare =
      gen!(
        """
        callfunc "F_Check", 1;
        end;
        """,
        functions: functions
      )

    assert piped =~ ~S{ctx |> mes("hi") |> Aesir.ZoneServer.Content.Npc.Functions.FCheck.call([1])}
    assert bare =~ "_ = Aesir.ZoneServer.Content.Npc.Functions.FCheck.call(ctx, [1])"
    refute piped =~ "{ctx, _}"
    refute bare =~ "{ctx, _}"
  end

  test "broadcast buildins transpile to DSL calls, not todo stubs" do
    src =
      gen!("""
      announce "hi", bc_all;
      close;
      """)

    assert src =~ ~S|announce("hi", 0)|
    refute src =~ "todo(ctx, :announce"
  end

  test "announce passes a combined flag and explicit color through" do
    src =
      gen!("""
      announce "hi", bc_all|bc_blue, 0xABCDEF;
      close;
      """)

    assert src =~ ~S|announce("hi", :erlang.bor(0, 16), 11_259_375)|
  end

  test "announce drops the rAthena font tail beyond the color arg" do
    src =
      gen!("""
      announce "hi", bc_all, 0xFFFFFF, 0x190, 12, 0, 0;
      close;
      """)

    assert src =~ ~S|announce("hi", 0, 16_777_215)|
    refute src =~ "400"
  end

  test "mapannounce, areaannounce and broadcast transpile to their DSL calls" do
    src =
      gen!("""
      mapannounce "prontera", "hi", bc_map;
      areaannounce "prontera", 10, 10, 20, 20, "hi", bc_area;
      broadcast "hi", bc_all;
      close;
      """)

    assert src =~ ~S|mapannounce("prontera", "hi", 1)|
    assert src =~ ~S|areaannounce("prontera", 10, 10, 20, 20, "hi", 2)|
    assert src =~ ~S|broadcast("hi", 0)|
    refute src =~ "todo(ctx, :mapannounce"
    refute src =~ "todo(ctx, :areaannounce"
    refute src =~ "todo(ctx, :broadcast"
  end

  test "rathena semantics: truthiness, bool_int, concat, bitwise" do
    src =
      gen!("""
      if (MISC_QUEST & 8) close;
      .@ok = BaseLevel > 10;
      mes "lv " + BaseLevel;
      close;
      """)

    assert src =~ "Rathena.truthy?(:erlang.band(get_char_var(ctx, :MISC_QUEST, 0), 8))"
    assert src =~ "Rathena.bool_int(base_level(ctx) > 10)"
    assert src =~ ~S|Rathena.concat("lv ", base_level(ctx))|
  end

  test "quest commands transpile to their DSL calls and the module compiles" do
    src =
      gen!(
        """
        setquest 7393;
        erasequest 7393;
        completequest 7393;
        changequest 7393,7394;
        getexp 300000,100000;
        close;
        """,
        module: "Aesir.ZoneServer.Content.Npc.Payon.TestNpcQuestCommands"
      )

    assert src =~ "setquest(7393)"
    assert src =~ "erasequest(7393)"
    assert src =~ "completequest(7393)"
    assert src =~ "changequest(7393, 7394)"
    assert src =~ "getexp(300_000, 100_000)"
    refute src =~ "todo(ctx, :setquest"
    refute src =~ "todo(ctx, :erasequest"
    refute src =~ "todo(ctx, :completequest"
    refute src =~ "todo(ctx, :changequest"
    refute src =~ "todo(ctx, :getexp"

    assert [{_module, _}] = Code.compile_string(src)
  end

  test "checkquest and questprogress keep the optional mode argument" do
    src =
      gen!("""
      .@a = checkquest(7393);
      .@b = checkquest(7393, HUNTING);
      .@c = questprogress(7393);
      .@d = questprogress(7393, PLAYTIME);
      close;
      """)

    assert src =~ "checkquest(ctx, 7393)"
    assert src =~ "checkquest(ctx, 7393, :hunting)"
    assert src =~ "questprogress(ctx, 7393)"
    assert src =~ "questprogress(ctx, 7393, :playtime)"
    refute src =~ "Todo.call!(:checkquest"
    refute src =~ "Todo.call!(:questprogress"
  end

  test "checkquest resolves HAVEQUEST explicitly and isbegin_quest reads in expression position" do
    src =
      gen!("""
      .@a = checkquest(7393, HAVEQUEST);
      .@b = isbegin_quest(7393);
      close;
      """)

    assert src =~ "checkquest(ctx, 7393, :havequest)"
    assert src =~ "isbegin_quest(ctx, 7393)"
  end

  test "specialeffect and specialeffect2 map to their DSL ops, resolving EF_* and raw ids" do
    src =
      gen!("""
      specialeffect EF_HIT1;
      specialeffect2 EF_HEAL2;
      specialeffect 42;
      close;
      """)

    assert src =~ "|> specialeffect(:hit1)"
    assert src =~ "|> specialeffect2(:heal2)"
    assert src =~ "|> specialeffect(42)"
    refute src =~ "Todo.call!(:specialeffect"
  end

  test "specialeffect drops the trailing send-target and named-NPC arguments" do
    src =
      gen!("""
      specialeffect EF_HIT1, AREA, "Some NPC";
      close;
      """)

    assert src =~ "|> specialeffect(:hit1)"
    refute src =~ "Some NPC"
  end

  test "getnpcid reads the running NPC's gid and a named NPC's gid" do
    src =
      gen!("""
      .@self = getnpcid(0);
      .@other = getnpcid(0, "Kafra Employee");
      close;
      """)

    assert src =~ "getnpcid(ctx)"
    assert src =~ ~S|getnpcid(ctx, "Kafra Employee")|
    refute src =~ "Todo.call!(:getnpcid"
  end

  test "playerattached reads as a zero-arg attachment check" do
    src =
      gen!("""
      if (!playerattached()) end;
      close;
      """)

    assert src =~ "playerattached(ctx)"
    refute src =~ "Todo.call!(:playerattached"
  end

  test "strnpcinfo reads an NPC info field by type" do
    src =
      gen!("""
      mes strnpcinfo(0);
      mes strnpcinfo(4);
      close;
      """)

    assert src =~ "strnpcinfo(ctx, 0)"
    assert src =~ "strnpcinfo(ctx, 4)"
    refute src =~ "Todo.call!(:strnpcinfo"
  end

  test "checkweight pairs item ids and amounts into a tuple list" do
    src =
      gen!("""
      if (checkweight(501, 5) == 0) close;
      if (checkweight(501, 1, 502, 2) == 0) close;
      close;
      """)

    assert src =~ "checkweight(ctx, [{501, 5}])"
    assert src =~ "checkweight(ctx, [{501, 1}, {502, 2}])"
    refute src =~ "Todo.call!(:checkweight"
  end

  test "consumeitem maps to its DSL op with a resolved item id" do
    src =
      gen!("""
      consumeitem 12043;
      close;
      """)

    assert src =~ "consumeitem(12043)"
    refute src =~ "todo(ctx, :consumeitem"
  end

  test "nude maps to its no-argument DSL op, dropping the optional char id" do
    src =
      gen!("""
      nude;
      nude getcharid(3);
      close;
      """)

    assert src =~ "|> nude()"
    refute src =~ "todo(ctx, :nude"
  end

  test "getequipid resolves EQI_* slots to their ordinal and passes ints through" do
    src =
      gen!("""
      .@top = getequipid(EQI_HEAD_TOP);
      .@dyn = getequipid(.@slot);
      close;
      """)

    assert src =~ "getequipid(ctx, 6)"
    assert src =~ "getequipid(ctx, get_local(ctx, :slot, 0))"
    refute src =~ "Todo.call!(:getequipid"
  end

  test "killmonster maps map and event to its DSL op, dropping the type flag" do
    src =
      gen!("""
      killmonster "moro_vol", "#f_boss_c::OnMobDead0";
      killmonster "prontera", "All", 1;
      close;
      """)

    assert src =~ ~S|killmonster("moro_vol", "#f_boss_c::OnMobDead0")|
    assert src =~ ~S|killmonster("prontera", "All")|
    refute src =~ "todo(ctx, :killmonster"
  end

  test "viewpoint maps to its DSL op with numeric args (color included)" do
    src =
      gen!("""
      viewpoint 1,85,131,1,0x00FF00;
      close;
      """)

    assert src =~ "viewpoint(1, 85, 131, 1, 65280)"
    refute src =~ "todo(ctx, :viewpoint"
  end

  test "F_GetNumSuffix callfunc maps to the num_suffix read with its argument" do
    src =
      gen!("""
      mes callfunc("F_GetNumSuffix", .@n);
      close;
      """)

    assert src =~ "num_suffix(ctx, get_local(ctx, :n, 0))"
    refute src =~ "Todo.call!(:callfunc"
  end

  test "a :read global called directly (F_GetNumSuffix(n)) maps like its callfunc form" do
    src =
      gen!("""
      mes F_GetNumSuffix(.@n);
      close;
      """)

    assert src =~ "num_suffix(ctx, get_local(ctx, :n, 0))"
    refute src =~ "Todo.call!(:F_GetNumSuffix"
  end

  test "F_InsertComma maps to insert_comma via both callfunc and direct-call forms" do
    via_callfunc =
      gen!("""
      mes callfunc("F_InsertComma", .@cost);
      close;
      """)

    direct =
      gen!("""
      mes F_InsertComma(.@cost);
      close;
      """)

    assert via_callfunc =~ "insert_comma(ctx, get_local(ctx, :cost, 0))"
    assert direct =~ "insert_comma(ctx, get_local(ctx, :cost, 0))"
    refute via_callfunc =~ "Todo.call!(:callfunc"
    refute direct =~ "Todo.call!(:F_InsertComma"
  end

  test "input with min/max clamps the entry back into range (statement form)" do
    src =
      gen!("""
      input .@x, 1, 5;
      close;
      """)

    assert src =~ "= input(ctx, :int)"
    assert src =~ "Rathena.input_int("
    assert src =~ ", 1, 5)"
    assert src =~ "set_local(:x,"
    refute src =~ "Todo.call!(:input"
  end

  test "input in expression position yields its range status (0/1/2)" do
    src =
      gen!("""
      if (input(.@x, 1, 5) != 0) mes "out of range";
      close;
      """)

    assert src =~ "= input(ctx, :string)" or src =~ "= input(ctx, :int)"
    assert src =~ "Rathena.input_int("
    assert src =~ "set_local(ctx, :x,"
    assert src =~ "!= 0"
    refute src =~ "Todo.call!(:input"
  end

  test "cutin and soundeffect map to their client-packet effect ops" do
    src =
      gen!("""
      cutin "kafra_01",2;
      cutin "",255;
      soundeffect "bragis_poem.wav",0;
      close;
      """)

    assert src =~ ~S{cutin("kafra_01", 2)}
    assert src =~ ~S{cutin("", 255)}
    assert src =~ ~S{soundeffect("bragis_poem.wav", 0)}
    refute src =~ "todo(ctx, :cutin"
    refute src =~ "todo(ctx, :soundeffect"
  end

  test "getpartnerid maps to a nullary read without a trailing comma" do
    src =
      gen!("""
      if (getpartnerid() == 0) close;
      close;
      """)

    assert src =~ "getpartnerid(ctx) == 0"
    refute src =~ "getpartnerid(ctx, )"
    refute src =~ "Todo.call!(:getpartnerid"
  end

  test "gettimetick maps to its read in both statement and expression position" do
    src =
      gen!("""
      set @cd_marketshop, gettimetick(2);
      if (@cd_marketshop + 60 > gettimetick(2)) close;
      close;
      """)

    assert src =~ "gettimetick(ctx, 2)"
    refute src =~ "Todo.call!(:gettimetick"
  end

  test "checkre and vip_status map to their reads, resolving VIP_STATUS_* constants" do
    src =
      gen!("""
      if (checkre(0) && !vip_status(VIP_STATUS_ACTIVE)) close;
      close;
      """)

    assert src =~ "checkre(ctx, 0)"
    assert src =~ "vip_status(ctx, 1)"
    refute src =~ "Todo.call!(:checkre"
    refute src =~ "Todo.call!(:vip_status"
    refute src =~ "Todo.const!(:VIP_STATUS_ACTIVE)"
  end

  test "scoped variables route to their store DSL ops instead of stubs" do
    src =
      gen!("""
      set $rachel_donate, $rachel_donate + 100;
      set $@stage, 3;
      set #points, 5;
      set ##global_points, 5;
      set .counter, .counter + 1;
      set $event_name$, "spring";
      close;
      """)

    assert src =~
             ~S{set_server_var("rachel_donate", get_server_var(ctx, "rachel_donate", 0) + 100)}

    assert src =~ ~S{set_server_temp_var("stage", 3)}
    assert src =~ ~S{set_account_var("#points", 5)}
    assert src =~ ~S{set_account_var("##global_points", 5)}
    assert src =~ ~S{set_npc_var("counter", get_npc_var(ctx, "counter", 0) + 1)}
    assert src =~ ~S{set_server_var("event_name$", "spring")}
    refute src =~ "Todo.call!(:get_var"
    refute src =~ ":set_var"
  end

  test "instance-scope variables stay stubbed (no instance system yet)" do
    src =
      gen!("""
      set 'progress, 1;
      close;
      """)

    assert src =~ ~S{todo(:set_var, ["'progress", 1])}
  end
end
