defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dewata.Monk do
  @moduledoc """
  Transpiled from rAthena re/cities/dewata.txt:430 (Monk#dew1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "dewata", x: 67, y: 186, dir: 8, sprite: 834, name: "Monk", unique_name: "Monk#dew1"}
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Monk]")
    |> mes("I am a monk, content to spend my days in religious study.")
    |> next()
    |> mes("[Monk]")
    |> mes("I've just returned from a pilgrimage to Borobudur temple with my fellow monks...")
    |> next()
    |> mes("[Monk]")
    |> mes(
      "Borobudur temple has many pilgrims visiting, since it is one of few temples left for worshipping the Great Buddha."
    )
    |> close()
  end
end
