defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dewata.SweetMarriedCouple234263 do
  @moduledoc """
  Transpiled from rAthena re/cities/dewata.txt:689 (Sweet Married Couple#2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "dewata",
        x: 234,
        y: 263,
        dir: 8,
        sprite: 727,
        name: "Sweet Married Couple",
        unique_name: "Sweet Married Couple#2",
        trigger: {2, 3}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx
    |> mes("[Sweet Wife]")
    |> mes("Baby~ You know what flower that is~?")
    |> emotion(:question)
    |> next()
    |> mes("[Sweet Husband]")
    |> mes("Hmm? I don't know. But it's really pretty.")
    |> next()
    |> mes("[Sweet Wife]")
    |> mes("Baby~ Who's prettier, me or the flower?")
    |> emotion(:question)
    |> next()
    |> mes("[Sweet Husband]")
    |> mes("No matter how pretty the flower is, you are always more beautiful~")
    |> emotion(:chup)
    |> next()
    |> mes("[Sweet Wife]")
    |> mes("Really? I'm that pretty? I love you, sweetie~")
    |> emotion(:chupchup)
    |> next()
    |> mes("[Sweet Married Couple]")
    |> mes("Hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha")
    |> mes("Hohohohohohohohohohohohohohohohohohohohohohohohohohohohohohohohohohohoho")
    |> emotion(:smile)
    |> emotion(:smile)
    |> next()
    |> mes("Come on now, this bores me. Let's move on.")
    |> close()
  end
end
