defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Dewata.YoungMan18188 do
  @moduledoc """
  Transpiled from rAthena re/cities/dewata.txt:989 (Young Man#dew-2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "dewata",
        x: 181,
        y: 88,
        dir: 6,
        sprite: 536,
        name: "Young Man",
        scope: :renewal,
        unique_name: "Young Man#dew-2"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Young Man]")
    |> mes("Isn't ^8B4513Dewata^000000 beach")
    |> mes("really beautiful?")
    |> mes("The children always play")
    |> mes("at this beach. It really")
    |> mes("reminds me of my youth.")
    |> next()
    |> mes("[Young Man]")
    |> mes("At the evening, you can see")
    |> mes("fireworks from the beach.")
    |> mes("With ocean breeze, the crashing waves,")
    |> mes("and fireworks lighting the sky,")
    |> mes("the nighttime is a time of beauty here!")
    |> close()
  end
end
