defmodule Aesir.ZoneServer.Content.Npc.Cities.Umbala.LaEd do
  @moduledoc """
  Transpiled from rAthena cities/umbala.txt:27 (La Ed#um).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "comodo",
        x: 170,
        y: 137,
        dir: 7,
        sprite: 84,
        name: "La Ed",
        scope: :shared,
        unique_name: "La Ed#um"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
  end
end
