defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Mora.WoundedRafflesia do
  @moduledoc """
  Transpiled from rAthena re/cities/mora.txt:379 (Wounded Rafflesia#ep14_1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :renewal,
    spawn: [
      %{
        map: "mora",
        x: 43,
        y: 113,
        dir: 4,
        sprite: 517,
        name: "Wounded Rafflesia",
        scope: :renewal,
        unique_name: "Wounded Rafflesia#ep14_1"
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Wounded Raffle]")
    |> mes("Ugghh... What was it")
    |> mes("that was in the bath... Arrrghh...")
    |> mes("To attack suddenly like that... Be careful...")
    |> mes("Whatever it is in there, it's very aggressive.")
    |> close()
  end
end
