defmodule Aesir.ZoneServer.Content.Npc.Quests.FirstClass.TuMerchant.Maos do
  @moduledoc """
  Transpiled from rAthena quests/first_class/tu_merchant.txt:852 (Maos).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "prt_in", x: 251, y: 129, dir: 3, sprite: 709, name: "Maos"}]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Maos]")

    ctx =
      if get_char_var(ctx, :tu_merchant, 0) == 6 do
        {ctx, _} = s_l_potions(ctx, [400, 10])
        ctx
      else
        ctx =
          if get_char_var(ctx, :tu_merchant, 0) == 7 do
            {ctx, _} = s_l_potions(ctx, [340, 10])
            ctx
          else
            ctx =
              if get_char_var(ctx, :tu_merchant, 0) == 8 do
                {ctx, _} = s_l_potions(ctx, [420, 10])
                ctx
              else
                ctx
              end

            ctx
          end

        ctx
      end

    ctx
    |> mes(
      "I see too many people struggling to scrape every penny and put it all into their savings..."
    )
    |> next()
    |> mes("[Maos]")
    |> mes(
      "Now, don't get me wrong. It's a good idea to invest in the future. But money exists to be spent! Enjoy every moment, that's what I say~"
    )
    |> next()
    |> mes("[Maos]")
    |> mes("Besides...")
    |> mes("You can't take")
    |> mes("your money with you")
    |> mes("when your time's up,")
    |> mes("you know?")
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  defp s_l_potions(ctx, args) do
    ctx =
      ctx
      |> set_local(:cost, Enum.at(args, 0, 0))
      |> mes("Don't say anything.")
      |> mes("I know what you want.")
      |> mes("10 Red Potions, right?")
      |> mes("I'll sell them to you")

    {ctx, v1} =
      ctx
      |> mes(
        Rathena.concat(
          Rathena.concat("for the low price of ", get_local(ctx, :cost, 0)),
          " Zeny~"
        )
      )
      |> next()
      |> select(["Buy", "Cancel"])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Maos]")
            |> mes("Excellent choice!")
            |> mes("Good products at affordable prices! That's my ethic as a merchant.")

          ctx =
            if zeny(ctx) < get_local(ctx, :cost, 0) do
              ctx =
                ctx
                |> next()
                |> mes("[Maos]")
                |> mes(
                  "Ooh, but you don't even have enough Zeny to purchase these potions. I'm sorry, but I can't sell these just to lose money, you know?"
                )
                |> close()

              throw({:script_end, ctx})
            else
              ctx
            end

          ctx =
            if get_char_var(ctx, :MaxWeight, 0) - weight(ctx) < 71 do
              ctx
              |> next()
              |> mes("[Maos]")
              |> mes(
                "Ooh, but it doesn't look like you've got enough inventory space to carry any more items."
              )
            else
              ctx
              |> pay_zeny(get_local(ctx, :cost, 0))
              |> set_char_var(:tu_merchant, Enum.at(args, 1, 0))
              |> give_item(501, 10)
            end

          ctx = close(ctx)
          throw({:script_end, ctx})

        2 ->
          ctx =
            ctx
            |> mes("[Maos]")
            |> mes(
              "Well, I can't force you to buy these, but I'm telling you that you're passing up a real bargain!"
            )
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    {ctx, nil}
  end
end
