defmodule Aesir.ZoneServer.Content.Npc.Re.Cities.Izlude.TalkativeKid do
  @moduledoc """
  Transpiled from rAthena re/cities/izlude.txt:111 (Talkative Kid#iz).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "izlude",
        x: 143,
        y: 205,
        dir: 7,
        sprite: 703,
        name: "Talkative Kid",
        unique_name: "Talkative Kid#iz"
      },
      %{
        map: "izlude_a",
        x: 143,
        y: 205,
        dir: 7,
        sprite: 703,
        name: "Talkative Kid",
        unique_name: "Talkative Kid#iza"
      },
      %{
        map: "izlude_b",
        x: 143,
        y: 205,
        dir: 7,
        sprite: 703,
        name: "Talkative Kid",
        unique_name: "Talkative Kid#izb"
      },
      %{
        map: "izlude_c",
        x: 143,
        y: 205,
        dir: 7,
        sprite: 703,
        name: "Talkative Kid",
        unique_name: "Talkative Kid#izc"
      },
      %{
        map: "izlude_d",
        x: 143,
        y: 205,
        dir: 7,
        sprite: 703,
        name: "Talkative Kid",
        unique_name: "Talkative Kid#izd"
      }
    ]

  @impl true
  def on_event("OnTimer64000", ctx), do: ev_ontimer64000(ctx)
  def on_event("OnTimer72000", ctx), do: ev_ontimer72000(ctx)
  def on_event("OnTimer136000", ctx), do: ev_ontimer136000(ctx)
  def on_event("OnTimer144000", ctx), do: ev_ontimer144000(ctx)
  def on_event("OnTimer212000", ctx), do: ev_ontimer212000(ctx)
  def on_event("OnTimer276000", ctx), do: ev_ontimer276000(ctx)
  def on_event("OnTimer284000", ctx), do: ev_ontimer284000(ctx)
  def on_event("OnTimer344000", ctx), do: ev_ontimer344000(ctx)
  def on_event("OnTimer348000", ctx), do: ev_ontimer348000(ctx)
  def on_event("OnTimer416000", ctx), do: ev_ontimer416000(ctx)
  def on_event("OnTimer424000", ctx), do: ev_ontimer424000(ctx)
  def on_event("OnTimer492000", ctx), do: ev_ontimer492000(ctx)
  def on_event("OnTimer552000", ctx), do: ev_ontimer552000(ctx)
  def on_event("OnTimer560000", ctx), do: ev_ontimer560000(ctx)
  def on_event("OnTimer565000", ctx), do: ev_ontimer565000(ctx)
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontimer64000(ctx) do
    npctalk(ctx, "Talkative Kid : I used all my Novice Red Potions. What should I do?")
  end

  def ev_ontimer72000(ctx) do
    npctalk(ctx, "Talkative Kid : Where is the shop?")
  end

  def ev_ontimer136000(ctx) do
    npctalk(ctx, "Talkative Kid : Idiot! You do not know about the 'shortcut window'?")
  end

  def ev_ontimer144000(ctx) do
    npctalk(
      ctx,
      "Talkative Kid : The items in your inventory can be dragged and put in the shortcut window."
    )
  end

  def ev_ontimer212000(ctx) do
    npctalk(ctx, "Talkative Kid : I got so many beginner's items in the Academy!")
  end

  def ev_ontimer276000(ctx) do
    npctalk(ctx, "Talkative Kid : They even gave me weapons and a shield!")
  end

  def ev_ontimer284000(ctx) do
    npctalk(ctx, "Talkative Kid : Just press  <Ctrl+~key> to open the map you have.")
  end

  def ev_ontimer344000(ctx) do
    npctalk(
      ctx,
      "Talkative Kid : Then do you want to go Criatura Academy with me? I'm learning how to battle from Instructor Subino!"
    )
  end

  def ev_ontimer348000(ctx) do
    npctalk(ctx, "Talkative Kid : The Academy is in North side of Izlude. Let's go~!")
  end

  def ev_ontimer416000(ctx) do
    npctalk(ctx, "Talkative Kid : It's a system to guide you to a destination.")
  end

  def ev_ontimer424000(ctx) do
    npctalk(ctx, "Talkative Kid : In the basic menu, please click the [Navigation] button.")
  end

  def ev_ontimer492000(ctx) do
    npctalk(
      ctx,
      "Talkative Kid : Whee, Ain't gonna use your brain? Please type /where in the chat window now!"
    )
  end

  def ev_ontimer552000(ctx) do
    npctalk(ctx, "Talkative Kid : In this case, you can push the <Enter> key.")
  end

  def ev_ontimer560000(ctx) do
    npctalk(ctx, "Talkative Kid : We are just repeating the same dialog. HaHaha.")
  end

  def ev_ontimer565000(ctx) do
    ctx
  end

  def ev_oninit(ctx) do
    initnpctimer(ctx)
  end
end
