defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Cities.Prontera.LibToPrtPrison do
  @moduledoc """
  Transpiled from rAthena re/warps/cities/prontera.txt:81 (lib_to_prt_prison).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "prt_lib",
        x: 9,
        y: 24,
        dir: 0,
        sprite: 45,
        name: "lib_to_prt_prison",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if get_char_var(ctx, :ep16_royal, 0) > 13 do
        warp(ctx, "prt_pri00", 60, 127)
      else
        ctx
        |> mes("[Guardian Knight]")
        |> mes("You cannot go that way.")
        |> close()
        |> warp("prt_lib", 60, 61)
      end

    ctx
  end
end
