defmodule Aesir.ZoneServer.Content.Npc.Dewata.Gourmet do
  @moduledoc """
  Transpiled from rAthena re/cities/dewata.txt:323 (Gourmet#dew).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "dewata", x: 147, y: 107, dir: 6, sprite: 85, name: "Gourmet"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Gourmet]")
    |> mes("Oh... it's like a party in my")
    |> mes("mouth... and everyone's invited!")
    |> emotion(:cry)
    |> next()
    |> mes("[Gourmet]")
    |> mes("Master~ One more please~")
    |> emotion(:best)
    |> emotion(:ok)
    |> next()
    |> mes("[Gourmet]")
    |> mes("You must try this! The Food here is succulent~")
    |> close()
  end
end
