defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Other.Verus.G2337262 do
  @moduledoc """
  Transpiled from rAthena re/warps/other/verus.txt:640 (G-2#Cafeteria).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "un_bk_q",
        x: 337,
        y: 262,
        dir: 0,
        sprite: 45,
        name: "G-2",
        unique_name: "G-2#Cafeteria",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx
    |> todo(:callfunc, ["F_time_limit_recorder", get_local(ctx, :cooldown_status_day, 0)])
    |> warp("un_bk_q", 321, 289)
  end
end
