defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Other.Verus.J0 do
  @moduledoc """
  Transpiled from rAthena re/warps/other/verus.txt:141 (J-0#Machine Warehouse).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "un_bk_q",
        x: 24,
        y: 276,
        dir: 0,
        sprite: 45,
        name: "J-0",
        unique_name: "J-0#Machine Warehouse",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx
    |> todo(:callfunc, ["F_time_limit_recorder", get_local(ctx, :cooldown_status_day, 0)])
    |> warp("un_bk_q", 45, 275)
  end
end
