defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Other.Verus.K0 do
  @moduledoc """
  Transpiled from rAthena re/warps/other/verus.txt:381 (K-0#L-2).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "un_bk_q",
        x: 169,
        y: 230,
        dir: 0,
        sprite: 45,
        name: "K-0",
        unique_name: "K-0#L-2",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx
    |> todo(:callfunc, ["F_time_limit_recorder", get_local(ctx, :cooldown_status_day, 0)])
    |> warp("un_bk_q", 171, 189)
  end
end
