defmodule Aesir.ZoneServer.Content.Npc.Re.Warps.Other.Verus.Z0229163 do
  @moduledoc """
  Transpiled from rAthena re/warps/other/verus.txt:696 (Z-0#Z-1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "un_bk_q",
        x: 229,
        y: 163,
        dir: 0,
        sprite: 45,
        name: "Z-0",
        unique_name: "Z-0#Z-1",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_ontouch(ctx) do
    ctx
    |> todo(:callfunc, ["F_time_limit_recorder", get_local(ctx, :cooldown_status_day, 0)])
    |> warp("un_bk_q", 159, 52)
  end
end
