defmodule Aesir.ZoneServer.Content.Npc.Cities.Lutie.UncleHairy do
  @moduledoc """
  Transpiled from rAthena cities/lutie.txt:318 (Uncle Hairy).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "xmas", x: 176, y: 236, dir: 4, sprite: 712, name: "Uncle Hairy"}]

  @impl true
  def on_talk(ctx) do
    if get_char_var(ctx, :xmas_npc, 0) == 4 do
      if count_item(ctx, 1024) > 0 and count_item(ctx, 938) > 0 do
        ctx =
          ctx
          |> mes("[Cantata]")
          |> mes(
            "Oh? Y-y-you've got the stuff? Goooooooood. It's been so long since I've been able to have some of this... G-give it to me!"
          )
          |> next()
          |> delitem(1024, 1)
          |> delitem(938, 1)
          |> mes(
            "^3355FFYou quickly handed him the Squid Ink and Sticky Mucus and watched with a little disgust as he relished the flavor.^000000"
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("*Burrrrpppp~*")
          |> mes(
            "Well, now it's the time for my story. Keep in mind that this is the whole story from what I know. I'm not sure how much you've already heard though..."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("A long time ago,")
          |> mes("there was a great")
          |> mes("Alchemist living")
          |> mes("in the far north.")
          |> mes("His name was")
          |> mes("^3355FFPhilip Varsez^000000!")
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "He was always foremost in the research of alchemy and needed rare materials to conduct his studies. Because of that, he had to travel the world in search of materials containing magical energies..."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "One day, his travels brought him to a northern village known for its freezing weather. But when he arrived, he was welcomed by a smouldering town that had recently been destroyed."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "It was a grim sight: People were lying at the roadside, groaning in agony. As Varsez walked by, each villager would beg, 'K-Kill me...' and plead for him to put them out of their misery."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Amidst the woeful cries of despair, the wails of two infants reached the ears of Philip Varsez. He rushed to investigate and found two babies cushioned in the bosom of a melting snowman."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("That snowman...")
          |> mes("was ^3355FFSnowysnow^000000.")
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Being the wise Alchemist that he is, Varsez deduced that Snowysnow sacrificed himself to protect those two babies from the great disaster that had destroyed the village."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Varsez was touched, and was determined to save the life of this snowman with his alchemy. He would then transport him here to Lutie, the safest place in the world."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Of course, there was another rumor that, in addition to the mercy from that Alchemist, Snowysnow was able to survive due to the special properties of his snow."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "It's believed that Snowysnow's snow used to cover a mysterious field that would be filled with the bloom of magical flowers."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("Muhahaha~")
          |> mes(
            "Well, that's pretty much all I know. I hope you were able to learn what you wanted from my story! Haw haw haw!"
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("Well...")
          |> mes("Now that I think about it...")
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Snowysnow can not only speak, but he also seems to be able to create an endless supply of Christmas presents. Or at least, that's what I hear."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "^3355FFThachentze^000000, that lovely pickle maker, knows more about it. So if you're curious, you should go talk to her. Alrighty then, Merry Christmas!"
          )
          |> set_char_var(:xmas_npc, 5)
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          ctx
          |> mes("[Cantata]")
          |> mes(
            "Oh yeah? Heard about me from Poze, did you? Haw haw haw! Yeah, I know a little bit about Snowysnow. In fact, I may even be his weak point, since..."
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("I know")
          |> mes("the secret of")
          |> mes("^3355FFSnowysnow's birth^000000!!")
          |> next()
          |> mes("[Cantata]")
          |> mes("Are you curious?")
          |> mes(
            "Heh heh heh~ Well, don't think I'll let you know unless you give me something in return!"
          )
          |> next()
          |> mes("[Cantata]")
          |> mes("Living in this")
          |> mes("town doesn't give me")
          |> mes("much of a chance to enjoy")
          |> mes("a man's drink. Hmmm, bring me...")
          |> next()
          |> mes("[Cantata]")
          |> mes("^3355FF1 Squid Ink^000000 and")
          |> mes("^3355FF1 Sticky Muscus^000000!")
          |> next()
          |> mes("[Cantata]")
          |> mes(
            "Wahhahaha! What the hell is that look for?! Never you mind my gourmet sense of taste! Now get to work~!"
          )
          |> close()

        throw({:script_end, ctx})
      end
    else
      ctx =
        ctx
        |> mes("[Cantata]")
        |> mes("Merry Christmas!")
        |> mes("Welcome to Lutie!")
        |> next()
        |> mes("[Cantata]")
        |> mes("It looks like the cold has brought a rosiness to your cheeks.")
        |> mes("Haw haw haw!")
        |> next()
        |> mes("[Cantata]")
        |> mes("Be careful, it wouldn't be good for you to catch the Lutie Flu.")
        |> mes("...")
        |> next()
        |> mes("[Cantata]")
        |> mes("*Sigh* That reminds me...")
        |> mes("My little boy had a terrible case of the Lutie Flu a while ago.")
        |> next()
        |> mes("[Cantata]")
        |> mes(
          "It was during the night, and there was no place I could get any medicine. It seemed I could do nothing for my little boy."
        )
        |> next()
        |> mes("[Cantata]")
        |> mes(
          "I thought the least I could do for my son was get something cold to bring down his fever, but the snow of Lutie kept on melting after being placed on his forehead. He was burning up, and I was failing to relieve him."
        )
        |> next()
        |> mes("[Cantata]")
        |> mes("It was then that")
        |> mes("I knew I needed")
        |> mes("some magic ice.")
        |> next()
        |> mes("[Cantata]")
        |> mes(
          "Eventually, I found myself in the Christmas dungeon without any goal in mind. Inside I found, thank God, a certain creature made entirely of ice!"
        )
        |> next()
        |> mes("[Cantata]")
        |> mes(
          "It was an ^3355FFIceporing^000000! The local people used to call it 'Icepantzering.' Anyway, I was able to save my boy's life with it. Thank goodness something like that was around in this town."
        )
        |> next()
        |> mes("[Cantata]")
        |> mes("Oops, I think I've talked a bit much. Merry Christmas~!")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
