defmodule Aesir.ZoneServer.Content.Npc.Rachel.KafraTeleportation do
  @moduledoc """
  Transpiled from rAthena re/kafras/Kafra_Teleportation_Services.txt:331 (Kafra Teleportation#rachel).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "rachel", x: 116, y: 139, dir: 5, sprite: 10242, name: "Kafra Teleportation"}]

  @impl true
  def on_talk(ctx) do
    {ctx, _} = Aesir.ZoneServer.Content.Npc.Functions.FKafteledoram.call(ctx, [9])
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
