defmodule Aesir.ZoneServer.Content.Npc.Rachel.RachelGuard do
  @moduledoc """
  Transpiled from rAthena cities/rachel.txt:195 (Rachel Guard#1aru::RaGuard).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "rachel",
        x: 268,
        y: 120,
        dir: 1,
        sprite: 934,
        name: "Rachel Guard",
        unique_name: "RaGuard"
      },
      %{map: "rachel", x: 125, y: 33, dir: 5, sprite: 934, name: "Rachel Guard"},
      %{map: "rachel", x: 31, y: 130, dir: 3, sprite: 934, name: "Rachel Guard"}
    ]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Rachel Guard]")
    |> mes("Welcome to Rachel")
    |> mes("the capital of Arunafeltz.")
    |> mes("Please ask our guide")
    |> mes("at the center of the city")
    |> mes("for information and")
    |> mes("guest services.")
    |> close()

    exit(:normal)
  end
end
