defmodule Aesir.ZoneServer.Content.Npc.Airplane.DomesticAirship do
  @moduledoc """
  Transpiled from rAthena airports/airships.txt:46 (Domestic_Airship).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc, spawn: []

  @impl true
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  def on_event("OnTimer20000", ctx), do: ev_ontimer20000(ctx)
  def on_event("OnTimer50000", ctx), do: ev_ontimer50000(ctx)
  def on_event("OnTimer60000", ctx), do: ev_ontimer60000(ctx)
  def on_event("OnTimer70000", ctx), do: ev_ontimer70000(ctx)
  def on_event("OnTimer80000", ctx), do: ev_ontimer80000(ctx)
  def on_event("OnTimer100000", ctx), do: ev_ontimer100000(ctx)
  def on_event("OnTimer130000", ctx), do: ev_ontimer130000(ctx)
  def on_event("OnTimer140000", ctx), do: ev_ontimer140000(ctx)
  def on_event("OnTimer150000", ctx), do: ev_ontimer150000(ctx)
  def on_event("OnTimer160000", ctx), do: ev_ontimer160000(ctx)
  def on_event("OnTimer180000", ctx), do: ev_ontimer180000(ctx)
  def on_event("OnTimer210000", ctx), do: ev_ontimer210000(ctx)
  def on_event("OnTimer220000", ctx), do: ev_ontimer220000(ctx)
  def on_event("OnTimer230000", ctx), do: ev_ontimer230000(ctx)
  def on_event("OnTimer240000", ctx), do: ev_ontimer240000(ctx)
  def on_event("OnTimer260000", ctx), do: ev_ontimer260000(ctx)
  def on_event("OnTimer290000", ctx), do: ev_ontimer290000(ctx)
  def on_event("OnTimer300000", ctx), do: ev_ontimer300000(ctx)
  def on_event("OnTimer310000", ctx), do: ev_ontimer310000(ctx)
  def on_event("OnTimer320000", ctx), do: ev_ontimer320000(ctx)
  def on_event("OnTimer340000", ctx), do: ev_ontimer340000(ctx)
  def on_event("OnTimer370000", ctx), do: ev_ontimer370000(ctx)
  def on_event("OnTimer380000", ctx), do: ev_ontimer380000(ctx)
  def on_event("OnTimer390000", ctx), do: ev_ontimer390000(ctx)
  def on_event("OnTimer400000", ctx), do: ev_ontimer400000(ctx)
  def on_event("OnTimer420000", ctx), do: ev_ontimer420000(ctx)
  def on_event("OnTimer450000", ctx), do: ev_ontimer450000(ctx)
  def on_event("OnTimer460000", ctx), do: ev_ontimer460000(ctx)
  def on_event("OnTimer470000", ctx), do: ev_ontimer470000(ctx)
  def on_event("OnTimer480000", ctx), do: ev_ontimer480000(ctx)
  @impl true
  def on_talk(_ctx) do
    exit(:normal)
  end

  def ev_oninit(ctx) do
    _ = initnpctimer(ctx)
    exit(:normal)
  end

  def ev_ontimer20000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Einbroch.", 1, "0x00ff00")
    exit(:normal)
  end

  def ev_ontimer50000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Einbroch shortly.", 1, "0x00ff00")
    exit(:normal)
  end

  def ev_ontimer60000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 1)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Einbroch. Have a safe trip.", 1, "0x00ff00")

    exit(:normal)
  end

  def ev_ontimer70000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Einbroch. The Airship will take off shortly.",
        1,
        "0x00ff00"
      )

    exit(:normal)
  end

  def ev_ontimer80000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is now taking off. Our next destination is Lighthalzen.",
      1,
      "0x70dbdb"
    )

    exit(:normal)
  end

  def ev_ontimer100000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Lighthalzen.", 1, "0x70dbdb")
    exit(:normal)
  end

  def ev_ontimer130000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Lighthalzen shortly.", 1, "0x70dbdb")
    exit(:normal)
  end

  def ev_ontimer140000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 2)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Lighthalzen. Have a safe trip.", 1, "0x70dbdb")

    exit(:normal)
  end

  def ev_ontimer150000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Lighthalzen. The Airship will leave shortly.",
        1,
        "0x70dbdb"
      )

    exit(:normal)
  end

  def ev_ontimer160000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is leaving the ground. Our next destination is Einbroch.",
      1,
      "0x00ff00"
    )

    exit(:normal)
  end

  def ev_ontimer180000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Einbroch.", 1, "0x00ff00")
    exit(:normal)
  end

  def ev_ontimer210000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Einbroch shortly.", 1, "0x00FF00")
    exit(:normal)
  end

  def ev_ontimer220000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 1)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Einbroch. Have a safe trip.", 1, "0x00ff00")

    exit(:normal)
  end

  def ev_ontimer230000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Einbroch. The Airship will take off shortly.",
        1,
        "0x00ff00"
      )

    exit(:normal)
  end

  def ev_ontimer240000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is now taking off. Our next destination is Juno.",
      1,
      "0xff8200"
    )

    exit(:normal)
  end

  def ev_ontimer260000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Juno.", 1, "0xff8200")
    exit(:normal)
  end

  def ev_ontimer290000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Juno shortly.", 1, "0xff8200")
    exit(:normal)
  end

  def ev_ontimer300000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 0)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Juno. Have a safe trip.", 1, "0xff8200")

    exit(:normal)
  end

  def ev_ontimer310000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Juno. The Airship will leave shortly.",
        1,
        "0xff8200"
      )

    exit(:normal)
  end

  def ev_ontimer320000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is leaving the ground. Our next destination is Hugel.",
      1,
      "0xca4bf3"
    )

    exit(:normal)
  end

  def ev_ontimer340000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Hugel.", 1, "0xca4bf3")
    exit(:normal)
  end

  def ev_ontimer370000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Hugel shortly.", 1, "0xca4bf3")
    exit(:normal)
  end

  def ev_ontimer380000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 3)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Hugel. Have a safe trip.", 1, "0xca4bf3")

    exit(:normal)
  end

  def ev_ontimer390000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Hugel. The Airship will leave shortly.",
        1,
        "0xca4bf3"
      )

    exit(:normal)
  end

  def ev_ontimer400000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is leaving the ground. Our next destination is Juno.",
      1,
      "0xff8200"
    )

    exit(:normal)
  end

  def ev_ontimer420000(ctx) do
    _ = mapannounce(ctx, "airplane", "We are heading to Juno.", 1, "0xff8200")
    exit(:normal)
  end

  def ev_ontimer450000(ctx) do
    _ = mapannounce(ctx, "airplane", "We will arrive in Juno shortly.", 1, "0xff8200")
    exit(:normal)
  end

  def ev_ontimer460000(ctx) do
    ctx
    |> set_server_temp_var("airplanelocation", 0)
    |> donpcevent("#AirshipWarp-1::OnUnhide")
    |> donpcevent("#AirshipWarp-2::OnUnhide")
    |> mapannounce("airplane", "Welcome to Juno. Have a safe trip.", 1, "0xff8200")

    exit(:normal)
  end

  def ev_ontimer470000(ctx) do
    _ =
      mapannounce(
        ctx,
        "airplane",
        "Currently we are in Juno. The Airship will leave shortly.",
        1,
        "0xff8200"
      )

    exit(:normal)
  end

  def ev_ontimer480000(ctx) do
    ctx
    |> donpcevent("#AirshipWarp-1::OnHide")
    |> donpcevent("#AirshipWarp-2::OnHide")
    |> mapannounce(
      "airplane",
      "The Airship is leaving the ground. Our next destination is Einbroch.",
      1,
      "0x00ff00"
    )
    |> stopnpctimer()
    |> initnpctimer()
  end
end
