defmodule Aesir.ZoneServer.Content.Npc.Airplane.Npc do
  @moduledoc """
  Transpiled from rAthena airports/airships.txt:21 (#AirshipWarp-1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{map: "airplane", x: 243, y: 73, dir: 0, sprite: 45, name: "", trigger: {1, 1}},
      %{map: "airplane", x: 243, y: 29, dir: 0, sprite: 45, name: "", trigger: {1, 1}}
    ]

  @impl true
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  def on_event("OnHide", ctx), do: ev_onhide(ctx)
  def on_event("OnUnhide", ctx), do: ev_onunhide(ctx)
  def on_event("OnTouch", ctx), do: ev_ontouch(ctx)
  @impl true
  def on_talk(_ctx) do
    exit(:normal)
  end

  def ev_oninit(ctx) do
    ctx
  end

  def ev_onhide(ctx) do
    ctx |> specialeffect(:bash) |> todo(:disablenpc, [])
    exit(:normal)
  end

  def ev_onunhide(ctx) do
    ctx |> todo(:enablenpc, []) |> specialeffect(:summonslave)
    exit(:normal)
  end

  def ev_ontouch(ctx) do
    v1 = get_server_temp_var(ctx, "airplanelocation", 0)

    ctx =
      case v1 do
        0 ->
          _ = warp(ctx, "yuno", 92, 260)
          exit(:normal)

        1 ->
          _ = warp(ctx, "einbroch", 92, 278)
          exit(:normal)

        2 ->
          _ = warp(ctx, "lighthalzen", 302, 75)
          exit(:normal)

        3 ->
          _ = warp(ctx, "hugel", 181, 146)
          exit(:normal)

        _ ->
          ctx
      end

    ctx
  end
end
