defmodule Aesir.ZoneServer.Mmo.JobManagement.Jobs do
  @moduledoc """
  Registry of all job definition modules.

  Each module implements `Aesir.ZoneServer.Mmo.JobManagement.Definition` and exposes `job/0`. The
  `@by_id` and `@by_name` maps resolve a job id/name to its module at compile
  time; the struct itself is built by calling `module.job/0`.
  """

  alias Aesir.ZoneServer.Mmo.JobManagement.Job
  alias Aesir.ZoneServer.Mmo.JobManagement.Jobs

  @modules [
    Jobs.Novice,
    Jobs.Swordman,
    Jobs.Mage,
    Jobs.Archer,
    Jobs.Acolyte,
    Jobs.Merchant,
    Jobs.Thief,
    Jobs.Knight,
    Jobs.Priest,
    Jobs.Wizard,
    Jobs.Blacksmith,
    Jobs.Hunter,
    Jobs.Assassin,
    Jobs.Knight2,
    Jobs.Crusader,
    Jobs.Monk,
    Jobs.Sage,
    Jobs.Rogue,
    Jobs.Alchemist,
    Jobs.Bard,
    Jobs.Dancer,
    Jobs.Crusader2,
    Jobs.SuperNovice,
    Jobs.Gunslinger,
    Jobs.Ninja,
    Jobs.NoviceHigh,
    Jobs.SwordmanHigh,
    Jobs.MageHigh,
    Jobs.ArcherHigh,
    Jobs.AcolyteHigh,
    Jobs.MerchantHigh,
    Jobs.ThiefHigh,
    Jobs.LordKnight,
    Jobs.HighPriest,
    Jobs.HighWizard,
    Jobs.Whitesmith,
    Jobs.Sniper,
    Jobs.AssassinCross,
    Jobs.LordKnight2,
    Jobs.Paladin,
    Jobs.Champion,
    Jobs.Professor,
    Jobs.Stalker,
    Jobs.Creator,
    Jobs.Clown,
    Jobs.Gypsy,
    Jobs.Paladin2,
    Jobs.Baby,
    Jobs.BabySwordman,
    Jobs.BabyMage,
    Jobs.BabyArcher,
    Jobs.BabyAcolyte,
    Jobs.BabyMerchant,
    Jobs.BabyThief,
    Jobs.BabyKnight,
    Jobs.BabyPriest,
    Jobs.BabyWizard,
    Jobs.BabyBlacksmith,
    Jobs.BabyHunter,
    Jobs.BabyAssassin,
    Jobs.BabyKnight2,
    Jobs.BabyCrusader,
    Jobs.BabyMonk,
    Jobs.BabySage,
    Jobs.BabyRogue,
    Jobs.BabyAlchemist,
    Jobs.BabyBard,
    Jobs.BabyDancer,
    Jobs.BabyCrusader2,
    Jobs.SuperBaby,
    Jobs.Taekwon,
    Jobs.StarGladiator,
    Jobs.StarGladiator2,
    Jobs.SoulLinker,
    Jobs.RuneKnight,
    Jobs.Warlock,
    Jobs.Ranger,
    Jobs.ArchBishop,
    Jobs.Mechanic,
    Jobs.GuillotineCross,
    Jobs.RuneKnightT,
    Jobs.WarlockT,
    Jobs.RangerT,
    Jobs.ArchBishopT,
    Jobs.MechanicT,
    Jobs.GuillotineCrossT,
    Jobs.RoyalGuard,
    Jobs.Sorcerer,
    Jobs.Minstrel,
    Jobs.Wanderer,
    Jobs.Sura,
    Jobs.Genetic,
    Jobs.ShadowChaser,
    Jobs.RoyalGuardT,
    Jobs.SorcererT,
    Jobs.MinstrelT,
    Jobs.WandererT,
    Jobs.SuraT,
    Jobs.GeneticT,
    Jobs.ShadowChaserT,
    Jobs.RuneKnight2,
    Jobs.RuneKnightT2,
    Jobs.RoyalGuard2,
    Jobs.RoyalGuardT2,
    Jobs.Ranger2,
    Jobs.RangerT2,
    Jobs.Mechanic2,
    Jobs.MechanicT2,
    Jobs.BabyRuneKnight,
    Jobs.BabyWarlock,
    Jobs.BabyRanger,
    Jobs.BabyArchBishop,
    Jobs.BabyMechanic,
    Jobs.BabyGuillotineCross,
    Jobs.BabyRoyalGuard,
    Jobs.BabySorcerer,
    Jobs.BabyMinstrel,
    Jobs.BabyWanderer,
    Jobs.BabySura,
    Jobs.BabyGenetic,
    Jobs.BabyShadowChaser,
    Jobs.BabyRuneKnight2,
    Jobs.BabyRoyalGuard2,
    Jobs.BabyRanger2,
    Jobs.BabyMechanic2,
    Jobs.SuperNoviceE,
    Jobs.SuperBabyE,
    Jobs.Kagerou,
    Jobs.Oboro,
    Jobs.Rebellion,
    Jobs.Summoner,
    Jobs.BabySummoner,
    Jobs.BabyNinja,
    Jobs.BabyKagerou,
    Jobs.BabyOboro,
    Jobs.BabyTaekwon,
    Jobs.BabyStarGladiator,
    Jobs.BabySoulLinker,
    Jobs.BabyGunslinger,
    Jobs.BabyRebellion,
    Jobs.BabyStarGladiator2,
    Jobs.StarEmperor,
    Jobs.SoulReaper,
    Jobs.BabyStarEmperor,
    Jobs.BabySoulReaper,
    Jobs.StarEmperor2,
    Jobs.BabyStarEmperor2,
    Jobs.DragonKnight,
    Jobs.Meister,
    Jobs.ShadowCross,
    Jobs.ArchMage,
    Jobs.Cardinal,
    Jobs.Windhawk,
    Jobs.ImperialGuard,
    Jobs.Biolo,
    Jobs.AbyssChaser,
    Jobs.ElementalMaster,
    Jobs.Inquisitor,
    Jobs.Troubadour,
    Jobs.Trouvere,
    Jobs.Windhawk2,
    Jobs.Meister2,
    Jobs.DragonKnight2,
    Jobs.ImperialGuard2,
    Jobs.SkyEmperor,
    Jobs.SoulAscetic,
    Jobs.Shinkiro,
    Jobs.Shiranui,
    Jobs.NightWatch,
    Jobs.HyperNovice,
    Jobs.SpiritHandler,
    Jobs.SkyEmperor2
  ]

  @by_id %{
    0 => Jobs.Novice,
    1 => Jobs.Swordman,
    2 => Jobs.Mage,
    3 => Jobs.Archer,
    4 => Jobs.Acolyte,
    5 => Jobs.Merchant,
    6 => Jobs.Thief,
    7 => Jobs.Knight,
    8 => Jobs.Priest,
    9 => Jobs.Wizard,
    10 => Jobs.Blacksmith,
    11 => Jobs.Hunter,
    12 => Jobs.Assassin,
    13 => Jobs.Knight2,
    14 => Jobs.Crusader,
    15 => Jobs.Monk,
    16 => Jobs.Sage,
    17 => Jobs.Rogue,
    18 => Jobs.Alchemist,
    19 => Jobs.Bard,
    20 => Jobs.Dancer,
    21 => Jobs.Crusader2,
    23 => Jobs.SuperNovice,
    24 => Jobs.Gunslinger,
    25 => Jobs.Ninja,
    4001 => Jobs.NoviceHigh,
    4002 => Jobs.SwordmanHigh,
    4003 => Jobs.MageHigh,
    4004 => Jobs.ArcherHigh,
    4005 => Jobs.AcolyteHigh,
    4006 => Jobs.MerchantHigh,
    4007 => Jobs.ThiefHigh,
    4008 => Jobs.LordKnight,
    4009 => Jobs.HighPriest,
    4010 => Jobs.HighWizard,
    4011 => Jobs.Whitesmith,
    4012 => Jobs.Sniper,
    4013 => Jobs.AssassinCross,
    4014 => Jobs.LordKnight2,
    4015 => Jobs.Paladin,
    4016 => Jobs.Champion,
    4017 => Jobs.Professor,
    4018 => Jobs.Stalker,
    4019 => Jobs.Creator,
    4020 => Jobs.Clown,
    4021 => Jobs.Gypsy,
    4022 => Jobs.Paladin2,
    4023 => Jobs.Baby,
    4024 => Jobs.BabySwordman,
    4025 => Jobs.BabyMage,
    4026 => Jobs.BabyArcher,
    4027 => Jobs.BabyAcolyte,
    4028 => Jobs.BabyMerchant,
    4029 => Jobs.BabyThief,
    4030 => Jobs.BabyKnight,
    4031 => Jobs.BabyPriest,
    4032 => Jobs.BabyWizard,
    4033 => Jobs.BabyBlacksmith,
    4034 => Jobs.BabyHunter,
    4035 => Jobs.BabyAssassin,
    4036 => Jobs.BabyKnight2,
    4037 => Jobs.BabyCrusader,
    4038 => Jobs.BabyMonk,
    4039 => Jobs.BabySage,
    4040 => Jobs.BabyRogue,
    4041 => Jobs.BabyAlchemist,
    4042 => Jobs.BabyBard,
    4043 => Jobs.BabyDancer,
    4044 => Jobs.BabyCrusader2,
    4045 => Jobs.SuperBaby,
    4046 => Jobs.Taekwon,
    4047 => Jobs.StarGladiator,
    4048 => Jobs.StarGladiator2,
    4049 => Jobs.SoulLinker,
    4054 => Jobs.RuneKnight,
    4055 => Jobs.Warlock,
    4056 => Jobs.Ranger,
    4057 => Jobs.ArchBishop,
    4058 => Jobs.Mechanic,
    4059 => Jobs.GuillotineCross,
    4060 => Jobs.RuneKnightT,
    4061 => Jobs.WarlockT,
    4062 => Jobs.RangerT,
    4063 => Jobs.ArchBishopT,
    4064 => Jobs.MechanicT,
    4065 => Jobs.GuillotineCrossT,
    4066 => Jobs.RoyalGuard,
    4067 => Jobs.Sorcerer,
    4068 => Jobs.Minstrel,
    4069 => Jobs.Wanderer,
    4070 => Jobs.Sura,
    4071 => Jobs.Genetic,
    4072 => Jobs.ShadowChaser,
    4073 => Jobs.RoyalGuardT,
    4074 => Jobs.SorcererT,
    4075 => Jobs.MinstrelT,
    4076 => Jobs.WandererT,
    4077 => Jobs.SuraT,
    4078 => Jobs.GeneticT,
    4079 => Jobs.ShadowChaserT,
    4080 => Jobs.RuneKnight2,
    4081 => Jobs.RuneKnightT2,
    4082 => Jobs.RoyalGuard2,
    4083 => Jobs.RoyalGuardT2,
    4084 => Jobs.Ranger2,
    4085 => Jobs.RangerT2,
    4086 => Jobs.Mechanic2,
    4087 => Jobs.MechanicT2,
    4096 => Jobs.BabyRuneKnight,
    4097 => Jobs.BabyWarlock,
    4098 => Jobs.BabyRanger,
    4099 => Jobs.BabyArchBishop,
    4100 => Jobs.BabyMechanic,
    4101 => Jobs.BabyGuillotineCross,
    4102 => Jobs.BabyRoyalGuard,
    4103 => Jobs.BabySorcerer,
    4104 => Jobs.BabyMinstrel,
    4105 => Jobs.BabyWanderer,
    4106 => Jobs.BabySura,
    4107 => Jobs.BabyGenetic,
    4108 => Jobs.BabyShadowChaser,
    4109 => Jobs.BabyRuneKnight2,
    4110 => Jobs.BabyRoyalGuard2,
    4111 => Jobs.BabyRanger2,
    4112 => Jobs.BabyMechanic2,
    4190 => Jobs.SuperNoviceE,
    4191 => Jobs.SuperBabyE,
    4211 => Jobs.Kagerou,
    4212 => Jobs.Oboro,
    4215 => Jobs.Rebellion,
    4218 => Jobs.Summoner,
    4220 => Jobs.BabySummoner,
    4222 => Jobs.BabyNinja,
    4223 => Jobs.BabyKagerou,
    4224 => Jobs.BabyOboro,
    4225 => Jobs.BabyTaekwon,
    4226 => Jobs.BabyStarGladiator,
    4227 => Jobs.BabySoulLinker,
    4228 => Jobs.BabyGunslinger,
    4229 => Jobs.BabyRebellion,
    4238 => Jobs.BabyStarGladiator2,
    4239 => Jobs.StarEmperor,
    4240 => Jobs.SoulReaper,
    4241 => Jobs.BabyStarEmperor,
    4242 => Jobs.BabySoulReaper,
    4243 => Jobs.StarEmperor2,
    4244 => Jobs.BabyStarEmperor2,
    4252 => Jobs.DragonKnight,
    4253 => Jobs.Meister,
    4254 => Jobs.ShadowCross,
    4255 => Jobs.ArchMage,
    4256 => Jobs.Cardinal,
    4257 => Jobs.Windhawk,
    4258 => Jobs.ImperialGuard,
    4259 => Jobs.Biolo,
    4260 => Jobs.AbyssChaser,
    4261 => Jobs.ElementalMaster,
    4262 => Jobs.Inquisitor,
    4263 => Jobs.Troubadour,
    4264 => Jobs.Trouvere,
    4278 => Jobs.Windhawk2,
    4279 => Jobs.Meister2,
    4280 => Jobs.DragonKnight2,
    4281 => Jobs.ImperialGuard2,
    4302 => Jobs.SkyEmperor,
    4303 => Jobs.SoulAscetic,
    4304 => Jobs.Shinkiro,
    4305 => Jobs.Shiranui,
    4306 => Jobs.NightWatch,
    4307 => Jobs.HyperNovice,
    4308 => Jobs.SpiritHandler,
    4316 => Jobs.SkyEmperor2
  }

  @by_name %{
    :abyss_chaser => Jobs.AbyssChaser,
    :acolyte => Jobs.Acolyte,
    :acolyte_high => Jobs.AcolyteHigh,
    :alchemist => Jobs.Alchemist,
    :arch_bishop => Jobs.ArchBishop,
    :arch_bishop_t => Jobs.ArchBishopT,
    :arch_mage => Jobs.ArchMage,
    :archer => Jobs.Archer,
    :archer_high => Jobs.ArcherHigh,
    :assassin => Jobs.Assassin,
    :assassin_cross => Jobs.AssassinCross,
    :baby => Jobs.Baby,
    :baby_acolyte => Jobs.BabyAcolyte,
    :baby_alchemist => Jobs.BabyAlchemist,
    :baby_arch_bishop => Jobs.BabyArchBishop,
    :baby_archer => Jobs.BabyArcher,
    :baby_assassin => Jobs.BabyAssassin,
    :baby_bard => Jobs.BabyBard,
    :baby_blacksmith => Jobs.BabyBlacksmith,
    :baby_crusader => Jobs.BabyCrusader,
    :baby_crusader2 => Jobs.BabyCrusader2,
    :baby_dancer => Jobs.BabyDancer,
    :baby_genetic => Jobs.BabyGenetic,
    :baby_guillotine_cross => Jobs.BabyGuillotineCross,
    :baby_gunslinger => Jobs.BabyGunslinger,
    :baby_hunter => Jobs.BabyHunter,
    :baby_kagerou => Jobs.BabyKagerou,
    :baby_knight => Jobs.BabyKnight,
    :baby_knight2 => Jobs.BabyKnight2,
    :baby_mage => Jobs.BabyMage,
    :baby_mechanic => Jobs.BabyMechanic,
    :baby_mechanic2 => Jobs.BabyMechanic2,
    :baby_merchant => Jobs.BabyMerchant,
    :baby_minstrel => Jobs.BabyMinstrel,
    :baby_monk => Jobs.BabyMonk,
    :baby_ninja => Jobs.BabyNinja,
    :baby_oboro => Jobs.BabyOboro,
    :baby_priest => Jobs.BabyPriest,
    :baby_ranger => Jobs.BabyRanger,
    :baby_ranger2 => Jobs.BabyRanger2,
    :baby_rebellion => Jobs.BabyRebellion,
    :baby_rogue => Jobs.BabyRogue,
    :baby_royal_guard => Jobs.BabyRoyalGuard,
    :baby_royal_guard2 => Jobs.BabyRoyalGuard2,
    :baby_rune_knight => Jobs.BabyRuneKnight,
    :baby_rune_knight2 => Jobs.BabyRuneKnight2,
    :baby_sage => Jobs.BabySage,
    :baby_shadow_chaser => Jobs.BabyShadowChaser,
    :baby_sorcerer => Jobs.BabySorcerer,
    :baby_soul_linker => Jobs.BabySoulLinker,
    :baby_soul_reaper => Jobs.BabySoulReaper,
    :baby_star_emperor => Jobs.BabyStarEmperor,
    :baby_star_emperor2 => Jobs.BabyStarEmperor2,
    :baby_star_gladiator => Jobs.BabyStarGladiator,
    :baby_star_gladiator2 => Jobs.BabyStarGladiator2,
    :baby_summoner => Jobs.BabySummoner,
    :baby_sura => Jobs.BabySura,
    :baby_swordman => Jobs.BabySwordman,
    :baby_taekwon => Jobs.BabyTaekwon,
    :baby_thief => Jobs.BabyThief,
    :baby_wanderer => Jobs.BabyWanderer,
    :baby_warlock => Jobs.BabyWarlock,
    :baby_wizard => Jobs.BabyWizard,
    :bard => Jobs.Bard,
    :biolo => Jobs.Biolo,
    :blacksmith => Jobs.Blacksmith,
    :cardinal => Jobs.Cardinal,
    :champion => Jobs.Champion,
    :clown => Jobs.Clown,
    :creator => Jobs.Creator,
    :crusader => Jobs.Crusader,
    :crusader2 => Jobs.Crusader2,
    :dancer => Jobs.Dancer,
    :dragon_knight => Jobs.DragonKnight,
    :dragon_knight2 => Jobs.DragonKnight2,
    :elemental_master => Jobs.ElementalMaster,
    :genetic => Jobs.Genetic,
    :genetic_t => Jobs.GeneticT,
    :guillotine_cross => Jobs.GuillotineCross,
    :guillotine_cross_t => Jobs.GuillotineCrossT,
    :gunslinger => Jobs.Gunslinger,
    :gypsy => Jobs.Gypsy,
    :high_priest => Jobs.HighPriest,
    :high_wizard => Jobs.HighWizard,
    :hunter => Jobs.Hunter,
    :hyper_novice => Jobs.HyperNovice,
    :imperial_guard => Jobs.ImperialGuard,
    :imperial_guard2 => Jobs.ImperialGuard2,
    :inquisitor => Jobs.Inquisitor,
    :kagerou => Jobs.Kagerou,
    :knight => Jobs.Knight,
    :knight2 => Jobs.Knight2,
    :lord_knight => Jobs.LordKnight,
    :lord_knight2 => Jobs.LordKnight2,
    :mage => Jobs.Mage,
    :mage_high => Jobs.MageHigh,
    :mechanic => Jobs.Mechanic,
    :mechanic2 => Jobs.Mechanic2,
    :mechanic_t => Jobs.MechanicT,
    :mechanic_t2 => Jobs.MechanicT2,
    :meister => Jobs.Meister,
    :meister2 => Jobs.Meister2,
    :merchant => Jobs.Merchant,
    :merchant_high => Jobs.MerchantHigh,
    :minstrel => Jobs.Minstrel,
    :minstrel_t => Jobs.MinstrelT,
    :monk => Jobs.Monk,
    :night_watch => Jobs.NightWatch,
    :ninja => Jobs.Ninja,
    :novice => Jobs.Novice,
    :novice_high => Jobs.NoviceHigh,
    :oboro => Jobs.Oboro,
    :paladin => Jobs.Paladin,
    :paladin2 => Jobs.Paladin2,
    :priest => Jobs.Priest,
    :professor => Jobs.Professor,
    :ranger => Jobs.Ranger,
    :ranger2 => Jobs.Ranger2,
    :ranger_t => Jobs.RangerT,
    :ranger_t2 => Jobs.RangerT2,
    :rebellion => Jobs.Rebellion,
    :rogue => Jobs.Rogue,
    :royal_guard => Jobs.RoyalGuard,
    :royal_guard2 => Jobs.RoyalGuard2,
    :royal_guard_t => Jobs.RoyalGuardT,
    :royal_guard_t2 => Jobs.RoyalGuardT2,
    :rune_knight => Jobs.RuneKnight,
    :rune_knight2 => Jobs.RuneKnight2,
    :rune_knight_t => Jobs.RuneKnightT,
    :rune_knight_t2 => Jobs.RuneKnightT2,
    :sage => Jobs.Sage,
    :shadow_chaser => Jobs.ShadowChaser,
    :shadow_chaser_t => Jobs.ShadowChaserT,
    :shadow_cross => Jobs.ShadowCross,
    :shinkiro => Jobs.Shinkiro,
    :shiranui => Jobs.Shiranui,
    :sky_emperor => Jobs.SkyEmperor,
    :sky_emperor2 => Jobs.SkyEmperor2,
    :sniper => Jobs.Sniper,
    :sorcerer => Jobs.Sorcerer,
    :sorcerer_t => Jobs.SorcererT,
    :soul_ascetic => Jobs.SoulAscetic,
    :soul_linker => Jobs.SoulLinker,
    :soul_reaper => Jobs.SoulReaper,
    :spirit_handler => Jobs.SpiritHandler,
    :stalker => Jobs.Stalker,
    :star_emperor => Jobs.StarEmperor,
    :star_emperor2 => Jobs.StarEmperor2,
    :star_gladiator => Jobs.StarGladiator,
    :star_gladiator2 => Jobs.StarGladiator2,
    :summoner => Jobs.Summoner,
    :super_baby => Jobs.SuperBaby,
    :super_baby_e => Jobs.SuperBabyE,
    :super_novice => Jobs.SuperNovice,
    :super_novice_e => Jobs.SuperNoviceE,
    :sura => Jobs.Sura,
    :sura_t => Jobs.SuraT,
    :swordman => Jobs.Swordman,
    :swordman_high => Jobs.SwordmanHigh,
    :taekwon => Jobs.Taekwon,
    :thief => Jobs.Thief,
    :thief_high => Jobs.ThiefHigh,
    :troubadour => Jobs.Troubadour,
    :trouvere => Jobs.Trouvere,
    :wanderer => Jobs.Wanderer,
    :wanderer_t => Jobs.WandererT,
    :warlock => Jobs.Warlock,
    :warlock_t => Jobs.WarlockT,
    :whitesmith => Jobs.Whitesmith,
    :windhawk => Jobs.Windhawk,
    :windhawk2 => Jobs.Windhawk2,
    :wizard => Jobs.Wizard
  }

  @doc "Returns all job definition modules."
  @spec modules() :: [module()]
  def modules, do: @modules

  @doc "Returns all job structs."
  @spec all() :: [Job.t()]
  def all, do: Enum.map(@modules, & &1.job())

  @doc "Resolves a job struct by id."
  @spec by_id(integer()) :: {:ok, Job.t()} | :error
  def by_id(id) do
    case Map.fetch(@by_id, id) do
      {:ok, module} -> {:ok, module.job()}
      :error -> :error
    end
  end

  @doc "Resolves a job struct by name."
  @spec by_name(atom()) :: {:ok, Job.t()} | :error
  def by_name(name) do
    case Map.fetch(@by_name, name) do
      {:ok, module} -> {:ok, module.job()}
      :error -> :error
    end
  end
end
