defmodule Aesir.ZoneServer.Content.Npc.Mora.RelievedRaffle do
  @moduledoc """
  Transpiled from rAthena re/cities/mora.txt:116 (Relieved Raffle#podo).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "mora", x: 102, y: 107, dir: 5, sprite: 517, name: "Relieved Raffle"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Relieved Raffle]")
    |> mes("Wow~!")
    |> mes("This is exciting.")
    |> mes("He woke up safe and sound again!")
    |> mes("Well, I'm sure he will next time!")
    |> mes("...")
    |> next()
    |> mes("[Relieved Raffle]")
    |> mes("Eh?")
    |> close()
  end
end
