defmodule Aesir.ZoneServer.Content.Npc.Cities.Manuk.Mechanic do
  @moduledoc """
  Transpiled from rAthena cities/manuk.txt:503 (Mechanic#ep13bs).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "man_in01",
        x: 360,
        y: 137,
        dir: 5,
        sprite: 454,
        name: "Mechanic",
        unique_name: "Mechanic#ep13bs"
      }
    ]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) == 1 do
      ctx =
        ctx
        |> mes("[Mechanic]")
        |> mes("Alien races are not allowed to enter.")
        |> mes("It's very dangerous here, please don't come any closer.")
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx |> mes("[Asoui]") |> mes("Fs iua sdjosow ww ") |> mes("Adds wwpq iusnd ") |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
