defmodule Aesir.ZoneServer.Content.Npc.Cities.Manuk.Soldier do
  @moduledoc """
  Transpiled from rAthena cities/manuk.txt:20 (Soldier#ep13pa829).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "manuk",
        x: 304,
        y: 195,
        dir: 5,
        sprite: 454,
        name: "Soldier",
        unique_name: "Soldier#ep13pa829"
      }
    ]

  @impl true
  def on_talk(ctx) do
    if is_equipped(ctx, 2782) == 1 do
      ctx =
        ctx
        |> mes("[Food Provider]")
        |> mes(
          "The Manuk family subsists mostly on refining Gray Hollows that were buried a long time ago deep down under the ground."
        )
        |> close()

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Food Provider]")
        |> mes("Gdiios duuie Dssoas pogggd fdrul fdddoweet")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
