defmodule Aesir.ZoneServer.Content.Npc.Functions.FGetarmortype do
  @moduledoc """
  Transpiled from rAthena other/Global_Functions.txt:291 (F_GetArmorType).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, args) do
    try do
      v1 = get_char_var(ctx, :EQP_HEAD_LOW, 0)
      v2 = get_char_var(ctx, :EQP_HAND_R, 0)
      v3 = get_char_var(ctx, :EQP_GARMENT, 0)
      v4 = get_char_var(ctx, :EQP_ACC_L, 0)
      v5 = get_char_var(ctx, :EQP_ACC_R, 0)
      v6 = get_char_var(ctx, :EQP_ACC_RL, 0)
      v7 = get_char_var(ctx, :EQP_ARMOR, 0)
      v8 = get_char_var(ctx, :EQP_HAND_L, 0)
      v9 = get_char_var(ctx, :EQP_SHOES, 0)
      v10 = get_char_var(ctx, :EQP_HEAD_TOP, 0)
      v11 = get_char_var(ctx, :EQP_HEAD_MID, 0)
      v12 = get_char_var(ctx, :EQP_COSTUME_HEAD_TOP, 0)
      v13 = get_char_var(ctx, :EQP_COSTUME_HEAD_MID, 0)
      v14 = get_char_var(ctx, :EQP_COSTUME_HEAD_LOW, 0)
      v15 = get_char_var(ctx, :EQP_COSTUME_GARMENT, 0)
      v16 = get_char_var(ctx, :EQP_AMMO, 0)
      v17 = get_char_var(ctx, :EQP_SHADOW_ARMOR, 0)
      v18 = get_char_var(ctx, :EQP_SHADOW_WEAPON, 0)
      v19 = get_char_var(ctx, :EQP_SHADOW_SHIELD, 0)
      v20 = get_char_var(ctx, :EQP_SHADOW_SHOES, 0)
      v21 = get_char_var(ctx, :EQP_SHADOW_ACC_R, 0)
      v22 = get_char_var(ctx, :EQP_SHADOW_ACC_L, 0)
      v23 = get_char_var(ctx, :EQP_SHADOW_ACC_RL, 0)
      v25 = getiteminfo(ctx, Enum.at(args, 0, 0), 5)

      case v25 do
        v when v == v1 ->
          throw({:script_return, {ctx, "Lower Headgear"}})

        v when v == v2 ->
          {ctx, v24} =
            Aesir.ZoneServer.Content.Npc.Functions.FGetweapontype.call(ctx, [Enum.at(args, 0, 0)])

          throw({:script_return, {ctx, v24}})

        v when v == v3 ->
          throw({:script_return, {ctx, "Garment"}})

        v when v == v4 or v == v5 or v == v6 ->
          throw({:script_return, {ctx, "Accessory"}})

        v when v == v7 ->
          throw({:script_return, {ctx, "Armor"}})

        v when v == v8 ->
          throw({:script_return, {ctx, "Shield"}})

        v when v == v9 ->
          throw({:script_return, {ctx, "Shoes"}})

        v when v == v10 ->
          throw({:script_return, {ctx, "Upper Headgear"}})

        v when v == v11 ->
          throw({:script_return, {ctx, "Middle Headgear"}})

        v when v == v12 ->
          throw({:script_return, {ctx, "Costume Upper Headgear"}})

        v when v == v13 ->
          throw({:script_return, {ctx, "Costume Midle Headgear"}})

        v when v == v14 ->
          throw({:script_return, {ctx, "Costume Lower Headgear"}})

        v when v == v15 ->
          throw({:script_return, {ctx, "Costume Garment"}})

        v when v == v16 ->
          throw({:script_return, {ctx, "Ammo"}})

        v when v == v17 ->
          throw({:script_return, {ctx, "Shadow Armor"}})

        v when v == v18 ->
          throw({:script_return, {ctx, "Shadow Weapon"}})

        v when v == v19 ->
          throw({:script_return, {ctx, "Shadow Shield"}})

        v when v == v20 ->
          throw({:script_return, {ctx, "Shadow Shoes"}})

        v when v == v21 or v == v22 or v == v23 ->
          throw({:script_return, {ctx, "Shadow Accessory"}})

        _ ->
          throw({:script_return, {ctx, "Unknown Equip"}})
      end
    catch
      :throw, {:script_return, result} -> result
    end
  end
end
