defmodule Aesir.ZoneServer.Content.Npc.Functions.FHi do
  @moduledoc """
  Transpiled from rAthena other/Global_Functions.txt:180 (F_Hi).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, _args) do
    {ctx, v1} =
      Aesir.ZoneServer.Content.Npc.Functions.FRand.call(ctx, [
        "Hi!",
        "Hello!",
        "Good day!",
        "How are you?",
        "Hello there."
      ])

    {ctx, v1}
  end
end
