defmodule Aesir.ZoneServer.Content.Npc.Functions.FItemname do
  @moduledoc """
  Transpiled from rAthena other/Global_Functions.txt:196 (F_ItemName).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false
  alias Aesir.ZoneServer.Script.Rathena
  alias Aesir.ZoneServer.Script.Todo

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, args) do
    ctx =
      if Rathena.truthy?(Enum.at(args, 3, 0)) do
        set_local(ctx, :"t$", Rathena.concat(Rathena.concat("+", Enum.at(args, 3, 0)), " "))
      else
        ctx
      end

    v1 = Enum.at(args, 2, 0)

    ctx =
      case v1 do
        0 ->
          ctx

        1 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "VS "))

        2 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "VVS "))

        3 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "VVVS "))

        _ ->
          set_local(
            ctx,
            :"t$",
            Rathena.concat(Rathena.concat(get_local(ctx, :"t$", ""), Enum.at(args, 2, 0)), "xVS ")
          )
      end

    v2 = Enum.at(args, 1, 0)

    ctx =
      case v2 do
        0 ->
          ctx

        1 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "Ice "))

        2 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "Earth "))

        3 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "Fire "))

        4 ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "Wind "))

        _ ->
          set_local(ctx, :"t$", Rathena.concat(get_local(ctx, :"t$", ""), "Strange "))
      end

    {ctx,
     Rathena.concat(
       Rathena.concat(
         Rathena.concat("^000090", get_local(ctx, :"t$", "")),
         Todo.call!(:getitemname, [Enum.at(args, 0, 0)])
       ),
       "^000000"
     )}
  end
end
