defmodule Aesir.ZoneServer.Content.Npc.Functions.FMalayaWarp do
  @moduledoc """
  Transpiled from rAthena re/warps/cities/malaya.txt:94 (F_Malaya_Warp).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false
  alias Aesir.ZoneServer.Script.Rathena

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, args) do
    {ctx, v1} =
      ctx
      |> mes("Where would you like to go?")
      |> next()
      |> select(
        Enum.flat_map(
          [
            "Back outside",
            Rathena.concat(Enum.at(args, 1, 0), " Jeepney"),
            Rathena.concat(Enum.at(args, 2, 0), " Jeepney")
          ],
          &String.split(&1, ":")
        )
      )

    ctx = ctx |> set_local(:"i$", Enum.at(args, v1 - 1, 0)) |> close()
    v2 = Enum.at(args, 3, 0)

    ctx =
      case v2 do
        1 ->
          ctx =
            if get_local(ctx, :"i$", "") == "Center" do
              warp(ctx, "malaya", 241, 238)
            else
              ctx
            end

          ctx =
            if get_local(ctx, :"i$", "") == "Southwest" do
              warp(ctx, "malaya", 71, 43)
            else
              ctx =
                if get_local(ctx, :"i$", "") == "Southeast" do
                  warp(ctx, "malaya", 284, 129)
                else
                  ctx
                end

              ctx
            end

          ctx

        2 ->
          ctx =
            if get_local(ctx, :"i$", "") == "Northwest" do
              warp(ctx, "malaya", 134, 247)
            else
              ctx =
                if get_local(ctx, :"i$", "") == "Southeast" do
                  warp(ctx, "malaya", 341, 150)
                else
                  ctx =
                    if get_local(ctx, :"i$", "") == "Northeast" do
                      warp(ctx, "malaya", 294, 293)
                    else
                      ctx
                    end

                  ctx
                end

              ctx
            end

          ctx

        3 ->
          ctx =
            if get_local(ctx, :"i$", "") == "Center" do
              warp(ctx, "malaya", 239, 221)
            else
              ctx =
                if get_local(ctx, :"i$", "") == "Northwest" do
                  warp(ctx, "malaya", 59, 246)
                else
                  ctx =
                    if get_local(ctx, :"i$", "") == "Southeast" do
                      warp(ctx, "malaya", 254, 68)
                    else
                      ctx
                    end

                  ctx
                end

              ctx
            end

          ctx

        _ ->
          ctx
      end

    throw({:script_end, ctx})
  end
end
