defmodule Aesir.ZoneServer.Content.Npc.Functions.Randomw do
  @moduledoc """
  Transpiled from rAthena warps/dungeons/lhz_dun.txt:208 (randomw).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  import Aesir.ZoneServer.Script.Dsl, warn: false

  @doc "Callable rAthena global function; returns `{ctx, return_value}`."
  def call(ctx, _args) do
    v1 = :rand.uniform(3) - 1

    case v1 do
      1 ->
        ctx = warp(ctx, "lhz_cube", 66, 136)
        throw({:script_end, ctx})

      2 ->
        ctx = warp(ctx, "lhz_cube", 66, 74)
        throw({:script_end, ctx})

      _ ->
        ctx = warp(ctx, "lhz_cube", 67, 193)
        throw({:script_end, ctx})
    end
  end
end
