defmodule Aesir.ZoneServer.Content.Npc.JawaiiIn.Employee do
  @moduledoc """
  Transpiled from rAthena cities/jawaii.txt:438 (Employee#jaw1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "jawaii_in", x: 25, y: 94, dir: 0, sprite: 724, name: "Employee"}]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnWelcome", ctx) do
    ev_onwelcome(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnSolo", ctx) do
    ev_onsolo(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx = ctx |> mes("[Employee Tryteh]") |> mes("Welcome to Jawaii Tavern~")

    ctx =
      if Rathena.truthy?(getpartnerid(ctx)) do
        ctx =
          ctx
          |> mes(
            "Anyway, I am so glad that you two have gotten married. I hope you both will live happily ever after~"
          )
          |> next()
          |> mes("[Employee Tryteh]")
          |> mes("Try to be a little careful if you bump into any rude customers.")
          |> mes("They might be drunk and do something stupid. You know")
          |> mes("how it is...")
          |> close()

        throw({:script_end, ctx})
      else
        ctx =
          if not Rathena.truthy?(getpartnerid(ctx)) do
            ctx =
              ctx
              |> mes("I hope you enjoy your stay")
              |> mes("over here. But try not")
              |> mes("to drink too much~")
              |> close()

            throw({:script_end, ctx})
          else
            ctx
          end

        ctx
      end

    ctx |> mes("I hope you will have a good time.") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_onwelcome(ctx) do
    emotion(ctx, :chup)
  end

  def ev_onsolo(ctx) do
    emotion(ctx, :huk)
  end
end
