defmodule Aesir.ZoneServer.Content.Npc.Quests.FirstClass.TuAcolyte.Boy do
  @moduledoc """
  Transpiled from rAthena quests/first_class/tu_acolyte.txt:986 (Boy#boy_voi).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "prt_monk",
        x: 243,
        y: 238,
        dir: 5,
        sprite: 139,
        name: "Boy",
        unique_name: "Boy#boy_voi",
        trigger: {5, 5}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx) do
    ev_ontouch(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if get_char_var(ctx, :tu_acolyte01, 0) != 10 do
        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("[??]") |> mes("^333333*Sniff*^000000") |> mes("Sister...") |> close()
  end
end
