defmodule Aesir.ZoneServer.Content.Npc.Quests.FirstClass.TuAcolyte.Npc do
  @moduledoc """
  Transpiled from rAthena quests/first_class/tu_acolyte.txt:1576 (#tu_monk).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "prt_monk",
        x: 217,
        y: 123,
        dir: 0,
        sprite: 139,
        name: "",
        unique_name: "#tu_monk",
        trigger: {10, 10}
      }
    ]

  @impl true
  def on_event("OnTouch", ctx) do
    ev_ontouch(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_ontouch(ctx) do
    ctx =
      if base_job(ctx) == :acolyte do
        v1 = get_char_var(ctx, :tu_acolyte01, 0)

        ctx =
          case v1 do
            v when v in [4, 10, 25] ->
              ctx =
                ctx
                |> mes("[Sound by Window]")
                |> mes("...")
                |> next()
                |> mes("^3355FFThere's some kind")
                |> mes("of noise coming from")
                |> mes("yonder window...^000000")
                |> close()

              throw({:script_end, ctx})

            _ ->
              ctx
          end

        ctx
      else
        ctx
      end

    ctx
  end
end
