defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22.Monk.Bashu do
  @moduledoc """
  Transpiled from rAthena jobs/2-2/monk.txt:1884 (Bashu#mk).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "monk_test",
        x: 329,
        y: 61,
        dir: 3,
        sprite: 753,
        name: "Bashu",
        scope: :shared,
        unique_name: "Bashu#mk"
      }
    ]

  @impl true
  def on_talk(ctx) do
    if get_char_var(ctx, :MONK_Q, 0) > 14 and get_char_var(ctx, :MONK_Q, 0) < 25 do
      ctx =
        if get_char_var(ctx, :MONK_Q, 0) == 15 do
          ctx
          |> mes("[Bashu]")
          |> mes("So, which test do you want to do...?")
          |> next()
          |> mes("[Bashu]")
          |> mes("From what I've heard, you chose the mushroom test...")
          |> mes("Oh well, it's still your choice.")
        else
          ctx =
            if get_char_var(ctx, :MONK_Q, 0) == 16 do
              ctx
              |> mes("[Bashu]")
              |> mes("Which test hall do you wish to enter?")
              |> next()
              |> mes("[Bashu]")
              |> mes("Well, as far as I've been told, you chose the marathon test...")
              |> mes("Oh well, it's your choice.")
            else
              ctx
              |> mes("[Bashu]")
              |> mes("Which test hall do you wish to enter?")
              |> mes("You can choose which one you want.")
              |> next()
            end

          ctx
        end

      {ctx, v1} =
        ctx |> next() |> select(["Tolerance - Gathering Mushrooms", "Self-Control - Marathon"])

      ctx =
        if v1 == 1 do
          ctx =
            ctx
            |> mes(
              "You have decided to take the test of tolerance by ^FF0000gathering mushrooms^000000."
            )
            |> close()
            |> warp("job_monk", 226, 175)

          throw({:script_end, ctx})
        else
          ctx
        end

      ctx =
        ctx
        |> mes(
          "You have decided to take the test of self control by taking a ^FF0000marathon^000000."
        )
        |> close()
        |> warp("monk_test", 386, 387)

      throw({:script_end, ctx})
    else
      ctx =
        ctx
        |> mes("[Bashu]")
        |> mes("Welcome... this place is a training place for monks, Saint Capitolina Abbey.")
        |> mes(
          "When you go inside....you will meet Tomoon the oldest monk who succeeds to the predecessors,"
        )
        |> next()
        |> mes("[Bashu]")
        |> mes("Please be advised and do not touch anything.")
        |> mes("And please avoid talking loud in front of Tomoon.")
        |> next()
        |> mes("[Bashu]")
        |> mes("I hope you will have a great time in here.")
        |> close()

      throw({:script_end, ctx})
    end
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
