defmodule Aesir.ZoneServer.Content.Npc.Jobs.M22.Monk.Proctor9585 do
  @moduledoc """
  Transpiled from rAthena jobs/2-2/monk.txt:2446 (Proctor#btl#3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "monk_test",
        x: 95,
        y: 85,
        dir: 1,
        sprite: 79,
        name: "Proctor",
        unique_name: "Proctor#btl#3"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("[Proctor]")
      |> mes("So, are you ready to undergo this spiritual training?")
      |> next()
      |> select(["Yes!", "No.", "Check the caution for the test."])

    ctx =
      case v1 do
        1 ->
          ctx =
            ctx
            |> mes("[Proctor]")
            |> mes(
              "Alright! I wish you luck. If you get lost and can't find a way out, simply log out and log back in."
            )
            |> mes(
              "Then you will return to your save point. What's that mean? Heck if I know, I'm just told to say that. Oh yes and also, please cooperate with your comrades."
            )
            |> close()
            |> set_char_var(:MONK_Q, 26)
            |> warp("monk_test", 230, 277)

          throw({:script_end, ctx})

        2 ->
          ctx = ctx |> mes("[Proctor]") |> mes("I see. Take your time.") |> close()
          throw({:script_end, ctx})

        3 ->
          ctx =
            ctx
            |> mes("[Proctor]")
            |> mes("Inside this test hall is the maze of spirits.")
            |> mes("There are spirits inside which will block you from moving freely.")
            |> next()
            |> mes("[Proctor]")
            |> mes(
              "If you want to exit the test hall, you must make your way to the warp portal located at the opposite side from the start point."
            )
            |> next()
            |> mes("[Proctor]")
            |> mes(
              "....Oh yes and also there are monsters wandering around in the maze, please clear them."
            )
            |> mes("Good luck.")
            |> close()

          throw({:script_end, ctx})

        _ ->
          ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
