defmodule Aesir.ZoneServer.Content.Npc.Dicastes01.FreeVenknick do
  @moduledoc """
  Transpiled from rAthena re/cities/dicastes.txt:516 (Free Venknick#a).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "dicastes01", x: 246, y: 210, dir: 3, sprite: 449, name: "Free Venknick"}]

  alias Aesir.ZoneServer.Script.Rathena

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Free Venknick]")

    ctx =
      if Rathena.truthy?(is_equipped(ctx, 2782)) do
        ctx =
          ctx
          |> mes("At least we have plenty of Bradium.")
          |> mes("Look,")
          |> mes("You can see Bradium")
          |> mes("everywhere you go.")
          |> next()
          |> mes("[Free Venknick]")
          |> mes("?")
          |> next()
          |> mes("[Free Venknick]")
          |> mes("The thing rolling around is a gem,")
          |> mes("but why are you interested in it?")
          |> close()

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx
    |> mes("???ï¢£ ?? ?????? ?? ????")
    |> mes("????")
    |> mes("?????? ?? ??????")
    |> mes("?????? ?? ?????? ??")
    |> next()
    |> mes("[Free Venknick]")
    |> mes("??")
    |> next()
    |> mes("[Free Venknick]")
    |> mes("?????? ?? ?????? ?? ????")
    |> mes("?????? ?? ?????? ?? ?????? ????")
    |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
