defmodule Aesir.ZoneServer.Content.Npc.Jobs.M21.Priest.MummyGenerator do
  @moduledoc """
  Transpiled from rAthena jobs/2-1/priest.txt:1613 (Mummy_Generator).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "job_prist",
        x: 1,
        y: 2,
        dir: 1,
        sprite: 110,
        name: "Mummy_Generator",
        trigger: {1, 1}
      }
    ]

  @impl true
  def on_event("OnInit", ctx), do: ev_oninit(ctx)
  def on_event("OnEnable", ctx), do: ev_onenable(ctx)
  def on_event("Onm1", ctx), do: ev_onm1(ctx)
  def on_event("Onm2", ctx), do: ev_onm2(ctx)
  def on_event("Onm3", ctx), do: ev_onm3(ctx)
  def on_event("OnDisable", ctx), do: ev_ondisable(ctx)
  @impl true
  def on_talk(ctx) do
    ctx
  end

  def ev_oninit(ctx) do
    disablenpc(ctx, "Mummy_Generator")
  end

  def ev_onenable(ctx) do
    ctx
    |> donpcevent("Mummy1_1::OnEnable")
    |> donpcevent("Mummy2_1::OnEnable")
    |> donpcevent("Mummy3_1::OnEnable")
  end

  def ev_onm1(ctx) do
    ctx
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {90, 55})
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {105, 55})
  end

  def ev_onm2(ctx) do
    ctx
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {90, 70})
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {105, 70})
  end

  def ev_onm3(ctx) do
    ctx
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {90, 85})
    |> summon_mob(mob_id: 1041, map: "job_prist", at: {105, 85})
  end

  def ev_ondisable(ctx) do
    ctx |> disablenpc("Mummy_Generator") |> killmonsterall("job_prist")
  end
end
