defmodule Aesir.ZoneServer.Content.Npc.Jobs.M21.Priest.PeterSAlberto do
  @moduledoc """
  Transpiled from rAthena jobs/2-1/priest.txt:847 (Peter S. Alberto).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "job_prist",
        x: 24,
        y: 187,
        dir: 4,
        sprite: 110,
        name: "Peter S. Alberto",
        scope: :shared
      }
    ]

  alias Aesir.ZoneServer.Script.Rathena
  @impl true
  def on_event("OnEnable", ctx) do
    ev_onenable(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def on_event("OnDisable", ctx) do
    ev_ondisable(ctx)
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  @impl true
  def on_talk(ctx) do
    ctx = mes(ctx, "[Father Peter]")

    ctx =
      if base_job(ctx) == :priest do
        ctx = mes(ctx, "Welcome!")

        ctx =
          if sex(ctx) == get_char_var(ctx, :SEX_MALE, 0) do
            mes(ctx, Rathena.concat(Rathena.concat("Brother ", char_name(ctx, 0)), "!"))
          else
            mes(ctx, Rathena.concat(Rathena.concat("Sister ", char_name(ctx, 0)), "!"))
          end

        {ctx, v1} =
          ctx
          |> mes("So good to see you again!")
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "Are you here to help an Acolyte friend for the spiritual training? That's great~ I think you'll do a good job."
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "Remember, no matter how much you want to help this Acolyte, this is not your quest."
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "You may assist and lighten your friend's burden, but you take upon this task for yourself."
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes("So...")
          |> mes("Are you gonna help him right now?")
          |> next()
          |> select(["Yes, I am.", "Give me a minute.", "I changed my mind."])

        ctx =
          case v1 do
            1 ->
              ctx =
                ctx
                |> mes("[Father Peter]")
                |> mes(
                  "Go for it! As your Acolyte enters, the test will begin. Now, I will send you to the testing area."
                )
                |> close()
                |> warp("job_prist", 24, 44)

              throw({:script_end, ctx})

            2 ->
              ctx =
                ctx
                |> mes("[Father Peter]")
                |> mes("Hm...?")
                |> mes("What for?")
                |> mes(
                  "Well, so long as you arrive in time to help your friend, it will be okay."
                )
                |> close()

              throw({:script_end, ctx})

            3 ->
              ctx =
                ctx
                |> mes("[Father Peter]")
                |> mes("Oh...?")
                |> mes("Then please,")
                |> mes("go ahead. God bless")
                |> mes("you, and take care!")
                |> close()
                |> warp("prontera", 234, 318)

              throw({:script_end, ctx})

            _ ->
              ctx
          end

        ctx
      else
        ctx
      end

    ctx =
      if get_char_var(ctx, :PRIEST_Q, 0) == 5 do
        {ctx, v2} =
          ctx
          |> mes("Welcome~!")
          |> mes("I congratulate you")
          |> mes("for passing the first trail.")
          |> next()
          |> mes("[Father Peter]")
          |> mes("My name is")
          |> mes("Peter S. Alberto.")
          |> mes("How is my buddy Paul?")
          |> mes("Is he doing alright")
          |> mes("these days?")
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "Oh, I keep forgetting that he was promoted to Bishop. I think I'm supposed to call him Bishop Paul, or 'His Excellency.' Haha~"
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "Anyway, let me give you a brief explanation of the spiritual training. Are you familiar with what the spiritual training is for Priests?"
          )
          |> next()
          |> select(["Yes, I do.", "Sorry..."])

        ctx =
          case v2 do
            1 ->
              ctx
              |> mes("[Father Peter]")
              |> mes(
                "Haha, I like you! But it never hurts to have too much information. The more well informed you are, the more easily you'll pass the test!"
              )
              |> next()

            2 ->
              ctx =
                ctx
                |> mes("[Father Peter]")
                |> mes(
                  "Oh, no need to be sorry. I'm here to give you the information you need anyway. So, don't worry."
                )
                |> next()

              ctx

            _ ->
              ctx
          end

        {ctx, v3} =
          ctx
          |> mes("[Father Peter]")
          |> mes(
            "In spiritual training, you will be defeating evil creatures. Creatures of the Undead and Demons are all evil. In choosing to serve darkness, they are our enemies!"
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "There are too many evil creatures that roam this world against the will of God. Innocents suffer as a result of their malignance."
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "We, as Priests, are obligated to exterminate all those creatures, thus spreading love and peace."
          )
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "This training will test your ability to eliminate evil. Since this trial is pretty difficult to be accomplished by yourself,"
          )
          |> mes("I recommend getting help from a Priest if you can.")
          |> next()
          |> mes("[Father Peter]")
          |> mes(
            "If you are close to a Priest, you'd better ask him to assist you during this trial. Now, are you ready?"
          )
          |> next()
          |> select(["I'm ready.", "Please hold on.", "I want to go back."])

        ctx =
          case v3 do
            1 ->
              ctx =
                ctx
                |> mes("[Father Peter]")
                |> mes(
                  "Now, let the spiritual training begin. It's simple. Just kill them all. Show no mercy to the creatures of darkness!"
                )
                |> next()
                |> mes("[Father Peter]")
                |> mes("Now...")
                |> mes("Go for it!")
                |> close()

              ctx =
                if checkquest(ctx, 8012) == -1 do
                  changequest(ctx, 8011, 8012)
                else
                  ctx
                end

              ctx =
                ctx
                |> warp("job_prist", 24, 44)
                |> donpcevent("Zombie_Generator#prst::OnEnable")
                |> donpcevent("Peter S. Alberto::OnDisable")
                |> donpcevent("Peter S. Alberto#2::OnEnable")

              throw({:script_end, ctx})

            2 ->
              ctx =
                ctx
                |> set_char_var(:PRIEST_Q, 6)
                |> mes("[Father Peter]")
                |> mes("Hm? What is it you need?")
                |> mes("Well, no problem. You can")
                |> mes("afford to take your time.")
                |> close()

              throw({:script_end, ctx})

            3 ->
              ctx =
                ctx
                |> set_char_var(:PRIEST_Q, 6)
                |> mes("[Father Peter]")
                |> mes("What...?")
                |> mes("You wanna go back??")
                |> next()
                |> mes("[Father Peter]")
                |> mes(
                  "I understand. I suppose you have some important reason or business that you must attend to. Come back whenever you can."
                )
                |> close()
                |> warp("prontera", 234, 318)

              throw({:script_end, ctx})

            _ ->
              ctx
          end

        ctx
      else
        ctx =
          if get_char_var(ctx, :PRIEST_Q, 0) == 6 do
            {ctx, v4} =
              ctx
              |> mes("Are you ready this time?")
              |> mes("Complete this trial quickly,")
              |> mes("and become a Priest!")
              |> next()
              |> mes("[Father Peter]")
              |> mes("Are you ready then?")
              |> next()
              |> select(["I'm ready.", "Please hold on.", "I want to go back."])

            ctx =
              case v4 do
                1 ->
                  ctx =
                    ctx
                    |> mes("[Father Peter]")
                    |> mes(
                      "Now, let the spiritual training begin. For the glory of God, for peace on earth, and goodwill towards all men..."
                    )
                    |> next()
                    |> mes("[Father Peter]")
                    |> mes("Go...")
                    |> mes("Kill those")
                    |> mes("misbegotten creatures!")
                    |> close()

                  ctx =
                    if checkquest(ctx, 8012) == -1 do
                      changequest(ctx, 8011, 8012)
                    else
                      ctx
                    end

                  ctx =
                    ctx
                    |> warp("job_prist", 24, 44)
                    |> donpcevent("Zombie_Generator#prst::OnEnable")
                    |> donpcevent("Peter S. Alberto::OnDisable")
                    |> donpcevent("Peter S. Alberto#2::OnEnable")

                  throw({:script_end, ctx})

                2 ->
                  ctx =
                    ctx
                    |> mes("[Father Peter]")
                    |> mes("Hm? What is it you need?")
                    |> mes("Well, no problem. You can")
                    |> mes("afford to take your time.")
                    |> close()

                  throw({:script_end, ctx})

                3 ->
                  ctx =
                    ctx
                    |> mes("[Father Peter]")
                    |> mes("What...?")
                    |> mes("You wanna go back??")
                    |> next()
                    |> mes("[Father Peter]")
                    |> mes(
                      "I understand. I suppose you have some important reason or business that you must attend to. Come back whenever you can."
                    )
                    |> close()
                    |> warp("prontera", 234, 318)

                  throw({:script_end, ctx})

                _ ->
                  ctx
              end

            ctx
          else
            ctx = ctx |> mes("Go back!") |> close() |> warp("prontera", 234, 318)
            throw({:script_end, ctx})
          end

        ctx
      end

    ctx
  catch
    :throw, {:script_end, ctx} -> ctx
  end

  def ev_onenable(ctx) do
    enablenpc(ctx, "Peter S. Alberto")
  end

  def ev_ondisable(ctx) do
    disablenpc(ctx, "Peter S. Alberto")
  end
end
