defmodule Aesir.ZoneServer.Content.Npc.Jobs.Valkyrie.HeartOfYmir do
  @moduledoc """
  Transpiled from rAthena jobs/valkyrie.txt:348 (Heart of Ymir).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    scope: :shared,
    spawn: [
      %{
        map: "yuno_in05",
        x: 49,
        y: 43,
        dir: 1,
        sprite: 111,
        name: "Heart of Ymir",
        scope: :shared
      }
    ]

  @impl true
  def on_talk(ctx) do
    ctx =
      if base_level(ctx) > 98 and job_level(ctx) > 49 and class(ctx) >= :knight and
           class(ctx) <= :crusader2 do
        ctx =
          if get_char_var(ctx, :valkyrie_Q, 0) == 2 do
            warp(ctx, "valkyrie", 48, 8)
          else
            ctx
          end

        ctx
      else
        ctx
      end

    ctx
  end
end
