defmodule Aesir.ZoneServer.Content.Npc.MocRuins.YoungMan do
  @moduledoc """
  Transpiled from rAthena cities/morocc.txt:146 (Young Man#moc01).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "moc_ruins", x: 123, y: 154, dir: 0, sprite: 99, name: "Young Man"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Young Man]")
    |> mes(
      "The town's completely destroyed, but that giant triangular structure hasn't been harmed at all. Maybe it's protected by some kinda special power."
    )
    |> next()
    |> mes("[Young Man]")
    |> mes(
      "You know...Those giant, triangular buildings at the NorthWest corner of Morocc known are known to us as Pyramids..."
    )
    |> next()
    |> mes("[Young Man]")
    |> mes(
      "Those things have been around here for thousands and thousands of years. No one knows when and why they were built, or who built them."
    )
    |> next()
    |> mes("[Young Man]")
    |> mes(
      "All we know is that tons of monsters live inside those weird buildings. You might wanna stay away from those really dangerous places."
    )
    |> next()
    |> mes("[Young Man]")
    |> mes(
      "Those monsters in the Pyramid would be very, very sensitive to sweet flash smell of people...."
    )
    |> close()

    exit(:normal)
  end
end
