defmodule Aesir.ZoneServer.Content.Npc.Warps.Dungeons.MoskDun.Milestone16828 do
  @moduledoc """
  Transpiled from rAthena warps/dungeons/mosk_dun.txt:143 (Milestone#2-1).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [
      %{
        map: "mosk_dun02",
        x: 168,
        y: 28,
        dir: 3,
        sprite: 111,
        name: "Milestone",
        unique_name: "Milestone#2-1"
      }
    ]

  @impl true
  def on_talk(ctx) do
    {ctx, v1} =
      ctx
      |> mes("- There is writing on a big rock. -")
      |> next()
      |> mes(
        "^3131FF- Those who advance may get hurt but are valorous of heart and those who move back will remain safe."
      )
      |> mes("If you valorous, then take a step forward. Otherwise, step back. -^000000")
      |> next()
      |> select(["Go back.", "Stay."])

    ctx =
      if v1 == 1 do
        ctx =
          ctx
          |> mes("- You sense danger and decide to go back -")
          |> close()
          |> warp("mosk_dun01", 201, 269)

        throw({:script_end, ctx})
      else
        ctx
      end

    ctx |> mes("- You decided to stay. -") |> close()
  catch
    :throw, {:script_end, ctx} -> ctx
  end
end
