defmodule Aesir.ZoneServer.Content.Npc.Lighthalzen.Kariya do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:140 (Kariya#li_01).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "lighthalzen", x: 233, y: 121, dir: 3, sprite: 72, name: "Kariya"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Kariya]")
    |> mes("I think ''Lighthalzen'' is")
    |> mes("supposed to mean ''crest of")
    |> mes("light,'' though I hear that this")
    |> mes("city was actually named after")
    |> mes("somebody. Who knows for sure?")
    |> next()
    |> mes("[Kariya]")
    |> mes("Still, it's a fitting")
    |> mes("name for the wealthiest")
    |> mes("and most luxurious city in")
    |> mes("all the Schwarzwald Republic.")
    |> mes("So how do you like this place?")
    |> close()

    exit(:normal)
  end
end
