defmodule Aesir.ZoneServer.Content.Npc.Lighthalzen.Reuben do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:1239 (Reuben#lhz_02).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "lighthalzen", x: 311, y: 194, dir: 3, sprite: 870, name: "Reuben"}]

  @impl true
  def on_talk(ctx) do
    ctx =
      if Enum.random(1..2) == 1 do
        ctx
        |> mes("[Reuben]")
        |> mes("Someday...")
        |> mes("Someday I just gotta")
        |> mes("become a train conductor")
        |> mes("and just get outta here!")
        |> mes("I really hate this place!")
        |> emotion(:anger)
        |> next()
        |> mes("[Reuben]]")
        |> mes("Wh-whoa...!")
        |> mes("Did you just hear")
        |> mes("me talk to myself?")
        |> mes("Crud! Don't be so nosy!")
        |> emotion(:fret)
        |> close()

        exit(:normal)
      else
        ctx
      end

    ctx
    |> mes("[Reuben]")
    |> mes("Hey. What are")
    |> mes("you doing just")
    |> mes("looking at me?")
    |> mes("I don't know you")
    |> mes("from Adam, so get lost~")
    |> emotion(:rock)
    |> close()

    exit(:normal)
  end
end
