defmodule Aesir.ZoneServer.Content.Npc.Lighthalzen.Sigmund do
  @moduledoc """
  Transpiled from rAthena cities/lighthalzen.txt:360 (Sigmund#zen3).

  Regenerated by `mix aesir.import.npcs`; hand edits are detected through
  the transpile manifest and future imports land in `_conflicts/` instead
  of overwriting them.
  """

  use Aesir.ZoneServer.Npc,
    spawn: [%{map: "lighthalzen", x: 232, y: 156, dir: 3, sprite: 869, name: "Sigmund"}]

  @impl true
  def on_talk(ctx) do
    ctx
    |> mes("[Sigmund Ting]")
    |> mes("You know what I noticed?")
    |> mes("The guards at the border")
    |> mes("to the slum seem distracted")
    |> mes("sometimes. I made use of one")
    |> mes("of their less attentive moments")
    |> mes("and basically jumped the fence!")
    |> next()
    |> mes("[Sigmund Ting]")
    |> mes("But once I was in the ")
    |> mes("slums, I was pretty bored.")
    |> mes("There really isn't much to")
    |> mes("do there. Which makes me")
    |> mes("wonder... Why guard it?")
    |> close()
  end
end
